// packages/react/components/src/CodeEditor.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import {
  installInputModality,
  isCodeEditorValueAdmissible,
} from "@inflatable-cookie/poodle-core";
import type {
  CodeEditorChange,
  CodeEditorDiagnostic,
  CodeEditorLanguageId,
  CodeEditorLanguageRegistry,
  CodeEditorPerformanceMode,
  CodeEditorTabBehavior,
} from "@inflatable-cookie/poodle-core";
import type { ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";

import "@inflatable-cookie/poodle-core/styles/code-editor.css";

import {
  assertAdmittedLanguage,
  createCodeEditorEngine,
} from "./code-editor-engine";
import type { CodeEditorActiveDiagnostic, CodeEditorEngine } from "./code-editor-engine";
import { resolveSemanticControlSize, useUiPresentation } from "./presentation";

export interface CodeEditorProps {
  value: string;
  language?: CodeEditorLanguageId;
  languageRegistry?: CodeEditorLanguageRegistry | null;
  lineNumbers?: boolean;
  searchable?: boolean;
  diagnostics?: CodeEditorDiagnostic[];
  readOnly?: boolean;
  disabled?: boolean;
  placeholder?: string;
  ariaLabel?: string;
  wrapLines?: boolean;
  tabSize?: number;
  tabBehavior?: CodeEditorTabBehavior;
  performanceMode?: CodeEditorPerformanceMode;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  onChange?: ((change: CodeEditorChange) => void) | null;
}

export interface CodeEditorHandle {
  focus: () => void;
}

/**
 * Web-admitted controlled code and plain-text editing surface over
 * CodeMirror 6. The engine stays private: no CodeMirror type crosses this
 * API, and the component is reached only through `./editor`.
 */
export const CodeEditor = forwardRef<CodeEditorHandle, CodeEditorProps>(function CodeEditor(
  {
    value,
    language = "plain-text",
    languageRegistry = null,
    lineNumbers = true,
    searchable = true,
    diagnostics = [],
    readOnly = false,
    disabled = false,
    placeholder = "",
    ariaLabel = "Code editor",
    wrapLines = false,
    tabSize = 2,
    tabBehavior = "focus",
    performanceMode = "full",
    size = null,
    sizeRole = "control",
    density = null,
    onChange = null,
  }: CodeEditorProps,
  ref,
) {
  assertAdmittedLanguage(language, languageRegistry);

  const uiPresentation = useUiPresentation();
  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const hostRef = useRef<HTMLDivElement | null>(null);
  const engineRef = useRef<CodeEditorEngine | null>(null);
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;
  // Live prop snapshot for the post-creation flush: renders that land while
  // the engine is still loading must not be silently dropped.
  const latestRef = useRef({
    value,
    language,
    languageRegistry,
    lineNumbers,
    searchable,
    readOnly,
    disabled,
    placeholder,
    ariaLabel,
    wrapLines,
    tabSize,
    tabBehavior,
    performanceMode,
    diagnostics,
  });
  latestRef.current = {
    value,
    language,
    languageRegistry,
    lineNumbers,
    searchable,
    readOnly,
    disabled,
    placeholder,
    ariaLabel,
    wrapLines,
    tabSize,
    tabBehavior,
    performanceMode,
    diagnostics,
  };
  const [activeDiagnostic, setActiveDiagnostic] = useState<CodeEditorActiveDiagnostic | null>(null);
  const [messageId] = useState(() => `poodle-code-editor-${Math.random().toString(36).slice(2)}`);

  useImperativeHandle(ref, () => ({
    focus: () => {
      (hostRef.current?.querySelector(".cm-content") as HTMLElement | null)?.focus();
    },
  }));

  useEffect(() => {
    installInputModality();
    if (!isCodeEditorValueAdmissible(value)) {
      console.warn(
        "code-editor: value exceeds the 2 MiB envelope; hosts must refuse larger sources before mounting",
      );
    }
    const host = hostRef.current;
    if (!host) return;
    let cancelled = false;
    createCodeEditorEngine(
      host,
      latestRef.current,
      {
        onChange: (change) => onChangeRef.current?.(change),
        onActiveDiagnostic: setActiveDiagnostic,
      },
    ).then((created) => {
      if (cancelled) {
        created.destroy();
        return;
      }
      engineRef.current = created;
      // Flush the live props: host updates may have landed while the engine
      // was loading, and the sync effect possibly ran with no engine.
      void engineRef.current.update(latestRef.current);
    });
    return () => {
      cancelled = true;
    };
    // Mount-only: prop updates flow through the sync effect below.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    void engineRef.current?.update({
      value,
      language,
      languageRegistry,
      lineNumbers,
      searchable,
      readOnly,
      disabled,
      placeholder,
      ariaLabel,
      wrapLines,
      tabSize,
      tabBehavior,
      performanceMode,
      diagnostics,
    });
  });

  return (
    <div
      className="poodle-code-editor"
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-disabled={disabled || undefined}
      data-readonly={readOnly || undefined}
    >
      <div
        ref={hostRef}
        className="poodle-code-editor__viewport"
        aria-describedby={activeDiagnostic ? messageId : undefined}
      />
      {activeDiagnostic ? (
        <div
          id={messageId}
          className="poodle-code-editor__diagnostic-message"
          data-severity={activeDiagnostic.diagnostic.severity}
          role="status"
        >
          {`${activeDiagnostic.diagnostic.severity} ${activeDiagnostic.line}:${activeDiagnostic.column} — ${activeDiagnostic.diagnostic.message}`}
        </div>
      ) : null}
    </div>
  );
});

// packages/svelte/components/src/CodeEditor.svelte
<script lang="ts">
  import "@inflatable-cookie/poodle-core/styles/code-editor.css";
  import {
    installInputModality,
    isCodeEditorValueAdmissible,
  } from "@inflatable-cookie/poodle-core";
  import type {
    CodeEditorChange,
    CodeEditorDiagnostic,
    CodeEditorLanguageId,
    CodeEditorLanguageRegistry,
    CodeEditorPerformanceMode,
    CodeEditorTabBehavior,
  } from "@inflatable-cookie/poodle-core";
  import type { ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";
  import { onDestroy, onMount } from "svelte";

  import {
    assertAdmittedLanguage,
    createCodeEditorEngine,
  } from "./code-editor-engine";
  import type { CodeEditorActiveDiagnostic, CodeEditorEngine } from "./code-editor-engine";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";

  /**
   * Web-admitted controlled code and plain-text editing surface over
   * CodeMirror 6. The engine stays private: no CodeMirror type crosses this
   * API, and the component is reached only through `./editor`.
   */
  interface Props {
    value: string;
    language?: CodeEditorLanguageId;
    languageRegistry?: CodeEditorLanguageRegistry | null;
    lineNumbers?: boolean;
    searchable?: boolean;
    diagnostics?: CodeEditorDiagnostic[];
    readOnly?: boolean;
    disabled?: boolean;
    placeholder?: string;
    ariaLabel?: string;
    wrapLines?: boolean;
    tabSize?: number;
    tabBehavior?: CodeEditorTabBehavior;
    performanceMode?: CodeEditorPerformanceMode;
    size?: ControlSize | null;
    sizeRole?: SemanticControlSizeRole;
    density?: ControlDensity | null;
    onChange?: ((change: CodeEditorChange) => void) | null;
  }

  let {
    value,
    language = "plain-text",
    languageRegistry = null,
    lineNumbers = true,
    searchable = true,
    diagnostics = [],
    readOnly = false,
    disabled = false,
    placeholder = "",
    ariaLabel = "Code editor",
    wrapLines = false,
    tabSize = 2,
    tabBehavior = "focus",
    performanceMode = "full",
    size = null,
    sizeRole = "control",
    density = null,
    onChange = null,
  }: Props = $props();

  const uiPresentation = getUiPresentation();
  const resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole));
  const resolvedDensity = $derived(density ?? $uiPresentation.density);
  // `language` is validated against `languageRegistry` when the engine mounts
  // and on every language update; asserting here would capture only the
  // initial prop values.
  /** Imperative escape hatch: focus the editing surface. Documented as a method, not a prop. */
  export function focus(): void {
    (hostElement?.querySelector(".cm-content") as HTMLElement | null)?.focus();
  }

  let hostElement: HTMLDivElement | null = $state(null);
  let engine: CodeEditorEngine | null = null;
  let activeDiagnostic: CodeEditorActiveDiagnostic | null = $state(null);
  let messageId = `poodle-code-editor-${Math.random().toString(36).slice(2)}`;

  // Live prop snapshot. Reads of $props bindings stay current, so the
  // post-creation flush below picks up host updates that landed while the
  // engine was still loading.
  function currentOptions() {
    return {
      value,
      language,
      languageRegistry,
      lineNumbers,
      searchable,
      readOnly,
      disabled,
      placeholder,
      ariaLabel,
      wrapLines,
      tabSize,
      tabBehavior,
      performanceMode,
      diagnostics,
    };
  }

  onMount(() => {
    assertAdmittedLanguage(language, languageRegistry);
    installInputModality();
    if (!isCodeEditorValueAdmissible(value)) {
      console.warn(
        "code-editor: value exceeds the 2 MiB envelope; hosts must refuse larger sources before mounting",
      );
    }
    let cancelled = false;
    createCodeEditorEngine(
      hostElement as HTMLDivElement,
      currentOptions(),
      {
        onChange: (change) => onChange?.(change),
        onActiveDiagnostic: (active) => {
          activeDiagnostic = active;
        },
      },
    ).then((created) => {
      if (cancelled) {
        created.destroy();
        return;
      }
      engine = created;
      // Host updates may have landed while the engine was loading; the sync
      // effect possibly ran with no engine to receive them. Flush the live
      // props so the host value stays authoritative.
      void engine.update(currentOptions());
    });
    return () => {
      cancelled = true;
    };
  });

  onDestroy(() => {
    engine?.destroy();
    engine = null;
  });

  $effect(() => {
    // Read every prop unconditionally before touching `engine`: `engine` is
    // null until the async mount resolves, and an `engine?.update(...)`
    // short-circuit would subscribe to nothing, leaving this effect dead.
    const next = currentOptions();
    void engine?.update(next);
  });
</script>

<div
  class="poodle-code-editor"
  data-size={resolvedSize}
  data-density={resolvedDensity}
  data-disabled={disabled || undefined}
  data-readonly={readOnly || undefined}
>
  <div
    bind:this={hostElement}
    class="poodle-code-editor__viewport"
    aria-describedby={activeDiagnostic ? messageId : undefined}
  ></div>
  {#if activeDiagnostic}
    {@const active = activeDiagnostic}
    <div
      id={messageId}
      class="poodle-code-editor__diagnostic-message"
      data-severity={active.diagnostic.severity}
      role="status"
    >
      {active.diagnostic.severity} {active.line}:{active.column} — {active.diagnostic.message}
    </div>
  {/if}
</div>
