// packages/react/components/src/ErrorBoundary.tsx
import { Component, type ReactNode } from "react";

import { Button } from "./Button";
import { EmptyState } from "./EmptyState";

export interface ErrorBoundaryProps {
  children: ReactNode;
  title?: string;
  retryLabel?: string;
}

interface ErrorBoundaryState {
  currentError: Error | null;
}

/**
 * Mirrors the Svelte `<svelte:boundary>` wrapper. React error boundaries
 * require a class component — the only one in the package.
 */
export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { currentError: null };

  static getDerivedStateFromError(error: unknown): ErrorBoundaryState {
    return { currentError: error instanceof Error ? error : new Error(String(error)) };
  }

  reset = (): void => {
    this.setState({ currentError: null });
  };

  render(): ReactNode {
    const { children, title = "Something went wrong", retryLabel = "Try again" } = this.props;

    if (this.state.currentError) {
      return (
        <EmptyState
          title={title}
          message={this.state.currentError.message}
          actions={
            <Button variant="secondary" onClick={this.reset}>
              {retryLabel}
            </Button>
          }
        />
      );
    }

    return children;
  }
}

// packages/svelte/components/src/ErrorBoundary.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  import { default as EmptyState } from "./EmptyState.svelte";
  import { default as Button } from "./Button.svelte";

  interface Props {
    children: Snippet;
    title?: string;
    retryLabel?: string;
  }

  let {
    children,
    title = "Something went wrong",
    retryLabel = "Try again",
  }: Props = $props();

  let currentError = $state<Error | null>(null);

  function handleError(error: unknown) {
    currentError = error instanceof Error ? error : new Error(String(error));
  }

  function reset() {
    currentError = null;
  }
</script>

{#if currentError}
  <EmptyState {title} message={currentError.message}>
    {#snippet actions()}
      <Button variant="secondary" onclick={reset}>{retryLabel}</Button>
    {/snippet}
  </EmptyState>
{:else}
  <svelte:boundary onerror={handleError}>
    {@render children()}
  </svelte:boundary>
{/if}
