// packages/react/components/src/InlineListSection.tsx
import "@inflatable-cookie/poodle-core/styles/inline-list-section.css";

import type { ReactNode } from "react";

import { Card } from "./Card";

export interface InlineListSectionProps<T> {
  title: string;
  items: T[];
  item: (entry: T) => ReactNode;
  actions?: ReactNode;
  emptyMessage?: string | null;
  count?: number | string | null;
  framed?: boolean;
}

export function InlineListSection<T>({
  title,
  items,
  item,
  actions,
  emptyMessage = "No items yet.",
  count = null,
  framed = true,
}: InlineListSectionProps<T>) {
  const section = (
    <section className="poodle-inline-list-section" aria-label={title}>
      <div className="poodle-inline-list-section__header">
        <div className="poodle-inline-list-section__heading">
          <h4 className="poodle-inline-list-section__title">{title}</h4>
          {count !== null ? <span className="poodle-inline-list-section__count">{count}</span> : null}
        </div>
        {actions ? <div className="poodle-inline-list-section__header-actions">{actions}</div> : null}
      </div>

      {items.length === 0 ? (
        emptyMessage ? <p className="poodle-inline-list-section__empty">{emptyMessage}</p> : null
      ) : (
        <ul className="poodle-inline-list-section__items">
          {items.map((entry, index) => (
            <li key={index} className="poodle-inline-list-section__item">
              {item(entry)}
            </li>
          ))}
        </ul>
      )}
    </section>
  );

  return framed ? <Card>{section}</Card> : section;
}

// packages/svelte/components/src/InlineListSection.svelte
<script lang="ts" generics="T">
  import "@inflatable-cookie/poodle-core/styles/inline-list-section.css";
  import type { Snippet } from "svelte";

  import { default as Card } from "./Card.svelte";

  interface Props {
    title: string;
    items: T[];
    item: Snippet<[T]>;
    actions?: Snippet;
    emptyMessage?: string | null;
    count?: number | string | null;
    framed?: boolean;
  }

  let {
    title,
    items,
    item,
    actions,
    emptyMessage = "No items yet.",
    count = null,
    framed = true
  }: Props = $props();
</script>

{#if framed}
  <Card>
    <section class="poodle-inline-list-section" aria-label={title}>
      <div class="poodle-inline-list-section__header">
        <div class="poodle-inline-list-section__heading">
          <h4 class="poodle-inline-list-section__title">{title}</h4>
          {#if count !== null}
            <span class="poodle-inline-list-section__count">{count}</span>
          {/if}
        </div>
        {#if actions}
          <div class="poodle-inline-list-section__header-actions">
            {@render actions()}
          </div>
        {/if}
      </div>

      {#if items.length === 0}
        {#if emptyMessage}
          <p class="poodle-inline-list-section__empty">{emptyMessage}</p>
        {/if}
      {:else}
        <ul class="poodle-inline-list-section__items">
          {#each items as entry}
            <li class="poodle-inline-list-section__item">
              {@render item(entry)}
            </li>
          {/each}
        </ul>
      {/if}
    </section>
  </Card>
{:else}
  <section class="poodle-inline-list-section" aria-label={title}>
    <div class="poodle-inline-list-section__header">
      <div class="poodle-inline-list-section__heading">
        <h4 class="poodle-inline-list-section__title">{title}</h4>
        {#if count !== null}
          <span class="poodle-inline-list-section__count">{count}</span>
        {/if}
      </div>
      {#if actions}
        <div class="poodle-inline-list-section__header-actions">
          {@render actions()}
        </div>
      {/if}
    </div>

    {#if items.length === 0}
      {#if emptyMessage}
        <p class="poodle-inline-list-section__empty">{emptyMessage}</p>
      {/if}
    {:else}
      <ul class="poodle-inline-list-section__items">
        {#each items as entry}
          <li class="poodle-inline-list-section__item">
            {@render item(entry)}
          </li>
        {/each}
      </ul>
    {/if}
  </section>
{/if}
