// packages/react/components/src/Popover.tsx
import { useEffect, useId, useRef, useState, type CSSProperties, type ReactNode } from "react";
import {
  getFocusableElements,
  layerContains,
  portalAnchorOf,
  portalledDescendantsOf,
  popoverParts,
  popoverTransition,
  registerDismissLayer,
  type PopoverContext,
  type PopoverEvent,
  type PopoverTriggerState,
  type OverlaySurfaceGeometryChangeHandler,
} from "@inflatable-cookie/poodle-core";

import "@inflatable-cookie/poodle-core/styles/popover.css";

import { AnchoredSurface } from "./AnchoredSurface";
import { reactifyPart } from "./parts";
import type { OverlayPlacement, PopoverInitialFocus } from "./types";

/**
 * The contracted Popover surface. `trigger` and the content take React nodes;
 * `triggerIsInteractive` and `onSurfaceGeometryChange` are documented web-only
 * extensions kept beside this adapter.
 *
 * Contract: `docs/contracts/components/popover.md`. The Svelte pair is
 * `packages/svelte/components/src/Popover.svelte`; the Rust counterpart is
 * `poodle_specs::PopoverSpec`.
 */
interface PopoverCommonProps {
  open?: boolean | null;
  defaultOpen?: boolean;
  placement?: OverlayPlacement;
  offset?: number;
  dismissOnOutsideInteract?: boolean;
  initialFocus?: PopoverInitialFocus;
  ariaLabel?: string | null;
  block?: boolean;
  disabled?: boolean;
  surfaceWidth?: "content" | "trigger";
  surfaceMinWidth?: string | null;
  surfaceMaxWidth?: string | null;
  onOpenChange?: (open: boolean) => void;
  onSurfaceGeometryChange?: OverlaySurfaceGeometryChangeHandler;
  children?: ReactNode;
}

/**
 * Trigger composition is a compile-time choice (contract §3, "Trigger
 * Modes"). In default mode `trigger` is a plain node and the wrapper owns the
 * button role, tab stop, keyboard activation, and disclosure ARIA. In
 * interactive mode `trigger` is a state-aware render: the caller applies all
 * three `PopoverTriggerState` fields (`expanded` → `aria-expanded`,
 * `controls` → `aria-controls`, `disabled`) to the real control inside.
 */
type PopoverTriggerProps =
  | { triggerIsInteractive?: false; trigger?: ReactNode }
  | { triggerIsInteractive: true; trigger: (state: PopoverTriggerState) => ReactNode };

export type PopoverProps = PopoverCommonProps & PopoverTriggerProps;

export function Popover({
  open = null,
  defaultOpen = false,
  placement = "bottom-start",
  offset = 8,
  dismissOnOutsideInteract = true,
  initialFocus = "first-focusable",
  ariaLabel = null,
  block = false,
  triggerIsInteractive = false,
  disabled = false,
  surfaceWidth = "content",
  surfaceMinWidth = null,
  surfaceMaxWidth = null,
  onOpenChange,
  onSurfaceGeometryChange,
  trigger,
  children,
}: PopoverProps) {
  // React's own id keeps the server render and hydration in agreement, so
  // the trigger's `aria-controls` and the surface id match without any
  // post-mount repair (SSR evidence lives in PopoverInteractiveTrigger.test).
  const popoverId = useId();

  // The root is state, not a ref: the portalled surface has to re-render once
  // it exists so it can be positioned against it.
  const [rootElement, setRootElement] = useState<HTMLDivElement | null>(null);
  const triggerRef = useRef<HTMLDivElement | null>(null);
  const surfaceRef = useRef<HTMLDivElement | null>(null);
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const [resolvedPlacement, setResolvedPlacement] = useState<OverlayPlacement>(placement);
  const previousOpen = useRef(false);

  const isControlled = open !== null;
  // Disabled blocks open in every direction (contract §3): a controlled
  // `open` request while disabled stays inert — the machine's own guard,
  // mirrored here so the visible state can never disagree with it.
  const isOpen = !disabled && (isControlled ? open === true : uncontrolledOpen);

  const machineContext: PopoverContext = { disabled, dismissOnOutsideInteract, initialFocus };

  // initial focus on open (after the surface renders)
  useEffect(() => {
    if (isOpen && !previousOpen.current && surfaceRef.current) {
      if (initialFocus === "content") {
        surfaceRef.current.focus();
      } else if (initialFocus === "first-focusable") {
        getFocusableElements(surfaceRef.current)[0]?.focus();
      }
    }
    previousOpen.current = isOpen;
  }, [isOpen, initialFocus]);

  const sendRef = useRef<(event: PopoverEvent) => void>(() => {});
  sendRef.current = (event: PopoverEvent) => {
    const result = popoverTransition(isOpen ? "open" : "closed", machineContext, event);
    for (const effect of result.effects) {
      switch (effect.type) {
        case "emitOpenChange":
          if (!isControlled) setUncontrolledOpen(effect.open);
          onOpenChange?.(effect.open);
          break;
        case "restoreTriggerFocus": {
          // With `triggerIsInteractive` the wrapper observes clicks without
          // becoming a button, so the operable control is the one the caller
          // composed inside it. Restoring focus to the wrapper would land it
          // on something that cannot be activated — the operator would press
          // Enter and nothing would happen.
          const target = triggerIsInteractive
            ? triggerRef.current?.querySelector<HTMLElement>(
                'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
              ) ?? triggerRef.current
            : triggerRef.current;
          target?.focus();
          break;
        }
        case "focusOnOpen":
          // handled by the isOpen effect above
          break;
      }
    }
  };

  useEffect(() => {
    if (isOpen) return;
    setResolvedPlacement(placement);
  }, [isOpen, placement]);

  useEffect(() => {
    if (!isOpen) return;

    /**
     * Tab from inside one of this popover's own portalled descendants — a
     * Select listbox opened from content in this surface, or any anchored
     * overlay a future child portals. The node lives at the theme root, so
     * the key never bubbles through the surface and no content-level trap
     * can see it; natively it would leave in document order while the child
     * stays open. Route it home instead: prevent the pass-through and focus
     * the control the portal opened from (the anchor's first focusable,
     * falling back into the surface). This is containment, not a trap — the
     * destination is always in-surface, where keys flow natively and no
     * content trap cycles, so exit stays one Tab away and nothing can loop.
     * In-surface targets are never touched; neither are other popovers'
     * surfaces, unless nested inside our own scope as portalled descendants.
     */
    function handleDocumentKeydown(event: KeyboardEvent): void {
      if (event.key !== "Tab") return;
      const target = event.target;
      if (!(target instanceof Node)) return;
      // In-scope targets keep native flow and content-owned traps.
      if (layerContains(target as Node, rootElement, surfaceRef.current)) return;
      const portalled = portalledDescendantsOf(rootElement, surfaceRef.current);
      // A surface that is not ours owns its own keys — a peer, or a nested
      // popover rendered elsewhere. But a nested popover surface that is
      // itself one of our portalled descendants stays in our scope: it fell
      // out of our subtree only through portalling, so Tabs inside it route
      // home to its anchor exactly like any other portal below.
      if (target instanceof Element) {
        const owner = target.closest(".poodle-popover__surface");
        if (
          owner !== null &&
          owner !== surfaceRef.current &&
          !portalled.includes(owner as HTMLElement)
        ) {
          return;
        }
      }
      const home = portalled.find((node) => node.contains(target));
      if (!home) return;
      const anchor = portalAnchorOf(home);
      const destination =
        (anchor ? getFocusableElements(anchor as HTMLElement)[0] : undefined) ??
        getFocusableElements(rootElement)[0] ??
        getFocusableElements(surfaceRef.current)[0] ??
        surfaceRef.current;
      event.preventDefault();
      destination?.focus();
    }

    document.addEventListener("keydown", handleDocumentKeydown);
    return () => {
      document.removeEventListener("keydown", handleDocumentKeydown);
    };
  }, [isOpen, rootElement]);

  useEffect(() => {
    if (!isOpen) return;
    return registerDismissLayer({
      // The surface is portalled out of the root, so both are "inside".
      contains: (target) => layerContains(target as Node, rootElement, surfaceRef.current),
      dismissOnOutsideInteract,
      onDismiss: (reason) =>
        sendRef.current(reason === "escape" ? { type: "ESCAPE" } : { type: "OUTSIDE_INTERACT" }),
      // Parenthood and stack order derive from real layer containment: the
      // layer's `contains` covers both the root and the portalled surface,
      // so a nested popover's root is contained by its host's layer no
      // matter where the surfaces were portalled to.
      hostElement: rootElement,
    });
  }, [isOpen, dismissOnOutsideInteract, rootElement]);

  const parts = popoverParts(isOpen ? "open" : "closed", machineContext, {
    surfaceId: popoverId,
    ariaLabel,
    block,
    triggerIsInteractive,
    placement: resolvedPlacement,
    surfaceWidth,
  });

  const surfaceStyle: CSSProperties & Record<string, string> = {
    ...(surfaceMinWidth ? { "--poodle-popover-surface-min-width": surfaceMinWidth } : null),
    ...(surfaceMaxWidth ? { "--poodle-popover-surface-max-width": surfaceMaxWidth } : null),
  };

  return (
    <div {...reactifyPart(parts.root)} className="poodle-popover" ref={setRootElement}>
      <div
        ref={triggerRef}
        {...reactifyPart(parts.trigger)}
        className="poodle-popover__trigger"
        onClick={() => sendRef.current({ type: "TOGGLE" })}
        onKeyDown={triggerIsInteractive ? undefined : (event) => {
          if (disabled) return;
          if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            sendRef.current({ type: "TOGGLE" });
          }
        }}
      >
        {typeof trigger === "function" ? trigger(parts.triggerState) : trigger}
      </div>

      {isOpen ? (
        <AnchoredSurface
          ref={surfaceRef}
          anchor={rootElement}
          placement={placement}
          offset={offset}
          matchWidth={surfaceWidth === "trigger"}
          onPlacement={setResolvedPlacement}
          onSurfaceGeometryChange={onSurfaceGeometryChange}
          {...reactifyPart(parts.surface)}
          className="poodle-popover__surface"
          style={surfaceStyle}
        >
          {children}
        </AnchoredSurface>
      ) : null}
    </div>
  );
}

// packages/svelte/components/src/Popover.svelte
<script lang="ts">
  import "@inflatable-cookie/poodle-core/styles/popover.css";
  import {
    getFocusableElements,
    layerContains,
    portalAnchorOf,
    portalledDescendantsOf,
    popoverParts,
    popoverTransition,
    registerDismissLayer,
    type PopoverContext,
    type PopoverEvent,
    type PopoverTriggerState,
    type OverlaySurfaceGeometryChangeHandler,
  } from "@inflatable-cookie/poodle-core";
  import { tick, untrack, type Snippet } from "svelte";

  import { anchored } from "./anchored";
  import type { OverlayPlacement, PopoverInitialFocus } from "./types";

  /**
   * The contracted Popover surface. `trigger` and the content take framework
   * snippets; `triggerIsInteractive` and `onSurfaceGeometryChange` are
   * documented web-only extensions kept beside this adapter.
   *
   * `triggerIsInteractive` discriminates the two compile-time trigger shapes
   * (contract §3): default mode takes a zero-argument `trigger` snippet and the
   * wrapper owns role/tab stop/disclosure ARIA; interactive mode requires a
   * `Snippet<[PopoverTriggerState]>` and the caller applies the payload to the
   * real control inside.
   *
   * Contract: `docs/contracts/components/popover.md`. The Rust counterpart is
   * `poodle_specs::PopoverSpec`.
   */
  interface CommonProps {
    open?: boolean | null;
    defaultOpen?: boolean;
    placement?: OverlayPlacement;
    offset?: number;
    dismissOnOutsideInteract?: boolean;
    initialFocus?: PopoverInitialFocus;
    ariaLabel?: string | null;
    block?: boolean;
    disabled?: boolean;
    surfaceWidth?: "content" | "trigger";
    surfaceMinWidth?: string | null;
    surfaceMaxWidth?: string | null;
    onOpenChange?: (open: boolean) => void;
    onSurfaceGeometryChange?: OverlaySurfaceGeometryChangeHandler | undefined;
    children?: Snippet<[]>;
  }

  type Props = CommonProps &
    (
      | {
          triggerIsInteractive?: false;
          trigger?: Snippet<[]>;
        }
      | {
          triggerIsInteractive: true;
          trigger: Snippet<[PopoverTriggerState]>;
        }
    );

  let {
    open = $bindable<boolean | null>(null),
    defaultOpen = false,
    placement = "bottom-start",
    offset = 8,
    dismissOnOutsideInteract = true,
    initialFocus = "first-focusable",
    ariaLabel = null,
    block = false,
    triggerIsInteractive = false,
    disabled = false,
    surfaceWidth = "content",
    surfaceMinWidth = null,
    surfaceMaxWidth = null,
    onOpenChange = undefined,
    onSurfaceGeometryChange = undefined,
    trigger,
    children,
  }: Props = $props();

  // Destructuring breaks the Props discriminated union's correlation between
  // `triggerIsInteractive` and the `trigger` snippet arity, so each render
  // branch below casts back to the shape its mode guarantees (contract §3).
  const triggerDefault = $derived(trigger as Snippet<[]> | undefined);
  const triggerWithState = $derived(trigger as Snippet<[PopoverTriggerState]> | undefined);

  // Svelte carries this identity from server output into hydration. A shared
  // module counter cannot do that in a long-lived SSR process because server
  // requests and client bundles advance independent counters.
  const componentId = $props.id();
  const popoverId = `poodle-popover-${componentId}`;
  let rootElement = $state<HTMLDivElement | null>(null);
  let triggerElement = $state<HTMLDivElement | null>(null);
  let surfaceElement = $state<HTMLDivElement | null>(null);
  // Seeded directly from the prop, not in `$effect.pre`: effects are stripped
  // from server output, so an effect-seeded initial state would render a
  // `defaultOpen` popover closed in SSR. The `untrack` closure is the explicit
  // "initial value only" read — the same value the effect applied before
  // first render on the client.
  let uncontrolledOpen = $state(untrack(() => defaultOpen));
  let previousOpen = $state(false);

  const isControlled = $derived(open !== null);
  // Disabled blocks open in every direction (contract §3): a controlled
  // `open` request while disabled stays inert — the machine's own guard,
  // mirrored here so the visible state can never disagree with it.
  const isOpen = $derived(!disabled && (isControlled ? open === true : uncontrolledOpen));
  // Null until the surface is measured; the anchored action reports back
  // whichever candidate survived collision resolution.
  let placementFromAnchor = $state<OverlayPlacement | null>(null);
  const resolvedPlacement = $derived(isOpen ? (placementFromAnchor ?? placement) : placement);

  $effect(() => {
    if (!(isOpen && !previousOpen)) {
      previousOpen = isOpen;
      return;
    }

    tick().then(() => {
      if (!surfaceElement) {
        return;
      }

      if (initialFocus === "content") {
        surfaceElement.focus();
        return;
      }

      if (initialFocus === "first-focusable") {
        getFocusableElements(surfaceElement)[0]?.focus();
      }
    });

    previousOpen = isOpen;
  });

  const machineContext = $derived<PopoverContext>({
    disabled,
    dismissOnOutsideInteract,
    initialFocus,
  });

  const parts = $derived(
    popoverParts(isOpen ? "open" : "closed", machineContext, {
      surfaceId: popoverId,
      ariaLabel,
      block,
      triggerIsInteractive,
      placement: resolvedPlacement,
      surfaceWidth,
    }),
  );

  function send(event: PopoverEvent): void {
    const result = popoverTransition(isOpen ? "open" : "closed", machineContext, event);

    for (const effect of result.effects) {
      switch (effect.type) {
        case "emitOpenChange": {
          if (isControlled) {
            open = effect.open;
          } else {
            uncontrolledOpen = effect.open;
          }

          onOpenChange?.(effect.open);
          break;
        }
        case "restoreTriggerFocus": {
          // With `triggerIsInteractive` the wrapper observes clicks without
          // becoming a button, so the operable control is the one the caller
          // composed inside it. Restoring focus to the wrapper would land it
          // on something that cannot be activated — the operator would press
          // Enter and nothing would happen.
          const target = triggerIsInteractive
            ? triggerElement?.querySelector<HTMLElement>(
                'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
              ) ?? triggerElement
            : triggerElement;
          target?.focus();
          break;
        }
        case "focusOnOpen": {
          // Executed by the isOpen $effect above, which waits for the surface
          // to render before applying the initialFocus strategy.
          break;
        }
      }
    }
  }

  /**
   * Tab from inside one of this popover's own portalled descendants — a
   * Select listbox opened from content in this surface, or any anchored
   * overlay a future child portals. The node lives at the theme root, so
   * the key never bubbles through the surface and no content-level trap
   * can see it; natively it would leave in document order while the child
   * stays open. Route it home instead: prevent the pass-through and focus
   * the control the portal opened from (the anchor's first focusable,
   * falling back into the surface). This is containment, not a trap — the
   * destination is always in-surface, where keys flow natively and no
   * content trap cycles, so exit stays one Tab away and nothing can loop.
   * In-surface targets are never touched; neither are other popovers'
   * surfaces, unless nested inside our own scope as portalled descendants.
   */
  function handleDocumentKeydown(event: KeyboardEvent): void {
    if (event.key !== "Tab" || !isOpen) {
      return;
    }

    const target = event.target;

    if (!(target instanceof Node)) {
      return;
    }

    // In-scope targets keep native flow and content-owned traps.
    if (layerContains(target, rootElement, surfaceElement)) {
      return;
    }

    const portalled = portalledDescendantsOf(rootElement, surfaceElement);

    // A surface that is not ours owns its own keys — a peer, or a nested
    // popover rendered elsewhere. But a nested popover surface that is
    // itself one of our portalled descendants stays in our scope: it fell
    // out of our subtree only through portalling, so Tabs inside it route
    // home to its anchor exactly like any other portal below.
    if (target instanceof Element) {
      const owner = target.closest(".poodle-popover__surface");

      if (
        owner !== null &&
        owner !== surfaceElement &&
        !portalled.includes(owner as HTMLElement)
      ) {
        return;
      }
    }

    const home = portalled.find((node) => node.contains(target));

    if (!home) {
      return;
    }

    const anchor = portalAnchorOf(home);
    const destination =
      (anchor ? getFocusableElements(anchor as HTMLElement)[0] : undefined) ??
      getFocusableElements(rootElement)[0] ??
      getFocusableElements(surfaceElement)[0] ??
      surfaceElement;
    event.preventDefault();
    destination?.focus();
  }

  $effect(() => {
    if (!isOpen) {
      return;
    }

    document.addEventListener("keydown", handleDocumentKeydown);

    return () => {
      document.removeEventListener("keydown", handleDocumentKeydown);
    };
  });

  $effect(() => {
    if (!isOpen) {
      return;
    }

    return registerDismissLayer({
      // The surface is portalled out of the root, so both are "inside".
      contains: (target) => layerContains(target, rootElement, surfaceElement),
      dismissOnOutsideInteract,
      onDismiss: (reason) => send(reason === "escape" ? { type: "ESCAPE" } : { type: "OUTSIDE_INTERACT" }),
      // Parenthood and stack order derive from real layer containment: the
      // layer's `contains` covers both the root and the portalled surface,
      // so a nested popover's root is contained by its host's layer no
      // matter where the surfaces were portalled to.
      hostElement: rootElement,
    });
  });
</script>

<div {...parts.root} class="poodle-popover" bind:this={rootElement}>
  <div
    bind:this={triggerElement}
    {...parts.trigger}
    class="poodle-popover__trigger"
    onclick={() => send({ type: "TOGGLE" })}
    onkeydown={triggerIsInteractive ? undefined : (event) => {
      if (disabled) {
        return;
      }

      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        send({ type: "TOGGLE" });
      }
    }}
  >
    {#if triggerIsInteractive}
      {@render triggerWithState?.(parts.triggerState)}
    {:else}
      {@render triggerDefault?.()}
    {/if}
  </div>

  {#if isOpen}
    <div
      bind:this={surfaceElement}
      use:anchored={{
        anchor: rootElement,
        placement,
        offset,
        matchWidth: surfaceWidth === "trigger",
        onPlacement: (next) => (placementFromAnchor = next),
        onSurfaceGeometryChange,
      }}
      {...parts.surface}
      class="poodle-popover__surface"
      style={[
        surfaceMinWidth ? `--poodle-popover-surface-min-width: ${surfaceMinWidth}` : "",
        surfaceMaxWidth ? `--poodle-popover-surface-max-width: ${surfaceMaxWidth}` : "",
      ].filter(Boolean).join("; ")}
    >
      {@render children?.()}
    </div>
  {/if}
</div>
