// packages/react/components/src/TriStateSwitch.tsx
import { useId, useState, type CSSProperties } from "react";
import { singleSelectTransition } from "@inflatable-cookie/poodle-headless";

import "@inflatable-cookie/poodle-styles/tri-state-switch.css";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, SemanticControlSizeRole, TriStateValue } from "./types";

export interface TriStateSwitchProps {
  value?: TriStateValue;
  defaultValue?: TriStateValue;
  options?: Record<TriStateValue, string>;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  disabled?: boolean;
  ariaLabel: string;
  excludedColor?: string | null;
  defaultColor?: string | null;
  includedColor?: string | null;
  onValueChange?: (value: TriStateValue) => void;
}

const ORDERED_VALUES: TriStateValue[] = ["excluded", "default", "included"];

export function TriStateSwitch({
  value,
  defaultValue = "default",
  options = { excluded: "Exclude", default: "Default", included: "Include" },
  size = null,
  sizeRole = "control",
  density = null,
  disabled = false,
  ariaLabel,
  excludedColor = null,
  defaultColor = null,
  includedColor = null,
  onValueChange,
}: TriStateSwitchProps) {
  const groupName = useId();
  const uiPresentation = useUiPresentation();
  const [uncontrolledValue, setUncontrolledValue] = useState<TriStateValue>(defaultValue);

  const isControlled = value !== undefined;
  const currentValue = isControlled ? value : uncontrolledValue;
  const selectedIndex = Math.max(0, ORDERED_VALUES.indexOf(currentValue));
  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;

  const style: CSSProperties & Record<string, string> = {
    "--poodle-tri-state-active-index": String(selectedIndex),
    ...(excludedColor ? { "--poodle-tri-state-excluded-color": excludedColor } : null),
    ...(defaultColor ? { "--poodle-tri-state-default-color": defaultColor } : null),
    ...(includedColor ? { "--poodle-tri-state-included-color": includedColor } : null),
  };

  function handleSelect(nextValue: TriStateValue): void {
    const result = singleSelectTransition(
      { value: currentValue, options: ORDERED_VALUES.map((candidate) => ({ value: candidate })), disabled },
      { type: "SELECT", value: nextValue },
    );
    for (const effect of result.effects) {
      if (effect.type === "emitValueChange") {
        if (!isControlled) setUncontrolledValue(effect.value as TriStateValue);
        onValueChange?.(effect.value as TriStateValue);
      }
    }
  }

  return (
    <div
      className="poodle-tri-state-switch"
      role="radiogroup"
      aria-label={ariaLabel}
      aria-disabled={disabled ? "true" : undefined}
      data-state={currentValue}
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-disabled={disabled}
      style={style}
    >
      <span className="poodle-tri-state-switch__selection" aria-hidden="true" />
      {ORDERED_VALUES.map((optionValue) => (
        <label
          key={optionValue}
          className="poodle-tri-state-switch__option"
          data-state={optionValue}
          data-selected={currentValue === optionValue}
        >
          <input
            className="poodle-tri-state-switch__control"
            type="radio"
            name={groupName}
            checked={currentValue === optionValue}
            disabled={disabled}
            aria-label={options[optionValue]}
            onChange={() => handleSelect(optionValue)}
          />
          <span className="poodle-tri-state-switch__segment">{options[optionValue]}</span>
        </label>
      ))}
    </div>
  );
}

// packages/svelte/components/src/TriStateSwitch.svelte
<script module lang="ts">
  let triStateSwitchInstanceCount = 0;
</script>

<script lang="ts">
  import "@inflatable-cookie/poodle-styles/tri-state-switch.css";
  import { singleSelectTransition } from "@inflatable-cookie/poodle-headless";

  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";

  import type {
    ControlDensity,
    ControlSize,
    SemanticControlSizeRole,
    TriStateValue,
  } from "./types";

  interface Props {
    value?: TriStateValue;
    options?: Record<TriStateValue, string>;
    size?: ControlSize | null;
    sizeRole?: SemanticControlSizeRole;
    density?: ControlDensity | null;
    disabled?: boolean;
    ariaLabel: string;
    excludedColor?: string | null;
    defaultColor?: string | null;
    includedColor?: string | null;
    onValueChange?: ((value: TriStateValue) => void) | undefined;
  }

  let {
    value = $bindable<TriStateValue>("default"),
    options = {
      excluded: "Exclude",
      default: "Default",
      included: "Include",
    },
    size = null,
    sizeRole = "control",
    density = null,
    disabled = false,
    ariaLabel,
    excludedColor = null,
    defaultColor = null,
    includedColor = null,
    onValueChange = undefined,
  }: Props = $props();

  const orderedValues: TriStateValue[] = ["excluded", "default", "included"];
  const instanceId = ++triStateSwitchInstanceCount;
  const groupName = `poodle-tri-state-switch-${instanceId}`;
  const uiPresentation = getUiPresentation();

  const selectedIndex = $derived(Math.max(0, orderedValues.indexOf(value)));
  const resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole));
  const resolvedDensity = $derived(density ?? $uiPresentation.density);
  const triStateStyles = $derived([
    excludedColor ? `--poodle-tri-state-excluded-color: ${excludedColor}` : "",
    defaultColor ? `--poodle-tri-state-default-color: ${defaultColor}` : "",
    includedColor ? `--poodle-tri-state-included-color: ${includedColor}` : "",
    `--poodle-tri-state-active-index: ${selectedIndex}`,
  ].filter(Boolean).join("; ") || undefined);

  function handleSelect(nextValue: TriStateValue): void {
    const result = singleSelectTransition(
      { value, options: orderedValues.map((candidate) => ({ value: candidate })), disabled },
      { type: "SELECT", value: nextValue },
    );

    for (const effect of result.effects) {
      if (effect.type === "emitValueChange") {
        value = effect.value as TriStateValue;
        onValueChange?.(effect.value as TriStateValue);
      }
    }
  }
</script>

<div
  class="poodle-tri-state-switch"
  role="radiogroup"
  aria-label={ariaLabel}
  aria-disabled={disabled ? "true" : undefined}
  data-state={value}
  data-size={resolvedSize}
  data-density={resolvedDensity}
  data-disabled={disabled}
  style={triStateStyles}
>
  <span class="poodle-tri-state-switch__selection" aria-hidden="true"></span>

  {#each orderedValues as optionValue}
    <label
      class="poodle-tri-state-switch__option"
      data-state={optionValue}
      data-selected={value === optionValue}
    >
      <input
        class="poodle-tri-state-switch__control"
        type="radio"
        name={groupName}
        checked={value === optionValue}
        disabled={disabled}
        aria-label={options[optionValue]}
        onchange={() => handleSelect(optionValue)}
      />
      <span class="poodle-tri-state-switch__segment">{options[optionValue]}</span>
    </label>
  {/each}
</div>
