// packages/react/preview/src/gallery/SceneSpecimen.tsx
import type { ReactNode } from "react";
import {
  Avatar,
  Callout,
  EmptyState,
  Pill,
  Spinner,
} from "@inflatable-cookie/poodle-react";
import { SpecimenGroup } from "./SpecimenGroup";
import { SpecimenLayout } from "./SpecimenLayout";
import { specimenScenes } from "../generated/specimens/specimen-scenes";

type FixtureValue = string | boolean | number | null;

interface FixtureInstance {
  component: string;
  caption?: string;
  props: Record<string, FixtureValue>;
}

interface FixtureGroup {
  label: string;
  instances: FixtureInstance[];
}

type FixtureScene = {
  id: string;
  name: string;
  description: string;
  tabs: readonly string[];
  sizeAxis: readonly string[];
  densityAxis: readonly string[];
  groups: readonly FixtureGroup[];
};

/**
 * The fixture renderer (g14-b005 tranche one): renders one display-specimen
 * scene in the React preview. The scene is generated data — groups,
 * instances, typed prop bindings, matrix axes. `content` bindings project
 * to children; every other binding forwards as a prop.
 */
export function SceneSpecimen({ slug }: { slug?: string }) {
  const scene = slug
    ? (specimenScenes[slug as keyof typeof specimenScenes] as unknown as FixtureScene | undefined)
    : undefined;

  // The fixture props are data; each component validates its own at runtime
  // where it matters, so the map is deliberately untyped.
  const componentMap: Record<string, (props: Record<string, FixtureValue>) => ReactNode> = {
    callout: ({ content, ...props }: any) => <Callout {...props}>{String(content)}</Callout>,
    pill: ({ content, ...props }: any) => <Pill {...props}>{String(content)}</Pill>,
    spinner: (props: any) => <Spinner {...props} />,
    avatar: (props: any) => <Avatar {...props} />,
    "empty-state": (props: any) => <EmptyState {...props} />,
  };

  function renderInstance(instance: FixtureInstance) {
    const render = componentMap[instance.component];
    return render ? render(instance.props) : null;
  }

  /** The matrix renders the scene's first instance at each axis value. */
  const matrixInstance = scene?.groups.flatMap((group) => group.instances)[0];

  if (!scene) return null;

  const sizes = (size: string): ReactNode =>
    matrixInstance ? renderInstance({ ...matrixInstance, props: { ...matrixInstance.props, size } }) : null;

  const densities = (density: string): ReactNode =>
    matrixInstance ? renderInstance({ ...matrixInstance, props: { ...matrixInstance.props, density } }) : null;

  return (
    <SpecimenLayout
      sizeValues={scene.sizeAxis.length > 0 ? scene.sizeAxis : undefined}
      densityValues={scene.densityAxis.length > 0 ? scene.densityAxis : undefined}
      sizes={scene.tabs.includes("sizes") ? sizes : undefined}
      densities={scene.tabs.includes("densities") ? densities : undefined}
    >
      {scene.groups.map((group) => (
        <SpecimenGroup key={group.label} label={group.label}>
          <div className="poodle-specimen__row">
            {group.instances.map((instance, index) => (
              <div key={index} className="poodle-specimen__cell">
                {renderInstance(instance)}
              </div>
            ))}
          </div>
        </SpecimenGroup>
      ))}
    </SpecimenLayout>
  );
}

// packages/svelte/preview/src/components/SceneSpecimen.svelte
<script lang="ts">
  import {
    Avatar,
    Callout,
    EmptyState,
    Pill,
    Spinner,
  } from "@inflatable-cookie/poodle-svelte";
  import type { Snippet } from "svelte";
  import SpecimenGroup from "./SpecimenGroup.svelte";
  import SpecimenLayout from "./SpecimenLayout.svelte";
  import { specimenScenes } from "../generated/specimens/specimen-scenes";

  let { slug, children }: { slug?: string; children?: Snippet } = $props();

  const scene = $derived(slug ? specimenScenes[slug as keyof typeof specimenScenes] : undefined);

  /**
   * The fixture renderer (g14-b005 tranche one): renders one display-specimen
   * scene in the Svelte preview. The scene is generated data — groups,
   * instances, typed prop bindings, matrix axes. `content` bindings project
   * to children; every other binding forwards as a prop.
   */
  const componentMap: Record<string, any> = {
    callout: Callout,
    pill: Pill,
    spinner: Spinner,
    avatar: Avatar,
    "empty-state": EmptyState,
  };

  /** The matrix renders the scene's first instance at each axis value. */
  const matrixInstance = $derived(scene?.groups.flatMap((group) => group.instances)[0]);

  function withoutContent(props: Record<string, unknown>) {
    const { content, ...rest } = props;
    return rest;
  }
</script>

{#snippet renderInstance(instance: { component: string; props: Record<string, unknown> })}
  {@const Cmp = componentMap[instance.component]}
  {#if Cmp}
    {#if instance.props.content != null}
      <svelte:component this={Cmp} {...withoutContent(instance.props)}>
        {String(instance.props.content)}
      </svelte:component>
    {:else}
      <svelte:component this={Cmp} {...withoutContent(instance.props)} />
    {/if}
  {/if}
{/snippet}

{#snippet sizes(size)}
  {#if matrixInstance}
    {@render renderInstance({
      component: matrixInstance.component,
      props: { ...matrixInstance.props, size },
    })}
  {/if}
{/snippet}

{#snippet densities(density)}
  {#if matrixInstance}
    {@render renderInstance({
      component: matrixInstance.component,
      props: { ...matrixInstance.props, density },
    })}
  {/if}
{/snippet}

{#if scene}
  <SpecimenLayout
    sizeValues={scene.sizeAxis.length > 0 ? scene.sizeAxis : undefined}
    densityValues={scene.densityAxis.length > 0 ? scene.densityAxis : undefined}
    sizes={(scene.tabs as readonly string[]).includes("sizes") ? (sizes as never) : undefined}
    densities={(scene.tabs as readonly string[]).includes("densities") ? (densities as never) : undefined}
  >
    {#each scene.groups as group}
      <SpecimenGroup label={group.label}>
        <div class="poodle-specimen__row">
          {#each group.instances as instance}
            <div class="poodle-specimen__cell">
              {@render renderInstance(instance)}
            </div>
          {/each}
        </div>
      </SpecimenGroup>
    {/each}
    {@render children?.()}
  </SpecimenLayout>
{/if}

<style>
  .poodle-specimen__row {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
    align-items: center;
  }

  .poodle-specimen__cell {
    display: inline-flex;
    align-items: center;
  }
</style>
