// packages/svelte/composites/src/ActionDiscoveryPanel.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  import {
    Eyebrow,
    ListCard,
    Skeleton,
    UiPresentationProvider,
    getUiPresentation,
    resolveSemanticControlSize,
  } from "@poodle/svelte-primitives";
  import type {
    ControlDensity,
    ControlSize,
    SemanticControlSizeRole,
  } from "@poodle/svelte-primitives";
  import EmptyState from "./EmptyState.svelte";

  import type { CommandActionItem, DiscoveryState } from "./types";

  export let items: CommandActionItem[] = [];
  export let state: DiscoveryState = "ready";
  export let activeId: string | null = null;
  export let ariaLabel = "Actions";
  export let size: ControlSize | null = null;
  export let sizeRole: SemanticControlSizeRole = "control";
  export let density: ControlDensity | null = null;

  const dispatch = createEventDispatcher<{
    itemSelect: { id: string };
    activeChange: { id: string | null };
  }>();

  let itemElements: Array<HTMLElement | null> = [];
  const uiPresentation = getUiPresentation();

  $: resolvedSize = size ?? resolveSemanticControlSize(uiPresentation?.sizeScale ?? "md", sizeRole);
  $: resolvedDensity = density ?? uiPresentation?.density ?? "default";

  $: enabledItems = items.filter((item) => !item.disabled);
  $: groupedItems = items.reduce<Record<string, CommandActionItem[]>>((acc, item) => {
    const group = item.group ?? "Commands";
    acc[group] ??= [];
    acc[group].push(item);
    return acc;
  }, {});
  $: groupEntries = Object.entries(groupedItems);

  export function moveActive(step: 1 | -1): void {
    if (enabledItems.length === 0) return;
    const idx = enabledItems.findIndex((item) => item.id === activeId);
    const next = idx === -1 ? 0 : (idx + step + enabledItems.length) % enabledItems.length;
    setActive(enabledItems[next]?.id ?? null);
  }

  export function moveToBoundary(direction: "start" | "end"): void {
    if (enabledItems.length === 0) return;
    setActive(direction === "start" ? enabledItems[0]?.id ?? null : enabledItems[enabledItems.length - 1]?.id ?? null);
  }

  export function selectActive(): void {
    if (activeId) dispatch("itemSelect", { id: activeId });
  }

  export function getEnabledItems(): CommandActionItem[] {
    return enabledItems;
  }

  function setActive(id: string | null): void {
    activeId = id;
    dispatch("activeChange", { id });

    if (id) {
      const idx = enabledItems.findIndex((item) => item.id === id);
      if (idx >= 0) {
        queueMicrotask(() => {
          itemElements[idx]?.scrollIntoView({ block: "nearest" });
        });
      }
    }
  }
</script>

<UiPresentationProvider sizeScale={resolvedSize} density={resolvedDensity}>
  <div
    class="action-discovery-panel"
    role="listbox"
    aria-label={ariaLabel}
    data-size={resolvedSize}
    data-density={resolvedDensity}
  >
    {#if state === "loading"}
      <div class="action-discovery-panel__state">
        <div class="action-discovery-panel__skeletons" aria-hidden="true">
          {#each Array.from({ length: 5 }) as _}
            <div class="action-discovery-panel__skeleton-row">
              <Skeleton width="48%" />
              <Skeleton width="20%" />
            </div>
          {/each}
        </div>
      </div>
    {:else if state === "error"}
      <EmptyState
        title="Could not load actions"
        message="Actions could not be loaded. Try again."
      />
    {:else if state === "empty"}
      <EmptyState
        title="No actions available"
        message="No actions are available in this context."
      />
    {:else if state === "no-results"}
      <EmptyState
        title="No matching actions"
        message="No actions match the current search."
        variant="search"
      />
    {:else}
      {#each groupEntries as [group, groupItems]}
        <div class="action-discovery-panel__group">
          <Eyebrow>{group}</Eyebrow>
          <ul class="action-discovery-panel__list">
            {#each groupItems as item (item.id)}
              <li
                bind:this={itemElements[enabledItems.findIndex((e) => e.id === item.id)]}
                role="option"
                aria-selected={activeId === item.id}
              >
                <ListCard
                  title={item.title}
                  subtitle={item.description}
                  interactive={!item.disabled}
                  disabled={item.disabled ?? false}
                  ariaLabel={item.title}
                  on:click={() => dispatch("itemSelect", { id: item.id })}
                  on:mouseenter={() => setActive(item.id)}
                  on:focus={() => setActive(item.id)}
                >
                  <svelte:fragment slot="trailing">
                    <span class="action-discovery-panel__trailing">
                      {#if item.badge}
                        <span class="action-discovery-panel__badge">{item.badge}</span>
                      {/if}
                      {#if item.shortcut}
                        <kbd class="action-discovery-panel__kbd">{item.shortcut}</kbd>
                      {/if}
                    </span>
                  </svelte:fragment>
                </ListCard>
              </li>
            {/each}
          </ul>
        </div>
      {/each}
    {/if}
  </div>
</UiPresentationProvider>

<style>
  .action-discovery-panel {
    --poodle-action-discovery-stack-gap: 0.75rem;
    --poodle-action-discovery-group-gap: 0.375rem;
    --poodle-action-discovery-list-gap: 0.25rem;
    --poodle-action-discovery-chip-height: 1.5rem;
    --poodle-action-discovery-chip-x: 0.5rem;
    --poodle-action-discovery-chip-gap: 0.375rem;
    --poodle-action-discovery-skeleton-pad: 0.875rem;
    display: grid;
    gap: var(--poodle-action-discovery-stack-gap);
    min-height: 0;
    overflow: auto;
    overscroll-behavior: contain;
  }

  .action-discovery-panel[data-size="xs"] {
    --poodle-action-discovery-chip-height: 1.25rem;
    --poodle-action-discovery-chip-x: 0.375rem;
  }

  .action-discovery-panel[data-size="sm"] {
    --poodle-action-discovery-chip-height: 1.5rem;
  }

  .action-discovery-panel[data-size="lg"] {
    --poodle-action-discovery-chip-height: 1.75rem;
    --poodle-action-discovery-chip-x: 0.625rem;
  }

  .action-discovery-panel[data-size="xl"] {
    --poodle-action-discovery-chip-height: 2rem;
    --poodle-action-discovery-chip-x: 0.75rem;
  }

  .action-discovery-panel[data-density="compact"] {
    --poodle-action-discovery-stack-gap: 0.5rem;
    --poodle-action-discovery-group-gap: 0.25rem;
    --poodle-action-discovery-list-gap: 0.1875rem;
    --poodle-action-discovery-chip-gap: 0.25rem;
    --poodle-action-discovery-skeleton-pad: 0.625rem;
  }

  .action-discovery-panel[data-density="comfortable"] {
    --poodle-action-discovery-stack-gap: 0.875rem;
    --poodle-action-discovery-group-gap: 0.5rem;
    --poodle-action-discovery-list-gap: 0.375rem;
    --poodle-action-discovery-chip-gap: 0.5rem;
    --poodle-action-discovery-skeleton-pad: 1rem;
  }

  .action-discovery-panel__group {
    display: grid;
    gap: var(--poodle-action-discovery-group-gap);
  }

  .action-discovery-panel__list {
    display: grid;
    gap: var(--poodle-action-discovery-list-gap);
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .action-discovery-panel__list li[aria-selected="true"] :global(.list-card) {
    border-color: transparent;
    background: color-mix(in srgb, var(--poodle-color-accent-base) 18%, var(--poodle-color-background-elevated));
    box-shadow: inset 0 0 0 0.0625rem color-mix(in srgb, var(--poodle-color-accent-base) 22%, transparent);
  }

  .action-discovery-panel__trailing {
    display: flex;
    flex-wrap: wrap;
    gap: var(--poodle-action-discovery-chip-gap);
    align-items: center;
  }

  .action-discovery-panel__badge,
  .action-discovery-panel__kbd {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-height: var(--poodle-action-discovery-chip-height);
    padding: 0 var(--poodle-action-discovery-chip-x);
    border-radius: var(--poodle-radius-control);
    background: color-mix(in srgb, var(--poodle-color-background-surface) 76%, transparent);
    color: var(--poodle-color-text-secondary);
    font-size: var(--poodle-typography-label-size);
  }

  .action-discovery-panel__kbd {
    font-family: var(--poodle-typography-code-family);
  }

  .action-discovery-panel__state {
    display: grid;
    gap: var(--poodle-space-stack-sm);
  }

  .action-discovery-panel__skeletons {
    display: grid;
    gap: var(--poodle-space-stack-sm);
  }

  .action-discovery-panel__skeleton-row {
    display: grid;
    grid-template-columns: minmax(0, 1fr) auto;
    gap: var(--poodle-space-inline-md);
    padding: var(--poodle-action-discovery-skeleton-pad);
    border-radius: calc(var(--poodle-radius-surface) - 0.125rem);
    background: color-mix(in srgb, var(--poodle-color-background-surface) 72%, transparent);
  }
</style>

// packages/react/components/src/ActionDiscoveryPanel.tsx
import "@poodle/styles/action-discovery-panel.css";

import { forwardRef, useImperativeHandle, useRef, useState } from "react";

import { EmptyState } from "./EmptyState";
import { Eyebrow } from "./Eyebrow";
import { ListCard } from "./ListCard";
import { Skeleton } from "./Skeleton";
import { UiPresentationProvider, resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type {
  CommandActionItem,
  ControlDensity,
  ControlSize,
  DiscoveryState,
  SemanticControlSizeRole,
} from "./types";

export interface ActionDiscoveryPanelProps {
  items?: CommandActionItem[];
  state?: DiscoveryState;
  activeId?: string | null;
  defaultActiveId?: string | null;
  ariaLabel?: string;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  onItemSelect?: ((id: string) => void) | null;
  onActiveChange?: ((id: string | null) => void) | null;
}

export interface ActionDiscoveryPanelHandle {
  moveActive: (step: 1 | -1) => void;
  moveToBoundary: (direction: "start" | "end") => void;
  selectActive: () => void;
  getEnabledItems: () => CommandActionItem[];
}

export const ActionDiscoveryPanel = forwardRef<ActionDiscoveryPanelHandle, ActionDiscoveryPanelProps>(
  function ActionDiscoveryPanel(
    {
      items = [],
      state: discoveryState = "ready",
      activeId: controlledActiveId,
      defaultActiveId = null,
      ariaLabel = "Actions",
      size = null,
      sizeRole = "control",
      density = null,
      onItemSelect = null,
      onActiveChange = null,
    },
    ref,
  ) {
    const uiPresentation = useUiPresentation();
    const [uncontrolledActiveId, setUncontrolledActiveId] = useState<string | null>(defaultActiveId);
    const activeId = controlledActiveId !== undefined ? controlledActiveId : uncontrolledActiveId;
    const itemRefs = useRef<Array<HTMLElement | null>>([]);

    const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
    const resolvedDensity = density ?? uiPresentation.density;
    const enabledItems = items.filter((item) => !item.disabled);
    const groupedItems = items.reduce<Record<string, CommandActionItem[]>>((acc, item) => {
      const group = item.group ?? "Commands";
      acc[group] ??= [];
      acc[group].push(item);
      return acc;
    }, {});
    const groupEntries = Object.entries(groupedItems);

    function setActive(id: string | null): void {
      if (controlledActiveId === undefined) {
        setUncontrolledActiveId(id);
      }
      onActiveChange?.(id);

      if (id) {
        const idx = enabledItems.findIndex((item) => item.id === id);
        if (idx >= 0) {
          queueMicrotask(() => {
            itemRefs.current[idx]?.scrollIntoView({ block: "nearest" });
          });
        }
      }
    }

    useImperativeHandle(ref, () => ({
      moveActive(step: 1 | -1): void {
        if (enabledItems.length === 0) return;
        const idx = enabledItems.findIndex((item) => item.id === activeId);
        const next = idx === -1 ? 0 : (idx + step + enabledItems.length) % enabledItems.length;
        setActive(enabledItems[next]?.id ?? null);
      },
      moveToBoundary(direction: "start" | "end"): void {
        if (enabledItems.length === 0) return;
        setActive(
          direction === "start" ? (enabledItems[0]?.id ?? null) : (enabledItems[enabledItems.length - 1]?.id ?? null),
        );
      },
      selectActive(): void {
        if (activeId) onItemSelect?.(activeId);
      },
      getEnabledItems(): CommandActionItem[] {
        return enabledItems;
      },
    }));

    return (
      <UiPresentationProvider sizeScale={resolvedSize} density={resolvedDensity}>
        <div
          className="poodle-action-discovery-panel"
          role="listbox"
          aria-label={ariaLabel}
          data-size={resolvedSize}
          data-density={resolvedDensity}
        >
          {discoveryState === "loading" ? (
            <div className="poodle-action-discovery-panel__state">
              <div className="poodle-action-discovery-panel__skeletons" aria-hidden="true">
                {Array.from({ length: 5 }).map((_, index) => (
                  <div key={index} className="poodle-action-discovery-panel__skeleton-row">
                    <Skeleton width="48%" />
                    <Skeleton width="20%" />
                  </div>
                ))}
              </div>
            </div>
          ) : discoveryState === "error" ? (
            <EmptyState title="Could not load actions" message="Actions could not be loaded. Try again." />
          ) : discoveryState === "empty" ? (
            <EmptyState title="No actions available" message="No actions are available in this context." />
          ) : discoveryState === "no-results" ? (
            <EmptyState title="No matching actions" message="No actions match the current search." variant="search" />
          ) : (
            groupEntries.map(([group, groupItems]) => (
              <div key={group} className="poodle-action-discovery-panel__group">
                <Eyebrow>{group}</Eyebrow>
                <ul className="poodle-action-discovery-panel__list">
                  {groupItems.map((item) => (
                    <li
                      key={item.id}
                      ref={(el) => {
                        const idx = enabledItems.findIndex((enabledItem) => enabledItem.id === item.id);
                        if (idx >= 0) {
                          itemRefs.current[idx] = el;
                        }
                      }}
                      role="option"
                      aria-selected={activeId === item.id}
                      onMouseEnter={() => setActive(item.id)}
                      onFocus={() => setActive(item.id)}
                    >
                      <ListCard
                        title={item.title}
                        subtitle={item.description}
                        interactive={!item.disabled}
                        disabled={item.disabled ?? false}
                        ariaLabel={item.title}
                        onClick={() => onItemSelect?.(item.id)}
                        trailing={
                          <span className="poodle-action-discovery-panel__trailing">
                            {item.badge ? (
                              <span className="poodle-action-discovery-panel__badge">{item.badge}</span>
                            ) : null}
                            {item.shortcut ? (
                              <kbd className="poodle-action-discovery-panel__kbd">{item.shortcut}</kbd>
                            ) : null}
                          </span>
                        }
                      />
                    </li>
                  ))}
                </ul>
              </div>
            ))
          )}
        </div>
      </UiPresentationProvider>
    );
  },
);
