// packages/svelte/primitives/src/Calendar.svelte
<script context="module" lang="ts">
  let nextCalendarId = 0;
</script>

<script lang="ts">
  import { createEventDispatcher, tick } from "svelte";

  import {
    addDays,
    addMonths,
    buildCalendarWeeks,
    compareIsoDate,
    dayDeltaForWeekBoundary,
    formatDateLabel,
    formatIsoDate,
    formatMonthLabel,
    getWeekdayLabels,
    isIsoDateWithinRange,
    monthAnchorIso,
    normalizeDateRange,
    parseIsoDate,
    todayIsoDate,
  } from "./date";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";

  import type { CalendarWeekStart, ControlDensity, ControlSize, DateRangeValue, SemanticControlSizeRole } from "./types";

  export let mode: "single" | "range" = "single";
  export let value: string | DateRangeValue | null = null;
  export let defaultValue: string | DateRangeValue | null = null;
  export let visibleMonth: string | null = null;
  export let weekStartsOn: CalendarWeekStart = "monday";
  export let locale = "en-US";
  export let disabled = false;
  export let ariaLabel: string | null = null;
  export let size: ControlSize | null = null;
  export let sizeRole: SemanticControlSizeRole = "control";
  export let density: ControlDensity | null = null;

  const dispatch = createEventDispatcher<{
    valueChange: { value: string } | { value: DateRangeValue };
    monthChange: { month: string };
  }>();

  const gridId = `poodle-calendar-grid-${++nextCalendarId}`;
  const uiPresentation = getUiPresentation();

  // Single mode state
  let uncontrolledSingleValue: string | null =
    mode === "single" && typeof defaultValue === "string" ? defaultValue : null;

  // Range mode state
  let uncontrolledRangeValue: DateRangeValue =
    mode === "range" && defaultValue !== null && typeof defaultValue === "object"
      ? normalizeDateRange(defaultValue as DateRangeValue)
      : { start: null, end: null };

  let uncontrolledMonth = monthAnchorIso(
    visibleMonth ??
    (mode === "range"
      ? (typeof defaultValue === "object" && defaultValue !== null ? (defaultValue as DateRangeValue).start : null) ?? todayIsoDate()
      : (typeof defaultValue === "string" ? defaultValue : null) ?? todayIsoDate())
  );

  let focusIso = mode === "range"
    ? (typeof defaultValue === "object" && defaultValue !== null ? (defaultValue as DateRangeValue).start : null) ?? todayIsoDate()
    : (typeof defaultValue === "string" ? defaultValue : null) ?? todayIsoDate();

  let dayElements: Record<string, HTMLButtonElement | undefined> = {};

  $: resolvedSize = size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole);
  $: resolvedDensity = density ?? $uiPresentation.density;

  // Resolved current values based on mode
  $: currentSingleValue = mode === "single"
    ? (typeof value === "string" ? value : null) ?? uncontrolledSingleValue
    : null;
  $: currentRangeValue = mode === "range"
    ? normalizeDateRange(
        (value !== null && typeof value === "object" ? value as DateRangeValue : null) ?? uncontrolledRangeValue
      )
    : { start: null, end: null };

  $: currentMonth = monthAnchorIso(visibleMonth ?? uncontrolledMonth);
  $: weeks = buildCalendarWeeks(currentMonth, weekStartsOn);
  $: weekdayLabels = getWeekdayLabels(weekStartsOn, locale);
  $: monthLabel = formatMonthLabel(currentMonth, locale);

  // Update focusIso when values change
  $: if (mode === "single" && currentSingleValue) {
    focusIso = currentSingleValue;
  }
  $: if (mode === "range") {
    if (currentRangeValue.end) {
      focusIso = currentRangeValue.end;
    } else if (currentRangeValue.start) {
      focusIso = currentRangeValue.start;
    }
  }

  // Day state helpers for range mode
  function isRangeStart(iso: string): boolean {
    return mode === "range" && currentRangeValue.start === iso;
  }
  function isRangeEnd(iso: string): boolean {
    return mode === "range" && currentRangeValue.end === iso;
  }
  function isInRange(iso: string): boolean {
    return mode === "range" && isIsoDateWithinRange(iso, currentRangeValue);
  }
  function isSelected(iso: string): boolean {
    if (mode === "single") {
      return currentSingleValue === iso;
    }
    return isRangeStart(iso) || isRangeEnd(iso);
  }

  function setMonth(nextMonth: string): void {
    if (visibleMonth === null) {
      uncontrolledMonth = nextMonth;
    }

    dispatch("monthChange", { month: nextMonth });
  }

  function selectDate(iso: string): void {
    if (disabled) {
      return;
    }

    if (mode === "single") {
      if (value === null) {
        uncontrolledSingleValue = iso;
      }

      focusIso = iso;
      dispatch("valueChange", { value: iso });
    } else {
      // Range mode: two-click selection
      if (!currentRangeValue.start || currentRangeValue.end) {
        commitRange({ start: iso, end: null });
        return;
      }

      if (compareIsoDate(iso, currentRangeValue.start) < 0) {
        commitRange({ start: iso, end: currentRangeValue.start });
        return;
      }

      commitRange({ start: currentRangeValue.start, end: iso });
    }
  }

  function commitRange(nextValue: DateRangeValue): void {
    const normalized = normalizeDateRange(nextValue);

    if (value === null) {
      uncontrolledRangeValue = normalized;
    }

    focusIso = normalized.end ?? normalized.start ?? focusIso;
    dispatch("valueChange", { value: normalized });
  }

  async function focusDate(iso: string): Promise<void> {
    focusIso = iso;
    const nextMonth = monthAnchorIso(iso);

    if (nextMonth !== currentMonth) {
      setMonth(nextMonth);
      await tick();
    }

    dayElements[iso]?.focus();
  }

  function handleDayKeydown(event: KeyboardEvent, iso: string): void {
    const date = parseIsoDate(iso);

    if (!date) {
      return;
    }

    let nextDate = date;

    if (event.key === "ArrowRight") {
      event.preventDefault();
      nextDate = addDays(date, 1);
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      nextDate = addDays(date, -1);
    } else if (event.key === "ArrowDown") {
      event.preventDefault();
      nextDate = addDays(date, 7);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      nextDate = addDays(date, -7);
    } else if (event.key === "Home") {
      event.preventDefault();
      nextDate = addDays(date, dayDeltaForWeekBoundary(iso, weekStartsOn, "start"));
    } else if (event.key === "End") {
      event.preventDefault();
      nextDate = addDays(date, dayDeltaForWeekBoundary(iso, weekStartsOn, "end"));
    } else if (event.key === "PageDown") {
      event.preventDefault();
      nextDate = addMonths(date, 1);
    } else if (event.key === "PageUp") {
      event.preventDefault();
      nextDate = addMonths(date, -1);
    } else if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      selectDate(iso);
      return;
    } else {
      return;
    }

    focusDate(formatIsoDate(nextDate) ?? todayIsoDate());
  }
</script>

<div class="calendar" data-size={resolvedSize} data-density={resolvedDensity} data-mode={mode} aria-label={ariaLabel ?? undefined}>
  <div class="calendar__header">
    <button
      type="button"
      class="calendar__nav"
      disabled={disabled}
      aria-label="Previous month"
      on:click={() => setMonth(monthAnchorIso(formatIsoDate(addMonths(parseIsoDate(currentMonth)!, -1))))}
    >
      <span aria-hidden="true">&#x2039;</span>
    </button>

    <div class="calendar__month" aria-live="polite">
      {monthLabel}
    </div>

    <button
      type="button"
      class="calendar__nav"
      disabled={disabled}
      aria-label="Next month"
      on:click={() => setMonth(monthAnchorIso(formatIsoDate(addMonths(parseIsoDate(currentMonth)!, 1))))}
    >
      <span aria-hidden="true">&#x203A;</span>
    </button>
  </div>

  <div class="calendar__weekdays" aria-hidden="true">
    {#each weekdayLabels as label}
      <span class="calendar__weekday">{label}</span>
    {/each}
  </div>

  <div id={gridId} class="calendar__grid" role="grid" aria-label={ariaLabel ?? monthLabel}>
    {#each weeks as week}
      <div class="calendar__week" role="row">
        {#each week as day}
          <div
            class="calendar__cell"
            role="gridcell"
            aria-selected={isSelected(day.iso) ? "true" : "false"}
          >
            <button
              bind:this={dayElements[day.iso]}
              type="button"
              class="calendar__day"
              data-current-month={day.inMonth}
              data-selected={mode === "single" && currentSingleValue === day.iso}
              data-today={day.isToday}
              data-range-start={isRangeStart(day.iso)}
              data-range-end={isRangeEnd(day.iso)}
              data-in-range={isInRange(day.iso)}
              disabled={disabled}
              aria-label={formatDateLabel(day.iso, locale)}
              tabindex={focusIso === day.iso ? 0 : -1}
              on:click={() => selectDate(day.iso)}
              on:focus={() => (focusIso = day.iso)}
              on:keydown={(event) => handleDayKeydown(event, day.iso)}
            >
              {day.label}
            </button>
          </div>
        {/each}
      </div>
    {/each}
  </div>
</div>

<style>
  .calendar {
    display: grid;
    gap: 0.75rem;
    width: 18rem;
  }

  .calendar__header,
  .calendar__weekdays,
  .calendar__week {
    display: grid;
    grid-template-columns: repeat(7, minmax(0, 1fr));
    align-items: center;
  }

  .calendar__header {
    grid-template-columns: auto minmax(0, 1fr) auto;
    gap: 0.5rem;
  }

  .calendar__month {
    font-family: var(--poodle-typography-label-family);
    font-size: 0.8125rem;
    font-weight: 600;
    letter-spacing: 0.02em;
    text-align: center;
  }

  .calendar__nav {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 2rem;
    height: 2rem;
    border: 0.0625rem solid var(--poodle-color-border-default);
    border-radius: var(--poodle-radius-control);
    background: var(--poodle-color-background-surface);
    color: var(--poodle-color-text-primary);
    cursor: pointer;
    font: inherit;
  }

  .calendar__nav:hover:not(:disabled) {
    background: color-mix(in srgb, var(--poodle-color-background-surface) 82%, var(--poodle-color-background-elevated));
  }

  .calendar__weekdays {
    gap: 0.125rem;
  }

  .calendar__weekday {
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-label-family);
    font-size: 0.6875rem;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-align: center;
    text-transform: uppercase;
  }

  .calendar__grid {
    display: grid;
    gap: 0.125rem;
  }

  .calendar__week {
    gap: 0.125rem;
  }

  .calendar__cell {
    display: grid;
  }

  .calendar__day {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-height: 2.25rem;
    padding: 0.25rem;
    border: 0.0625rem solid transparent;
    border-radius: var(--poodle-radius-control);
    background: transparent;
    color: var(--poodle-color-text-primary);
    cursor: pointer;
    font-family: var(--poodle-typography-label-family);
    font-size: 0.75rem;
    font-weight: 500;
  }

  .calendar__day[data-current-month="false"] {
    color: var(--poodle-color-text-secondary);
    opacity: 0.72;
  }

  .calendar__day[data-today="true"] {
    border-color: color-mix(in srgb, var(--poodle-color-accent-base) 44%, var(--poodle-color-border-default));
  }

  /* Single mode: selected day */
  .calendar__day[data-selected="true"] {
    background: var(--poodle-color-accent-base);
    color: var(--poodle-color-text-inverse);
  }

  /* Range mode: in-range days */
  .calendar__day[data-in-range="true"] {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 16%, transparent);
  }

  /* Range mode: range endpoints */
  .calendar__day[data-range-start="true"],
  .calendar__day[data-range-end="true"] {
    background: var(--poodle-color-accent-base);
    color: var(--poodle-color-text-inverse);
  }

  .calendar__day:hover:not(:disabled),
  .calendar__day:focus-visible {
    border-color: color-mix(in srgb, var(--poodle-color-accent-base) 46%, var(--poodle-color-border-default));
    background: color-mix(in srgb, var(--poodle-color-accent-base) 14%, transparent);
    outline: none;
  }

  .calendar__day[data-selected="true"]:hover:not(:disabled),
  .calendar__day[data-selected="true"]:focus-visible {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 88%, white 8%);
  }

  .calendar__day[data-range-start="true"]:hover:not(:disabled),
  .calendar__day[data-range-start="true"]:focus-visible,
  .calendar__day[data-range-end="true"]:hover:not(:disabled),
  .calendar__day[data-range-end="true"]:focus-visible {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 88%, white 8%);
  }

  .calendar__nav:focus-visible {
    outline: var(--poodle-border-width-focus) solid var(--poodle-color-accent-focusRing);
    outline-offset: 0.125rem;
  }

  .calendar__nav:disabled,
  .calendar__day:disabled {
    cursor: not-allowed;
    opacity: var(--poodle-state-opacity-disabled);
  }

  /* Size variants */
  .calendar[data-size="xs"] { width: 14.5rem; }
  .calendar[data-size="sm"] { width: 16rem; }
  .calendar[data-size="lg"] { width: 20.5rem; }
  .calendar[data-size="xl"] { width: 23rem; }

  .calendar[data-size="xs"] .calendar__nav {
    width: 1.5rem;
    height: 1.5rem;
  }

  .calendar[data-size="xs"] .calendar__day {
    min-height: 1.75rem;
    font-size: 0.6875rem;
  }

  .calendar[data-size="xs"] .calendar__month {
    font-size: 0.6875rem;
  }

  .calendar[data-size="sm"] .calendar__nav {
    width: 1.75rem;
    height: 1.75rem;
  }

  .calendar[data-size="sm"] .calendar__day {
    min-height: 2rem;
  }

  .calendar[data-size="lg"] .calendar__nav {
    width: 2.25rem;
    height: 2.25rem;
  }

  .calendar[data-size="lg"] .calendar__day {
    min-height: 2.5rem;
    font-size: 0.8125rem;
  }

  .calendar[data-size="lg"] .calendar__month {
    font-size: 0.875rem;
  }

  .calendar[data-size="xl"] .calendar__nav {
    width: 2.5rem;
    height: 2.5rem;
  }

  .calendar[data-size="xl"] .calendar__day {
    min-height: 2.75rem;
    font-size: 0.875rem;
  }

  .calendar[data-size="xl"] .calendar__month {
    font-size: 0.9375rem;
  }

  /* Density variants */
  .calendar[data-density="compact"] .calendar__grid { gap: 0; }
  .calendar[data-density="compact"] .calendar__week { gap: 0; }
  .calendar[data-density="compact"] .calendar__nav { gap: 0.25rem; }
  .calendar[data-density="comfortable"] .calendar__grid { gap: 0.375rem; }
  .calendar[data-density="comfortable"] .calendar__week { gap: 0.375rem; }
  .calendar[data-density="comfortable"] .calendar__nav { gap: 0.75rem; }
</style>

// packages/react/components/src/Calendar.tsx
import { useEffect, useId, useRef, useState, type ChangeEvent, type FormEvent, type KeyboardEvent } from "react";
import {
  addDays,
  addMonths,
  buildCalendarWeeks,
  compareIsoDate,
  dayDeltaForWeekBoundary,
  formatDateLabel,
  formatIsoDate,
  formatMonthLabel,
  getWeekdayLabels,
  isIsoDateWithinRange,
  monthAnchorIso,
  normalizeDateRange,
  parseIsoDate,
  todayIsoDate,
} from "@inflatable-cookie/poodle-core";

import "@inflatable-cookie/poodle-core/styles/calendar.css";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type {
  CalendarWeekStart,
  ControlDensity,
  ControlSize,
  DateRangeValue,
  SemanticControlSizeRole,
} from "./types";

export interface CalendarProps {
  mode?: "single" | "range";
  value?: string | DateRangeValue | null;
  defaultValue?: string | DateRangeValue | null;
  visibleMonth?: string | null;
  weekStartsOn?: CalendarWeekStart;
  locale?: string;
  disabled?: boolean;
  ariaLabel?: string | null;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  onValueChange?: (value: string | DateRangeValue) => void;
  onMonthChange?: (month: string) => void;
}

const EMPTY_RANGE: DateRangeValue = { start: null, end: null };

export function Calendar({
  mode = "single",
  value,
  defaultValue = null,
  visibleMonth,
  weekStartsOn = "monday",
  locale = "en-US",
  disabled = false,
  ariaLabel = null,
  size = null,
  sizeRole = "control",
  density = null,
  onValueChange,
  onMonthChange,
}: CalendarProps) {
  const gridId = useId();
  const uiPresentation = useUiPresentation();

  const [uncontrolledSingleValue, setUncontrolledSingleValue] = useState<string | null>(() =>
    mode === "single" && typeof defaultValue === "string" ? defaultValue : null,
  );
  const [uncontrolledRangeValue, setUncontrolledRangeValue] = useState<DateRangeValue>(() =>
    mode === "range" && defaultValue !== null && typeof defaultValue === "object"
      ? normalizeDateRange(defaultValue as DateRangeValue)
      : EMPTY_RANGE,
  );
  const [uncontrolledMonth, setUncontrolledMonth] = useState(() =>
    monthAnchorIso(
      visibleMonth ??
        (mode === "range"
          ? ((typeof defaultValue === "object" && defaultValue !== null ? (defaultValue as DateRangeValue).start : null) ??
            todayIsoDate())
          : ((typeof defaultValue === "string" ? defaultValue : null) ?? todayIsoDate())),
    ),
  );
  const [focusIso, setFocusIso] = useState(() =>
    mode === "range"
      ? ((typeof defaultValue === "object" && defaultValue !== null ? (defaultValue as DateRangeValue).start : null) ??
        todayIsoDate())
      : ((typeof defaultValue === "string" ? defaultValue : null) ?? todayIsoDate()),
  );
  const [editingMonth, setEditingMonth] = useState(false);
  const [editingYear, setEditingYear] = useState(false);
  const [monthDraft, setMonthDraft] = useState("");
  const [yearDraft, setYearDraft] = useState("");
  const dayElements = useRef<Record<string, HTMLButtonElement | undefined>>({});
  const monthSelectRef = useRef<HTMLSelectElement | null>(null);
  const yearInputRef = useRef<HTMLInputElement | null>(null);
  const pendingDayFocus = useRef<string | null>(null);

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const hasControlledValue = value !== undefined;
  const hasControlledVisibleMonth = visibleMonth !== undefined;
  const currentSingleValue =
    mode === "single" ? (hasControlledValue ? (typeof value === "string" ? value : null) : uncontrolledSingleValue) : null;
  const currentRangeValue =
    mode !== "range"
      ? EMPTY_RANGE
      : normalizeDateRange(
          hasControlledValue
            ? value !== null && typeof value === "object"
              ? (value as DateRangeValue)
              : EMPTY_RANGE
            : uncontrolledRangeValue,
        );
  const currentMonth = monthAnchorIso(hasControlledVisibleMonth ? (visibleMonth ?? uncontrolledMonth) : uncontrolledMonth);
  const currentMonthDate = parseIsoDate(currentMonth) ?? parseIsoDate(todayIsoDate())!;
  const weeks = buildCalendarWeeks(currentMonth, weekStartsOn);
  const weekdayLabels = getWeekdayLabels(weekStartsOn, locale);
  const monthLabel = formatMonthLabel(currentMonth, locale);
  const monthName = new Intl.DateTimeFormat(locale, { month: "long", timeZone: "UTC" }).format(currentMonthDate);
  const yearLabel = String(currentMonthDate.getUTCFullYear());
  const monthOptions = Array.from({ length: 12 }, (_, monthIndex) => ({
    value: String(monthIndex),
    label: new Intl.DateTimeFormat(locale, { month: "long", timeZone: "UTC" }).format(new Date(Date.UTC(2000, monthIndex, 1))),
  }));

  // focus tracking follows the committed value (Svelte parity)
  useEffect(() => {
    if (mode === "single" && currentSingleValue) {
      setFocusIso(currentSingleValue);
      return;
    }
    if (mode === "range") {
      if (currentRangeValue.end) setFocusIso(currentRangeValue.end);
      else if (currentRangeValue.start) setFocusIso(currentRangeValue.start);
    }
  }, [mode, currentSingleValue, currentRangeValue.start, currentRangeValue.end]);

  useEffect(() => {
    if (editingMonth) monthSelectRef.current?.focus();
  }, [editingMonth]);

  useEffect(() => {
    if (editingYear) {
      yearInputRef.current?.focus();
      yearInputRef.current?.select();
    }
  }, [editingYear]);

  // focus a day cell after a month change re-render
  useEffect(() => {
    if (pendingDayFocus.current) {
      dayElements.current[pendingDayFocus.current]?.focus();
      pendingDayFocus.current = null;
    }
  });

  const isRangeStart = (iso: string) => mode === "range" && currentRangeValue.start === iso;
  const isRangeEnd = (iso: string) => mode === "range" && currentRangeValue.end === iso;
  const isInRange = (iso: string) => mode === "range" && isIsoDateWithinRange(iso, currentRangeValue);
  const isSelected = (iso: string) =>
    mode === "single" ? currentSingleValue === iso : isRangeStart(iso) || isRangeEnd(iso);

  function setMonth(nextMonth: string): void {
    if (!hasControlledVisibleMonth) setUncontrolledMonth(nextMonth);
    onMonthChange?.(nextMonth);
  }

  function commitSingleValue(nextValue: string): void {
    if (!hasControlledValue) setUncontrolledSingleValue(nextValue);
    setFocusIso(nextValue);
    onValueChange?.(nextValue);
  }

  function commitRange(nextValue: DateRangeValue): void {
    const normalized = normalizeDateRange(nextValue);
    if (!hasControlledValue) setUncontrolledRangeValue(normalized);
    setFocusIso(normalized.end ?? normalized.start ?? focusIso);
    onValueChange?.(normalized);
  }

  function selectDate(iso: string): void {
    if (disabled) return;
    if (mode === "single") {
      commitSingleValue(iso);
      return;
    }
    if (!currentRangeValue.start || currentRangeValue.end) {
      commitRange({ start: iso, end: null });
      return;
    }
    if (compareIsoDate(iso, currentRangeValue.start) < 0) {
      commitRange({ start: iso, end: currentRangeValue.start });
      return;
    }
    commitRange({ start: currentRangeValue.start, end: iso });
  }

  function focusDate(iso: string): void {
    setFocusIso(iso);
    const nextMonth = monthAnchorIso(iso);
    if (nextMonth !== currentMonth) {
      pendingDayFocus.current = iso;
      setMonth(nextMonth);
      return;
    }
    dayElements.current[iso]?.focus();
  }

  function handleDayKeydown(event: KeyboardEvent<HTMLButtonElement>, iso: string): void {
    const date = parseIsoDate(iso);
    if (!date) return;

    let nextDate = date;
    if (event.key === "ArrowRight") {
      event.preventDefault();
      nextDate = addDays(date, 1);
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      nextDate = addDays(date, -1);
    } else if (event.key === "ArrowDown") {
      event.preventDefault();
      nextDate = addDays(date, 7);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      nextDate = addDays(date, -7);
    } else if (event.key === "Home") {
      event.preventDefault();
      nextDate = addDays(date, dayDeltaForWeekBoundary(iso, weekStartsOn, "start"));
    } else if (event.key === "End") {
      event.preventDefault();
      nextDate = addDays(date, dayDeltaForWeekBoundary(iso, weekStartsOn, "end"));
    } else if (event.key === "PageDown") {
      event.preventDefault();
      nextDate = addMonths(date, 1);
    } else if (event.key === "PageUp") {
      event.preventDefault();
      nextDate = addMonths(date, -1);
    } else if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      selectDate(iso);
      return;
    } else {
      return;
    }

    focusDate(formatIsoDate(nextDate) ?? todayIsoDate());
  }

  function commitMonthDraft(draft: string): void {
    const parsedMonth = Number(draft);
    if (!Number.isInteger(parsedMonth) || parsedMonth < 0 || parsedMonth > 11) {
      setEditingMonth(false);
      return;
    }
    const nextDate = new Date(Date.UTC(currentMonthDate.getUTCFullYear(), parsedMonth, 1));
    setMonth(monthAnchorIso(formatIsoDate(nextDate) ?? currentMonth));
    setEditingMonth(false);
  }

  function commitYearDraft(): void {
    const trimmed = yearDraft.trim();
    const parsedYear = Number(trimmed);
    if (!Number.isInteger(parsedYear) || trimmed.length !== 4) {
      setEditingYear(false);
      return;
    }
    const nextDate = new Date(Date.UTC(parsedYear, currentMonthDate.getUTCMonth(), 1));
    setMonth(monthAnchorIso(formatIsoDate(nextDate) ?? currentMonth));
    setEditingYear(false);
  }

  function handleYearDraftBeforeInput(event: FormEvent<HTMLInputElement>): void {
    const native = event.nativeEvent as InputEvent;
    if (
      native.data &&
      !/^\d+$/.test(native.data) &&
      native.inputType !== "deleteContentBackward" &&
      native.inputType !== "deleteContentForward"
    ) {
      event.preventDefault();
      return;
    }
    if (native.data && /^\d+$/.test(native.data) && yearDraft.length >= 4 && native.inputType?.startsWith("insert")) {
      event.preventDefault();
    }
  }

  return (
    <div
      className="poodle-calendar"
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-mode={mode}
      aria-label={ariaLabel ?? undefined}
    >
      <div className="poodle-calendar__header">
        <button
          type="button"
          className="poodle-calendar__nav"
          disabled={disabled}
          aria-label="Previous month"
          onClick={() => setMonth(monthAnchorIso(formatIsoDate(addMonths(parseIsoDate(currentMonth)!, -1))))}
        >
          <span aria-hidden="true">‹</span>
        </button>

        <div className="poodle-calendar__month" aria-live="polite">
          {editingMonth ? (
            <select
              ref={monthSelectRef}
              className="poodle-calendar__month-select"
              value={monthDraft}
              aria-label="Select month"
              onChange={(event: ChangeEvent<HTMLSelectElement>) => {
                setMonthDraft(event.currentTarget.value);
                commitMonthDraft(event.currentTarget.value);
              }}
              onBlur={() => setEditingMonth(false)}
              onKeyDown={(event) => {
                if (event.key === "Escape") {
                  event.preventDefault();
                  setEditingMonth(false);
                }
              }}
            >
              {monthOptions.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          ) : (
            <button
              type="button"
              className="poodle-calendar__month-button"
              disabled={disabled}
              aria-label={`Edit month, currently ${monthName}`}
              onDoubleClick={() => {
                if (disabled) return;
                setEditingYear(false);
                setMonthDraft(String(currentMonthDate.getUTCMonth()));
                setEditingMonth(true);
              }}
            >
              <span className="poodle-calendar__month-name">{monthName}</span>
            </button>
          )}
          {editingYear ? (
            <input
              ref={yearInputRef}
              className="poodle-calendar__year-input"
              type="number"
              min={1}
              max={9999}
              step={1}
              inputMode="numeric"
              aria-label="Edit year"
              value={yearDraft}
              onBeforeInput={handleYearDraftBeforeInput}
              onChange={(event) => setYearDraft(event.currentTarget.value)}
              onBlur={commitYearDraft}
              onKeyDown={(event) => {
                if (["e", "E", "+", "-", "."].includes(event.key)) {
                  event.preventDefault();
                  return;
                }
                if (event.key === "Enter") {
                  event.preventDefault();
                  commitYearDraft();
                } else if (event.key === "Escape") {
                  event.preventDefault();
                  setEditingYear(false);
                }
              }}
            />
          ) : (
            <button
              type="button"
              className="poodle-calendar__year-button"
              disabled={disabled}
              aria-label={`Edit year, currently ${yearLabel}`}
              onDoubleClick={() => {
                if (disabled) return;
                setEditingMonth(false);
                setYearDraft(yearLabel);
                setEditingYear(true);
              }}
            >
              {yearLabel}
            </button>
          )}
        </div>

        <button
          type="button"
          className="poodle-calendar__nav"
          disabled={disabled}
          aria-label="Next month"
          onClick={() => setMonth(monthAnchorIso(formatIsoDate(addMonths(parseIsoDate(currentMonth)!, 1))))}
        >
          <span aria-hidden="true">›</span>
        </button>
      </div>

      <div className="poodle-calendar__weekdays" aria-hidden="true">
        {weekdayLabels.map((label, i) => (
          <span key={i} className="poodle-calendar__weekday">
            {label}
          </span>
        ))}
      </div>

      <div id={gridId} className="poodle-calendar__grid" role="grid" aria-label={ariaLabel ?? monthLabel}>
        {weeks.map((week, wi) => (
          <div key={wi} className="poodle-calendar__week" role="row">
            {week.map((day) => (
              <div key={day.iso} className="poodle-calendar__cell" role="gridcell" aria-selected={isSelected(day.iso)}>
                <button
                  ref={(node) => {
                    dayElements.current[day.iso] = node ?? undefined;
                  }}
                  type="button"
                  className="poodle-calendar__day"
                  data-current-month={day.inMonth}
                  data-selected={mode === "single" && currentSingleValue === day.iso}
                  data-today={day.isToday}
                  data-range-start={isRangeStart(day.iso)}
                  data-range-end={isRangeEnd(day.iso)}
                  data-in-range={isInRange(day.iso)}
                  disabled={disabled}
                  aria-label={formatDateLabel(day.iso, locale)}
                  tabIndex={focusIso === day.iso ? 0 : -1}
                  onClick={() => selectDate(day.iso)}
                  onFocus={() => setFocusIso(day.iso)}
                  onKeyDown={(event) => handleDayKeydown(event, day.iso)}
                >
                  {day.label}
                </button>
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}
