// packages/svelte/primitives/src/CodeInput.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";

  import Field from "./Field.svelte";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";
  import type { ControlDensity, ControlSize, SemanticControlSizeRole, ValidationState } from "./types";

  export let id: string | null = null;
  export let value: string | null = null;
  export let defaultValue = "";
  export let name = "code";
  export let label = "Authenticator code";
  export let hint: string | null = null;
  export let error: string | null = null;
  export let disabled = false;
  export let length = 6;
  export let mask = false;
  export let ariaLabel: string | null = null;
  export let size: ControlSize | null = null;
  export let sizeRole: SemanticControlSizeRole = "control";
  export let density: ControlDensity | null = null;
  export let autocomplete: HTMLInputAttributes["autocomplete"] = "one-time-code";
  export let validationState: ValidationState = "none";

  const dispatch = createEventDispatcher<{
    valueChange: { value: string };
    complete: { value: string };
  }>();

  const uiPresentation = getUiPresentation();

  let uncontrolledValue = defaultValue;
  let inputRef: HTMLInputElement | null = null;
  let caretIndex = 0;
  let hasFocus = false;

  $: resolvedSize = size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole);
  $: resolvedDensity = density ?? $uiPresentation.density;
  $: effectiveId = id ?? `code-${name}`;
  $: isControlled = value !== null;
  $: currentValue = sanitizeValue(isControlled ? value ?? "" : uncontrolledValue);
  $: digits = Array.from({ length }, (_, index) => currentValue[index] ?? "");
  $: effectiveValidationState = error ? "invalid" : validationState;
  $: activeCaretIndex = Math.min(caretIndex, Math.max(length - 1, 0));
  $: slotBorderColor =
    effectiveValidationState === "invalid"
      ? "var(--poodle-color-status-danger)"
      : "var(--poodle-color-border-default)";
  $: slotFocusColor =
    effectiveValidationState === "invalid"
      ? "var(--poodle-color-status-danger)"
      : "var(--poodle-color-accent-border)";
  $: slotFocusRing =
    effectiveValidationState === "invalid"
      ? "color-mix(in srgb, var(--poodle-color-status-danger) 24%, transparent)"
      : "color-mix(in srgb, var(--poodle-color-accent-focusRing) 28%, transparent)";

  function sanitizeValue(input: string): string {
    return input.replace(/\D/g, "").slice(0, length);
  }

  function updateValue(nextRawValue: string): void {
    const nextValue = sanitizeValue(nextRawValue);

    if (!isControlled) {
      uncontrolledValue = nextValue;
    }

    dispatch("valueChange", { value: nextValue });

    if (nextValue.length === length) {
      dispatch("complete", { value: nextValue });
    }
  }

  function syncCaret(): void {
    if (!inputRef) return;
    const selectionStart = inputRef.selectionStart ?? currentValue.length;
    caretIndex = Math.min(selectionStart, Math.max(length - 1, 0));
  }

  function handleInput(event: Event): void {
    const input = event.currentTarget as HTMLInputElement;
    updateValue(input.value);
    syncCaret();
  }

  function handleKeydown(): void {
    requestAnimationFrame(syncCaret);
  }

  function handleFocus(): void {
    hasFocus = true;
    caretIndex = Math.min(currentValue.length, Math.max(length - 1, 0));
  }

  function handleBlur(): void {
    hasFocus = false;
  }

  function handleSlotClick(index: number): void {
    inputRef?.focus();

    if (!inputRef) return;

    const nextPosition = Math.min(index, currentValue.length);
    inputRef.setSelectionRange(nextPosition, nextPosition);
    caretIndex = Math.min(nextPosition, Math.max(length - 1, 0));
  }

  function displayDigit(digit: string): string {
    if (!digit) return "";
    return mask ? "\u2022" : digit;
  }
</script>

<Field
  id={effectiveId}
  {label}
  hint={hint}
  error={error}
  validationState={effectiveValidationState}
>
  <svelte:fragment let:describedBy>
    <input type="hidden" {name} value={currentValue} />

    <div
      class="code-input"
      class:code-input--disabled={disabled}
      class:code-input--focused={hasFocus}
      data-size={resolvedSize}
      data-density={resolvedDensity}
      style={`--code-slot-border:${slotBorderColor}; --code-slot-focus:${slotFocusColor}; --code-slot-focus-ring:${slotFocusRing};`}
      role="group"
      aria-label={ariaLabel ?? label}
    >
      <input
        bind:this={inputRef}
        id={effectiveId}
        class="code-input__control"
        type="text"
        inputmode="numeric"
        pattern="[0-9]*"
        maxlength={length}
        {disabled}
        value={currentValue}
        {autocomplete}
        aria-label={ariaLabel ?? label}
        aria-describedby={describedBy ?? undefined}
        aria-invalid={effectiveValidationState === "invalid" ? "true" : undefined}
        oninput={handleInput}
        onkeydown={handleKeydown}
        onkeyup={handleKeydown}
        onfocus={handleFocus}
        onblur={handleBlur}
      />

      {#each digits as digit, index}
        <button
          type="button"
          class="code-input__slot"
          class:code-input__slot--active={hasFocus && index === activeCaretIndex}
          class:code-input__slot--filled={digit.length > 0}
          class:code-input__slot--split-after={length === 6 && index === 2}
          tabindex={-1}
          onclick={() => handleSlotClick(index)}
          aria-hidden="true"
        >
          {displayDigit(digit)}
        </button>
      {/each}
    </div>
  </svelte:fragment>
</Field>

<style>
  .code-input {
    position: relative;
    display: inline-flex;
    gap: var(--poodle-space-inline-sm);
    width: max-content;
  }

  .code-input__control {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
    cursor: text;
    z-index: 1;
  }

  .code-input__slot {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 2.25rem;
    height: 2.25rem;
    padding: 0;
    border: 0.0625rem solid var(--code-slot-border, var(--poodle-color-border-default));
    border-radius: var(--poodle-radius-control);
    background: var(--poodle-color-background-surface);
    color: var(--poodle-color-text-primary);
    font-family: var(--poodle-typography-code-family);
    font-size: 1rem;
    font-weight: 600;
    line-height: 1;
    text-align: center;
    cursor: text;
    transition: border-color var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard), box-shadow var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard);
    z-index: 0;
  }

  .code-input__slot--active {
    border-color: var(--code-slot-focus, var(--poodle-color-accent-border));
    box-shadow: 0 0 0 var(--poodle-border-width-focus) var(--code-slot-focus-ring, color-mix(in srgb, var(--poodle-color-accent-focusRing) 28%, transparent));
  }

  .code-input__slot--split-after {
    margin-right: var(--poodle-space-inline-md);
  }

  .code-input--disabled .code-input__slot {
    opacity: var(--poodle-state-opacity-disabled);
    cursor: not-allowed;
  }

  .code-input[data-size="xs"] .code-input__slot {
    width: 1.5rem;
    height: 1.5rem;
    font-size: 0.8125rem;
  }

  .code-input[data-size="sm"] .code-input__slot {
    width: 1.75rem;
    height: 1.75rem;
    font-size: 0.875rem;
  }

  .code-input[data-size="lg"] .code-input__slot {
    width: 2.75rem;
    height: 2.75rem;
    font-size: 1.125rem;
  }

  .code-input[data-size="xl"] .code-input__slot {
    width: 3.25rem;
    height: 3.25rem;
    font-size: 1.25rem;
  }

  .code-input[data-density="compact"] {
    gap: 0.25rem;
  }

  .code-input[data-density="comfortable"] {
    gap: var(--poodle-space-inline-md);
  }

  @media (max-width: 30rem) {
    .code-input__slot {
      width: 2rem;
      height: 2rem;
      font-size: 0.9375rem;
    }

    .code-input__slot--split-after {
      margin-right: var(--poodle-space-inline-sm);
    }
  }
</style>

// packages/react/components/src/CodeInput.tsx
import {
  useRef,
  useState,
  type ChangeEvent,
  type CSSProperties,
  type FormEvent,
  type KeyboardEvent,
} from "react";
import {
  clampCodePosition,
  codeInsertReplacement,
  codeSelectionRange,
  codeSlotSelection,
  sanitizeCodeValue,
} from "@poodle/headless";

import "@poodle/styles/code-input.css";

import { Field } from "./Field";
import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, SemanticControlSizeRole, ValidationState } from "./types";

export interface CodeInputProps {
  id?: string | null;
  value?: string | null;
  defaultValue?: string;
  name?: string;
  label?: string;
  hint?: string | null;
  error?: string | null;
  disabled?: boolean;
  length?: number;
  mask?: boolean;
  numbersOnly?: boolean;
  ariaLabel?: string | null;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  autoComplete?: string;
  validationState?: ValidationState;
  onValueChange?: (value: string) => void;
  onComplete?: (value: string) => void;
}

export function CodeInput({
  id = null,
  value,
  defaultValue = "",
  name = "code",
  label = "Authenticator code",
  hint = null,
  error = null,
  disabled = false,
  length = 6,
  mask = false,
  numbersOnly = true,
  ariaLabel = null,
  size = null,
  sizeRole = "control",
  density = null,
  autoComplete = "one-time-code",
  validationState = "none",
  onValueChange,
  onComplete,
}: CodeInputProps) {
  const uiPresentation = useUiPresentation();

  const sanitize = (input: string) => sanitizeCodeValue(input, length, numbersOnly);

  const [uncontrolledValue, setUncontrolledValue] = useState(() => sanitize(defaultValue));
  const [caretIndex, setCaretIndex] = useState(0);
  const [hasFocus, setHasFocus] = useState(false);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const pendingSelection = useRef<{ start: number; end: number } | null>(null);

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const effectiveId = id ?? `code-${name}`;
  const isControlled = value !== undefined;
  const currentValue = sanitize(isControlled ? (value ?? "") : uncontrolledValue);
  const currentValueRef = useRef(currentValue);
  currentValueRef.current = currentValue;
  const digits = Array.from({ length }, (_, index) => currentValue[index] ?? "");
  const effectiveValidationState = error ? "invalid" : validationState;
  const activeCaretIndex = Math.min(caretIndex, Math.max(length - 1, 0));

  const slotBorderColor =
    effectiveValidationState === "invalid" ? "var(--poodle-color-status-danger)" : "var(--poodle-color-border-default)";
  const slotFocusColor =
    effectiveValidationState === "invalid" ? "var(--poodle-color-status-danger)" : "var(--poodle-color-accent-border)";
  const slotFocusRing =
    effectiveValidationState === "invalid"
      ? "color-mix(in srgb, var(--poodle-color-status-danger) 24%, transparent)"
      : "color-mix(in srgb, var(--poodle-color-accent-focusRing) 28%, transparent)";

  function updateValue(nextRawValue: string): void {
    const nextValue = sanitize(nextRawValue);
    if (!isControlled) setUncontrolledValue(nextValue);
    onValueChange?.(nextValue);
    if (nextValue.length === length) onComplete?.(nextValue);
  }

  function syncCaret(): void {
    if (!inputRef.current) return;
    const selectionStart = inputRef.current.selectionStart ?? currentValueRef.current.length;
    setCaretIndex(Math.min(selectionStart, Math.max(length - 1, 0)));
  }

  function applyPendingSelection(): void {
    if (!inputRef.current || !pendingSelection.current) return;
    inputRef.current.setSelectionRange(pendingSelection.current.start, pendingSelection.current.end);
    setCaretIndex(Math.min(pendingSelection.current.start, Math.max(length - 1, 0)));
    pendingSelection.current = null;
  }

  function setActivePosition(index: number, selectFilled: boolean): void {
    if (!inputRef.current) return;
    const nextPosition = clampCodePosition(index, currentValueRef.current.length, length);
    const range = codeSelectionRange(nextPosition, currentValueRef.current.length, selectFilled);
    inputRef.current.setSelectionRange(range.start, range.end);
    setCaretIndex(nextPosition);
  }

  function handleInput(event: ChangeEvent<HTMLInputElement>): void {
    updateValue(event.currentTarget.value);
    requestAnimationFrame(() => {
      applyPendingSelection();
      syncCaret();
    });
  }

  function handleKeydown(event: KeyboardEvent<HTMLInputElement>): void {
    if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
      event.preventDefault();
      if (!inputRef.current) return;
      const nextPosition = event.key === "ArrowLeft" ? caretIndex - 1 : caretIndex + 1;
      setActivePosition(nextPosition, true);
      return;
    }
    requestAnimationFrame(syncCaret);
  }

  function handleFocus(): void {
    setHasFocus(true);
    requestAnimationFrame(() => {
      const hadPendingSelection = pendingSelection.current !== null;
      applyPendingSelection();
      if (hadPendingSelection) return;
      setActivePosition(Math.min(currentValueRef.current.length, Math.max(length - 1, 0)), false);
    });
  }

  function handleSlotClick(index: number): void {
    inputRef.current?.focus();
    if (!inputRef.current) return;
    pendingSelection.current = codeSlotSelection(index, currentValueRef.current.length);
    requestAnimationFrame(() => {
      applyPendingSelection();
    });
  }

  function handleBeforeInput(event: FormEvent<HTMLInputElement>): void {
    const native = event.nativeEvent as InputEvent;
    if (disabled) return;

    if (!inputRef.current || !native.inputType?.startsWith("insert")) {
      if (
        numbersOnly &&
        native.data &&
        !/^\d+$/.test(native.data) &&
        native.inputType !== "deleteContentBackward" &&
        native.inputType !== "deleteContentForward"
      ) {
        event.preventDefault();
      }
      return;
    }

    const selectionStart = inputRef.current.selectionStart ?? currentValueRef.current.length;
    const selectionEnd = inputRef.current.selectionEnd ?? selectionStart;
    const replacement = codeInsertReplacement(
      currentValueRef.current,
      native.data ?? "",
      selectionStart,
      selectionEnd,
      length,
      numbersOnly,
    );

    event.preventDefault();
    if (!replacement) return;

    updateValue(replacement.value);
    requestAnimationFrame(() => {
      setActivePosition(replacement.caret, true);
    });
  }

  function displayDigit(digit: string): string {
    if (!digit) return "";
    return mask ? "•" : digit;
  }

  return (
    <Field
      id={effectiveId}
      label={label}
      hint={hint}
      error={error}
      validationState={effectiveValidationState}
      control={({ describedBy }) => (
        <>
          <input type="hidden" name={name} value={currentValue} />

          <div
            className={[
              "poodle-code-input",
              disabled ? "poodle-code-input--disabled" : "",
              hasFocus ? "poodle-code-input--focused" : "",
            ]
              .filter(Boolean)
              .join(" ")}
            data-size={resolvedSize}
            data-density={resolvedDensity}
            style={
              {
                "--code-slot-border": slotBorderColor,
                "--code-slot-focus": slotFocusColor,
                "--code-slot-focus-ring": slotFocusRing,
              } as CSSProperties
            }
            role="group"
            aria-label={ariaLabel ?? label}
          >
            <input
              ref={inputRef}
              id={effectiveId}
              className="poodle-code-input__control"
              type="text"
              inputMode={numbersOnly ? "numeric" : "text"}
              pattern={numbersOnly ? "[0-9]*" : undefined}
              maxLength={length}
              disabled={disabled}
              value={currentValue}
              autoComplete={autoComplete}
              aria-label={ariaLabel ?? label}
              aria-describedby={describedBy ?? undefined}
              aria-invalid={effectiveValidationState === "invalid" ? "true" : undefined}
              onBeforeInput={handleBeforeInput}
              onChange={handleInput}
              onKeyDown={handleKeydown}
              onFocus={handleFocus}
              onBlur={() => setHasFocus(false)}
            />

            {digits.map((digit, index) => (
              <button
                key={index}
                type="button"
                className={[
                  "poodle-code-input__slot",
                  hasFocus && index === activeCaretIndex ? "poodle-code-input__slot--active" : "",
                  digit.length > 0 ? "poodle-code-input__slot--filled" : "",
                  length === 6 && index === 2 ? "poodle-code-input__slot--split-after" : "",
                ]
                  .filter(Boolean)
                  .join(" ")}
                tabIndex={-1}
                onMouseDown={(event) => event.preventDefault()}
                onClick={() => handleSlotClick(index)}
                aria-hidden="true"
              >
                {displayDigit(digit)}
              </button>
            ))}
          </div>
        </>
      )}
    />
  );
}
