// packages/svelte/composites/src/DataTable.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  import { Checkbox, Icon, Popover, getUiPresentation, resolveSemanticControlSize } from "@poodle/svelte-primitives";
  import type { ControlSize, SemanticControlSizeRole } from "@poodle/svelte-primitives";

  import type { TableColumn, TableRow, TableSortDirection } from "./types";

  export let ariaLabel = "Data table";
  export let columns: TableColumn[] = [];
  export let rows: TableRow[] = [];
  export let selectedRowIds: string[] = [];
  export let sortColumnId: string | null = null;
  export let sortDirection: TableSortDirection = "asc";
  export let rowActionLabel = "Open";
  export let showRowActions = true;
  export let emptyMessage = "No rows match the current view.";
  export let hiddenColumnIds: string[] = [];
  export let showColumnVisibility = false;
  export let showExport = false;
  export let exportFilename = "export.csv";
  export let size: ControlSize | null = null;
  export let sizeRole: SemanticControlSizeRole = "control";

  const dispatch = createEventDispatcher<{
    sortChange: { columnId: string; direction: TableSortDirection };
    rowToggle: { rowId: string; selected: boolean };
    toggleAll: { selected: boolean };
    rowAction: { rowId: string };
    columnVisibilityChange: { columnId: string; visible: boolean };
    exportCsv: { filename: string };
  }>();

  const uiPresentation = getUiPresentation();

  $: resolvedSize = size ?? resolveSemanticControlSize(uiPresentation?.sizeScale ?? "md", sizeRole);

  $: visibleColumns = columns.filter((c) => !hiddenColumnIds.includes(c.id));
  $: hideableColumns = columns.filter((c) => c.hideable !== false);
  $: selectableRowCount = rows.length;
  $: selectionCount = rows.filter((row) => selectedRowIds.includes(row.id)).length;
  $: allRowsSelected = selectableRowCount > 0 && selectionCount === selectableRowCount;
  $: mixedSelection = selectionCount > 0 && !allRowsSelected;

  function requestSort(column: TableColumn): void {
    if (!column.sortable) {
      return;
    }

    const direction =
      sortColumnId === column.id && sortDirection === "asc"
        ? "desc"
        : "asc";

    dispatch("sortChange", { columnId: column.id, direction });
  }

  function toggleColumnVisibility(columnId: string): void {
    const isHidden = hiddenColumnIds.includes(columnId);
    dispatch("columnVisibilityChange", { columnId, visible: isHidden });
  }

  function handleExport(): void {
    const header = visibleColumns.map((c) => c.label).join(",");
    const body = rows
      .map((row) =>
        visibleColumns
          .map((col) => {
            const val = row.cells[col.id] ?? "";
            return val.includes(",") || val.includes('"')
              ? `"${val.replace(/"/g, '""')}"`
              : val;
          })
          .join(","),
      )
      .join("\n");
    const csv = `${header}\n${body}`;
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = exportFilename;
    link.click();
    URL.revokeObjectURL(url);
    dispatch("exportCsv", { filename: exportFilename });
  }
</script>

<div class="data-table" data-size={resolvedSize}>
  {#if showColumnVisibility || showExport}
    <div class="data-table__toolbar">
      {#if showExport}
        <button
          type="button"
          class="data-table__toolbar-btn"
          on:click={handleExport}
          aria-label="Export as CSV"
        >
          <Icon name="download" />
          Export
        </button>
      {/if}

      {#if showColumnVisibility && hideableColumns.length > 0}
        <Popover placement="bottom-end" ariaLabel="Column visibility">
          <span slot="trigger" class="data-table__toolbar-btn">
            <Icon name="columns-3" />
            Columns
          </span>
          <div class="data-table__col-menu" role="menu">
            {#each hideableColumns as col}
              <label class="data-table__col-menu-item">
                <Checkbox
                  ariaLabel={col.label}
                  checked={!hiddenColumnIds.includes(col.id)}
                  on:checkedChange={() => toggleColumnVisibility(col.id)}
                />
                <span>{col.label}</span>
              </label>
            {/each}
          </div>
        </Popover>
      {/if}
    </div>
  {/if}

  <table aria-label={ariaLabel}>
    <caption class="data-table__caption">
      {ariaLabel}. {selectionCount} selected row{selectionCount === 1 ? "" : "s"} out of {selectableRowCount}.
    </caption>
    <thead>
      <tr>
        <th class="data-table__selection">
          <Checkbox
            ariaLabel="Select all visible rows"
            checked={allRowsSelected}
            mixed={mixedSelection}
            on:checkedChange={(event) => dispatch("toggleAll", { selected: event.detail.checked })}
          />
        </th>
        {#each visibleColumns as column}
          <th
            scope="col"
            class:end-align={column.align === "end"}
            aria-sort={column.sortable && sortColumnId === column.id ? (sortDirection === "asc" ? "ascending" : "descending") : column.sortable ? "none" : undefined}
          >
            {#if column.sortable}
              <button
                type="button"
                class="data-table__sort"
                on:click={() => requestSort(column)}
                aria-label={`Sort by ${column.label}${sortColumnId === column.id ? `, currently ${sortDirection}` : ""}`}
              >
                <span>{column.label}</span>
                {#if sortColumnId === column.id}
                  <span aria-hidden="true"><Icon name={sortDirection === "asc" ? "arrow-up" : "arrow-down"} /></span>
                {/if}
              </button>
            {:else}
              <span>{column.label}</span>
            {/if}
          </th>
        {/each}
        {#if showRowActions}
          <th scope="col" class="data-table__actions-header">Actions</th>
        {/if}
      </tr>
    </thead>
    <tbody>
      {#if rows.length === 0}
        <tr>
          <td colspan={visibleColumns.length + (showRowActions ? 2 : 1)} class="data-table__empty">
            {emptyMessage}
          </td>
        </tr>
      {:else}
        {#each rows as row}
          <tr class:selected={selectedRowIds.includes(row.id)} aria-selected={selectedRowIds.includes(row.id)}>
            <td class="data-table__selection">
              <Checkbox
                ariaLabel={`Select row ${row.cells[visibleColumns[0]?.id ?? "id"] ?? row.id}`}
                checked={selectedRowIds.includes(row.id)}
                on:checkedChange={(event) =>
                  dispatch("rowToggle", { rowId: row.id, selected: event.detail.checked })}
              />
            </td>
            {#each visibleColumns as column, index}
              <svelte:element this={index === 0 ? "th" : "td"} scope={index === 0 ? "row" : undefined} class:end-align={column.align === "end"}>
                <div class="data-table__cell">
                  <span>{row.cells[column.id] ?? "—"}</span>
                  {#if column.id === visibleColumns[0]?.id && row.summary}
                    <small>{row.summary}</small>
                  {/if}
                </div>
              </svelte:element>
            {/each}
            {#if showRowActions}
              <td class="data-table__actions">
                <button
                  type="button"
                  aria-label={`${rowActionLabel} ${row.cells[visibleColumns[0]?.id ?? "id"] ?? row.id}`}
                  on:click={() => dispatch("rowAction", { rowId: row.id })}
                >
                  {rowActionLabel}
                </button>
              </td>
            {/if}
          </tr>
        {/each}
      {/if}
    </tbody>
  </table>
</div>

<style>
  .data-table {
    overflow: auto;
    border: 0.0625rem solid var(--poodle-color-border-subtle);
    border-radius: var(--poodle-radius-surface);
    background: var(--poodle-color-background-panel);
  }

  .data-table__toolbar {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: var(--poodle-space-inline-md);
    padding: var(--poodle-space-control-y) var(--poodle-space-panel-x);
    border-bottom: 0.0625rem solid var(--poodle-color-border-subtle);
    background: color-mix(in srgb, var(--poodle-color-background-elevated) 92%, transparent);
  }

  .data-table__toolbar-btn {
    display: inline-flex;
    align-items: center;
    gap: var(--poodle-space-inline-sm);
    padding: var(--poodle-space-control-y) var(--poodle-space-control-x);
    border: 0.0625rem solid var(--poodle-color-border-default);
    border-radius: var(--poodle-radius-control);
    background: var(--poodle-color-background-surface);
    color: var(--poodle-color-text-secondary);
    cursor: pointer;
    font: inherit;
    font-size: var(--poodle-typography-label-size);
    line-height: 1;
    transition: background var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard);
  }

  .data-table__toolbar-btn:hover {
    background: color-mix(in srgb, var(--poodle-color-background-elevated) 72%, transparent);
  }

  .data-table__toolbar-btn:focus-visible {
    outline: var(--poodle-border-width-focus) solid var(--poodle-color-accent-focusRing);
    outline-offset: 0.125rem;
  }

  .data-table__toolbar-btn :global(.poodle-icon) {
    width: 0.875rem;
    height: 0.875rem;
  }

  .data-table__col-menu {
    display: flex;
    flex-direction: column;
  }

  .data-table__col-menu-item {
    display: flex;
    align-items: center;
    gap: var(--poodle-space-inline-md);
    padding: var(--poodle-space-control-y) var(--poodle-space-control-x);
    border-radius: calc(var(--poodle-radius-control) - 0.125rem);
    cursor: pointer;
    font-size: var(--poodle-typography-label-size);
    color: var(--poodle-color-text-primary);
  }

  .data-table__col-menu-item:hover {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 12%, transparent);
  }

  table {
    width: 100%;
    border-collapse: collapse;
  }

  .data-table__caption {
    position: absolute;
    width: 0.0625rem;
    height: 0.0625rem;
    padding: 0;
    margin: -0.0625rem;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }

  th,
  td {
    padding: var(--poodle-space-panel-y) var(--poodle-space-panel-x);
    border-bottom: 0.0625rem solid var(--poodle-color-border-subtle);
    text-align: left;
    vertical-align: middle;
    font-size: var(--poodle-typography-label-size);
  }

  thead th {
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-label-family);
    font-size: var(--poodle-typography-label-size);
    font-weight: var(--poodle-typography-label-weight);
    line-height: var(--poodle-typography-label-lineHeight);
    background: color-mix(in srgb, var(--poodle-color-background-elevated) 92%, transparent);
  }

  tbody tr.selected {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 8%, transparent);
  }

  tbody tr:hover {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 5%, transparent);
  }

  .data-table__selection {
    width: 3.25rem;
  }

  .data-table__sort,
  .data-table__actions button {
    display: inline-flex;
    align-items: center;
    gap: var(--poodle-space-inline-sm);
    min-height: var(--poodle-size-control-height);
    padding: 0;
    border: 0;
    background: transparent;
    color: inherit;
    cursor: pointer;
    font: inherit;
  }

  .data-table__sort:focus-visible,
  .data-table__actions button:focus-visible {
    outline: var(--poodle-border-width-focus) solid var(--poodle-color-accent-focusRing);
    outline-offset: 0.125rem;
    border-radius: var(--poodle-radius-control);
  }

  .data-table__cell {
    display: grid;
    gap: 0.25rem;
  }

  .data-table__cell small {
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-body-family);
    font-size: var(--poodle-typography-body-size);
    line-height: var(--poodle-typography-body-lineHeight);
  }

  .end-align {
    text-align: right;
  }

  .data-table__actions-header,
  .data-table__actions {
    width: 7.5rem;
    text-align: right;
  }

  .data-table__empty {
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-body-family);
    font-size: var(--poodle-typography-body-size);
    line-height: var(--poodle-typography-body-lineHeight);
  }

  /* ── Size variants ──────────────────────────────────────────── */

  .data-table[data-size="xs"] .data-table__toolbar-btn {
    font-size: 0.6875rem;
    padding: 0.1875rem 0.375rem;
  }

  .data-table[data-size="xs"] .data-table__toolbar-btn :global(.poodle-icon) {
    width: 0.75rem;
    height: 0.75rem;
  }

  .data-table[data-size="xs"] th,
  .data-table[data-size="xs"] td {
    padding: 0.25rem 0.5rem;
    font-size: 0.6875rem;
  }

  .data-table[data-size="xs"] .data-table__sort,
  .data-table[data-size="xs"] .data-table__actions button {
    min-height: 1.25rem;
  }

  .data-table[data-size="xs"] .data-table__selection {
    width: 2.5rem;
  }

  .data-table[data-size="sm"] .data-table__toolbar-btn {
    font-size: 0.71875rem;
    padding: 0.25rem 0.4375rem;
  }

  .data-table[data-size="sm"] th,
  .data-table[data-size="sm"] td {
    padding: 0.3125rem 0.625rem;
    font-size: 0.71875rem;
  }

  .data-table[data-size="sm"] .data-table__sort,
  .data-table[data-size="sm"] .data-table__actions button {
    min-height: 1.375rem;
  }

  .data-table[data-size="sm"] .data-table__selection {
    width: 2.75rem;
  }

  .data-table[data-size="lg"] .data-table__toolbar-btn {
    font-size: 0.8125rem;
    padding: 0.375rem 0.625rem;
  }

  .data-table[data-size="lg"] .data-table__toolbar-btn :global(.poodle-icon) {
    width: 1rem;
    height: 1rem;
  }

  .data-table[data-size="lg"] th,
  .data-table[data-size="lg"] td {
    padding: 0.5rem 0.875rem;
    font-size: 0.8125rem;
  }

  .data-table[data-size="lg"] .data-table__sort,
  .data-table[data-size="lg"] .data-table__actions button {
    min-height: 2.125rem;
  }

  .data-table[data-size="lg"] .data-table__selection {
    width: 3.625rem;
  }

  .data-table[data-size="xl"] .data-table__toolbar-btn {
    font-size: 0.875rem;
    padding: 0.4375rem 0.75rem;
  }

  .data-table[data-size="xl"] .data-table__toolbar-btn :global(.poodle-icon) {
    width: 1.125rem;
    height: 1.125rem;
  }

  .data-table[data-size="xl"] th,
  .data-table[data-size="xl"] td {
    padding: 0.625rem 1rem;
    font-size: 0.875rem;
  }

  .data-table[data-size="xl"] .data-table__sort,
  .data-table[data-size="xl"] .data-table__actions button {
    min-height: 2.25rem;
  }

  .data-table[data-size="xl"] .data-table__selection {
    width: 4rem;
  }
</style>

// packages/react/components/src/DataTable.tsx
import type { CSSProperties, MouseEvent, ReactNode } from "react";

import "@poodle/styles/data-table.css";

import { Button } from "./Button";
import { Checkbox } from "./Checkbox";
import { Icon } from "./Icon";
import { IconButton } from "./IconButton";
import { Menu } from "./Menu";
import { Popover } from "./Popover";
import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import { Select } from "./Select";
import { TextInput } from "./TextInput";
import type {
  ControlDensity,
  ControlSize,
  MenuItem,
  SemanticControlSizeRole,
  TableCellValue,
  TableColumn,
  TableFilters,
  TablePagination,
  TableRow,
  TableRowAction,
  TableSortDirection,
} from "./types";

export interface DataTableProps {
  ariaLabel?: string;
  columns?: TableColumn[];
  rows?: TableRow[];
  filters?: TableFilters;
  pagination?: TablePagination | null;
  loading?: boolean;
  loadingRows?: number;
  selectable?: boolean;
  selectedRowIds?: string[];
  sortColumnId?: string | null;
  sortDirection?: TableSortDirection;
  rowActionLabel?: string;
  showRowActions?: boolean;
  rowActions?: TableRowAction[] | ((row: TableRow) => TableRowAction[]);
  expandedRowIds?: string[];
  emptyMessage?: string;
  hiddenColumnIds?: string[];
  showColumnVisibility?: boolean;
  showExport?: boolean;
  exportFilename?: string;
  limitOptions?: number[];
  showLimitSelector?: boolean;
  compact?: boolean;
  striped?: boolean;
  stickyHeader?: boolean;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  onSortChange?: ((payload: { columnId: string; direction: TableSortDirection }) => void) | null;
  onRowToggle?: ((payload: { rowId: string; selected: boolean }) => void) | null;
  onToggleAll?: ((payload: { selected: boolean }) => void) | null;
  onRowAction?: ((payload: { rowId: string }) => void) | null;
  onRowActionSelect?: ((payload: { rowId: string; row: TableRow; action: TableRowAction }) => void) | null;
  onColumnVisibilityChange?: ((payload: { columnId: string; visible: boolean }) => void) | null;
  onExportCsv?: ((payload: { filename: string }) => void) | null;
  onRowClick?: ((payload: { rowId: string; row: TableRow }) => void) | null;
  onFilterChange?: ((payload: { filters: TableFilters }) => void) | null;
  onPageChange?: ((payload: { page: number }) => void) | null;
  onLimitChange?: ((payload: { limit: number }) => void) | null;
  cell?: (column: TableColumn, row: TableRow, value: TableCellValue) => ReactNode;
  expandedRow?: (row: TableRow) => ReactNode;
  empty?: () => ReactNode;
}

function stringifyCellValue(value: TableCellValue): string {
  if (value === null || value === undefined) return "";
  return String(value);
}

function getColumnStyle(column: TableColumn): CSSProperties | undefined {
  const style: CSSProperties = {
    ...(column.width ? { width: column.width } : null),
    ...(column.minWidth ? { minWidth: column.minWidth } : null),
  };
  return Object.keys(style).length > 0 ? style : undefined;
}

function columnClass(column: TableColumn, extra?: string): string | undefined {
  const classes = [
    extra ?? "",
    column.align === "center" ? "poodle-center-align" : "",
    column.align === "end" ? "poodle-end-align" : "",
    column.hideOnMobile === true ? "poodle-data-table__hide-mobile" : "",
  ].filter(Boolean);
  return classes.length > 0 ? classes.join(" ") : undefined;
}

export function DataTable({
  ariaLabel = "Data table",
  columns = [],
  rows = [],
  filters = {},
  pagination = null,
  loading = false,
  loadingRows = 5,
  selectable = false,
  selectedRowIds = [],
  sortColumnId = null,
  sortDirection = "asc",
  rowActionLabel = "Open",
  showRowActions = true,
  rowActions = [],
  expandedRowIds = [],
  emptyMessage = "No rows match the current view.",
  hiddenColumnIds = [],
  showColumnVisibility = false,
  showExport = false,
  exportFilename = "export.csv",
  limitOptions = [10, 20, 50, 100],
  showLimitSelector = true,
  compact = false,
  striped = false,
  stickyHeader = false,
  size = null,
  sizeRole = "control",
  density = null,
  onSortChange = null,
  onRowToggle = null,
  onToggleAll = null,
  onRowAction = null,
  onRowActionSelect = null,
  onColumnVisibilityChange = null,
  onExportCsv = null,
  onRowClick = null,
  onFilterChange = null,
  onPageChange = null,
  onLimitChange = null,
  cell,
  expandedRow,
  empty,
}: DataTableProps) {
  const uiPresentation = useUiPresentation();

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const visibleColumns = columns.filter((column) => !hiddenColumnIds.includes(column.id));
  const hideableColumns = columns.filter((column) => column.hideable !== false);
  const hasFilters = visibleColumns.some((column) => column.filterable);
  const selectableRowCount = selectable ? rows.length : 0;
  const selectionCount = selectable ? rows.filter((row) => selectedRowIds.includes(row.id)).length : 0;
  const allRowsSelected = selectableRowCount > 0 && selectionCount === selectableRowCount;
  const mixedSelection = selectionCount > 0 && !allRowsSelected;
  const expandedIdSet = new Set(expandedRowIds);
  const hasRichRowActions = typeof rowActions === "function" || rowActions.length > 0;
  const showLegacyRowAction = showRowActions && !hasRichRowActions;
  const showActionsColumn = showRowActions && (showLegacyRowAction || hasRichRowActions);
  const totalPages = pagination ? Math.max(1, Math.ceil(pagination.total / pagination.limit)) : 1;
  const showPaginationFooter = pagination !== null && (totalPages > 1 || showLimitSelector);
  const columnCount = visibleColumns.length + (selectable ? 1 : 0) + (showActionsColumn ? 1 : 0);

  const getRowPrimaryLabel = (row: TableRow) =>
    stringifyCellValue(row.cells[visibleColumns[0]?.id ?? "id"]) || row.id;

  function resolveRowActions(row: TableRow): TableRowAction[] {
    const resolved = typeof rowActions === "function" ? rowActions(row) : rowActions;
    return resolved.filter((action) => action.kind === "separator" || action.hidden !== true);
  }

  const toMenuItem = (action: TableRowAction): MenuItem => ({
    value: action.value,
    label: action.label,
    disabled: action.disabled,
    shortcutLabel: action.shortcutLabel,
    tone: action.tone,
    kind: action.kind === "separator" ? "separator" : "action",
  });

  const getActionButtonClass = (action: TableRowAction) =>
    action.tone === "danger"
      ? "poodle-data-table__row-action-btn poodle-data-table__row-action-btn--danger"
      : "poodle-data-table__row-action-btn";

  function requestRowAction(row: TableRow, action: TableRowAction): void {
    if (action.disabled || action.kind === "separator") return;
    onRowActionSelect?.({ rowId: row.id, row, action });
  }

  function handleRowClick(event: MouseEvent, row: TableRow): void {
    const target = event.target as HTMLElement | null;
    if (target?.closest("button, a, input, label, [role='button'], [role='menuitem'], [data-row-action-trigger='true']")) {
      return;
    }
    onRowClick?.({ rowId: row.id, row });
  }

  function requestSort(column: TableColumn): void {
    if (!column.sortable) return;
    const direction: TableSortDirection = sortColumnId === column.id && sortDirection === "asc" ? "desc" : "asc";
    onSortChange?.({ columnId: column.id, direction });
  }

  function requestPageChange(page: number): void {
    if (!pagination) return;
    const nextPage = Math.min(Math.max(page, 1), totalPages);
    if (nextPage === pagination.page) return;
    onPageChange?.({ page: nextPage });
  }

  function handleExport(): void {
    const header = visibleColumns.map((column) => column.label).join(",");
    const body = rows
      .map((row) =>
        visibleColumns
          .map((column) => {
            const value = stringifyCellValue(row.cells[column.id] ?? null);
            return value.includes(",") || value.includes('"') ? `"${value.replace(/"/g, '""')}"` : value;
          })
          .join(","),
      )
      .join("\n");
    const csv = `${header}\n${body}`;
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = exportFilename;
    link.click();
    URL.revokeObjectURL(url);
    onExportCsv?.({ filename: exportFilename });
  }

  function getPaginationSummary(): string {
    if (!pagination || pagination.total === 0) return "Showing 0 results";
    const start = (pagination.page - 1) * pagination.limit + 1;
    const end = Math.min(pagination.page * pagination.limit, pagination.total);
    return `Showing ${start} to ${end} of ${pagination.total}`;
  }

  return (
    <div
      className={[
        "poodle-data-table",
        compact ? "poodle-data-table--compact" : "",
        striped ? "poodle-data-table--striped" : "",
        stickyHeader ? "poodle-data-table--sticky-header" : "",
      ]
        .filter(Boolean)
        .join(" ")}
      data-size={resolvedSize}
      data-density={resolvedDensity}
    >
      {showColumnVisibility || showExport ? (
        <div className="poodle-data-table__toolbar">
          {showExport ? (
            <button type="button" className="poodle-data-table__toolbar-btn" onClick={handleExport} aria-label="Export as CSV">
              <Icon name="download" />
              Export
            </button>
          ) : null}

          {showColumnVisibility && hideableColumns.length > 0 ? (
            <Popover
              placement="bottom-end"
              ariaLabel="Column visibility"
              trigger={
                <span className="poodle-data-table__toolbar-btn">
                  <Icon name="columns-3" />
                  Columns
                </span>
              }
            >
              <div className="poodle-data-table__col-menu" role="menu">
                {hideableColumns.map((column) => (
                  <label key={column.id} className="poodle-data-table__col-menu-item">
                    <Checkbox
                      ariaLabel={column.label}
                      checked={!hiddenColumnIds.includes(column.id)}
                      onCheckedChange={() =>
                        onColumnVisibilityChange?.({ columnId: column.id, visible: hiddenColumnIds.includes(column.id) })
                      }
                    />
                    <span>{column.label}</span>
                  </label>
                ))}
              </div>
            </Popover>
          ) : null}
        </div>
      ) : null}

      <table aria-label={ariaLabel}>
        <caption className="poodle-data-table__caption">
          {selectable
            ? `${ariaLabel}. ${selectionCount} selected row${selectionCount === 1 ? "" : "s"} out of ${selectableRowCount}.`
            : `${ariaLabel}.`}
        </caption>
        <thead>
          <tr>
            {selectable ? (
              <th className="poodle-data-table__selection">
                <Checkbox
                  ariaLabel="Select all visible rows"
                  checked={allRowsSelected}
                  mixed={mixedSelection}
                  onCheckedChange={(checked) => onToggleAll?.({ selected: checked })}
                />
              </th>
            ) : null}
            {visibleColumns.map((column) => (
              <th
                key={column.id}
                style={getColumnStyle(column)}
                className={columnClass(column)}
                aria-sort={
                  column.sortable && sortColumnId === column.id
                    ? sortDirection === "asc"
                      ? "ascending"
                      : "descending"
                    : column.sortable
                      ? "none"
                      : undefined
                }
              >
                {column.sortable ? (
                  <button
                    type="button"
                    className="poodle-data-table__sort"
                    onClick={() => requestSort(column)}
                    aria-label={`Sort by ${column.label}${sortColumnId === column.id ? `, currently ${sortDirection}` : ""}`}
                  >
                    <span>{column.label}</span>
                    {sortColumnId === column.id ? (
                      <span aria-hidden="true">
                        <Icon name={sortDirection === "asc" ? "arrow-up" : "arrow-down"} />
                      </span>
                    ) : null}
                  </button>
                ) : (
                  <span>{column.label}</span>
                )}
              </th>
            ))}
            {showActionsColumn ? (
              <th scope="col" className="poodle-data-table__actions-header">
                Actions
              </th>
            ) : null}
          </tr>
          {hasFilters ? (
            <tr className="poodle-data-table__filters-row">
              {selectable ? <td className="poodle-data-table__selection" aria-hidden="true" /> : null}
              {visibleColumns.map((column) => (
                <td key={column.id} style={getColumnStyle(column)} className={columnClass(column)}>
                  {column.filterable ? (
                    column.filterType === "select" && column.filterOptions ? (
                      <Select
                        id={`data-table-filter-${column.id}`}
                        value={filters[column.id] ?? ""}
                        options={[
                          { value: "", label: "All" },
                          ...column.filterOptions.map((option) =>
                            typeof option === "string" ? { value: option, label: option } : option,
                          ),
                        ]}
                        onValueChange={(nextValue) =>
                          onFilterChange?.({ filters: { ...filters, [column.id]: nextValue } })
                        }
                        ariaLabel={`Filter ${column.label}`}
                        clearable
                        valueLabel="All"
                      />
                    ) : column.filterType === "date" ? (
                      <TextInput
                        id={`data-table-filter-${column.id}`}
                        type="date"
                        value={filters[column.id] ?? ""}
                        ariaLabel={`Filter ${column.label}`}
                        onValueChange={(nextValue) =>
                          onFilterChange?.({ filters: { ...filters, [column.id]: nextValue } })
                        }
                      />
                    ) : (
                      <TextInput
                        id={`data-table-filter-${column.id}`}
                        type="search"
                        value={filters[column.id] ?? ""}
                        placeholder={`Filter ${column.label.toLowerCase()}...`}
                        ariaLabel={`Filter ${column.label}`}
                        debounce={300}
                        onValueChange={(nextValue) =>
                          onFilterChange?.({ filters: { ...filters, [column.id]: nextValue } })
                        }
                      />
                    )
                  ) : null}
                </td>
              ))}
              {showActionsColumn ? <td aria-hidden="true" /> : null}
            </tr>
          ) : null}
        </thead>
        <tbody>
          {loading && rows.length === 0 ? (
            Array.from({ length: loadingRows }, (_, index) => (
              <tr key={index} className="poodle-data-table__loading-row">
                {selectable ? (
                  <td className="poodle-data-table__selection">
                    <span className="poodle-data-table__loading-block poodle-data-table__loading-block--checkbox" />
                  </td>
                ) : null}
                {visibleColumns.map((column) => (
                  <td key={column.id} style={getColumnStyle(column)} className={columnClass(column)}>
                    <span className="poodle-data-table__loading-block" />
                  </td>
                ))}
                {showActionsColumn ? (
                  <td className="poodle-data-table__actions">
                    <span className="poodle-data-table__loading-block poodle-data-table__loading-block--action" />
                  </td>
                ) : null}
              </tr>
            ))
          ) : rows.length === 0 ? (
            <tr>
              <td colSpan={columnCount} className="poodle-data-table__empty">
                {empty ? empty() : emptyMessage}
              </td>
            </tr>
          ) : (
            rows.map((row) => {
              const rowSelected = selectable && selectedRowIds.includes(row.id);
              const actions = hasRichRowActions ? resolveRowActions(row) : [];
              const actionableActions = actions.filter((action) => action.kind !== "separator");
              return [
                <tr
                  key={row.id}
                  className={rowSelected ? "poodle-selected" : undefined}
                  aria-selected={selectable ? rowSelected : undefined}
                  onClick={(event) => handleRowClick(event, row)}
                >
                  {selectable ? (
                    <td className="poodle-data-table__selection">
                      <Checkbox
                        ariaLabel={`Select row ${getRowPrimaryLabel(row)}`}
                        checked={selectedRowIds.includes(row.id)}
                        onCheckedChange={(checked) => onRowToggle?.({ rowId: row.id, selected: checked })}
                      />
                    </td>
                  ) : null}
                  {visibleColumns.map((column, index) => {
                    const isRowHeader = index === 0 && column.isRowHeader !== false;
                    const Tag = isRowHeader ? "th" : "td";
                    return (
                      <Tag
                        key={column.id}
                        scope={isRowHeader ? "row" : undefined}
                        style={getColumnStyle(column)}
                        className={columnClass(column)}
                      >
                        {cell ? (
                          cell(column, row, row.cells[column.id] ?? null)
                        ) : (
                          <div className="poodle-data-table__cell">
                            <span>{stringifyCellValue(row.cells[column.id] ?? null) || "—"}</span>
                            {column.id === visibleColumns[0]?.id && row.summary ? <small>{row.summary}</small> : null}
                          </div>
                        )}
                      </Tag>
                    );
                  })}
                  {showActionsColumn ? (
                    <td className="poodle-data-table__actions">
                      {hasRichRowActions ? (
                        actionableActions.length === 1 && actions.length === 1 ? (
                          actionableActions[0].href ? (
                            <a
                              href={actionableActions[0].href ?? undefined}
                              className={getActionButtonClass(actionableActions[0])}
                              aria-label={`${actionableActions[0].label} ${getRowPrimaryLabel(row)}`}
                            >
                              {actionableActions[0].label}
                            </a>
                          ) : (
                            <button
                              type="button"
                              className={getActionButtonClass(actionableActions[0])}
                              aria-label={`${actionableActions[0].label} ${getRowPrimaryLabel(row)}`}
                              onClick={(event) => {
                                event.stopPropagation();
                                requestRowAction(row, actionableActions[0]);
                              }}
                            >
                              {actionableActions[0].label}
                            </button>
                          )
                        ) : actions.length > 0 ? (
                          <Menu
                            items={actions.map(toMenuItem)}
                            ariaLabel={`Actions for ${getRowPrimaryLabel(row)}`}
                            placement="bottom-end"
                            onAction={(value) => {
                              const action = actions.find((candidate) => candidate.value === value);
                              if (action) requestRowAction(row, action);
                            }}
                            trigger={
                              <span className="poodle-data-table__actions-trigger" data-row-action-trigger="true">
                                <IconButton
                                  icon="ellipsis"
                                  variant="ghost"
                                  sizeRole="chrome"
                                  ariaLabel={`Actions for ${getRowPrimaryLabel(row)}`}
                                  tooltip="Actions"
                                />
                              </span>
                            }
                          />
                        ) : null
                      ) : showLegacyRowAction ? (
                        <button
                          type="button"
                          className="poodle-data-table__row-action-btn"
                          aria-label={`${rowActionLabel} ${getRowPrimaryLabel(row)}`}
                          onClick={(event) => {
                            event.stopPropagation();
                            onRowAction?.({ rowId: row.id });
                          }}
                        >
                          {rowActionLabel}
                        </button>
                      ) : null}
                    </td>
                  ) : null}
                </tr>,
                expandedRow && expandedIdSet.has(row.id) ? (
                  <tr key={`${row.id}-expanded`} className="poodle-data-table__expanded-row">
                    <td colSpan={columnCount}>
                      <div className="poodle-data-table__expanded-panel">{expandedRow(row)}</div>
                    </td>
                  </tr>
                ) : null,
              ];
            })
          )}
        </tbody>
      </table>

      {showPaginationFooter && pagination ? (
        <div className="poodle-data-table__footer">
          <p className="poodle-data-table__pagination-summary">{getPaginationSummary()}</p>
          <div className="poodle-data-table__pagination-actions">
            {showLimitSelector && limitOptions.length > 0 ? (
              <label className="poodle-data-table__limit">
                <span>Show</span>
                <Select
                  id={`${ariaLabel.replace(/\s+/g, "-").toLowerCase()}-limit`}
                  value={String(pagination.limit)}
                  options={limitOptions.map((option) => ({ value: String(option), label: String(option) }))}
                  onValueChange={(nextValue) => onLimitChange?.({ limit: Number(nextValue) })}
                  ariaLabel="Items per page"
                />
                <span>per page</span>
              </label>
            ) : null}
            {totalPages > 1 ? (
              <div className="poodle-data-table__pagination-controls">
                <Button type="button" variant="ghost" size="sm" disabled={pagination.page <= 1} onClick={() => requestPageChange(1)}>
                  First
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  disabled={pagination.page <= 1}
                  onClick={() => requestPageChange(pagination.page - 1)}
                >
                  Previous
                </Button>
                <span className="poodle-data-table__pagination-page">
                  Page {pagination.page} of {totalPages}
                </span>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  disabled={pagination.page >= totalPages}
                  onClick={() => requestPageChange(pagination.page + 1)}
                >
                  Next
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  disabled={pagination.page >= totalPages}
                  onClick={() => requestPageChange(totalPages)}
                >
                  Last
                </Button>
              </div>
            ) : null}
          </div>
        </div>
      ) : null}
    </div>
  );
}
