// packages/svelte/primitives/src/DateTimePicker.svelte
<script context="module" lang="ts">
  let nextDateTimePickerId = 0;
</script>

<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";

  import Calendar from "./Calendar.svelte";
  import TimeInput from "./TimeInput.svelte";
  import {
    formatDateTimeLabel,
    monthAnchorIso,
    normalizeDateTimeValue,
    todayIsoDate,
  } from "./date";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";

  import type { CalendarWeekStart, ControlDensity, ControlSize, DateTimeValue, SemanticControlSizeRole } from "./types";

  export let value: DateTimeValue | null = null;
  export let defaultValue: DateTimeValue = { date: null, time: null };
  export let open: boolean | null = null;
  export let defaultOpen = false;
  export let placeholder = "Select date and time";
  export let weekStartsOn: CalendarWeekStart = "monday";
  export let locale = "en-US";
  export let disabled = false;
  export let ariaLabel: string | null = null;
  export let size: ControlSize | null = null;
  export let sizeRole: SemanticControlSizeRole = "control";
  export let density: ControlDensity | null = null;

  const dispatch = createEventDispatcher<{
    valueChange: { value: DateTimeValue };
    openChange: { open: boolean };
  }>();

  const surfaceId = `poodle-date-time-picker-surface-${++nextDateTimePickerId}`;
  const uiPresentation = getUiPresentation();
  let rootElement: HTMLDivElement | null = null;
  let uncontrolledValue = normalizeDateTimeValue(defaultValue);
  let uncontrolledOpen = defaultOpen;
  let visibleMonth = monthAnchorIso(defaultValue.date ?? todayIsoDate());

  $: resolvedSize = size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole);
  $: resolvedDensity = density ?? $uiPresentation.density;
  $: currentValue = normalizeDateTimeValue(value ?? uncontrolledValue);
  $: isOpen = open ?? uncontrolledOpen;
  $: if (currentValue.date) {
    visibleMonth = monthAnchorIso(currentValue.date);
  }
  $: valueLabel =
    formatDateTimeLabel(currentValue, locale) ||
    (currentValue.date ? "Select time" : currentValue.time ? "Select date" : placeholder);

  function setOpen(nextOpen: boolean): void {
    if (open === null) {
      uncontrolledOpen = nextOpen;
    }

    dispatch("openChange", { open: nextOpen });
  }

  function commitValue(nextValue: DateTimeValue): void {
    const normalized = normalizeDateTimeValue(nextValue);

    if (value === null) {
      uncontrolledValue = normalized;
    }

    if (normalized.date) {
      visibleMonth = monthAnchorIso(normalized.date);
    }

    dispatch("valueChange", { value: normalized });
  }

  onMount(() => {
    function handlePointerDown(event: MouseEvent): void {
      if (!isOpen || !rootElement) {
        return;
      }

      if (!rootElement.contains(event.target as Node)) {
        setOpen(false);
      }
    }

    function handleKeydown(event: KeyboardEvent): void {
      if (event.key === "Escape" && isOpen) {
        event.preventDefault();
        setOpen(false);
      }
    }

    document.addEventListener("mousedown", handlePointerDown);
    document.addEventListener("keydown", handleKeydown);

    return () => {
      document.removeEventListener("mousedown", handlePointerDown);
      document.removeEventListener("keydown", handleKeydown);
    };
  });
</script>

<div bind:this={rootElement} class="date-time-picker" data-size={resolvedSize} data-density={resolvedDensity} data-open={isOpen}>
  <button
    type="button"
    class="date-time-picker__trigger"
    disabled={disabled}
    aria-haspopup="dialog"
    aria-expanded={isOpen ? "true" : "false"}
    aria-controls={isOpen ? surfaceId : undefined}
    aria-label={ariaLabel ?? undefined}
    on:click={() => setOpen(!isOpen)}
  >
    <span
      class="date-time-picker__value"
      data-placeholder={!currentValue.date || !currentValue.time}
    >
      {valueLabel}
    </span>
    <span class="date-time-picker__indicator" aria-hidden="true">▾</span>
  </button>

  {#if isOpen}
    <div
      id={surfaceId}
      class="date-time-picker__surface"
      role="dialog"
      aria-label={ariaLabel ?? placeholder}
    >
      <div class="date-time-picker__body">
        <Calendar
          value={currentValue.date}
          visibleMonth={visibleMonth}
          {weekStartsOn}
          {locale}
          {disabled}
          size={resolvedSize}
          density={resolvedDensity}
          ariaLabel={ariaLabel ?? "Date"}
          on:valueChange={(event) => commitValue({ ...currentValue, date: event.detail.value as string | null })}
          on:monthChange={(event) => (visibleMonth = event.detail.month)}
        />

        <div class="date-time-picker__time-section">
          <label class="date-time-picker__time-label" for={`${surfaceId}-time`}>
            Time
          </label>
          <TimeInput
            id={`${surfaceId}-time`}
            value={currentValue.time}
            disabled={disabled}
            size={resolvedSize}
            density={resolvedDensity}
            ariaLabel={ariaLabel ? `${ariaLabel} time` : "Time"}
            on:valueChange={(event) => commitValue({ ...currentValue, time: event.detail.value })}
          />
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .date-time-picker {
    position: relative;
    display: inline-grid;
    min-width: 16rem;
  }

  .date-time-picker__trigger {
    display: inline-flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.75rem;
    min-height: var(--poodle-size-control-height);
    padding: 0 var(--poodle-space-control-x);
    border: 0.0625rem solid var(--poodle-color-border-default);
    border-radius: var(--poodle-radius-control);
    background: var(--poodle-color-background-surface);
    color: var(--poodle-color-text-primary);
    cursor: pointer;
    font-family: var(--poodle-typography-body-family);
    font-size: var(--poodle-typography-body-size);
    line-height: var(--poodle-typography-body-lineHeight);
    text-align: left;
  }

  .date-time-picker__value {
    min-width: 0;
  }

  .date-time-picker__value[data-placeholder="true"] {
    color: var(--poodle-color-text-secondary);
  }

  .date-time-picker__indicator {
    color: var(--poodle-color-text-secondary);
    font-size: 0.75rem;
  }

  .date-time-picker__surface {
    position: absolute;
    top: calc(100% + 0.375rem);
    left: 0;
    z-index: var(--poodle-overlay-z-menu);
    padding: var(--poodle-space-panel-y) var(--poodle-space-panel-x);
    border: 0.0625rem solid color-mix(in srgb, var(--poodle-color-border-default) 72%, transparent);
    border-radius: var(--poodle-radius-surface);
    background: color-mix(
      in srgb,
      var(--poodle-color-background-elevated) 98%,
      var(--poodle-color-background-panel)
    );
    box-shadow: var(--poodle-elevation-overlay);
  }

  .date-time-picker__body {
    display: grid;
    gap: 0.875rem;
  }

  .date-time-picker__time-section {
    display: grid;
    gap: 0.375rem;
  }

  .date-time-picker__time-label {
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-label-family);
    font-size: 0.6875rem;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-transform: uppercase;
  }

  .date-time-picker__trigger:hover:not(:disabled) {
    background: color-mix(
      in srgb,
      var(--poodle-color-background-surface) 86%,
      var(--poodle-color-background-elevated)
    );
  }

  .date-time-picker__trigger:focus-visible {
    outline: var(--poodle-border-width-focus) solid var(--poodle-color-accent-focusRing);
    outline-offset: 0.125rem;
  }

  .date-time-picker__trigger:disabled {
    cursor: not-allowed;
    opacity: var(--poodle-state-opacity-disabled);
  }

  /* Size variants */
  .date-time-picker[data-size="xs"] .date-time-picker__trigger {
    min-height: var(--poodle-size-control-height);
    padding: 0 var(--poodle-space-control-x);
    font-size: 0.75rem;
  }

  .date-time-picker[data-size="sm"] .date-time-picker__trigger {
    min-height: var(--poodle-size-control-height);
    padding: 0 var(--poodle-space-control-x);
  }

  .date-time-picker[data-size="lg"] .date-time-picker__trigger {
    min-height: var(--poodle-size-control-height);
    padding: 0 var(--poodle-space-control-x);
    font-size: 0.9375rem;
  }

  .date-time-picker[data-size="xl"] .date-time-picker__trigger {
    min-height: var(--poodle-size-control-height);
    padding: 0 var(--poodle-space-control-x);
    font-size: 1rem;
  }

  /* Density variants */
  .date-time-picker[data-density="compact"] .date-time-picker__trigger { padding: 0 calc(var(--poodle-space-control-x) - 0.125rem); }
  .date-time-picker[data-density="comfortable"] .date-time-picker__trigger { padding: 0 calc(var(--poodle-space-control-x) + 0.125rem); }
</style>

// packages/react/components/src/DateTimePicker.tsx
import { useEffect, useId, useRef, useState } from "react";
import { formatDateTimeLabel, monthAnchorIso, normalizeDateTimeValue, todayIsoDate } from "@poodle/headless";

import "@poodle/styles/date-time-picker.css";

import { Calendar } from "./Calendar";
import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import { TimeInput } from "./TimeInput";
import type {
  CalendarWeekStart,
  ControlDensity,
  ControlSize,
  DateRangeValue,
  DateTimeValue,
  SemanticControlSizeRole,
} from "./types";

export interface DateTimePickerProps {
  value?: DateTimeValue | null;
  defaultValue?: DateTimeValue;
  open?: boolean;
  defaultOpen?: boolean;
  placeholder?: string;
  weekStartsOn?: CalendarWeekStart;
  locale?: string;
  disabled?: boolean;
  ariaLabel?: string | null;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  onValueChange?: (value: DateTimeValue) => void;
  onOpenChange?: (open: boolean) => void;
}

export function DateTimePicker({
  value,
  defaultValue = { date: null, time: null },
  open,
  defaultOpen = false,
  placeholder = "Select date and time",
  weekStartsOn = "monday",
  locale = "en-US",
  disabled = false,
  ariaLabel = null,
  size = null,
  sizeRole = "control",
  density = null,
  onValueChange,
  onOpenChange,
}: DateTimePickerProps) {
  const surfaceId = useId();
  const uiPresentation = useUiPresentation();
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [uncontrolledValue, setUncontrolledValue] = useState<DateTimeValue>(() => normalizeDateTimeValue(defaultValue));
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const [visibleMonth, setVisibleMonth] = useState(() => monthAnchorIso(defaultValue.date ?? todayIsoDate()));

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const hasControlledValue = value !== undefined;
  const hasControlledOpen = open !== undefined;
  const currentValue = normalizeDateTimeValue((hasControlledValue ? value : uncontrolledValue) ?? defaultValue);
  const isOpen = hasControlledOpen ? open === true : uncontrolledOpen;
  const valueLabel =
    formatDateTimeLabel(currentValue, locale) ||
    (currentValue.date ? "Select time" : currentValue.time ? "Select date" : placeholder);

  useEffect(() => {
    if (currentValue.date) setVisibleMonth(monthAnchorIso(currentValue.date));
  }, [currentValue.date]);

  const setOpenRef = useRef<(nextOpen: boolean) => void>(() => {});
  setOpenRef.current = (nextOpen: boolean) => {
    if (!hasControlledOpen) setUncontrolledOpen(nextOpen);
    onOpenChange?.(nextOpen);
  };

  useEffect(() => {
    if (!isOpen) return;
    function handlePointerDown(event: MouseEvent): void {
      if (!rootRef.current) return;
      if (!rootRef.current.contains(event.target as Node)) setOpenRef.current(false);
    }
    function handleKeydown(event: KeyboardEvent): void {
      if (event.key === "Escape") {
        event.preventDefault();
        setOpenRef.current(false);
      }
    }
    document.addEventListener("mousedown", handlePointerDown);
    document.addEventListener("keydown", handleKeydown);
    return () => {
      document.removeEventListener("mousedown", handlePointerDown);
      document.removeEventListener("keydown", handleKeydown);
    };
  }, [isOpen]);

  function commitValue(nextValue: DateTimeValue): void {
    const normalized = normalizeDateTimeValue(nextValue);
    if (!hasControlledValue) setUncontrolledValue(normalized);
    if (normalized.date) setVisibleMonth(monthAnchorIso(normalized.date));
    onValueChange?.(normalized);
  }

  return (
    <div
      ref={rootRef}
      className="poodle-date-time-picker"
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-open={isOpen}
    >
      <button
        type="button"
        className="poodle-date-time-picker__trigger"
        disabled={disabled}
        aria-haspopup="dialog"
        aria-expanded={isOpen}
        aria-controls={isOpen ? surfaceId : undefined}
        aria-label={ariaLabel ?? undefined}
        onClick={() => setOpenRef.current(!isOpen)}
      >
        <span className="poodle-date-time-picker__value" data-placeholder={!currentValue.date || !currentValue.time}>
          {valueLabel}
        </span>
        <span className="poodle-date-time-picker__indicator" aria-hidden="true">
          ▾
        </span>
      </button>

      {isOpen ? (
        <div id={surfaceId} className="poodle-date-time-picker__surface" role="dialog" aria-label={ariaLabel ?? placeholder}>
          <div className="poodle-date-time-picker__body">
            <Calendar
              value={currentValue.date}
              visibleMonth={visibleMonth}
              weekStartsOn={weekStartsOn}
              locale={locale}
              disabled={disabled}
              size={resolvedSize}
              density={resolvedDensity}
              ariaLabel={ariaLabel ?? "Date"}
              onValueChange={(nextValue: string | DateRangeValue) => {
                if (typeof nextValue === "string") commitValue({ ...currentValue, date: nextValue });
              }}
              onMonthChange={setVisibleMonth}
            />

            <div className="poodle-date-time-picker__time-section">
              <label className="poodle-date-time-picker__time-label" htmlFor={`${surfaceId}-time`}>
                Time
              </label>
              <TimeInput
                id={`${surfaceId}-time`}
                value={currentValue.time}
                disabled={disabled}
                size={resolvedSize}
                density={resolvedDensity}
                ariaLabel={ariaLabel ? `${ariaLabel} time` : "Time"}
                onValueChange={(nextValue) => commitValue({ ...currentValue, time: nextValue })}
              />
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
