// packages/svelte/components/src/DatePicker.svelte
<script module lang="ts">
  let nextDatePickerId = 0;
</script>

<script lang="ts">
  import "@poodle/styles/date-picker.css";
  import { default as Calendar } from "./Calendar.svelte";
  import { formatDateLabel, monthAnchorIso, todayIsoDate } from "./date";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";

  import type { CalendarWeekStart, ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";

  interface Props {
    value?: string | null | undefined;
    defaultValue?: string | null;
    open?: boolean | null | undefined;
    defaultOpen?: boolean;
    placeholder?: string;
    weekStartsOn?: CalendarWeekStart;
    locale?: string;
    disabled?: boolean;
    ariaLabel?: string | null;
    size?: ControlSize | null;
    sizeRole?: SemanticControlSizeRole;
    density?: ControlDensity | null;
    onValueChange?: ((value: string) => void) | undefined;
    onOpenChange?: ((open: boolean) => void) | undefined;
  }

  let {
    value = undefined,
    defaultValue = null,
    open = undefined,
    defaultOpen = false,
    placeholder = "Select date",
    weekStartsOn = "monday",
    locale = "en-US",
    disabled = false,
    ariaLabel = null,
    size = null,
    sizeRole = "control",
    density = null,
    onValueChange = undefined,
    onOpenChange = undefined,
  }: Props = $props();

  const surfaceId = `poodle-date-picker-surface-${++nextDatePickerId}`;
  const uiPresentation = getUiPresentation();
  let rootElement: HTMLDivElement | null = null;
  let uncontrolledValue = $state<string | null>(null);
  let uncontrolledOpen = $state(false);
  let visibleMonth = $state(todayIsoDate());
  let seededDefaults = $state(false);

  const resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole));
  const resolvedDensity = $derived(density ?? $uiPresentation.density);
  const hasControlledValue = $derived(value !== undefined);
  const hasControlledOpen = $derived(open !== undefined);
  const currentValue = $derived(hasControlledValue ? value ?? null : uncontrolledValue);
  const isOpen = $derived(hasControlledOpen ? open === true : uncontrolledOpen);
  const valueLabel = $derived(currentValue ? formatDateLabel(currentValue, locale) : placeholder);

  $effect.pre(() => {
    if (seededDefaults) {
      return;
    }

    uncontrolledValue = defaultValue;
    uncontrolledOpen = defaultOpen;
    visibleMonth = monthAnchorIso(defaultValue ?? todayIsoDate());
    seededDefaults = true;
  });

  $effect(() => {
    if (currentValue) {
      visibleMonth = monthAnchorIso(currentValue);
    }
  });

  $effect(() => {
    if (!isOpen) {
      return;
    }

    function handlePointerDown(event: MouseEvent): void {
      if (!rootElement) {
        return;
      }

      if (!rootElement.contains(event.target as Node)) {
        setOpen(false);
      }
    }

    function handleKeydown(event: KeyboardEvent): void {
      if (event.key === "Escape") {
        event.preventDefault();
        setOpen(false);
      }
    }

    document.addEventListener("mousedown", handlePointerDown);
    document.addEventListener("keydown", handleKeydown);

    return () => {
      document.removeEventListener("mousedown", handlePointerDown);
      document.removeEventListener("keydown", handleKeydown);
    };
  });

  function setOpen(nextOpen: boolean): void {
    if (!hasControlledOpen) {
      uncontrolledOpen = nextOpen;
    }

    onOpenChange?.(nextOpen);
  }

  function commitValue(nextValue: string): void {
    if (!hasControlledValue) {
      uncontrolledValue = nextValue;
    }

    visibleMonth = monthAnchorIso(nextValue);
    setOpen(false);
    onValueChange?.(nextValue);
  }

  function handleCalendarValueChange(nextValue: string | string[] | { start: string | null; end: string | null }): void {
    if (typeof nextValue === "string") {
      commitValue(nextValue);
    }
  }
</script>

<div bind:this={rootElement} class="poodle-date-picker" data-size={resolvedSize} data-density={resolvedDensity} data-open={isOpen}>
  <button
    type="button"
    class="poodle-date-picker__trigger"
    disabled={disabled}
    aria-haspopup="dialog"
    aria-expanded={isOpen ? "true" : "false"}
    aria-controls={isOpen ? surfaceId : undefined}
    aria-label={ariaLabel ?? undefined}
    onclick={() => setOpen(!isOpen)}
  >
    <span class="poodle-date-picker__value" data-placeholder={currentValue === null}>
      {valueLabel}
    </span>
    <span class="poodle-date-picker__indicator" aria-hidden="true">▾</span>
  </button>

  {#if isOpen}
    <div id={surfaceId} class="poodle-date-picker__surface" role="dialog" aria-label={ariaLabel ?? placeholder}>
      <Calendar
        value={currentValue}
        visibleMonth={visibleMonth}
        {weekStartsOn}
        {locale}
        {disabled}
        size={resolvedSize}
        density={resolvedDensity}
        ariaLabel={ariaLabel ?? placeholder}
        onValueChange={handleCalendarValueChange}
        onMonthChange={(month) => (visibleMonth = month)}
      />
    </div>
  {/if}
</div>

// packages/react/components/src/DatePicker.tsx
import { useEffect, useId, useRef, useState } from "react";
import { formatDateLabel, monthAnchorIso, todayIsoDate } from "@poodle/headless";

import "@poodle/styles/date-picker.css";

import { Calendar } from "./Calendar";
import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type {
  CalendarWeekStart,
  ControlDensity,
  ControlSize,
  DateRangeValue,
  SemanticControlSizeRole,
} from "./types";

export interface DatePickerProps {
  value?: string | null;
  defaultValue?: string | null;
  open?: boolean;
  defaultOpen?: boolean;
  placeholder?: string;
  weekStartsOn?: CalendarWeekStart;
  locale?: string;
  disabled?: boolean;
  ariaLabel?: string | null;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  onValueChange?: (value: string) => void;
  onOpenChange?: (open: boolean) => void;
}

export function DatePicker({
  value,
  defaultValue = null,
  open,
  defaultOpen = false,
  placeholder = "Select date",
  weekStartsOn = "monday",
  locale = "en-US",
  disabled = false,
  ariaLabel = null,
  size = null,
  sizeRole = "control",
  density = null,
  onValueChange,
  onOpenChange,
}: DatePickerProps) {
  const surfaceId = useId();
  const uiPresentation = useUiPresentation();
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [uncontrolledValue, setUncontrolledValue] = useState<string | null>(defaultValue);
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const [visibleMonth, setVisibleMonth] = useState(() => monthAnchorIso(defaultValue ?? todayIsoDate()));

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const hasControlledValue = value !== undefined;
  const hasControlledOpen = open !== undefined;
  const currentValue = hasControlledValue ? (value ?? null) : uncontrolledValue;
  const isOpen = hasControlledOpen ? open === true : uncontrolledOpen;
  const valueLabel = currentValue ? formatDateLabel(currentValue, locale) : placeholder;

  // follow the committed value's month
  useEffect(() => {
    if (currentValue) setVisibleMonth(monthAnchorIso(currentValue));
  }, [currentValue]);

  const setOpenRef = useRef<(nextOpen: boolean) => void>(() => {});
  setOpenRef.current = (nextOpen: boolean) => {
    if (!hasControlledOpen) setUncontrolledOpen(nextOpen);
    onOpenChange?.(nextOpen);
  };

  useEffect(() => {
    if (!isOpen) return;
    function handlePointerDown(event: MouseEvent): void {
      if (!rootRef.current) return;
      if (!rootRef.current.contains(event.target as Node)) setOpenRef.current(false);
    }
    function handleKeydown(event: KeyboardEvent): void {
      if (event.key === "Escape") {
        event.preventDefault();
        setOpenRef.current(false);
      }
    }
    document.addEventListener("mousedown", handlePointerDown);
    document.addEventListener("keydown", handleKeydown);
    return () => {
      document.removeEventListener("mousedown", handlePointerDown);
      document.removeEventListener("keydown", handleKeydown);
    };
  }, [isOpen]);

  function commitValue(nextValue: string): void {
    if (!hasControlledValue) setUncontrolledValue(nextValue);
    setVisibleMonth(monthAnchorIso(nextValue));
    setOpenRef.current(false);
    onValueChange?.(nextValue);
  }

  return (
    <div
      ref={rootRef}
      className="poodle-date-picker"
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-open={isOpen}
    >
      <button
        type="button"
        className="poodle-date-picker__trigger"
        disabled={disabled}
        aria-haspopup="dialog"
        aria-expanded={isOpen}
        aria-controls={isOpen ? surfaceId : undefined}
        aria-label={ariaLabel ?? undefined}
        onClick={() => setOpenRef.current(!isOpen)}
      >
        <span className="poodle-date-picker__value" data-placeholder={currentValue === null}>
          {valueLabel}
        </span>
        <span className="poodle-date-picker__indicator" aria-hidden="true">
          ▾
        </span>
      </button>

      {isOpen ? (
        <div id={surfaceId} className="poodle-date-picker__surface" role="dialog" aria-label={ariaLabel ?? placeholder}>
          <Calendar
            value={currentValue}
            visibleMonth={visibleMonth}
            weekStartsOn={weekStartsOn}
            locale={locale}
            disabled={disabled}
            size={resolvedSize}
            density={resolvedDensity}
            ariaLabel={ariaLabel ?? placeholder}
            onValueChange={(nextValue: string | DateRangeValue) => {
              if (typeof nextValue === "string") commitValue(nextValue);
            }}
            onMonthChange={setVisibleMonth}
          />
        </div>
      ) : null}
    </div>
  );
}
