// packages/svelte/components/src/MediaBrowsePanel.svelte
<script lang="ts">
  import "@poodle/styles/media-browse-panel.css";
  import { default as Button } from "./Button.svelte";
  import { default as Callout } from "./Callout.svelte";
  import { default as UiPresentationProvider } from "./UiPresentationProvider.svelte";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";
  import type {
    ControlDensity,
    ControlSize,
    SemanticControlSizeRole,
  } from "./types";

  import { default as MediaThumbnail } from "./MediaThumbnail.svelte";
  import type { MediaKind, MediaPickerItem } from "./types";

  interface Props {
    loading?: boolean;
    error?: string | null;
    items?: MediaPickerItem[];
    hasMore?: boolean;
    emptyMessage?: string;
    loadMoreLabel?: string;
    size?: ControlSize | null;
    sizeRole?: SemanticControlSizeRole;
    density?: ControlDensity | null;
    onSelect?: ((item: MediaPickerItem) => void) | undefined;
    onLoadMore?: (() => void) | undefined;
  }

  let {
    loading = false,
    error = null,
    items = [],
    hasMore = false,
    emptyMessage = "No media found",
    loadMoreLabel = "Load more",
    size = null,
    sizeRole = "control",
    density = null,
    onSelect = undefined,
    onLoadMore = undefined,
  }: Props = $props();
  const uiPresentation = getUiPresentation();

  const resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole));
  const resolvedDensity = $derived(density ?? $uiPresentation.density);

  function toMediaKind(kind?: MediaKind): MediaKind {
    return kind ?? "image";
  }
</script>

<UiPresentationProvider sizeScale={resolvedSize} density={resolvedDensity}>
  <div class="poodle-media-browse-panel" data-size={resolvedSize} data-density={resolvedDensity}>
    {#if loading && items.length === 0}
      <div class="poodle-media-browse-panel__state">
        <p>Loading media...</p>
      </div>
    {:else if error}
      <Callout tone="danger" message={error} announceMode="polite" />
    {:else if items.length === 0}
      <div class="poodle-media-browse-panel__state">
        <p>{emptyMessage}</p>
      </div>
    {:else}
      <div class="poodle-media-browse-panel__grid">
        {#each items as item (item.id)}
          <button
            type="button"
            class="poodle-media-browse-panel__item"
            onclick={() => onSelect?.(item)}
          >
            <MediaThumbnail
              kind={toMediaKind(item.kind)}
              presentation="compact"
              aspectRatio="square"
              ariaLabel={item.label}
            >
              {#if item.thumbnailUrl}
                <img
                  src={item.thumbnailUrl}
                  alt={item.label}
                  class="poodle-media-browse-panel__image"
                />
              {/if}
            </MediaThumbnail>
            <span class="poodle-media-browse-panel__label">{item.label}</span>
            {#if item.meta}
              <span class="poodle-media-browse-panel__meta">{item.meta}</span>
            {/if}
          </button>
        {/each}
      </div>

      {#if hasMore}
        <div class="poodle-media-browse-panel__actions">
          <Button variant="secondary" size={resolvedSize} onClick={() => onLoadMore?.()} disabled={loading}>
            {loading ? "Loading..." : loadMoreLabel}
          </Button>
        </div>
      {/if}
    {/if}
  </div>
</UiPresentationProvider>

// packages/react/components/src/MediaBrowsePanel.tsx
import "@poodle/styles/media-browse-panel.css";

import { Button } from "./Button";
import { Callout } from "./Callout";
import { MediaThumbnail } from "./MediaThumbnail";
import { UiPresentationProvider, resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, MediaKind, MediaPickerItem, SemanticControlSizeRole } from "./types";

export interface MediaBrowsePanelProps {
  loading?: boolean;
  error?: string | null;
  items?: MediaPickerItem[];
  hasMore?: boolean;
  emptyMessage?: string;
  loadMoreLabel?: string;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  onSelect?: ((item: MediaPickerItem) => void) | undefined;
  onLoadMore?: (() => void) | undefined;
}

function toMediaKind(kind?: MediaKind): MediaKind {
  return kind ?? "image";
}

export function MediaBrowsePanel({
  loading = false,
  error = null,
  items = [],
  hasMore = false,
  emptyMessage = "No media found",
  loadMoreLabel = "Load more",
  size = null,
  sizeRole = "control",
  density = null,
  onSelect = undefined,
  onLoadMore = undefined,
}: MediaBrowsePanelProps) {
  const uiPresentation = useUiPresentation();

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;

  return (
    <UiPresentationProvider sizeScale={resolvedSize} density={resolvedDensity}>
      <div className="poodle-media-browse-panel" data-size={resolvedSize} data-density={resolvedDensity}>
        {loading && items.length === 0 ? (
          <div className="poodle-media-browse-panel__state">
            <p>Loading media...</p>
          </div>
        ) : error ? (
          <Callout tone="danger" message={error} announceMode="polite" />
        ) : items.length === 0 ? (
          <div className="poodle-media-browse-panel__state">
            <p>{emptyMessage}</p>
          </div>
        ) : (
          <>
            <div className="poodle-media-browse-panel__grid">
              {items.map((item) => (
                <button key={item.id} type="button" className="poodle-media-browse-panel__item" onClick={() => onSelect?.(item)}>
                  <MediaThumbnail kind={toMediaKind(item.kind)} presentation="compact" aspectRatio="square" ariaLabel={item.label}>
                    {item.thumbnailUrl ? (
                      <img src={item.thumbnailUrl} alt={item.label} className="poodle-media-browse-panel__image" />
                    ) : null}
                  </MediaThumbnail>
                  <span className="poodle-media-browse-panel__label">{item.label}</span>
                  {item.meta ? <span className="poodle-media-browse-panel__meta">{item.meta}</span> : null}
                </button>
              ))}
            </div>

            {hasMore ? (
              <div className="poodle-media-browse-panel__actions">
                <Button variant="secondary" size={resolvedSize} onClick={() => onLoadMore?.()} disabled={loading}>
                  {loading ? "Loading..." : loadMoreLabel}
                </Button>
              </div>
            ) : null}
          </>
        )}
      </div>
    </UiPresentationProvider>
  );
}
