// packages/svelte/primitives/src/Meter.svelte
<script lang="ts">
  export let value = 0;
  export let min = 0;
  export let max = 100;
  export let low: number | null = null;
  export let high: number | null = null;
  export let optimum: number | null = null;
  export let ariaLabel: string | null = null;

  $: safeMax = max <= min ? min + 1 : max;
  $: safeValue = Math.min(Math.max(value, min), safeMax);
  $: percentage = ((safeValue - min) / (safeMax - min)) * 100;
</script>

<div class="meter" aria-label={ariaLabel ?? undefined}>
  <meter
    class="meter__native"
    min={min}
    max={safeMax}
    {low}
    {high}
    {optimum}
    value={safeValue}
  ></meter>
  <span class="meter__track" aria-hidden="true">
    <span class="meter__fill" style={`width: ${percentage}%;`}></span>
  </span>
</div>

<style>
  .meter {
    display: grid;
    gap: 0;
    width: 100%;
  }

  .meter__native {
    position: absolute;
    opacity: 0;
    pointer-events: none;
  }

  .meter__track {
    position: relative;
    display: block;
    overflow: hidden;
    min-height: 0.5rem;
    border-radius: 999px;
    background: color-mix(in srgb, var(--poodle-surface) 96%, var(--poodle-color-text-primary));
  }

  .meter__fill {
    display: block;
    height: 100%;
    border-radius: inherit;
    background: linear-gradient(
      90deg,
      color-mix(in srgb, var(--poodle-color-status-success) 82%, white),
      var(--poodle-color-status-success)
    );
  }
</style>

// packages/react/components/src/Meter.tsx
import "@poodle/styles/meter.css";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlSize, SemanticControlSizeRole } from "./types";

export interface MeterProps {
  value?: number;
  min?: number;
  max?: number;
  low?: number | null;
  high?: number | null;
  optimum?: number | null;
  ariaLabel?: string | null;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
}

export function Meter({
  value = 0,
  min = 0,
  max = 100,
  low = null,
  high = null,
  optimum = null,
  ariaLabel = null,
  size = null,
  sizeRole = "control",
}: MeterProps) {
  const uiPresentation = useUiPresentation();
  const safeMax = max <= min ? min + 1 : max;
  const safeValue = Math.min(Math.max(value, min), safeMax);
  const percentage = ((safeValue - min) / (safeMax - min)) * 100;
  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);

  return (
    <div className="poodle-meter" aria-label={ariaLabel ?? undefined} data-size={resolvedSize}>
      <meter
        className="poodle-meter__native"
        min={min}
        max={safeMax}
        low={low ?? undefined}
        high={high ?? undefined}
        optimum={optimum ?? undefined}
        value={safeValue}
      />
      <span className="poodle-meter__track" aria-hidden="true">
        <span className="poodle-meter__fill" style={{ width: `${percentage}%` }} />
      </span>
    </div>
  );
}
