// packages/svelte/components/src/StatusBar.svelte
<script lang="ts">
  import "@inflatable-cookie/poodle-core/styles/status-bar.css";
  import type { Snippet } from "svelte";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";
  import type { ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";

  interface Props {
    summary?: string | null;
    ariaLabel?: string | null;
    chrome?: boolean;
    size?: ControlSize | null;
    sizeRole?: SemanticControlSizeRole;
    density?: ControlDensity | null;
    leading?: Snippet;
    trailing?: Snippet;
  }

  const uiPresentation = getUiPresentation();

  let {
    summary = null,
    ariaLabel = null,
    chrome = false,
    size = null,
    sizeRole = "chrome",
    density = null,
    leading,
    trailing,
  }: Props = $props();

  let resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole));
  let resolvedDensity = $derived(density ?? $uiPresentation.density);
</script>

<footer
  class="poodle-status-bar"
  class:poodle-status-bar--chrome={chrome}
  data-size={resolvedSize}
  data-density={resolvedDensity}
  aria-label={ariaLabel ?? summary ?? "Status"}
>
  <div class="poodle-status-bar__leading">
    {#if leading}
      {@render leading()}
    {:else if summary}
      <span>{summary}</span>
    {/if}
  </div>

  {#if trailing}
    <div class="poodle-status-bar__trailing">
      {@render trailing()}
    </div>
  {/if}
</footer>

// packages/react/components/src/StatusBar.tsx
import "@inflatable-cookie/poodle-core/styles/status-bar.css";

import type { ReactNode } from "react";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";

export interface StatusBarProps {
  summary?: string | null;
  ariaLabel?: string | null;
  chrome?: boolean;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  leading?: ReactNode;
  trailing?: ReactNode;
}

export function StatusBar({
  summary = null,
  ariaLabel = null,
  chrome = false,
  size = null,
  sizeRole = "chrome",
  density = null,
  leading,
  trailing,
}: StatusBarProps) {
  const uiPresentation = useUiPresentation();

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;

  return (
    <footer
      className={chrome ? "poodle-status-bar poodle-status-bar--chrome" : "poodle-status-bar"}
      data-size={resolvedSize}
      data-density={resolvedDensity}
      aria-label={ariaLabel ?? summary ?? "Status"}
    >
      <div className="poodle-status-bar__leading">{leading ?? (summary ? <span>{summary}</span> : null)}</div>

      {trailing ? <div className="poodle-status-bar__trailing">{trailing}</div> : null}
    </footer>
  );
}
