// packages/svelte/components/src/StatusIndicator.svelte
<script lang="ts">
  import "@poodle/styles/status-indicator.css";
  import type { Snippet } from "svelte";

  import { getUiPresentation, resolveSemanticControlSize } from "./presentation.ts";
  import type { ControlDensity, ControlSize, SemanticControlSizeRole, StatusTone } from "./types.ts";

  type StatusIndicatorTypography = "label" | "inherit";

  let {
    status = "neutral",
    label = null,
    ariaLabel = null,
    size = null,
    sizeRole = "control",
    density = null,
    typography = "label",
    children = undefined,
  }: {
    status?: StatusTone;
    label?: string | null;
    ariaLabel?: string | null;
    size?: ControlSize | null;
    sizeRole?: SemanticControlSizeRole;
    density?: ControlDensity | null;
    typography?: StatusIndicatorTypography;
    children?: Snippet;
  } = $props();

  const uiPresentation = getUiPresentation();

  const resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole));
  const resolvedDensity = $derived(density ?? $uiPresentation.density);
</script>

<span
  class="poodle-status-indicator"
  data-status={status}
  data-size={resolvedSize}
  data-density={resolvedDensity}
  data-typography={typography}
  aria-label={ariaLabel ?? undefined}
>
  <span class="poodle-status-indicator__dot" aria-hidden="true"></span>
  {#if label}
    <span class="poodle-status-indicator__label">{label}</span>
  {:else}
    {@render children?.()}
  {/if}
</span>

// packages/react/components/src/StatusIndicator.tsx
import type { ReactNode } from "react";

import "@poodle/styles/status-indicator.css";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, SemanticControlSizeRole, StatusTone } from "./types";

export interface StatusIndicatorProps {
  status?: StatusTone;
  label?: string | null;
  ariaLabel?: string | null;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  typography?: "label" | "inherit";
  children?: ReactNode;
}

export function StatusIndicator({
  status = "neutral",
  label = null,
  ariaLabel = null,
  size = null,
  sizeRole = "control",
  density = null,
  typography = "label",
  children,
}: StatusIndicatorProps) {
  const uiPresentation = useUiPresentation();
  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;

  return (
    <span
      className="poodle-status-indicator"
      data-status={status}
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-typography={typography}
      aria-label={ariaLabel ?? undefined}
    >
      <span className="poodle-status-indicator__dot" aria-hidden="true" />
      {label ? <span className="poodle-status-indicator__label">{label}</span> : children}
    </span>
  );
}
