// packages/svelte/components/src/TokenInput.svelte
<script lang="ts">
  import "@inflatable-cookie/poodle-styles/token-input.css";
  import { mergeTokens, splitTokenInput, tokenBackspaceRemoves } from "@inflatable-cookie/poodle-headless";
  import type { HTMLInputAttributes } from "svelte/elements";

  import { default as Icon } from "./Icon.svelte";
  import { default as Pill } from "./Pill.svelte";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";
  import type { ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";

  interface Props {
    id?: string;
    values?: string[];
    name?: string | undefined;
    placeholder?: string | null;
    disabled?: boolean;
    readOnly?: boolean;
    required?: boolean;
    spellcheck?: HTMLInputAttributes["spellcheck"];
    autocapitalize?: HTMLInputAttributes["autocapitalize"];
    autocomplete?: HTMLInputAttributes["autocomplete"];
    ariaLabel?: string | null;
    describedBy?: string | null;
    size?: ControlSize | null;
    sizeRole?: SemanticControlSizeRole;
    density?: ControlDensity | null;
    separators?: string[];
    dedupe?: boolean;
    commitOnBlur?: boolean;
    maxLength?: number | null;
    resolveToken?: ((value: string, values: string[]) => string | null | undefined) | undefined;
    onValuesChange?: ((values: string[]) => void) | undefined;
    onTokenReject?: ((value: string) => void) | undefined;
  }

  let {
    id = "",
    values = $bindable<string[]>([]),
    name = undefined,
    placeholder = null,
    disabled = false,
    readOnly = false,
    required = false,
    spellcheck = false,
    autocapitalize = "none",
    autocomplete = "off",
    ariaLabel = null,
    describedBy = null,
    size = null,
    sizeRole = "control",
    density = null,
    separators = [","],
    dedupe = true,
    commitOnBlur = true,
    maxLength = null,
    resolveToken = undefined,
    onValuesChange = undefined,
    onTokenReject = undefined,
  }: Props = $props();

  const uiPresentation = getUiPresentation();

  let inputValue = $state("");
  let inputElement = $state<HTMLInputElement | null>(null);

  const resolvedSize = $derived(size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole));
  const resolvedDensity = $derived(density ?? $uiPresentation.density);
  const canEdit = $derived(!disabled && !readOnly);
  const separatorChars = $derived(
    Array.from(new Set(separators.filter((separator) => separator.length > 0))).join("")
  );
  const splitPattern = $derived(
    separatorChars.length > 0
      ? new RegExp(`[${escapeRegExp(separatorChars)}]+`)
      : null
  );

  function escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  function normalizeToken(value: string, currentValues: string[]): string | null {
    const trimmed = value.trim();
    if (!trimmed) return null;

    const resolved = resolveToken ? resolveToken(trimmed, currentValues) : trimmed;
    if (typeof resolved !== "string") {
      onTokenReject?.(trimmed);
      return null;
    }

    const normalized = resolved.trim();
    if (!normalized) {
      onTokenReject?.(trimmed);
      return null;
    }

    return normalized;
  }

  function applyValues(nextValues: string[]): void {
    values = nextValues;
    onValuesChange?.(nextValues);
  }

  function addTokens(rawTokens: string[]): void {
    const current = values ?? [];
    const nextTokens = rawTokens
      .map((token) => normalizeToken(token, current))
      .filter((token): token is string => Boolean(token));

    if (nextTokens.length === 0) {
      return;
    }

    applyValues(mergeTokens(current, nextTokens, dedupe));
  }

  function commitInput(): void {
    const trimmed = normalizeToken(inputValue, values ?? []);
    if (!trimmed) {
      inputValue = "";
      return;
    }

    addTokens([trimmed]);
    inputValue = "";
  }

  function removeToken(index: number): void {
    if (!canEdit) return;
    applyValues(values.filter((_, currentIndex) => currentIndex !== index));
  }

  function handleInput(nextValue: string): void {
    const split = splitTokenInput(nextValue, splitPattern, separatorChars);

    if (!split) {
      inputValue = nextValue;
      return;
    }

    addTokens(split.committed);
    inputValue = split.remainder;
  }

  function handleKeyDown(event: KeyboardEvent): void {
    if (!canEdit) return;

    if (event.key === "Enter" || event.key === "Tab") {
      if (inputValue.trim().length > 0) {
        event.preventDefault();
        commitInput();
      }
      return;
    }

    if (event.key === "Backspace" && tokenBackspaceRemoves(inputValue, values.length)) {
      event.preventDefault();
      applyValues(values.slice(0, -1));
    }
  }

  function handleBlur(): void {
    if (commitOnBlur) {
      commitInput();
    }
  }

  function focusInput(): void {
    if (!canEdit) return;
    inputElement?.focus();
  }

  function handlePointerDown(event: PointerEvent): void {
    if (!canEdit || event.target === inputElement) return;
    if (event.target instanceof Element && event.target.closest("button")) return;
    event.preventDefault();
    focusInput();
  }

  function focusInputOnPointerDown(node: HTMLDivElement): { destroy: () => void } {
    node.addEventListener("pointerdown", handlePointerDown);
    return {
      destroy: () => node.removeEventListener("pointerdown", handlePointerDown),
    };
  }
</script>

<div
  class="poodle-token-input"
  data-size={resolvedSize}
  data-density={resolvedDensity}
  data-disabled={disabled || undefined}
  data-read-only={readOnly || undefined}
  use:focusInputOnPointerDown
>
  {#if name}
    {#each values as token, index (`${token}:${index}`)}
      <input type="hidden" {name} value={token} />
    {/each}
  {/if}

  <div class="poodle-token-input__tokens">
    {#each values as token, index (`${token}:${index}`)}
      <span class="poodle-token-input__token">
        <Pill tone="neutral" appearance="subtle" size={resolvedSize} adaptiveWidth>
          <span class="poodle-token-input__token-label">{token}</span>
          {#if canEdit}
            <button
              type="button"
              class="poodle-token-input__remove"
              aria-label={`Remove ${token}`}
              onclick={() => removeToken(index)}
            >
              <Icon name="x" size="xs" />
            </button>
          {/if}
        </Pill>
      </span>
    {/each}

    <input
      {id}
      bind:this={inputElement}
      class="poodle-token-input__control"
      type="text"
      bind:value={inputValue}
      {disabled}
      readonly={readOnly}
      {required}
      {spellcheck}
      {autocapitalize}
      {autocomplete}
      aria-label={ariaLabel ?? undefined}
      aria-describedby={describedBy ?? undefined}
      placeholder={values.length === 0 ? (placeholder ?? undefined) : undefined}
      maxlength={maxLength ?? undefined}
      oninput={(event) => handleInput((event.currentTarget as HTMLInputElement).value)}
      onkeydown={handleKeyDown}
      onblur={handleBlur}
    />
  </div>
</div>

// packages/react/components/src/TokenInput.tsx
import { useRef, useState, type KeyboardEvent, type PointerEvent } from "react";
import { mergeTokens, splitTokenInput, tokenBackspaceRemoves } from "@inflatable-cookie/poodle-headless";

import "@inflatable-cookie/poodle-styles/token-input.css";

import { Icon } from "./Icon";
import { Pill } from "./Pill";
import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, SemanticControlSizeRole } from "./types";

export interface TokenInputProps {
  id?: string;
  values?: string[];
  defaultValues?: string[];
  name?: string;
  placeholder?: string | null;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  spellCheck?: boolean;
  autoCapitalize?: string;
  autoComplete?: string;
  ariaLabel?: string | null;
  describedBy?: string | null;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  separators?: string[];
  dedupe?: boolean;
  commitOnBlur?: boolean;
  maxLength?: number | null;
  resolveToken?: (value: string, values: string[]) => string | null | undefined;
  onValuesChange?: (values: string[]) => void;
  onTokenReject?: (value: string) => void;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function TokenInput({
  id = "",
  values,
  defaultValues = [],
  name,
  placeholder = null,
  disabled = false,
  readOnly = false,
  required = false,
  spellCheck = false,
  autoCapitalize = "none",
  autoComplete = "off",
  ariaLabel = null,
  describedBy = null,
  size = null,
  sizeRole = "control",
  density = null,
  separators = [","],
  dedupe = true,
  commitOnBlur = true,
  maxLength = null,
  resolveToken,
  onValuesChange,
  onTokenReject,
}: TokenInputProps) {
  const uiPresentation = useUiPresentation();

  const [inputValue, setInputValue] = useState("");
  const [uncontrolledValues, setUncontrolledValues] = useState<string[]>(defaultValues);
  const inputRef = useRef<HTMLInputElement | null>(null);

  const isControlled = values !== undefined;
  const currentValues = isControlled ? values : uncontrolledValues;

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const canEdit = !disabled && !readOnly;
  const separatorChars = Array.from(new Set(separators.filter((separator) => separator.length > 0))).join("");
  const splitPattern = separatorChars.length > 0 ? new RegExp(`[${escapeRegExp(separatorChars)}]+`) : null;

  function normalizeToken(value: string, current: string[]): string | null {
    const trimmed = value.trim();
    if (!trimmed) return null;

    const resolved = resolveToken ? resolveToken(trimmed, current) : trimmed;
    if (typeof resolved !== "string") {
      onTokenReject?.(trimmed);
      return null;
    }

    const normalized = resolved.trim();
    if (!normalized) {
      onTokenReject?.(trimmed);
      return null;
    }
    return normalized;
  }

  function applyValues(nextValues: string[]): void {
    if (!isControlled) setUncontrolledValues(nextValues);
    onValuesChange?.(nextValues);
  }

  function addTokens(rawTokens: string[]): void {
    const current = currentValues ?? [];
    const nextTokens = rawTokens
      .map((token) => normalizeToken(token, current))
      .filter((token): token is string => Boolean(token));
    if (nextTokens.length === 0) return;
    applyValues(mergeTokens(current, nextTokens, dedupe));
  }

  function commitInput(): void {
    const trimmed = normalizeToken(inputValue, currentValues ?? []);
    if (!trimmed) {
      setInputValue("");
      return;
    }
    addTokens([trimmed]);
    setInputValue("");
  }

  function removeToken(index: number): void {
    if (!canEdit) return;
    applyValues(currentValues.filter((_, currentIndex) => currentIndex !== index));
  }

  function handleInput(nextValue: string): void {
    const split = splitTokenInput(nextValue, splitPattern, separatorChars);
    if (!split) {
      setInputValue(nextValue);
      return;
    }
    addTokens(split.committed);
    setInputValue(split.remainder);
  }

  function handleKeyDown(event: KeyboardEvent<HTMLInputElement>): void {
    if (!canEdit) return;

    if (event.key === "Enter" || event.key === "Tab") {
      if (inputValue.trim().length > 0) {
        event.preventDefault();
        commitInput();
      }
      return;
    }

    if (event.key === "Backspace" && tokenBackspaceRemoves(inputValue, currentValues.length)) {
      event.preventDefault();
      applyValues(currentValues.slice(0, -1));
    }
  }

  function handlePointerDown(event: PointerEvent<HTMLDivElement>): void {
    if (!canEdit || event.target === inputRef.current) return;
    if (event.target instanceof Element && event.target.closest("button")) return;
    event.preventDefault();
    inputRef.current?.focus();
  }

  return (
    <div
      className="poodle-token-input"
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-disabled={disabled || undefined}
      data-read-only={readOnly || undefined}
      onPointerDown={handlePointerDown}
    >
      {name
        ? currentValues.map((token, index) => (
            <input key={`${token}:${index}`} type="hidden" name={name} value={token} />
          ))
        : null}

      <div className="poodle-token-input__tokens">
        {currentValues.map((token, index) => (
          <span key={`${token}:${index}`} className="poodle-token-input__token">
            <Pill tone="neutral" appearance="subtle" size={resolvedSize} adaptiveWidth>
              <span className="poodle-token-input__token-label">{token}</span>
              {canEdit ? (
                <button
                  type="button"
                  className="poodle-token-input__remove"
                  aria-label={`Remove ${token}`}
                  onClick={() => removeToken(index)}
                >
                  <Icon name="x" size="xs" />
                </button>
              ) : null}
            </Pill>
          </span>
        ))}

        <input
          id={id}
          ref={inputRef}
          className="poodle-token-input__control"
          type="text"
          value={inputValue}
          disabled={disabled}
          readOnly={readOnly}
          required={required}
          spellCheck={spellCheck}
          autoCapitalize={autoCapitalize}
          autoComplete={autoComplete}
          aria-label={ariaLabel ?? undefined}
          aria-describedby={describedBy ?? undefined}
          placeholder={currentValues.length === 0 ? (placeholder ?? undefined) : undefined}
          maxLength={maxLength ?? undefined}
          onChange={(event) => handleInput(event.currentTarget.value)}
          onKeyDown={handleKeyDown}
          onBlur={() => {
            if (commitOnBlur) commitInput();
          }}
        />
      </div>
    </div>
  );
}
