// packages/react/components/src/ListCard.tsx
import "@poodle/styles/list-card.css";

import {
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent,
  type ReactNode,
} from "react";

import { menuNavigableItems, registerDismissLayer } from "@poodle/headless";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, MenuItem, SemanticControlSizeRole } from "./types";

export interface ListCardProps {
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  title: string;
  subtitle?: string | null;
  meta?: string | null;
  href?: string | null;
  leadingShape?: "circle" | "rounded-square";
  leadingFill?: "tint" | "solid";
  leadingSizeOffset?: number;
  accentColor?: string | null;
  layout?: "default" | "compact" | "stacked";
  interactive?: boolean;
  disabled?: boolean;
  selectable?: boolean;
  selected?: boolean;
  highlighted?: boolean;
  selectionIndicator?: "none" | "checkbox";
  showReorderHandle?: boolean;
  notLive?: boolean;
  sash?: string | null;
  sashColor?: string | null;
  ariaLabel?: string | null;
  contextMenuItems?: MenuItem[] | null;
  contextMenuAriaLabel?: string | null;
  contextMenuTrigger?: "context" | "leading";
  onClick?: ((event: ReactMouseEvent | MouseEvent) => void) | null;
  onSelectedChange?: ((selected: boolean) => void) | null;
  onContextAction?: ((value: string) => void) | null;
  titleContent?: ReactNode;
  subtitleContent?: ReactNode;
  metaContent?: ReactNode;
  sashContent?: ReactNode;
  leading?: ReactNode;
  badges?: ReactNode;
  corner?: ReactNode;
  footer?: ReactNode;
  actions?: ReactNode;
  trailing?: ReactNode;
}

const controlSizes: ControlSize[] = ["xs", "sm", "md", "lg", "xl"];

function offsetControlSize(size: ControlSize, offset: number): ControlSize {
  const baseIndex = controlSizes.indexOf(size);
  const nextIndex = Math.max(0, Math.min(controlSizes.length - 1, baseIndex + Math.round(offset)));
  return controlSizes[nextIndex] ?? size;
}

function SelectionBox({ selected }: { selected: boolean }) {
  return (
    <span className="poodle-list-card__selection-box">
      {selected ? (
        <svg
          viewBox="0 0 16 16"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M3.5 8.25l2.75 2.75L12.5 4.75" />
        </svg>
      ) : null}
    </span>
  );
}

export function ListCard({
  size = null,
  sizeRole = "control",
  density = null,
  title,
  subtitle = null,
  meta = null,
  href = null,
  leadingShape = "circle",
  leadingFill = "tint",
  leadingSizeOffset = 0,
  accentColor = null,
  layout = "default",
  interactive = false,
  disabled = false,
  selectable = false,
  selected = false,
  highlighted = false,
  selectionIndicator = "none",
  showReorderHandle = false,
  notLive = false,
  sash = null,
  sashColor = null,
  ariaLabel = null,
  contextMenuItems = null,
  contextMenuAriaLabel = null,
  contextMenuTrigger = "context",
  onClick = null,
  onSelectedChange = null,
  onContextAction = null,
  titleContent,
  subtitleContent,
  metaContent,
  sashContent,
  leading,
  badges,
  corner,
  footer,
  actions,
  trailing,
}: ListCardProps) {
  const uiPresentation = useUiPresentation();

  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedContextMenuSize = resolveSemanticControlSize(uiPresentation.sizeScale, "chrome");
  const resolvedDensity = density ?? uiPresentation.density;
  const resolvedLeadingSize = offsetControlSize(resolvedSize, leadingSizeOffset);
  const isCompact = layout === "compact";
  const isStacked = layout === "stacked";
  const showMeta = !trailing && Boolean(meta || metaContent) && !isCompact;
  const showActions = !trailing && Boolean(actions);
  const showUtilityRail = isStacked && (Boolean(trailing) || showMeta || showActions);
  const isInteractive = Boolean(href) || interactive || selectable;
  const showSelectionIndicator = selectable && selectionIndicator === "checkbox";
  const showSelectionOverlay = showSelectionIndicator && Boolean(leading);
  const actionableContextMenuItems = menuNavigableItems(contextMenuItems ?? []);
  const hasContextMenu = (contextMenuItems?.length ?? 0) > 0;
  const useLeadingContextMenu = contextMenuTrigger === "leading" && hasContextMenu && !selectable;

  const rootRef = useRef<HTMLElement | null>(null);
  const leadingRef = useRef<HTMLElement | null>(null);
  const overlayRef = useRef<HTMLDivElement | null>(null);
  const itemRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const highlightRef = useRef(0);
  const pendingMenuFocus = useRef(false);

  const [contextMenuOpen, setContextMenuOpen] = useState(false);
  const [contextMenuAnchorPoint, setContextMenuAnchorPoint] = useState<{ x: number; y: number } | null>(null);
  const [contextMenuAdjustedPosition, setContextMenuAdjustedPosition] = useState<{ left: string; top: string } | null>(
    null,
  );

  function openContextMenuAt(x: number, y: number) {
    if (!hasContextMenu) return;
    highlightRef.current = 0;
    setContextMenuAnchorPoint({ x, y });
    setContextMenuAdjustedPosition(null);
    pendingMenuFocus.current = true;
    setContextMenuOpen(true);
  }

  function closeContextMenu() {
    setContextMenuOpen(false);
    highlightRef.current = 0;
  }

  function moveContextMenuHighlight(direction: 1 | -1): void {
    const count = actionableContextMenuItems.length;
    if (count === 0) return;

    let nextIndex = highlightRef.current;
    for (let step = 0; step < count; step += 1) {
      nextIndex = (nextIndex + direction + count) % count;
      if (!actionableContextMenuItems[nextIndex]?.disabled) {
        highlightRef.current = nextIndex;
        itemRefs.current[nextIndex]?.focus();
        return;
      }
    }
  }

  function activateContextMenuItem(item: MenuItem): void {
    if (item.disabled || item.kind === "separator") return;
    onContextAction?.(item.value);
    closeContextMenu();
  }

  function handleClick(event: ReactMouseEvent) {
    if (disabled) return;

    if (selectable) {
      event.preventDefault();
      onSelectedChange?.(!selected);
      return;
    }

    if (interactive || href) {
      onClick?.(event);
    }
  }

  function handleKeydown(event: ReactKeyboardEvent) {
    if (disabled || href) return;

    if ((interactive || selectable) && (event.key === "Enter" || event.key === " ")) {
      event.preventDefault();
      if (selectable) {
        onSelectedChange?.(!selected);
      } else {
        onClick?.(new MouseEvent("click"));
      }
    }
  }

  function handleContextMenu(event: ReactMouseEvent) {
    if (disabled || !hasContextMenu) return;
    if (useLeadingContextMenu) return;
    event.preventDefault();
    event.stopPropagation();
    openContextMenuAt(event.clientX, event.clientY);
  }

  function toggleContextMenuFromLeading(event: ReactMouseEvent | ReactKeyboardEvent) {
    if (disabled || !useLeadingContextMenu || !leadingRef.current) return;
    event.preventDefault();
    event.stopPropagation();

    if (contextMenuOpen) {
      closeContextMenu();
      return;
    }

    const rect = leadingRef.current.getBoundingClientRect();
    openContextMenuAt(rect.left + rect.width / 2, rect.bottom + 4);
  }

  function handleContextMenuKeydown(event: ReactKeyboardEvent) {
    if (disabled || !hasContextMenu) return;
    if (event.key === "ContextMenu" || (event.shiftKey && event.key === "F10")) {
      event.preventDefault();
      event.stopPropagation();
      if (useLeadingContextMenu) {
        toggleContextMenuFromLeading(event);
        return;
      }
      const rect = rootRef.current?.getBoundingClientRect();
      if (!rect) return;
      openContextMenuAt(rect.left + 16, rect.top + 16);
    }
  }

  function handleRootKeydown(event: ReactKeyboardEvent) {
    handleKeydown(event);
    handleContextMenuKeydown(event);
  }

  useLayoutEffect(() => {
    if (!contextMenuOpen || !contextMenuAnchorPoint) return;
    if (contextMenuAdjustedPosition) return;
    const overlay = overlayRef.current;
    if (!overlay) return;

    const rect = overlay.getBoundingClientRect();
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const pad = 8;
    let x = contextMenuAnchorPoint.x;
    let y = contextMenuAnchorPoint.y;

    if (x + rect.width > vw - pad) {
      x = Math.max(pad, x - rect.width);
    }

    if (y + rect.height > vh - pad) {
      y = Math.max(pad, vh - rect.height - pad);
    }

    setContextMenuAdjustedPosition({ left: `${x}px`, top: `${y}px` });
  }, [contextMenuOpen, contextMenuAnchorPoint, contextMenuAdjustedPosition]);

  useEffect(() => {
    if (!contextMenuOpen || !contextMenuAdjustedPosition) return;
    if (!pendingMenuFocus.current) return;
    pendingMenuFocus.current = false;
    itemRefs.current[highlightRef.current]?.focus();
  }, [contextMenuOpen, contextMenuAdjustedPosition]);

  useEffect(() => {
    if (!contextMenuOpen) return;

    return registerDismissLayer({
      // The overlay and the leading trigger area count as inside.
      contains: (target) =>
        (overlayRef.current?.contains(target) ?? false) || (leadingRef.current?.contains(target) ?? false),
      dismissOnOutsideInteract: true,
      onDismiss: () => closeContextMenu(),
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [contextMenuOpen]);

  const rootStyle: CSSProperties | undefined =
    accentColor || sashColor
      ? ({
          ...(accentColor ? { "--list-card-accent": accentColor } : {}),
          ...(sashColor ? { "--list-card-sash": sashColor } : {}),
        } as CSSProperties)
      : undefined;

  const rootClassName = [
    "poodle-list-card",
    isInteractive ? "poodle-list-card--interactive" : "",
    sash ? "poodle-list-card--has-sash" : "",
  ]
    .filter(Boolean)
    .join(" ");

  const selectionOverlay = showSelectionOverlay ? (
    <span
      className="poodle-list-card__selection-indicator poodle-list-card__selection-indicator--overlay"
      aria-hidden="true"
    >
      <SelectionBox selected={selected} />
    </span>
  ) : null;

  const leadingContent = leading ? (
    useLeadingContextMenu && !disabled ? (
      <button
        ref={(el) => {
          leadingRef.current = el;
        }}
        type="button"
        className="poodle-list-card__leading poodle-list-card__leading-button"
        data-interactive={true}
        data-selection-overlay={showSelectionOverlay}
        aria-label={contextMenuAriaLabel ?? `${title} actions`}
        onClick={toggleContextMenuFromLeading}
        onKeyDown={(event) => {
          if (event.key === "Enter" || event.key === " ") {
            toggleContextMenuFromLeading(event);
          }
        }}
      >
        <span className="poodle-list-card__leading-content" aria-hidden={showSelectionOverlay ? "true" : undefined}>
          {leading}
        </span>
        {selectionOverlay}
      </button>
    ) : (
      <span
        ref={(el) => {
          leadingRef.current = el;
        }}
        className="poodle-list-card__leading"
        data-interactive={useLeadingContextMenu}
        data-selection-overlay={showSelectionOverlay}
      >
        <span className="poodle-list-card__leading-content" aria-hidden={showSelectionOverlay ? "true" : undefined}>
          {leading}
        </span>
        {selectionOverlay}
      </span>
    )
  ) : showSelectionIndicator ? (
    <span className="poodle-list-card__selection-indicator" aria-hidden="true">
      <SelectionBox selected={selected} />
    </span>
  ) : null;

  const cardInner = (
    <>
      {sashContent || sash ? (
        <span className="poodle-list-card__sash" aria-label={sash ?? undefined}>
          {sashContent ?? sash}
        </span>
      ) : null}

      {showReorderHandle ? (
        <span className="poodle-list-card__handle" aria-hidden="true">
          <svg viewBox="0 0 16 16" fill="currentColor">
            <circle cx="5" cy="4" r="1.1" />
            <circle cx="5" cy="8" r="1.1" />
            <circle cx="5" cy="12" r="1.1" />
            <circle cx="11" cy="4" r="1.1" />
            <circle cx="11" cy="8" r="1.1" />
            <circle cx="11" cy="12" r="1.1" />
          </svg>
        </span>
      ) : null}

      {leadingContent}

      <div className="poodle-list-card__body">
        <div className="poodle-list-card__header">
          <span className="poodle-list-card__title">{titleContent ?? title}</span>
          {badges || corner ? (
            <span className="poodle-list-card__header-accessories">
              {badges ? <span className="poodle-list-card__badges">{badges}</span> : null}
              {corner ? <span className="poodle-list-card__corner">{corner}</span> : null}
            </span>
          ) : null}
        </div>
        {subtitleContent ? (
          <span className="poodle-list-card__subtitle">{subtitleContent}</span>
        ) : subtitle ? (
          <span className="poodle-list-card__subtitle">{subtitle}</span>
        ) : null}
        {footer ? <div className="poodle-list-card__footer">{footer}</div> : null}
      </div>

      {showUtilityRail ? (
        <div className="poodle-list-card__utility-rail">
          {showMeta ? <span className="poodle-list-card__meta">{metaContent ?? meta}</span> : null}
          {showActions ? <span className="poodle-list-card__actions">{actions}</span> : null}
          {trailing ? <span className="poodle-list-card__trailing">{trailing}</span> : null}
        </div>
      ) : (
        <>
          {showMeta ? <span className="poodle-list-card__meta">{metaContent ?? meta}</span> : null}
          {showActions ? <span className="poodle-list-card__actions">{actions}</span> : null}
          {trailing ? <span className="poodle-list-card__trailing">{trailing}</span> : null}
        </>
      )}
    </>
  );

  const sharedDataProps = {
    "data-density": resolvedDensity,
    "data-disabled": disabled,
    "data-not-live": notLive,
    "data-leading-shape": leadingShape,
    "data-leading-fill": leadingFill,
    "data-leading-size": resolvedLeadingSize,
    "data-layout": layout,
    "data-selected": selected,
    "data-highlighted": highlighted,
    "data-reorder": showReorderHandle,
  };

  const contextMenuOverlay =
    contextMenuOpen && hasContextMenu && contextMenuAnchorPoint ? (
      <div
        ref={overlayRef}
        className="poodle-list-card__context-menu"
        data-size={resolvedSize}
        data-density={resolvedDensity}
        role="menu"
        aria-label={contextMenuAriaLabel ?? undefined}
        style={
          contextMenuAdjustedPosition
            ? { left: contextMenuAdjustedPosition.left, top: contextMenuAdjustedPosition.top }
            : { left: `${contextMenuAnchorPoint.x}px`, top: `${contextMenuAnchorPoint.y}px`, visibility: "hidden" }
        }
      >
        {(contextMenuItems ?? []).map((item) =>
          item.kind === "separator" ? (
            <div key={item.value} className="poodle-list-card__context-separator" role="separator" />
          ) : (
            <button
              key={item.value}
              ref={(el) => {
                const index = actionableContextMenuItems.findIndex((candidate) => candidate.value === item.value);
                if (index >= 0) {
                  itemRefs.current[index] = el;
                }
              }}
              type="button"
              className="poodle-list-card__context-item"
              disabled={item.disabled === true}
              data-tone={item.tone ?? "default"}
              role={item.kind === "checkbox" || item.kind === "radio" ? `menuitem${item.kind}` : "menuitem"}
              aria-checked={
                item.kind === "checkbox" || item.kind === "radio" ? (item.checked ? "true" : "false") : undefined
              }
              onClick={() => activateContextMenuItem(item)}
              onKeyDown={(event) => {
                if (event.key === "ArrowDown") {
                  event.preventDefault();
                  moveContextMenuHighlight(1);
                }

                if (event.key === "ArrowUp") {
                  event.preventDefault();
                  moveContextMenuHighlight(-1);
                }

                if (event.key === "Home") {
                  event.preventDefault();
                  highlightRef.current = 0;
                  itemRefs.current[0]?.focus();
                }

                if (event.key === "End") {
                  event.preventDefault();
                  highlightRef.current = actionableContextMenuItems.length - 1;
                  itemRefs.current[actionableContextMenuItems.length - 1]?.focus();
                }

                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  activateContextMenuItem(item);
                }
              }}
            >
              <span>{item.label}</span>

              {item.checked ? (
                <span className="poodle-list-card__context-meta" aria-hidden="true">
                  ✓
                </span>
              ) : item.shortcutLabel ? (
                <span className="poodle-list-card__context-meta" aria-hidden="true">
                  {item.shortcutLabel}
                </span>
              ) : null}
            </button>
          ),
        )}
      </div>
    ) : null;

  if (href && !disabled && !selectable) {
    return (
      <>
        <a
          ref={(el) => {
            rootRef.current = el;
          }}
          className={rootClassName}
          href={href}
          data-size={resolvedContextMenuSize}
          {...sharedDataProps}
          aria-label={ariaLabel ?? title}
          style={rootStyle}
          onClick={handleClick}
          onContextMenu={handleContextMenu}
          onKeyDown={handleContextMenuKeydown}
        >
          {cardInner}
        </a>
        {contextMenuOverlay}
      </>
    );
  }

  return (
    <>
      <div
        ref={(el) => {
          rootRef.current = el;
        }}
        className={rootClassName}
        data-size={resolvedSize}
        {...sharedDataProps}
        role={isInteractive ? "button" : undefined}
        aria-pressed={selectable ? selected : undefined}
        tabIndex={isInteractive && !disabled ? 0 : -1}
        aria-label={ariaLabel ?? title}
        style={rootStyle}
        onClick={handleClick}
        onKeyDown={handleRootKeydown}
        onContextMenu={handleContextMenu}
      >
        {cardInner}
      </div>
      {contextMenuOverlay}
    </>
  );
}

// packages/svelte/primitives/src/ListCard.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  export let title: string;
  export let subtitle: string | null = null;
  export let meta: string | null = null;
  export let href: string | null = null;
  export let leadingShape: "circle" | "rounded-square" = "circle";
  export let leadingFill: "tint" | "solid" = "tint";
  export let accentColor: string | null = null;
  export let layout: "default" | "compact" = "default";
  export let interactive = false;
  export let disabled = false;
  export let selectable = false;
  export let selected = false;
  export let showReorderHandle = false;
  export let notLive = false;
  export let sash: string | null = null;
  export let sashColor: string | null = null;
  export let ariaLabel: string | null = null;

  const dispatch = createEventDispatcher<{
    click: MouseEvent;
    selectedChange: { selected: boolean };
  }>();

  $: isCompact = layout === "compact";
  $: isInteractive = Boolean(href) || interactive || selectable;

  function handleClick(event: MouseEvent) {
    if (disabled) return;

    if (selectable) {
      event.preventDefault();
      dispatch("selectedChange", { selected: !selected });
      return;
    }

    if (interactive || href) {
      dispatch("click", event);
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (disabled || href) return;

    if ((interactive || selectable) && (event.key === "Enter" || event.key === " ")) {
      event.preventDefault();
      if (selectable) {
        dispatch("selectedChange", { selected: !selected });
      } else {
        dispatch("click", new MouseEvent("click"));
      }
    }
  }
</script>

{#if href && !disabled && !selectable}
  <a
    class="list-card"
    class:list-card--interactive={isInteractive}
    href={href}
    data-disabled={disabled}
    data-not-live={notLive}
    data-leading-shape={leadingShape}
    data-leading-fill={leadingFill}
    data-layout={layout}
    data-selected={selected}
    aria-label={ariaLabel ?? title}
    class:list-card--has-sash={!!sash}
    style={[
      accentColor ? `--list-card-accent: ${accentColor}` : '',
      sashColor ? `--list-card-sash: ${sashColor}` : '',
    ].filter(Boolean).join('; ') || undefined}
    on:click={handleClick}
  >
    {#if sash}
      <span class="list-card__sash" aria-label={sash}>{sash}</span>
    {/if}

    {#if showReorderHandle}
      <span class="list-card__handle" aria-hidden="true">
        <svg viewBox="0 0 16 16" fill="currentColor">
          <circle cx="5" cy="4" r="1.1"></circle>
          <circle cx="5" cy="8" r="1.1"></circle>
          <circle cx="5" cy="12" r="1.1"></circle>
          <circle cx="11" cy="4" r="1.1"></circle>
          <circle cx="11" cy="8" r="1.1"></circle>
          <circle cx="11" cy="12" r="1.1"></circle>
        </svg>
      </span>
    {/if}

    {#if $$slots.leading}
      <span class="list-card__leading">
        <slot name="leading" />
      </span>
    {/if}

    <div class="list-card__body">
      <div class="list-card__header">
        <span class="list-card__title">
          <slot name="title">{title}</slot>
        </span>
        {#if $$slots.badges}
          <span class="list-card__badges">
            <slot name="badges" />
          </span>
        {/if}
      </div>
      {#if subtitle}
        <span class="list-card__subtitle">{subtitle}</span>
      {/if}
      {#if $$slots.footer}
        <div class="list-card__footer">
          <slot name="footer" />
        </div>
      {/if}
    </div>

    {#if meta && !isCompact}
      <span class="list-card__meta">{meta}</span>
    {/if}

    {#if $$slots.actions}
      <span class="list-card__actions">
        <slot name="actions" />
      </span>
    {/if}

    {#if $$slots.trailing}
      <span class="list-card__trailing">
        <slot name="trailing" />
      </span>
    {/if}
  </a>
{:else}
  <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
  <div
    class="list-card"
    class:list-card--interactive={isInteractive}
    data-disabled={disabled}
    data-not-live={notLive}
    data-leading-shape={leadingShape}
    data-leading-fill={leadingFill}
    data-layout={layout}
    data-selected={selected}
    role={isInteractive ? (selectable ? "button" : "button") : undefined}
    aria-pressed={selectable ? selected : undefined}
    tabindex={isInteractive && !disabled ? 0 : -1}
    aria-label={ariaLabel ?? title}
    class:list-card--has-sash={!!sash}
    style={[
      accentColor ? `--list-card-accent: ${accentColor}` : '',
      sashColor ? `--list-card-sash: ${sashColor}` : '',
    ].filter(Boolean).join('; ') || undefined}
    on:click={handleClick}
    on:keydown={handleKeydown}
  >
    {#if sash}
      <span class="list-card__sash" aria-label={sash}>{sash}</span>
    {/if}

    {#if showReorderHandle}
      <span class="list-card__handle" aria-hidden="true">
        <svg viewBox="0 0 16 16" fill="currentColor">
          <circle cx="5" cy="4" r="1.1"></circle>
          <circle cx="5" cy="8" r="1.1"></circle>
          <circle cx="5" cy="12" r="1.1"></circle>
          <circle cx="11" cy="4" r="1.1"></circle>
          <circle cx="11" cy="8" r="1.1"></circle>
          <circle cx="11" cy="12" r="1.1"></circle>
        </svg>
      </span>
    {/if}

    {#if $$slots.leading}
      <span class="list-card__leading">
        <slot name="leading" />
      </span>
    {/if}

    <div class="list-card__body">
      <div class="list-card__header">
        <span class="list-card__title">
          <slot name="title">{title}</slot>
        </span>
        {#if $$slots.badges}
          <span class="list-card__badges">
            <slot name="badges" />
          </span>
        {/if}
      </div>
      {#if subtitle}
        <span class="list-card__subtitle">{subtitle}</span>
      {/if}
      {#if $$slots.footer}
        <div class="list-card__footer">
          <slot name="footer" />
        </div>
      {/if}
    </div>

    {#if meta && !isCompact}
      <span class="list-card__meta">{meta}</span>
    {/if}

    {#if $$slots.actions}
      <span class="list-card__actions">
        <slot name="actions" />
      </span>
    {/if}

    {#if $$slots.trailing}
      <span class="list-card__trailing">
        <slot name="trailing" />
      </span>
    {/if}
  </div>
{/if}

<style>
  .list-card {
    display: flex;
    align-items: center;
    gap: var(--poodle-space-inline-md);
    padding: var(--poodle-space-panel-y) var(--poodle-space-panel-x);
    border: 0.0625rem solid color-mix(in srgb, var(--poodle-color-border-subtle) 18%, transparent);
    border-radius: var(--poodle-radius-control);
    background: color-mix(in srgb, var(--poodle-surface) 88%, var(--poodle-color-text-primary));
    text-decoration: none;
    width: 100%;
    transition:
      background var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard),
      border-color var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard);
  }

  .list-card--has-sash {
    position: relative;
    overflow: hidden;
  }

  .list-card--interactive {
    cursor: pointer;
  }

  .list-card--interactive:hover:not([data-disabled="true"]) {
    background: color-mix(in srgb, var(--poodle-surface) 82%, var(--poodle-color-text-primary));
    border-color: color-mix(in srgb, var(--poodle-color-border-default) 52%, transparent);
  }

  .list-card[data-selected="true"] {
    border-color: var(--list-card-accent, var(--poodle-color-accent-base));
    box-shadow:
      0 0 0 0.0625rem var(--list-card-accent, var(--poodle-color-accent-base)),
      inset 0 0 0 0.0625rem color-mix(
        in srgb,
        var(--list-card-accent, var(--poodle-color-accent-base)) 12%,
        transparent
      );
  }

  .list-card--interactive[data-selected="true"]:hover:not([data-disabled="true"]) {
    border-color: var(--list-card-accent, var(--poodle-color-accent-base));
  }

  .list-card:focus-visible {
    outline: var(--poodle-border-width-focus) solid var(--poodle-color-accent-focusRing);
    outline-offset: -0.0625rem;
  }

  .list-card[data-disabled="true"] {
    cursor: not-allowed;
    opacity: var(--poodle-state-opacity-disabled);
  }

  .list-card[data-not-live="true"] {
    border: 0.1875rem dashed color-mix(in srgb, var(--poodle-color-border-default) 72%, transparent);
    background: color-mix(in srgb, var(--poodle-surface) 32%, transparent);
    filter: grayscale(1);
    opacity: 0.72;
  }

  .list-card[data-not-live="true"]:hover:not([data-disabled="true"]) {
    border-color: var(--poodle-color-border-default);
    filter: grayscale(0);
    opacity: 1;
  }

  .list-card[data-layout="compact"] {
    gap: var(--poodle-space-inline-sm);
    padding: 0.5rem 0.625rem;
    min-height: 3rem;
  }

  .list-card[data-layout="compact"] .list-card__leading {
    width: 1.5rem;
    height: 1.5rem;
    font-size: 0.75rem;
  }

  .list-card[data-layout="compact"][data-leading-shape="rounded-square"] .list-card__leading {
    width: 1.75rem;
    height: 1.75rem;
  }

  .list-card[data-layout="compact"] .list-card__body {
    gap: 0;
  }

  .list-card[data-layout="compact"] .list-card__title {
    font-size: 0.875rem;
  }

  .list-card[data-layout="compact"] .list-card__subtitle,
  .list-card[data-layout="compact"] .list-card__footer {
    display: none;
  }

  .list-card__handle {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    width: 1rem;
    height: 1rem;
    color: var(--poodle-color-text-secondary);
    opacity: 0.8;
  }

  .list-card__handle svg {
    width: 100%;
    height: 100%;
  }

  .list-card__leading {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    width: 2rem;
    height: 2rem;
    overflow: hidden;
    border-radius: 999px;
    background: color-mix(in srgb, var(--list-card-accent, var(--poodle-color-accent-base)) 12%, transparent);
    color: var(--list-card-accent, var(--poodle-color-accent-base));
    font-size: 0.875rem;
    font-weight: 600;
  }

  .list-card[data-leading-shape="rounded-square"] .list-card__leading {
    width: 2.75rem;
    height: 2.75rem;
    border-radius: var(--poodle-radius-control);
  }

  .list-card[data-leading-fill="solid"] .list-card__leading {
    background: var(--list-card-accent, var(--poodle-color-accent-base));
    color: #fff;
  }

  .list-card__body {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
    gap: 0.0625rem;
  }

  .list-card__header {
    display: flex;
    align-items: baseline;
    gap: var(--poodle-space-inline-sm);
  }

  .list-card__title {
    flex: 1;
    min-width: 0;
    font-family: var(--poodle-typography-body-family);
    font-size: var(--poodle-typography-body-size);
    font-weight: 500;
    color: var(--poodle-color-text-primary);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .list-card__badges {
    flex-shrink: 0;
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: var(--poodle-space-inline-sm);
  }

  .list-card__subtitle {
    font-size: 0.75rem;
    color: var(--poodle-color-text-secondary);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .list-card__footer {
    display: flex;
    align-items: center;
    gap: var(--poodle-space-inline-md);
    margin-top: 0.125rem;
  }

  .list-card__meta {
    flex-shrink: 0;
    font-size: 0.75rem;
    color: var(--poodle-color-text-secondary);
    font-variant-numeric: tabular-nums;
  }

  .list-card__trailing {
    display: flex;
    align-items: center;
    flex-shrink: 0;
  }

  .list-card__actions {
    display: flex;
    align-items: center;
    flex-shrink: 0;
  }

  .list-card__sash {
    position: absolute;
    top: 0.34375rem;
    left: -2.25rem;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 6rem;
    padding: 0.125rem 0;
    background: var(--list-card-sash, var(--poodle-color-positive-base, #22c55e));
    color: #fff;
    font-size: 0.5625rem;
    font-weight: 700;
    text-transform: uppercase;
    line-height: 1;
    transform: rotate(-45deg);
    pointer-events: none;
    z-index: 1;
  }
</style>
