// packages/react/components/src/ListCardCounter.tsx
import type { MouseEvent, ReactNode } from "react";

import "@poodle/styles/list-card-counter.css";

import { Icon } from "./Icon";
import { Tooltip } from "./Tooltip";
import type { IconProp } from "./types";

export interface ListCardCounterProps {
  icon: IconProp;
  count: number;
  tooltip?: string | null;
  href?: string | null;
  onClick?: ((event: MouseEvent<HTMLElement>) => void) | null;
  typography?: "label" | "inherit";
}

export function ListCardCounter({
  icon,
  count,
  tooltip = null,
  href = null,
  onClick = null,
  typography = "label",
}: ListCardCounterProps) {
  const handleClick = (e: MouseEvent<HTMLElement>) => {
    if (href) e.stopPropagation();
    onClick?.(e);
  };

  const body: ReactNode = href ? (
    <a className="poodle-list-card-counter" data-typography={typography} href={href} onClick={handleClick}>
      <Icon icon={icon} />
      <span>{count}</span>
    </a>
  ) : (
    <span className="poodle-list-card-counter" data-typography={typography}>
      <Icon icon={icon} />
      <span>{count}</span>
    </span>
  );

  return tooltip ? <Tooltip content={tooltip}>{body}</Tooltip> : body;
}

// packages/svelte/primitives/src/ListCardCounter.svelte
<script lang="ts">
  import Icon from "./Icon.svelte";
  import type { IconProp } from "./types";
  import Tooltip from "./Tooltip.svelte";

  export let icon: IconProp;
  export let count: number;
  export let tooltip: string | null = null;
  export let href: string | null = null;
  export let onClick: ((event: MouseEvent) => void) | null = null;

  function handleClick(e: MouseEvent): void {
    if (href) e.stopPropagation();
    onClick?.(e);
  }
</script>

{#if tooltip}
  <Tooltip content={tooltip}>
    {#if href}
      <a class="list-card-counter" {href} onclick={handleClick}>
        <Icon icon={icon} />
        <span>{count}</span>
      </a>
    {:else}
      <span class="list-card-counter">
        <Icon icon={icon} />
        <span>{count}</span>
      </span>
    {/if}
  </Tooltip>
{:else if href}
  <a class="list-card-counter" {href} onclick={handleClick}>
    <Icon icon={icon} />
    <span>{count}</span>
  </a>
{:else}
  <span class="list-card-counter">
    <Icon icon={icon} />
    <span>{count}</span>
  </span>
{/if}

<style>
  .list-card-counter {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
    color: var(--poodle-color-text-secondary);
    font-size: 0.75rem;
    font-variant-numeric: tabular-nums;
    text-decoration: none;
  }

  a.list-card-counter:hover {
    color: var(--poodle-color-text-primary);
  }
</style>
