// packages/react/components/src/NavigationMenu.tsx
import "@inflatable-cookie/poodle-core/styles/navigation-menu.css";

import { useEffect, useId, useRef, useState, type KeyboardEvent as ReactKeyboardEvent, type ReactNode } from "react";

import { findNextEnabledIndex, firstEnabledIndex, registerDismissLayer } from "@inflatable-cookie/poodle-core";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, NavigationMenuItem, SemanticControlSizeRole } from "./types";

export interface NavigationMenuProps {
  value?: string | null;
  defaultValue?: string | null;
  items?: NavigationMenuItem[];
  ariaLabel?: string | null;
  sizeRole?: SemanticControlSizeRole;
  size?: ControlSize | null;
  density?: ControlDensity | null;
  onValueChange?: ((value: string | null) => void) | undefined;
  children?: (value: string | null, item: NavigationMenuItem | null) => ReactNode;
}

export function NavigationMenu({
  value: controlledValue,
  defaultValue = null,
  items = [],
  ariaLabel = null,
  sizeRole = "chrome",
  size = null,
  density = null,
  onValueChange = undefined,
  children,
}: NavigationMenuProps) {
  const menuId = useId();
  const uiPresentation = useUiPresentation();

  const rootRef = useRef<HTMLDivElement | null>(null);
  const triggerRefs = useRef<Array<HTMLButtonElement | null>>([]);

  const [uncontrolledValue, setUncontrolledValue] = useState<string | null>(defaultValue);
  const [focusIndex, setFocusIndex] = useState(0);

  const isControlled = controlledValue !== undefined && controlledValue !== null;
  const currentValue = isControlled ? controlledValue : uncontrolledValue;
  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;
  const currentItem = items.find((item) => item.value === currentValue) ?? null;
  const selectedIndex = items.findIndex((item) => item.value === currentValue);

  const firstEnabled = firstEnabledIndex(items);
  const resolvedFocusIndex =
    selectedIndex >= 0 ? selectedIndex : firstEnabled >= 0 && focusIndex === 0 ? firstEnabled : focusIndex;

  function setValue(nextValue: string | null): void {
    if (!isControlled) {
      setUncontrolledValue(nextValue);
    }
    onValueChange?.(nextValue);
  }

  function toggleValue(nextValue: string): void {
    setValue(currentValue === nextValue ? null : nextValue);
  }

  function moveFocus(nextIndex: number): void {
    setFocusIndex(nextIndex);
    triggerRefs.current[nextIndex]?.focus();
  }

  function handleKeydown(event: ReactKeyboardEvent, index: number): void {
    if (event.key === "ArrowRight") {
      event.preventDefault();
      moveFocus(findNextEnabledIndex(items, index, 1));
    }

    if (event.key === "ArrowLeft") {
      event.preventDefault();
      moveFocus(findNextEnabledIndex(items, index, -1));
    }

    if (event.key === "Home") {
      event.preventDefault();
      moveFocus(firstEnabledIndex(items));
    }

    if (event.key === "End") {
      event.preventDefault();
      moveFocus(findNextEnabledIndex(items, 0, -1));
    }

    if (event.key === "ArrowDown" || event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      const nextValue = items[index]?.value;

      if (nextValue) {
        setValue(nextValue);
      }
    }

    if (event.key === "Escape") {
      event.preventDefault();
      setValue(null);
    }
  }

  useEffect(() => {
    if (!currentValue) {
      return;
    }

    return registerDismissLayer({
      contains: (target) => rootRef.current?.contains(target) ?? false,
      dismissOnOutsideInteract: true,
      onDismiss: () => setValue(null),
    });
  }, [currentValue]);

  return (
    <div ref={rootRef} className="poodle-navigation-menu" data-size={resolvedSize} data-density={resolvedDensity}>
      <nav className="poodle-navigation-menu__list" aria-label={ariaLabel ?? undefined}>
        {items.map((item, index) => (
          <button
            key={item.value}
            ref={(el) => {
              triggerRefs.current[index] = el;
            }}
            type="button"
            className="poodle-navigation-menu__trigger"
            data-open={currentValue === item.value}
            disabled={item.disabled === true}
            tabIndex={index === resolvedFocusIndex ? 0 : -1}
            id={`poodle-navigation-menu-trigger-${menuId}-${item.value}`}
            aria-expanded={currentValue === item.value ? "true" : "false"}
            aria-controls={
              currentValue === item.value ? `poodle-navigation-menu-panel-${menuId}-${item.value}` : undefined
            }
            onFocus={() => setFocusIndex(index)}
            onClick={() => toggleValue(item.value)}
            onKeyDown={(event) => handleKeydown(event, index)}
          >
            <span className="poodle-navigation-menu__label">{item.label}</span>
          </button>
        ))}
      </nav>

      {currentItem ? (
        <div
          className="poodle-navigation-menu__viewport"
          id={`poodle-navigation-menu-panel-${menuId}-${currentItem.value}`}
          aria-labelledby={`poodle-navigation-menu-trigger-${menuId}-${currentItem.value}`}
        >
          {children?.(currentItem.value, currentItem)}
        </div>
      ) : null}
    </div>
  );
}

// packages/svelte/primitives/src/NavigationMenu.svelte
<script context="module" lang="ts">
  let nextNavigationMenuId = 0;
</script>

<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";

  import { findNextEnabledIndex, firstEnabledIndex } from "./internal";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";

  import type { ControlDensity, ControlSize, NavigationMenuItem, SemanticControlSizeRole } from "./types";

  export let value: string | null = null;
  export let defaultValue: string | null = null;
  export let items: NavigationMenuItem[] = [];
  export let ariaLabel: string | null = null;
  export let sizeRole: SemanticControlSizeRole = "chrome";
  export let size: ControlSize | null = null;
  export let density: ControlDensity | null = null;

  const dispatch = createEventDispatcher<{
    valueChange: { value: string | null };
  }>();

  const menuId = ++nextNavigationMenuId;
  const uiPresentation = getUiPresentation();

  let rootElement: HTMLDivElement | null = null;
  let triggerElements: Array<HTMLButtonElement | null> = [];
  let uncontrolledValue = defaultValue;
  let focusIndex = 0;

  $: resolvedSize = size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole);
  $: resolvedDensity = density ?? $uiPresentation.density;
  $: currentValue = value ?? uncontrolledValue;
  $: currentItem = items.find((item) => item.value === currentValue) ?? null;
  $: selectedIndex = items.findIndex((item) => item.value === currentValue);
  $: if (selectedIndex >= 0) {
    focusIndex = selectedIndex;
  } else if (firstEnabledIndex(items) >= 0 && focusIndex === 0) {
    focusIndex = firstEnabledIndex(items);
  }

  function setValue(nextValue: string | null): void {
    if (value === null) {
      uncontrolledValue = nextValue;
    }

    dispatch("valueChange", { value: nextValue });
  }

  function toggleValue(nextValue: string): void {
    setValue(currentValue === nextValue ? null : nextValue);
  }

  function moveFocus(nextIndex: number): void {
    focusIndex = nextIndex;
    triggerElements[nextIndex]?.focus();
  }

  function handleKeydown(event: KeyboardEvent, index: number): void {
    if (event.key === "ArrowRight") {
      event.preventDefault();
      moveFocus(findNextEnabledIndex(items, index, 1));
    }

    if (event.key === "ArrowLeft") {
      event.preventDefault();
      moveFocus(findNextEnabledIndex(items, index, -1));
    }

    if (event.key === "Home") {
      event.preventDefault();
      moveFocus(firstEnabledIndex(items));
    }

    if (event.key === "End") {
      event.preventDefault();
      moveFocus(findNextEnabledIndex(items, 0, -1));
    }

    if (event.key === "ArrowDown" || event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      const nextValue = items[index]?.value;

      if (nextValue) {
        setValue(nextValue);
      }
    }

    if (event.key === "Escape") {
      event.preventDefault();
      setValue(null);
    }
  }

  onMount(() => {
    function handlePointerDown(event: MouseEvent): void {
      if (!currentValue || !rootElement) {
        return;
      }

      if (!rootElement.contains(event.target as Node)) {
        setValue(null);
      }
    }

    function handleKeydown(event: KeyboardEvent): void {
      if (event.key === "Escape" && currentValue) {
        event.preventDefault();
        setValue(null);
      }
    }

    document.addEventListener("mousedown", handlePointerDown);
    document.addEventListener("keydown", handleKeydown);

    return () => {
      document.removeEventListener("mousedown", handlePointerDown);
      document.removeEventListener("keydown", handleKeydown);
    };
  });
</script>

<div class="navigation-menu" bind:this={rootElement} data-size={resolvedSize} data-density={resolvedDensity}>
  <nav
    class="navigation-menu__list"
    aria-label={ariaLabel ?? undefined}
  >
    {#each items as item, index (item.value)}
      <button
        bind:this={triggerElements[index]}
        type="button"
        class="navigation-menu__trigger"
        data-open={currentValue === item.value}
        disabled={item.disabled === true}
        tabindex={index === focusIndex ? 0 : -1}
        id={`poodle-navigation-menu-trigger-${menuId}-${item.value}`}
        aria-expanded={currentValue === item.value ? "true" : "false"}
        aria-controls={currentValue === item.value ? `poodle-navigation-menu-panel-${menuId}-${item.value}` : undefined}
        on:focus={() => (focusIndex = index)}
        on:click={() => toggleValue(item.value)}
        on:keydown={(event) => handleKeydown(event, index)}
      >
        <span class="navigation-menu__label">{item.label}</span>
      </button>
    {/each}
  </nav>

  {#if currentItem}
    <div
      class="navigation-menu__viewport"
      id={`poodle-navigation-menu-panel-${menuId}-${currentItem.value}`}
      aria-labelledby={`poodle-navigation-menu-trigger-${menuId}-${currentItem.value}`}
    >
      <slot activeValue={currentItem.value} activeItem={currentItem} />
    </div>
  {/if}
</div>

<style>
  .navigation-menu {
    display: grid;
    gap: var(--poodle-space-stack-md);
    min-width: 0;
  }

  .navigation-menu__list {
    display: inline-flex;
    flex-wrap: wrap;
    gap: var(--poodle-space-inline-sm);
    align-items: center;
  }

  .navigation-menu__trigger {
    display: inline-flex;
    align-items: center;
    gap: var(--poodle-space-inline-sm);
    min-height: calc(var(--poodle-size-control-height) - 0.125rem);
    padding: 0 var(--poodle-space-control-x);
    border: 0.0625rem solid color-mix(in srgb, var(--poodle-color-border-subtle) 72%, transparent);
    border-radius: var(--poodle-radius-control);
    background: color-mix(in srgb, var(--poodle-color-background-surface) 88%, transparent);
    color: var(--poodle-color-text-primary);
    cursor: pointer;
    font-family: var(--poodle-typography-label-family);
    font-size: 0.75rem;
    font-weight: 600;
    line-height: 1;
  }

  .navigation-menu__trigger[data-open="true"] {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 16%, transparent);
    border-color: color-mix(in srgb, var(--poodle-color-accent-base) 42%, var(--poodle-color-border-default));
  }

  .navigation-menu__trigger:hover:not(:disabled),
  .navigation-menu__trigger:focus-visible {
    background: color-mix(in srgb, var(--poodle-color-accent-base) 12%, transparent);
    outline: none;
  }

  .navigation-menu__trigger:disabled {
    cursor: not-allowed;
    opacity: var(--poodle-state-opacity-disabled);
  }

  .navigation-menu__viewport {
    min-width: 0;
    padding: var(--poodle-space-panel-y) var(--poodle-space-panel-x);
    border: 0.0625rem solid color-mix(in srgb, var(--poodle-color-border-subtle) 74%, transparent);
    border-radius: var(--poodle-radius-surface);
    background: color-mix(in srgb, var(--poodle-color-background-panel) 96%, transparent);
    box-shadow: var(--poodle-elevation-overlay);
  }

  /* Size variants */
  .navigation-menu[data-size="xs"] .navigation-menu__trigger {
    min-height: calc(var(--poodle-size-control-height) - 0.625rem);
    padding: 0 calc(var(--poodle-space-control-x) - 0.125rem);
    font-size: 0.6875rem;
  }

  .navigation-menu[data-size="sm"] .navigation-menu__trigger {
    min-height: calc(var(--poodle-size-control-height) - 0.5rem);
    padding: 0 calc(var(--poodle-space-control-x) - 0.0625rem);
  }

  .navigation-menu[data-size="lg"] .navigation-menu__trigger {
    min-height: calc(var(--poodle-size-control-height) + 0.25rem);
    padding: 0 calc(var(--poodle-space-control-x) + 0.125rem);
    font-size: 0.8125rem;
  }

  .navigation-menu[data-size="xl"] .navigation-menu__trigger {
    min-height: calc(var(--poodle-size-control-height) + 0.375rem);
    padding: 0 calc(var(--poodle-space-control-x) + 0.1875rem);
    font-size: 0.875rem;
  }

  /* Density variants */
  .navigation-menu[data-density="compact"] .navigation-menu__trigger { padding-inline: 0.5rem; }
  .navigation-menu[data-density="comfortable"] .navigation-menu__trigger { padding-inline: 0.75rem; }
</style>
