// packages/react/components/src/ResizeHandle.tsx
import "@poodle/styles/resize-handle.css";

import { useEffect, useRef, useState, type KeyboardEvent as ReactKeyboardEvent, type MouseEvent as ReactMouseEvent } from "react";

import { resizeAxisPosition, resizeDragDelta, resizeKeydownStep } from "@poodle/headless";

import type { SplitOrientation } from "./types";

export interface ResizeHandleProps {
  orientation?: SplitOrientation;
  disabled?: boolean;
  ariaLabel?: string | null;
  ariaValueNow?: number | null;
  ariaValueMin?: number;
  ariaValueMax?: number;
  onResizeStart?: ((position: number) => void) | null;
  onResizeMove?: ((delta: number) => void) | null;
  onResizeEnd?: ((position: number) => void) | null;
  onResizeStep?: ((delta: number) => void) | null;
}

export function ResizeHandle({
  orientation = "horizontal",
  disabled = false,
  ariaLabel = null,
  ariaValueNow = null,
  ariaValueMin = 0,
  ariaValueMax = 100,
  onResizeStart = null,
  onResizeMove = null,
  onResizeEnd = null,
  onResizeStep = null,
}: ResizeHandleProps) {
  const [isDragging, setIsDragging] = useState(false);
  const lastPosition = useRef(0);
  const cleanupRef = useRef<(() => void) | null>(null);

  function handlePointerDown(event: ReactMouseEvent): void {
    if (disabled) return;
    event.preventDefault();
    setIsDragging(true);
    lastPosition.current = resizeAxisPosition(orientation, event.clientX, event.clientY);
    onResizeStart?.(lastPosition.current);

    function handlePointerMove(moveEvent: MouseEvent): void {
      const move = resizeDragDelta(
        lastPosition.current,
        resizeAxisPosition(orientation, moveEvent.clientX, moveEvent.clientY),
      );
      lastPosition.current = move.position;
      onResizeMove?.(move.delta);
    }

    function handlePointerUp(): void {
      setIsDragging(false);
      onResizeEnd?.(lastPosition.current);
      cleanupRef.current?.();
      cleanupRef.current = null;
    }

    window.addEventListener("mousemove", handlePointerMove);
    window.addEventListener("mouseup", handlePointerUp);
    cleanupRef.current = () => {
      window.removeEventListener("mousemove", handlePointerMove);
      window.removeEventListener("mouseup", handlePointerUp);
    };
  }

  function handleKeydown(event: ReactKeyboardEvent): void {
    if (disabled) return;

    const step = resizeKeydownStep(event.key, orientation);

    if (step === null) return;

    event.preventDefault();
    onResizeStep?.(step);
  }

  useEffect(() => {
    return () => {
      cleanupRef.current?.();
      cleanupRef.current = null;
    };
  }, []);

  return (
    <div
      className="poodle-resize-handle"
      data-orientation={orientation}
      data-disabled={disabled || undefined}
      data-dragging={isDragging || undefined}
      role="separator"
      aria-orientation={orientation}
      aria-label={ariaLabel ?? "Resize"}
      aria-valuenow={ariaValueNow ?? undefined}
      aria-valuemin={ariaValueMin}
      aria-valuemax={ariaValueMax}
      tabIndex={disabled ? -1 : 0}
      onMouseDown={handlePointerDown}
      onKeyDown={handleKeydown}
    >
      <span className="poodle-resize-handle__line" aria-hidden="true" />
    </div>
  );
}

// packages/svelte/primitives/src/ResizeHandle.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy } from "svelte";

  import type { SplitOrientation } from "./types";

  export let orientation: SplitOrientation = "horizontal";
  export let disabled = false;
  export let ariaLabel: string | null = null;
  export let ariaValueNow: number | null = null;
  export let ariaValueMin = 0;
  export let ariaValueMax = 100;

  const dispatch = createEventDispatcher<{
    resizeStart: { position: number };
    resizeMove: { delta: number };
    resizeEnd: { position: number };
    resizeStep: { delta: number };
  }>();

  let isDragging = false;
  let lastPosition = 0;
  let isListening = false;

  function handlePointerDown(event: MouseEvent): void {
    if (disabled) return;
    event.preventDefault();
    isDragging = true;
    lastPosition = orientation === "horizontal" ? event.clientX : event.clientY;
    dispatch("resizeStart", { position: lastPosition });
    startListening();
  }

  function handlePointerMove(event: MouseEvent): void {
    if (!isDragging) return;
    const pos = orientation === "horizontal" ? event.clientX : event.clientY;
    const delta = pos - lastPosition;
    lastPosition = pos;
    dispatch("resizeMove", { delta });
  }

  function handlePointerUp(): void {
    if (!isDragging) return;
    isDragging = false;
    dispatch("resizeEnd", { position: lastPosition });
    stopListening();
  }

  function startListening(): void {
    if (isListening || typeof window === "undefined") return;
    window.addEventListener("mousemove", handlePointerMove);
    window.addEventListener("mouseup", handlePointerUp);
    isListening = true;
  }

  function stopListening(): void {
    if (!isListening || typeof window === "undefined") return;
    window.removeEventListener("mousemove", handlePointerMove);
    window.removeEventListener("mouseup", handlePointerUp);
    isListening = false;
  }

  function handleKeydown(event: KeyboardEvent): void {
    if (disabled) return;
    const step = 8;
    const prevKey = orientation === "horizontal" ? "ArrowLeft" : "ArrowUp";
    const nextKey = orientation === "horizontal" ? "ArrowRight" : "ArrowDown";

    if (event.key === prevKey) {
      event.preventDefault();
      dispatch("resizeStep", { delta: -step });
    } else if (event.key === nextKey) {
      event.preventDefault();
      dispatch("resizeStep", { delta: step });
    } else if (event.key === "Home") {
      event.preventDefault();
      dispatch("resizeStep", { delta: -9999 });
    } else if (event.key === "End") {
      event.preventDefault();
      dispatch("resizeStep", { delta: 9999 });
    }
  }

  onDestroy(() => {
    stopListening();
  });
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex a11y_no_noninteractive_element_interactions -->
<div
  class="resize-handle"
  data-orientation={orientation}
  data-disabled={disabled || undefined}
  data-dragging={isDragging || undefined}
  role="separator"
  aria-orientation={orientation}
  aria-label={ariaLabel ?? "Resize"}
  aria-valuenow={ariaValueNow}
  aria-valuemin={ariaValueMin}
  aria-valuemax={ariaValueMax}
  tabindex={disabled ? -1 : 0}
  on:mousedown={handlePointerDown}
  on:keydown={handleKeydown}
>
  <span class="resize-handle__line" aria-hidden="true"></span>
</div>

<style>
  .resize-handle {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }

  .resize-handle[data-orientation="horizontal"] {
    width: 0.5rem;
    height: 100%;
    cursor: col-resize;
  }

  .resize-handle[data-orientation="vertical"] {
    width: 100%;
    height: 0.5rem;
    cursor: row-resize;
  }

  .resize-handle[data-disabled] {
    cursor: default;
    opacity: 0.4;
  }

  .resize-handle__line {
    position: absolute;
    border-radius: 999rem;
    background: color-mix(in srgb, var(--poodle-color-border-default) 82%, transparent);
    transition: background 120ms ease;
  }

  .resize-handle[data-orientation="horizontal"] .resize-handle__line {
    width: 0.125rem;
    height: 100%;
  }

  .resize-handle[data-orientation="vertical"] .resize-handle__line {
    width: 100%;
    height: 0.125rem;
  }

  .resize-handle:hover .resize-handle__line,
  .resize-handle[data-dragging] .resize-handle__line {
    background: var(--poodle-color-accent-base);
  }

  .resize-handle:focus-visible {
    outline: var(--poodle-border-width-focus) solid var(--poodle-color-accent-focusRing);
    outline-offset: 0.0625rem;
  }
</style>
