// packages/react/components/src/TriStateSwitch.tsx
import { useId, useState, type CSSProperties } from "react";
import { singleSelectTransition } from "@poodle/headless";

import "@poodle/styles/tri-state-switch.css";

import { resolveSemanticControlSize, useUiPresentation } from "./presentation";
import type { ControlDensity, ControlSize, SemanticControlSizeRole, TriStateValue } from "./types";

export interface TriStateSwitchProps {
  value?: TriStateValue;
  defaultValue?: TriStateValue;
  options?: Record<TriStateValue, string>;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  disabled?: boolean;
  ariaLabel: string;
  excludedColor?: string | null;
  defaultColor?: string | null;
  includedColor?: string | null;
  onValueChange?: (value: TriStateValue) => void;
}

const ORDERED_VALUES: TriStateValue[] = ["excluded", "default", "included"];

export function TriStateSwitch({
  value,
  defaultValue = "default",
  options = { excluded: "Exclude", default: "Default", included: "Include" },
  size = null,
  sizeRole = "control",
  density = null,
  disabled = false,
  ariaLabel,
  excludedColor = null,
  defaultColor = null,
  includedColor = null,
  onValueChange,
}: TriStateSwitchProps) {
  const groupName = useId();
  const uiPresentation = useUiPresentation();
  const [uncontrolledValue, setUncontrolledValue] = useState<TriStateValue>(defaultValue);

  const isControlled = value !== undefined;
  const currentValue = isControlled ? value : uncontrolledValue;
  const selectedIndex = Math.max(0, ORDERED_VALUES.indexOf(currentValue));
  const resolvedSize = size ?? resolveSemanticControlSize(uiPresentation.sizeScale, sizeRole);
  const resolvedDensity = density ?? uiPresentation.density;

  const style: CSSProperties & Record<string, string> = {
    "--poodle-tri-state-active-index": String(selectedIndex),
    ...(excludedColor ? { "--poodle-tri-state-excluded-color": excludedColor } : null),
    ...(defaultColor ? { "--poodle-tri-state-default-color": defaultColor } : null),
    ...(includedColor ? { "--poodle-tri-state-included-color": includedColor } : null),
  };

  function handleSelect(nextValue: TriStateValue): void {
    const result = singleSelectTransition(
      { value: currentValue, options: ORDERED_VALUES.map((candidate) => ({ value: candidate })), disabled },
      { type: "SELECT", value: nextValue },
    );
    for (const effect of result.effects) {
      if (effect.type === "emitValueChange") {
        if (!isControlled) setUncontrolledValue(effect.value as TriStateValue);
        onValueChange?.(effect.value as TriStateValue);
      }
    }
  }

  return (
    <div
      className="poodle-tri-state-switch"
      role="radiogroup"
      aria-label={ariaLabel}
      aria-disabled={disabled ? "true" : undefined}
      data-state={currentValue}
      data-size={resolvedSize}
      data-density={resolvedDensity}
      data-disabled={disabled}
      style={style}
    >
      <span className="poodle-tri-state-switch__selection" aria-hidden="true" />
      {ORDERED_VALUES.map((optionValue) => (
        <label
          key={optionValue}
          className="poodle-tri-state-switch__option"
          data-state={optionValue}
          data-selected={currentValue === optionValue}
        >
          <input
            className="poodle-tri-state-switch__control"
            type="radio"
            name={groupName}
            checked={currentValue === optionValue}
            disabled={disabled}
            aria-label={options[optionValue]}
            onChange={() => handleSelect(optionValue)}
          />
          <span className="poodle-tri-state-switch__segment">{options[optionValue]}</span>
        </label>
      ))}
    </div>
  );
}

// packages/svelte/primitives/src/TriStateSwitch.svelte
<script context="module" lang="ts">
  let triStateSwitchInstanceCount = 0;
</script>

<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { getUiPresentation, resolveSemanticControlSize } from "./presentation";

  import type {
    ControlDensity,
    ControlSize,
    SemanticControlSizeRole,
    TriStateValue,
  } from "./types";

  export let value: TriStateValue = "default";
  export let options: Record<TriStateValue, string> = {
    excluded: "Exclude",
    default: "Default",
    included: "Include",
  };
  export let size: ControlSize | null = null;
  export let sizeRole: SemanticControlSizeRole = "control";
  export let density: ControlDensity | null = null;
  export let disabled = false;
  export let ariaLabel: string;
  export let excludedColor: string | null = null;
  export let defaultColor: string | null = null;
  export let includedColor: string | null = null;

  const dispatch = createEventDispatcher<{
    valueChange: { value: TriStateValue };
  }>();

  const orderedValues: TriStateValue[] = ["excluded", "default", "included"];
  const instanceId = ++triStateSwitchInstanceCount;
  const groupName = `poodle-tri-state-switch-${instanceId}`;
  const uiPresentation = getUiPresentation();

  $: selectedIndex = Math.max(0, orderedValues.indexOf(value));
  $: resolvedSize = size ?? resolveSemanticControlSize($uiPresentation.sizeScale, sizeRole);
  $: resolvedDensity = density ?? $uiPresentation.density;
  $: triStateStyles = [
    excludedColor ? `--poodle-tri-state-excluded-color: ${excludedColor}` : "",
    defaultColor ? `--poodle-tri-state-default-color: ${defaultColor}` : "",
    includedColor ? `--poodle-tri-state-included-color: ${includedColor}` : "",
    `--poodle-tri-state-active-index: ${selectedIndex}`,
  ].filter(Boolean).join("; ") || undefined;

  function handleSelect(nextValue: TriStateValue): void {
    if (disabled || value === nextValue) {
      return;
    }

    value = nextValue;
    dispatch("valueChange", { value: nextValue });
  }
</script>

<div
  class="tri-state-switch"
  role="radiogroup"
  aria-label={ariaLabel}
  aria-disabled={disabled ? "true" : undefined}
  data-state={value}
  data-size={resolvedSize}
  data-density={resolvedDensity}
  data-disabled={disabled}
  style={triStateStyles}
>
  <span class="tri-state-switch__selection" aria-hidden="true"></span>

  {#each orderedValues as optionValue}
    <label
      class="tri-state-switch__option"
      data-state={optionValue}
      data-selected={value === optionValue}
    >
      <input
        class="tri-state-switch__control"
        type="radio"
        name={groupName}
        checked={value === optionValue}
        disabled={disabled}
        aria-label={options[optionValue]}
        on:change={() => handleSelect(optionValue)}
      />
      <span class="tri-state-switch__segment">{options[optionValue]}</span>
    </label>
  {/each}
</div>

<style>
  .tri-state-switch {
    --poodle-tri-state-excluded-color: var(--poodle-color-status-danger);
    --poodle-tri-state-default-color: var(--poodle-color-text-primary);
    --poodle-tri-state-included-color: var(--poodle-color-status-success);
    --poodle-tri-state-excluded-track: color-mix(in srgb, var(--poodle-tri-state-excluded-color) 18%, var(--poodle-color-background-surface));
    --poodle-tri-state-default-track: color-mix(in srgb, var(--poodle-tri-state-default-color) 10%, var(--poodle-color-background-surface));
    --poodle-tri-state-included-track: color-mix(in srgb, var(--poodle-tri-state-included-color) 18%, var(--poodle-color-background-surface));
    --poodle-tri-state-height: var(--poodle-size-control-height);
    --poodle-tri-state-x: var(--poodle-space-control-x);
    --poodle-tri-state-track-inset: 0.125rem;
    --poodle-tri-state-min-width: 4.5rem;
    position: relative;
    display: inline-grid;
    width: max-content;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    align-items: stretch;
    padding: var(--poodle-tri-state-track-inset);
    border: 0.0625rem solid var(--poodle-color-border-default);
    border-radius: 999px;
    background: color-mix(in srgb, var(--poodle-color-text-primary) 18%, var(--poodle-color-background-surface));
    color: var(--poodle-color-text-primary);
    isolation: isolate;
  }

  .tri-state-switch[data-size="xs"] {
    --poodle-tri-state-height: 1.5rem;
    --poodle-tri-state-min-width: 3.75rem;
  }

  .tri-state-switch[data-size="sm"] {
    --poodle-tri-state-height: 1.75rem;
    --poodle-tri-state-min-width: 4rem;
  }

  .tri-state-switch[data-size="md"] {
    --poodle-tri-state-height: 2.25rem;
    --poodle-tri-state-min-width: 4.5rem;
  }

  .tri-state-switch[data-size="lg"] {
    --poodle-tri-state-height: 2.75rem;
    --poodle-tri-state-min-width: 5.25rem;
  }

  .tri-state-switch[data-size="xl"] {
    --poodle-tri-state-height: 3.25rem;
    --poodle-tri-state-min-width: 6rem;
  }

  .tri-state-switch[data-density="compact"] {
    --poodle-tri-state-x: 0.5rem;
    --poodle-tri-state-track-inset: 0.0625rem;
  }

  .tri-state-switch[data-density="default"] {
    --poodle-tri-state-x: 0.75rem;
    --poodle-tri-state-track-inset: 0.125rem;
  }

  .tri-state-switch[data-density="comfortable"] {
    --poodle-tri-state-x: 1rem;
    --poodle-tri-state-track-inset: 0.1875rem;
  }

  .tri-state-switch[data-disabled="true"] {
    opacity: var(--poodle-state-opacity-disabled);
  }

  .tri-state-switch__selection {
    position: absolute;
    top: var(--poodle-tri-state-track-inset);
    bottom: var(--poodle-tri-state-track-inset);
    left: var(--poodle-tri-state-track-inset);
    width: calc((100% - (var(--poodle-tri-state-track-inset) * 2)) / 3);
    border: 0.0625rem solid transparent;
    border-radius: 999px;
    box-shadow:
      inset 0 0.0625rem 0 color-mix(in srgb, white 8%, transparent),
      0 0.125rem 0.5rem color-mix(in srgb, black 18%, transparent);
    transform: translateX(calc(var(--poodle-tri-state-active-index, 1) * 100%));
    transition:
      transform var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard),
      background var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard),
      border-color var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard),
      box-shadow var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard);
    z-index: 0;
  }

  .tri-state-switch[data-state="excluded"] .tri-state-switch__selection {
    background: var(--poodle-tri-state-excluded-track);
    border-color: color-mix(in srgb, var(--poodle-tri-state-excluded-color) 58%, var(--poodle-color-border-default));
  }

  .tri-state-switch[data-state="default"] .tri-state-switch__selection {
    background: var(--poodle-tri-state-default-track);
    border-color: var(--poodle-color-border-default);
  }

  .tri-state-switch[data-state="included"] .tri-state-switch__selection {
    background: var(--poodle-tri-state-included-track);
    border-color: color-mix(in srgb, var(--poodle-tri-state-included-color) 58%, var(--poodle-color-border-default));
  }

  .tri-state-switch__option {
    position: relative;
    z-index: 1;
    cursor: pointer;
  }

  .tri-state-switch[data-disabled="true"] .tri-state-switch__option {
    cursor: not-allowed;
  }

  .tri-state-switch__control {
    position: absolute;
    opacity: 0;
    pointer-events: none;
  }

  .tri-state-switch__segment {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: calc(var(--poodle-tri-state-height) - (var(--poodle-tri-state-track-inset) * 2));
    min-width: var(--poodle-tri-state-min-width);
    padding: 0 var(--poodle-tri-state-x);
    border-radius: 999px;
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-label-family);
    font-size: var(--poodle-typography-label-size);
    font-weight: var(--poodle-typography-label-weight);
    line-height: var(--poodle-typography-label-lineHeight);
    transition:
      color var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard),
      opacity var(--poodle-motion-duration-interaction) var(--poodle-motion-easing-standard);
  }

  .tri-state-switch__option[data-selected="true"] .tri-state-switch__segment {
    color: var(--poodle-color-text-primary);
  }

  .tri-state-switch__option[data-state="excluded"][data-selected="true"] .tri-state-switch__segment {
    color: var(--poodle-tri-state-excluded-color);
  }

  .tri-state-switch__option[data-state="default"][data-selected="true"] .tri-state-switch__segment {
    color: var(--poodle-color-text-primary);
  }

  .tri-state-switch__option[data-state="included"][data-selected="true"] .tri-state-switch__segment {
    color: var(--poodle-tri-state-included-color);
  }

  .tri-state-switch__control:focus-visible + .tri-state-switch__segment {
    outline: var(--poodle-border-width-focus) solid var(--poodle-color-accent-focusRing);
    outline-offset: 0.125rem;
  }
</style>
