// packages/react/components/src/audio/XYPadVisual.tsx
import type { CSSProperties } from "react";
import type { XYPadVisualState } from "@inflatable-cookie/poodle-core";

export function XYPadVisual({ visualState }: { visualState: XYPadVisualState }) {
  return <span className="poodle-xy-pad-visual" data-hover={visualState.hover} data-focus={visualState.focus} data-drag={visualState.drag} data-enabled={visualState.enabled} aria-hidden="true" style={{ "--poodle-xy-pad-x": visualState.xNorm, "--poodle-xy-pad-y": visualState.yNorm } as CSSProperties}>
    <span className="poodle-xy-pad-visual__grid" />
    <span className="poodle-xy-pad-visual__trace-x" />
    <span className="poodle-xy-pad-visual__trace-y" />
    <span className="poodle-xy-pad-visual__thumb" />
  </span>;
}

// packages/svelte/components/src/audio/XYPadVisual.svelte
<script lang="ts">
  import type { XYPadVisualState } from "@inflatable-cookie/poodle-core";
  let { visualState }: { visualState: XYPadVisualState } = $props();
</script>

<span
  class="poodle-xy-pad-visual"
  data-hover={visualState.hover}
  data-focus={visualState.focus}
  data-drag={visualState.drag}
  data-enabled={visualState.enabled}
  aria-hidden="true"
  style={`--poodle-xy-pad-x: ${visualState.xNorm}; --poodle-xy-pad-y: ${visualState.yNorm};`}
>
  <span class="poodle-xy-pad-visual__grid"></span>
  <span class="poodle-xy-pad-visual__trace-x"></span>
  <span class="poodle-xy-pad-visual__trace-y"></span>
  <span class="poodle-xy-pad-visual__thumb"></span>
</span>
