// packages/react/preview/src/gallery/specimens/AlertDialogSpecimen.tsx
import { useState, type CSSProperties } from "react";
import { AlertDialog, Button, Eyebrow, Surface } from "@poodle/react";

const rowStyle: CSSProperties = { display: "flex", alignItems: "center", gap: "0.75rem" };
const hintStyle: CSSProperties = { margin: 0, fontSize: "0.75rem", color: "var(--poodle-color-text-secondary)" };
const cardStyle: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: "0.125rem",
  padding: "0.5rem 0.75rem",
  borderRadius: "0.375rem",
  background: "var(--poodle-color-background-panel)",
};
const cardSpanStyle: CSSProperties = { color: "var(--poodle-color-text-secondary)", fontSize: "0.8125rem" };

export function AlertDialogSpecimen() {
  const [dangerOpen, setDangerOpen] = useState(false);
  const [warningOpen, setWarningOpen] = useState(false);
  const [asyncOpen, setAsyncOpen] = useState(false);
  const [lastAction, setLastAction] = useState("");

  async function simulateAsync(): Promise<void> {
    await new Promise((resolve) => setTimeout(resolve, 1500));
    setLastAction("Async confirm completed");
  }

  return (
    <Surface tone="panel" border="subtle" padding="md">
      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
        <div style={rowStyle}>
          <Eyebrow>Danger tone</Eyebrow>
          <Button tone="danger" onClick={() => setDangerOpen(true)}>
            Delete item
          </Button>
          <AlertDialog
            open={dangerOpen}
            title="Delete this item?"
            description="This action cannot be undone. The item and all associated data will be permanently removed."
            confirmLabel="Delete"
            cancelLabel="Keep it"
            onConfirm={() => {
              setLastAction("Item deleted");
              setDangerOpen(false);
            }}
            onCancel={() => setDangerOpen(false)}
            onOpenChange={(open) => setDangerOpen(open)}
          />
        </div>

        <div style={rowStyle}>
          <Eyebrow>Warning tone</Eyebrow>
          <Button variant="secondary" onClick={() => setWarningOpen(true)}>
            Reset settings
          </Button>
          <AlertDialog
            open={warningOpen}
            title="Reset all settings?"
            description="Your customized settings will be restored to their default values."
            tone="warning"
            confirmLabel="Reset"
            cancelLabel="Cancel"
            onConfirm={() => {
              setLastAction("Settings reset");
              setWarningOpen(false);
            }}
            onCancel={() => setWarningOpen(false)}
            onOpenChange={(open) => setWarningOpen(open)}
          />
        </div>

        <div style={rowStyle}>
          <Eyebrow>Async confirm</Eyebrow>
          <Button tone="danger" onClick={() => setAsyncOpen(true)}>
            Archive project
          </Button>
          <AlertDialog
            open={asyncOpen}
            title="Archive this project?"
            description="The project will be hidden from active lists but can still be restored later."
            confirmLabel="Archive"
            workingLabel="Archiving…"
            onConfirm={async () => {
              await simulateAsync();
              setAsyncOpen(false);
            }}
            onCancel={() => setAsyncOpen(false)}
            onOpenChange={(open) => setAsyncOpen(open)}
          >
            <div style={cardStyle}>
              <strong>Roadmap Cleanup</strong>
              <span style={cardSpanStyle}>14 linked tasks will move to the archived view.</span>
            </div>
          </AlertDialog>
        </div>

        {lastAction ? (
          <p style={hintStyle}>
            Last action: <strong>{lastAction}</strong>
          </p>
        ) : null}
      </div>
    </Surface>
  );
}

// packages/svelte/preview/src/specimens/AlertDialogSpecimen.svelte
<script lang="ts">
  import { AlertDialog, Button, Eyebrow, Surface } from "@poodle/svelte";

  let dangerOpen = false;
  let warningOpen = false;
  let asyncOpen = false;
  let lastAction = "";

  async function simulateAsync(): Promise<void> {
    await new Promise((resolve) => setTimeout(resolve, 1500));
    lastAction = "Async confirm completed";
  }
</script>

<Surface tone="panel" border="subtle" padding="md">
  <div class="poodle-specimen">
    <div class="poodle-specimen__row">
      <Eyebrow>Danger tone</Eyebrow>
      <Button tone="danger" onClick={() => (dangerOpen = true)}>Delete item</Button>
      <AlertDialog
        open={dangerOpen}
        title="Delete this item?"
        description="This action cannot be undone. The item and all associated data will be permanently removed."
        confirmLabel="Delete"
        cancelLabel="Keep it"
        onConfirm={() => { lastAction = "Item deleted"; dangerOpen = false; }}
        onCancel={() => (dangerOpen = false)}
        onOpenChange={(open) => (dangerOpen = open)}
      />
    </div>

    <div class="poodle-specimen__row">
      <Eyebrow>Warning tone</Eyebrow>
      <Button variant="secondary" onClick={() => (warningOpen = true)}>Reset settings</Button>
      <AlertDialog
        open={warningOpen}
        title="Reset all settings?"
        description="Your customized settings will be restored to their default values."
        tone="warning"
        confirmLabel="Reset"
        cancelLabel="Cancel"
        onConfirm={() => { lastAction = "Settings reset"; warningOpen = false; }}
        onCancel={() => (warningOpen = false)}
        onOpenChange={(open) => (warningOpen = open)}
      />
    </div>

    <div class="poodle-specimen__row">
      <Eyebrow>Async confirm</Eyebrow>
      <Button tone="danger" onClick={() => (asyncOpen = true)}>Archive project</Button>
      <AlertDialog
        open={asyncOpen}
        title="Archive this project?"
        description="The project will be hidden from active lists but can still be restored later."
        confirmLabel="Archive"
        workingLabel="Archiving…"
        onConfirm={async () => { await simulateAsync(); asyncOpen = false; }}
        onCancel={() => (asyncOpen = false)}
        onOpenChange={(open) => (asyncOpen = open)}
      >
        <div class="poodle-user-card">
          <strong>Roadmap Cleanup</strong>
          <span>14 linked tasks will move to the archived view.</span>
        </div>
      </AlertDialog>
    </div>

    {#if lastAction}
      <p class="poodle-specimen__hint">Last action: <strong>{lastAction}</strong></p>
    {/if}
  </div>
</Surface>

<style>
  .poodle-specimen {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .poodle-specimen__row {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .poodle-specimen__hint {
    margin: 0;
    font-size: 0.75rem;
    color: var(--poodle-color-text-secondary);
  }

  .poodle-user-card {
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
    padding: 0.5rem 0.75rem;
    border-radius: 0.375rem;
    background: var(--poodle-color-background-panel);
  }

  .poodle-user-card span {
    color: var(--poodle-color-text-secondary);
    font-size: 0.8125rem;
  }
</style>
