// packages/react/preview/src/gallery/specimens/DateRangePickerSpecimen.tsx
import { useState } from "react";
import { DateRangePicker, type DateRangeValue } from "@inflatable-cookie/poodle-react";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

export function DateRangePickerSpecimen() {
  const [range, setRange] = useState<DateRangeValue>({ start: "", end: "" });

  return (
    <SpecimenLayout
      sizes={(size) => (
        <div style={{ maxWidth: "20rem" }}>
          <DateRangePicker size={size} ariaLabel={size} />
        </div>
      )}
      densities={(density) => (
        <div style={{ maxWidth: "20rem" }}>
          <DateRangePicker density={density} />
        </div>
      )}
    >
      <SpecimenGroup label="Default">
        <div style={{ maxWidth: "20rem" }}>
          <DateRangePicker ariaLabel="Select date range" onValueChange={(value) => setRange(value)} />
        </div>
        {range.start ? (
          <p>
            {range.start} → {range.end || "…"}
          </p>
        ) : null}
      </SpecimenGroup>

      <SpecimenGroup label="With default range">
        <div style={{ maxWidth: "20rem" }}>
          <DateRangePicker defaultValue={{ start: "2026-03-01", end: "2026-03-14" }} ariaLabel="Pre-filled range" />
        </div>
      </SpecimenGroup>

      <SpecimenGroup label="Disabled">
        <div style={{ maxWidth: "20rem" }}>
          <DateRangePicker disabled ariaLabel="Disabled range picker" />
        </div>
      </SpecimenGroup>
    </SpecimenLayout>
  );
}

// packages/svelte/preview/src/specimens/DateRangePickerSpecimen.svelte
<script lang="ts">
  import { DateRangePicker } from "@inflatable-cookie/poodle-svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  let range = $state({ start: "", end: "" });
</script>

<SpecimenLayout>
  <SpecimenGroup label="Default">
    <div class="poodle-specimen__control">
      <DateRangePicker
        ariaLabel="Select date range"
        onValueChange={(value) => (range = value)}
      />
    </div>
    {#if range.start}
      <p>{range.start} → {range.end || "…"}</p>
    {/if}
  </SpecimenGroup>

  <SpecimenGroup label="With default range">
    <div class="poodle-specimen__control">
      <DateRangePicker
        defaultValue={{ start: "2026-03-01", end: "2026-03-14" }}
        ariaLabel="Pre-filled range"
      />
    </div>
  </SpecimenGroup>

  <SpecimenGroup label="Disabled">
    <div class="poodle-specimen__control">
      <DateRangePicker disabled ariaLabel="Disabled range picker" />
    </div>
  </SpecimenGroup>

  {#snippet sizes(size)}
    <div class="poodle-specimen__control">
      <DateRangePicker {size} ariaLabel={size} />
    </div>
  {/snippet}

  {#snippet densities(density)}
    <div class="poodle-specimen__control">
      <DateRangePicker {density} />
    </div>
  {/snippet}
</SpecimenLayout>

<style>
  .poodle-specimen__control {
    max-width: 20rem;
  }
</style>
