// packages/react/preview/src/gallery/specimens/DialogSpecimen.tsx
import { SpecimenGroup } from "../SpecimenGroup";
import { useState, type CSSProperties } from "react";
import { Button, Checkbox, Dialog, Field, Pill, Popover, Select, TextInput } from "@inflatable-cookie/poodle-react";
import { SpecimenLayout } from "../SpecimenLayout";

const WIDTHS = ["sm", "md", "lg", "xl", "full"] as const;
type DialogWidth = (typeof WIDTHS)[number];

const textSecondary = "var(--poodle-color-text-secondary)";
const codeFamily = "var(--poodle-typography-code-family)";

const kbdStyle: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  minWidth: "4.5rem",
  padding: "0.25rem 0.5rem",
  border: "0.0625rem solid var(--poodle-color-border-default)",
  borderRadius: "0.25rem",
  background: "color-mix(in srgb, var(--poodle-color-background-panel) 80%, var(--poodle-color-background-elevated))",
  fontFamily: codeFamily,
  fontSize: "0.75rem",
  fontWeight: 500,
};

const shortcuts: Array<[string, string]> = [
  ["⌘ K", "Command palette"],
  ["⌘ S", "Save"],
  ["⌘ /", "Toggle comment"],
  ["⌘ ⇧ P", "Quick actions"],
  ["Esc", "Close dialog"],
];

const logMessages = [
  "User signed in",
  "Project created",
  "File uploaded",
  "Settings updated",
  "Comment added",
  "Build completed",
  "Deploy started",
  "Review requested",
];

export function DialogSpecimen() {
  const [basicOpen, setBasicOpen] = useState(false);
  const [alertOpen, setAlertOpen] = useState(false);
  const [formOpen, setFormOpen] = useState(false);
  const [contentOnlyOpen, setContentOnlyOpen] = useState(false);
  const [customFooterOpen, setCustomFooterOpen] = useState(false);
  const [bareOpen, setBareOpen] = useState(false);
  const [wideOpen, setWideOpen] = useState(false);
  const [scrollableOpen, setScrollableOpen] = useState(false);
  const [widthOpenMap, setWidthOpenMap] = useState<Record<string, boolean>>({});
  const [overlayInDialogOpen, setOverlayInDialogOpen] = useState(false);
  const [axisOpen, setAxisOpen] = useState<Record<string, boolean>>({});

  const setWidthOpen = (w: string, open: boolean) => setWidthOpenMap((prev) => ({ ...prev, [w]: open }));
  const setAxis = (key: string, open: boolean) => setAxisOpen((prev) => ({ ...prev, [key]: open }));

  return (
    <SpecimenLayout
      sizes={(size) => (
        <>
          <Button variant="secondary" onClick={() => setAxis(`size-${size}`, true)}>
            Open {size} dialog
          </Button>
          <Dialog
            open={axisOpen[`size-${size}`] ?? false}
            onOpenChange={(open) => setAxis(`size-${size}`, open)}
            title={`Control scale: ${size}`}
            description="Size scales the dialog header and close control; width is configured separately."
            showCloseButton
            size={size}
          >
            <p>Command palette, save, and toggle comment live here.</p>
          </Dialog>
        </>
      )}
      densities={(density) => (
        <>
          <Button variant="secondary" onClick={() => setAxis(`density-${density}`, true)}>
            Open {density} dialog
          </Button>
          <Dialog
            open={axisOpen[`density-${density}`] ?? false}
            onOpenChange={(open) => setAxis(`density-${density}`, open)}
            title={`Density: ${density}`}
            description="Density changes surface spacing; width is configured separately."
            showCloseButton
            density={density}
          >
            <p>Command palette, save, and toggle comment live here.</p>
          </Dialog>
        </>
      )}
    >
      <SpecimenGroup
        label="Basic and alert dialogs"
        description="A titled dialog for reading, and Dialog's own alertdialog role for a destructive confirm. Both triggers stay live."
      >
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", alignItems: "center" }}>
          <Button variant="secondary" onClick={() => setBasicOpen(true)}>
            View details
          </Button>
          <Button variant="secondary" tone="danger" onClick={() => setAlertOpen(true)}>
            Delete item
          </Button>
        </div>
      </SpecimenGroup>

      <SpecimenGroup
        label="Forms and nested controls"
        description="A create-project form, and a nested popover that stays inside the dialog."
      >
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", alignItems: "center" }}>
          <Button variant="secondary" onClick={() => setFormOpen(true)}>
            Create project
          </Button>
          <Button variant="secondary" onClick={() => setOverlayInDialogOpen(true)}>
            Open dialog
          </Button>
        </div>
      </SpecimenGroup>

      <SpecimenGroup
        label="Custom header and footer"
        description="Replace the built-in title, or replace the action row with a custom footer."
      >
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", alignItems: "center" }}>
          <Button variant="secondary" onClick={() => setContentOnlyOpen(true)}>
            View changelog
          </Button>
          <Button variant="secondary" onClick={() => setCustomFooterOpen(true)}>
            Terms &amp; conditions
          </Button>
        </div>
      </SpecimenGroup>

      <SpecimenGroup
        label="Bare content"
        description="No padding or internal structure — the consumer owns the layout."
      >
        <Button variant="secondary" onClick={() => setBareOpen(true)}>
          Preview image
        </Button>
      </SpecimenGroup>

      <SpecimenGroup
        label="Scrolling and width presets"
        description="A long log that scrolls, plus the width presets."
      >
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", alignItems: "center" }}>
          <Button variant="secondary" onClick={() => setScrollableOpen(true)}>
            View log
          </Button>
          {WIDTHS.map((w) => (
            <Button key={w} variant="secondary" onClick={() => setWidthOpen(w, true)}>
              {w}
            </Button>
          ))}
        </div>
      </SpecimenGroup>

      <SpecimenGroup
        label="Dismissal rules"
        description="Escape and backdrop can be turned off so only an explicit action closes."
      >
        <Button variant="secondary" onClick={() => setWideOpen(true)}>
          Open persistent
        </Button>
      </SpecimenGroup>

      {/* Dialogs (rendered outside the Surface, portaled to [data-theme]) */}

      <Dialog open={basicOpen} title="Keyboard shortcuts" showCloseButton onOpenChange={setBasicOpen}>
        <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
          {shortcuts.map(([keys, label]) => (
            <div key={label} style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <kbd style={kbdStyle}>{keys}</kbd>
              <span style={{ color: textSecondary, fontSize: "0.8125rem" }}>{label}</span>
            </div>
          ))}
        </div>
      </Dialog>

      <Dialog
        open={alertOpen}
        role="alertdialog"
        title="Delete item?"
        description="This will permanently remove the item and all associated data."
        onOpenChange={setAlertOpen}
        actions={
          <>
            <Button variant="ghost" onClick={() => setAlertOpen(false)}>
              Cancel
            </Button>
            <Button tone="danger" onClick={() => setAlertOpen(false)}>
              Delete
            </Button>
          </>
        }
      >
        <p>This action cannot be undone.</p>
      </Dialog>

      <Dialog
        open={formOpen}
        title="New project"
        description="Set up a new project workspace."
        width="lg"
        showCloseButton
        onOpenChange={setFormOpen}
        actions={
          <>
            <Button variant="ghost" onClick={() => setFormOpen(false)}>
              Cancel
            </Button>
            <Button onClick={() => setFormOpen(false)}>Create project</Button>
          </>
        }
      >
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
          <Field label="Project name" id="dialog-project-name">
            <TextInput id="dialog-proj-name" placeholder="My project" />
          </Field>
          <Field label="Template" id="dialog-template">
            <Select
              id="dialog-template"
              placeholder="Choose a template"
              options={[
                { value: "blank", label: "Blank" },
                { value: "starter", label: "Starter kit" },
                { value: "advanced", label: "Advanced" },
              ]}
            />
          </Field>
          <div style={{ gridColumn: "1 / -1" }}>
            <Field label="Description" id="dialog-description">
              <TextInput id="dialog-desc" placeholder="What is this project for?" rows={3} />
            </Field>
          </div>
          <div style={{ gridColumn: "1 / -1" }}>
            <Checkbox id="dialog-private" label="Make this project private" />
          </div>
        </div>
      </Dialog>

      <Dialog
        open={contentOnlyOpen}
        showCloseButton
        onOpenChange={setContentOnlyOpen}
        header={
          <div style={{ display: "flex", alignItems: "center", gap: "0.625rem" }}>
            <h2
              style={{
                margin: 0,
                fontFamily: "var(--poodle-typography-heading-family)",
                fontSize: "1rem",
                fontWeight: 600,
                lineHeight: 1.2,
              }}
            >
              What's new
            </h2>
            <Pill tone="info" appearance="badge">
              v2.4.0
            </Pill>
          </div>
        }
      >
        <div style={{ display: "flex", flexDirection: "column", gap: "0.875rem" }}>
          <div style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
            <strong style={{ fontSize: "0.875rem" }}>Dialog flexibility improvements</strong>
            <p style={{ margin: 0, color: textSecondary, fontSize: "0.8125rem", lineHeight: 1.5 }}>
              Dialogs now support custom headers, footers, width presets, and bare mode.
            </p>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
            <strong style={{ fontSize: "0.875rem" }}>Size propagation fixes</strong>
            <p style={{ margin: 0, color: textSecondary, fontSize: "0.8125rem", lineHeight: 1.5 }}>
              All parent components now correctly forward size and density to embedded children.
            </p>
          </div>
        </div>
      </Dialog>

      <Dialog
        open={customFooterOpen}
        title="Terms of service"
        showCloseButton
        onOpenChange={setCustomFooterOpen}
        footer={
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <a
              href="#terms"
              style={{ color: "var(--poodle-color-accent-base)", fontSize: "0.8125rem", textDecoration: "none" }}
            >
              Read full terms
            </a>
            <div style={{ display: "flex", gap: "0.5rem" }}>
              <Button variant="ghost" onClick={() => setCustomFooterOpen(false)}>
                Decline
              </Button>
              <Button onClick={() => setCustomFooterOpen(false)}>Accept</Button>
            </div>
          </div>
        }
      >
        <div>
          <p style={{ margin: "0 0 0.5rem", color: textSecondary, fontSize: "0.8125rem", lineHeight: 1.6 }}>
            By using this service, you agree to our terms and conditions.
          </p>
        </div>
      </Dialog>

      <Dialog open={bareOpen} bare width="lg" ariaLabel="Image preview" onOpenChange={setBareOpen}>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              display: "grid",
              placeItems: "center",
              minHeight: "20rem",
              background: "color-mix(in srgb, var(--poodle-color-background-canvas) 90%, black)",
              borderRadius: "var(--poodle-radius-surface) var(--poodle-radius-surface) 0 0",
            }}
          >
            <span style={{ color: textSecondary, fontFamily: codeFamily, fontSize: "0.875rem", opacity: 0.5 }}>
              2400 × 1600
            </span>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: "1rem",
              padding: "0.75rem 1rem",
              borderTop: "0.0625rem solid var(--poodle-color-border-subtle)",
            }}
          >
            <div style={{ display: "flex", flexDirection: "column", gap: "0.125rem" }}>
              <strong style={{ fontSize: "0.8125rem" }}>landscape-hero.png</strong>
              <span style={{ color: textSecondary, fontSize: "0.75rem" }}>2.4 MB · Uploaded today</span>
            </div>
            <div style={{ display: "flex", gap: "0.5rem" }}>
              <Button variant="ghost" onClick={() => setBareOpen(false)}>
                Close
              </Button>
              <Button leadingIcon="download" onClick={() => setBareOpen(false)}>
                Download
              </Button>
            </div>
          </div>
        </div>
      </Dialog>

      <Dialog
        open={scrollableOpen}
        title="Activity log"
        description="Recent activity across all projects."
        showCloseButton
        onOpenChange={setScrollableOpen}
        actions={
          <>
            <Button variant="ghost" onClick={() => setScrollableOpen(false)}>
              Close
            </Button>
            <Button onClick={() => setScrollableOpen(false)}>Export log</Button>
          </>
        }
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "0.25rem",
            maxHeight: "18rem",
            overflowY: "auto",
          }}
        >
          {Array.from({ length: 20 }, (_, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                gap: "0.75rem",
                padding: "0.375rem 0",
                borderBottom: "0.0625rem solid color-mix(in srgb, var(--poodle-color-border-subtle) 50%, transparent)",
              }}
            >
              <span style={{ color: textSecondary, fontFamily: codeFamily, fontSize: "0.75rem", minWidth: "3rem" }}>
                {String(9 + Math.floor(i / 3)).padStart(2, "0")}:{String((i * 17) % 60).padStart(2, "0")}
              </span>
              <span style={{ fontSize: "0.8125rem" }}>{logMessages[i % 8]}</span>
            </div>
          ))}
        </div>
      </Dialog>

      {WIDTHS.map((w) => (
        <Dialog
          key={w}
          open={widthOpenMap[w] ?? false}
          width={w as DialogWidth}
          title={`Width: ${w}`}
          showCloseButton
          onOpenChange={(open) => setWidthOpen(w, open)}
          actions={<Button onClick={() => setWidthOpen(w, false)}>Close</Button>}
        >
          <p>
            This dialog uses <code>{`width="${w}"`}</code>.
          </p>
        </Dialog>
      ))}

      <Dialog
        open={wideOpen}
        title="Processing"
        dismissOnBackdrop={false}
        dismissOnEscape={false}
        onOpenChange={setWideOpen}
        actions={<Button onClick={() => setWideOpen(false)}>Done</Button>}
      >
        <p>This dialog cannot be dismissed by clicking the backdrop or pressing Escape.</p>
      </Dialog>

      <Dialog open={overlayInDialogOpen} title="Settings" showCloseButton onOpenChange={setOverlayInDialogOpen}>
        <Field id="dialog-model" label="Model">
          <Popover
            ariaLabel="Model settings"
            trigger={<Button variant="secondary">Opus 5 · Medium</Button>}
          >
            <div style={{ display: "flex", flexDirection: "column", gap: "0.25rem", minWidth: "14rem" }}>
              <strong>Opus 5</strong>
              <span>Reasoning depth. Higher costs more time and tokens.</span>
            </div>
          </Popover>
        </Field>
      </Dialog>
    </SpecimenLayout>
  );
}

// packages/svelte/preview/src/specimens/DialogSpecimen.svelte
<script lang="ts">
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";
  import { Dialog, Button, TextInput, Select, Field, Checkbox, Pill, Popover } from "@inflatable-cookie/poodle-svelte";

  // One $state rune puts the whole file in runes mode, where plain `let`
  // stops being reactive — every flag here must be $state or its dialog
  // never opens.
  let basicOpen = $state(false);
  let alertOpen = $state(false);
  let formOpen = $state(false);
  let contentOnlyOpen = $state(false);
  let customFooterOpen = $state(false);
  let bareOpen = $state(false);
  let wideOpen = $state(false);
  let scrollableOpen = $state(false);
  let widthOpenMap: Record<string, boolean> = $state({});
  let overlayInDialogOpen = $state(false);
  let axisOpen: Record<string, boolean> = $state({});
</script>

<SpecimenLayout>
  <SpecimenGroup
    label="Basic and alert dialogs"
    description="A titled dialog for reading, and Dialog's own alertdialog role for a destructive confirm. Both triggers stay live."
  >
    <div class="poodle-dialog-specimen__triggers">
      <Button variant="secondary" onClick={() => (basicOpen = true)}>View details</Button>
      <Button variant="secondary" tone="danger" onClick={() => (alertOpen = true)}>Delete item</Button>
    </div>
  </SpecimenGroup>

  <SpecimenGroup
    label="Forms and nested controls"
    description="A create-project form, and a nested popover that stays inside the dialog."
  >
    <div class="poodle-dialog-specimen__triggers">
      <Button variant="secondary" onClick={() => (formOpen = true)}>Create project</Button>
      <Button variant="secondary" onClick={() => (overlayInDialogOpen = true)}>Open dialog</Button>
    </div>
  </SpecimenGroup>

  <SpecimenGroup
    label="Custom header and footer"
    description="Replace the built-in title, or replace the action row with a custom footer."
  >
    <div class="poodle-dialog-specimen__triggers">
      <Button variant="secondary" onClick={() => (contentOnlyOpen = true)}>View changelog</Button>
      <Button variant="secondary" onClick={() => (customFooterOpen = true)}>Terms &amp; conditions</Button>
    </div>
  </SpecimenGroup>

  <SpecimenGroup
    label="Bare content"
    description="No padding or internal structure — the consumer owns the layout."
  >
    <Button variant="secondary" onClick={() => (bareOpen = true)}>Preview image</Button>
  </SpecimenGroup>

  <SpecimenGroup
    label="Scrolling and width presets"
    description="A long log that scrolls, plus the width presets."
  >
    <div class="poodle-dialog-specimen__triggers">
      <Button variant="secondary" onClick={() => (scrollableOpen = true)}>View log</Button>
      {#each ["sm", "md", "lg", "xl", "full"] as w}
        <Button variant="secondary" onClick={() => (widthOpenMap[w] = true)}>{w}</Button>
      {/each}
    </div>
  </SpecimenGroup>

  <SpecimenGroup
    label="Dismissal rules"
    description="Escape and backdrop can be turned off so only an explicit action closes."
  >
    <Button variant="secondary" onClick={() => (wideOpen = true)}>Open persistent</Button>
  </SpecimenGroup>

<!-- Dialogs (rendered outside the Surface, portaled to [data-theme]) -->

<Dialog
  open={basicOpen}
  title="Keyboard shortcuts"
  showCloseButton
  onOpenChange={(open) => (basicOpen = open)}
>
  <div class="poodle-shortcuts-list">
    <div class="poodle-shortcut"><kbd>⌘ K</kbd> <span>Command palette</span></div>
    <div class="poodle-shortcut"><kbd>⌘ S</kbd> <span>Save</span></div>
    <div class="poodle-shortcut"><kbd>⌘ /</kbd> <span>Toggle comment</span></div>
    <div class="poodle-shortcut"><kbd>⌘ ⇧ P</kbd> <span>Quick actions</span></div>
    <div class="poodle-shortcut"><kbd>Esc</kbd> <span>Close dialog</span></div>
  </div>
</Dialog>

<Dialog
  open={alertOpen}
  role="alertdialog"
  title="Delete item?"
  description="This will permanently remove the item and all associated data."
  onOpenChange={(open) => (alertOpen = open)}
>
  <p>This action cannot be undone.</p>
  {#snippet actions()}
    <Button variant="ghost" onClick={() => (alertOpen = false)}>Cancel</Button>
    <Button tone="danger" onClick={() => (alertOpen = false)}>Delete</Button>
  {/snippet}
</Dialog>

<Dialog
  open={formOpen}
  title="New project"
  description="Set up a new project workspace."
  width="lg"
  showCloseButton
  onOpenChange={(open) => (formOpen = open)}
>
  <div class="poodle-form-grid">
    <Field label="Project name" id="dialog-project-name">
      <TextInput id="dialog-proj-name" placeholder="My project" />
    </Field>
    <Field label="Template" id="dialog-template">
      <Select id="dialog-template" placeholder="Choose a template" options={[
        { value: "blank", label: "Blank" },
        { value: "starter", label: "Starter kit" },
        { value: "advanced", label: "Advanced" },
      ]} />
    </Field>
    <div class="poodle-form-full-width">
      <Field label="Description" id="dialog-description">
        <TextInput id="dialog-desc" placeholder="What is this project for?" rows={3} />
      </Field>
    </div>
    <div class="poodle-form-full-width">
      <Checkbox id="dialog-private" label="Make this project private" />
    </div>
  </div>
  {#snippet actions()}
    <Button variant="ghost" onClick={() => (formOpen = false)}>Cancel</Button>
    <Button onClick={() => (formOpen = false)}>Create project</Button>
  {/snippet}
</Dialog>

<Dialog
  open={contentOnlyOpen}
  showCloseButton
  onOpenChange={(open) => (contentOnlyOpen = open)}
>
  {#snippet header()}
    <div class="poodle-changelog-header">
      <h2 class="poodle-changelog-header__title">What's new</h2>
      <Pill tone="info" appearance="badge">v2.4.0</Pill>
    </div>
  {/snippet}
  <div class="poodle-changelog">
    <div class="poodle-changelog__entry">
      <strong>Dialog flexibility improvements</strong>
      <p>Dialogs now support custom headers, footers, width presets, and bare mode.</p>
    </div>
    <div class="poodle-changelog__entry">
      <strong>Size propagation fixes</strong>
      <p>All parent components now correctly forward size and density to embedded children.</p>
    </div>
  </div>
</Dialog>

<Dialog
  open={customFooterOpen}
  title="Terms of service"
  showCloseButton
  onOpenChange={(open) => (customFooterOpen = open)}
>
  <div class="poodle-terms-body">
    <p>By using this service, you agree to our terms and conditions.</p>
  </div>
  {#snippet footer()}
    <div class="poodle-split-footer">
      <a href="#terms" class="poodle-split-footer__link">Read full terms</a>
      <div class="poodle-split-footer__actions">
        <Button variant="ghost" onClick={() => (customFooterOpen = false)}>Decline</Button>
        <Button onClick={() => (customFooterOpen = false)}>Accept</Button>
      </div>
    </div>
  {/snippet}
</Dialog>

<Dialog
  open={bareOpen}
  bare
  width="lg"
  ariaLabel="Image preview"
  onOpenChange={(open) => (bareOpen = open)}
>
  <div class="poodle-image-preview">
    <div class="poodle-image-preview__canvas">
      <span class="poodle-image-preview__placeholder">2400 × 1600</span>
    </div>
    <div class="poodle-image-preview__bar">
      <div class="poodle-image-preview__meta">
        <strong>landscape-hero.png</strong>
        <span>2.4 MB · Uploaded today</span>
      </div>
      <div class="poodle-image-preview__actions">
        <Button variant="ghost" onClick={() => (bareOpen = false)}>Close</Button>
        <Button leadingIcon="download" onClick={() => (bareOpen = false)}>Download</Button>
      </div>
    </div>
  </div>
</Dialog>

<Dialog
  open={scrollableOpen}
  title="Activity log"
  description="Recent activity across all projects."
  showCloseButton
  onOpenChange={(open) => (scrollableOpen = open)}
>
  <div class="poodle-log-list">
    {#each Array(20) as _, i}
      <div class="poodle-log-entry">
        <span class="poodle-log-entry__time">{String(9 + Math.floor(i / 3)).padStart(2, "0")}:{String((i * 17) % 60).padStart(2, "0")}</span>
        <span class="poodle-log-entry__message">
          {["User signed in", "Project created", "File uploaded", "Settings updated", "Comment added", "Build completed", "Deploy started", "Review requested"][i % 8]}
        </span>
      </div>
    {/each}
  </div>
  {#snippet actions()}
    <Button variant="ghost" onClick={() => (scrollableOpen = false)}>Close</Button>
    <Button onClick={() => (scrollableOpen = false)}>Export log</Button>
  {/snippet}
</Dialog>

{#each ["sm", "md", "lg", "xl", "full"] as w}
  <Dialog
    open={widthOpenMap[w] ?? false}
    width={w as "sm" | "md" | "lg" | "xl"}
    title="Width: {w}"
    showCloseButton
    onOpenChange={(open) => (widthOpenMap[w] = open)}
  >
    <p>This dialog uses <code>width="{w}"</code>.</p>
    {#snippet actions()}
      <Button onClick={() => (widthOpenMap[w] = false)}>Close</Button>
    {/snippet}
  </Dialog>
{/each}

<Dialog
  open={wideOpen}
  title="Processing"
  dismissOnBackdrop={false}
  dismissOnEscape={false}
  onOpenChange={(open) => (wideOpen = open)}
>
  <p>This dialog cannot be dismissed by clicking the backdrop or pressing Escape.</p>
  {#snippet actions()}
    <Button onClick={() => (wideOpen = false)}>Done</Button>
  {/snippet}
</Dialog>

<Dialog bind:open={overlayInDialogOpen} title="Settings" showCloseButton>
  <Field id="overlay-model" label="Model">
    <Popover ariaLabel="Model settings">
      {#snippet trigger()}
        <Button variant="secondary">Opus 5 · Medium</Button>
      {/snippet}
      <div style="display:flex;flex-direction:column;gap:0.25rem;min-width:14rem;">
        <strong>Opus 5</strong>
        <span>Reasoning depth. Higher costs more time and tokens.</span>
      </div>
    </Popover>
  </Field>
</Dialog>

{#snippet sizes(size)}
  <Button variant="secondary" onClick={() => (axisOpen[`size-${size}`] = true)}>Open {size} dialog</Button>
  <Dialog
    open={axisOpen[`size-${size}`] ?? false}
    onOpenChange={(v) => (axisOpen[`size-${size}`] = v)}
    title="Control scale: {size}"
    description="Size scales the dialog header and close control; width is configured separately."
    showCloseButton
    {size}
  >
    <p>Command palette, save, and toggle comment live here.</p>
  </Dialog>
{/snippet}

{#snippet densities(density)}
  <Button variant="secondary" onClick={() => (axisOpen[`density-${density}`] = true)}>Open {density} dialog</Button>
  <Dialog
    open={axisOpen[`density-${density}`] ?? false}
    onOpenChange={(v) => (axisOpen[`density-${density}`] = v)}
    title="Density: {density}"
    description="Density changes surface spacing; width is configured separately."
    showCloseButton
    {density}
  >
    <p>Command palette, save, and toggle comment live here.</p>
  </Dialog>
{/snippet}
</SpecimenLayout>

<style>
  .poodle-dialog-specimen__triggers {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    align-items: center;
  }
  .poodle-shortcuts-list { display: flex; flex-direction: column; gap: 0.5rem; }
  .poodle-shortcut { display: flex; align-items: center; gap: 0.75rem; }
  .poodle-shortcut kbd {
    display: inline-flex; align-items: center; justify-content: center;
    min-width: 4.5rem; padding: 0.25rem 0.5rem;
    border: 0.0625rem solid var(--poodle-color-border-default);
    border-radius: 0.25rem;
    background: color-mix(in srgb, var(--poodle-color-background-panel) 80%, var(--poodle-color-background-elevated));
    font-family: var(--poodle-typography-code-family); font-size: 0.75rem; font-weight: 500;
  }
  .poodle-shortcut span { color: var(--poodle-color-text-secondary); font-size: 0.8125rem; }

  .poodle-form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
  .poodle-form-full-width { grid-column: 1 / -1; }

  .poodle-changelog-header { display: flex; align-items: center; gap: 0.625rem; }
  .poodle-changelog-header__title { margin: 0; font-family: var(--poodle-typography-heading-family); font-size: 1rem; font-weight: 600; line-height: 1.2; }
  .poodle-changelog { display: flex; flex-direction: column; gap: 0.875rem; }
  .poodle-changelog__entry { display: flex; flex-direction: column; gap: 0.25rem; }
  .poodle-changelog__entry strong { font-size: 0.875rem; }
  .poodle-changelog__entry p { margin: 0; color: var(--poodle-color-text-secondary); font-size: 0.8125rem; line-height: 1.5; }

  .poodle-terms-body p { margin: 0 0 0.5rem; color: var(--poodle-color-text-secondary); font-size: 0.8125rem; line-height: 1.6; }
  .poodle-split-footer { display: flex; align-items: center; justify-content: space-between; }
  .poodle-split-footer__link { color: var(--poodle-color-accent-base); font-size: 0.8125rem; text-decoration: none; }
  .poodle-split-footer__link:hover { text-decoration: underline; }
  .poodle-split-footer__actions { display: flex; gap: 0.5rem; }

  .poodle-image-preview { display: flex; flex-direction: column; }
  .poodle-image-preview__canvas { display: grid; place-items: center; min-height: 20rem; background: color-mix(in srgb, var(--poodle-color-background-canvas) 90%, black); border-radius: var(--poodle-radius-surface) var(--poodle-radius-surface) 0 0; }
  .poodle-image-preview__placeholder { color: var(--poodle-color-text-secondary); font-family: var(--poodle-typography-code-family); font-size: 0.875rem; opacity: 0.5; }
  .poodle-image-preview__bar { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: 0.75rem 1rem; border-top: 0.0625rem solid var(--poodle-color-border-subtle); }
  .poodle-image-preview__meta { display: flex; flex-direction: column; gap: 0.125rem; }
  .poodle-image-preview__meta strong { font-size: 0.8125rem; }
  .poodle-image-preview__meta span { color: var(--poodle-color-text-secondary); font-size: 0.75rem; }
  .poodle-image-preview__actions { display: flex; gap: 0.5rem; }

  .poodle-log-list { display: flex; flex-direction: column; gap: 0.25rem; max-height: 18rem; overflow-y: auto; }
  .poodle-log-entry { display: flex; gap: 0.75rem; padding: 0.375rem 0; border-bottom: 0.0625rem solid color-mix(in srgb, var(--poodle-color-border-subtle) 50%, transparent); }
  .poodle-log-entry__time { color: var(--poodle-color-text-secondary); font-family: var(--poodle-typography-code-family); font-size: 0.75rem; min-width: 3rem; }
  .poodle-log-entry__message { font-size: 0.8125rem; }
</style>
