// packages/react/preview/src/gallery/specimens/ErrorBoundaryCrashOnce.tsx
import type { ReactNode } from "react";
import { Text } from "@inflatable-cookie/poodle-react";

const thrownTokens = new WeakSet<object>();

export function ErrorBoundaryCrashOnce({ token }: { token: object }): ReactNode {
  if (!thrownTokens.has(token)) {
    thrownTokens.add(token);
    throw new Error("Preview child failed during render.");
  }

  return <Text>Recovered child content.</Text>;
}

// packages/svelte/preview/src/specimens/ErrorBoundaryCrashOnce.svelte
<script module lang="ts">
  const thrownTokens = new WeakSet<object>();
</script>

<script lang="ts">
  import { Text } from "@inflatable-cookie/poodle-svelte";

  let { token }: { token: object } = $props();

  if (!thrownTokens.has(token)) {
    thrownTokens.add(token);
    throw new Error("Preview child failed during render.");
  }
</script>

<Text>Recovered child content.</Text>
