// packages/react/preview/src/gallery/specimens/ListCardSpecimen.tsx
import { useState, type CSSProperties } from "react";
import { Icon, IconButton, ListCard, ListCardCounter, Pill } from "@inflatable-cookie/poodle-react";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

const tiles: CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(16rem, 1fr))",
  gap: "0.75rem",
};
// The Svelte specimen scopes a tighter stack gap for list rows; the shared
// gallery rule is 0.5rem. Kept in sync so the visual gate compares the cards,
// not the harness spacing.
const stack: CSSProperties = { display: "flex", flexDirection: "column", gap: "0.25rem" };
const densityDemo: CSSProperties = { width: "min(100%, 26rem)" };
const secondary: CSSProperties = { color: "var(--poodle-color-text-secondary)" };

export function ListCardSpecimen() {
  const [lastClick, setLastClick] = useState("");
  const [selectedCard, setSelectedCard] = useState(false);

  return (
    <SpecimenLayout
      sizes={(size) => (
        <div style={densityDemo}>
          <ListCard
            title="Workspace settings"
            subtitle="Shared defaults and access controls"
            interactive
            size={size}
            leading={<Icon icon="folder" />}
            trailing={<Pill tone="success" size={size}>Live</Pill>}
          />
        </div>
      )}
      densities={(density) => (
        <div style={densityDemo}>
          <ListCard
            title="Workspace settings"
            subtitle="Shared defaults and access controls"
            interactive
            density={density}
            leading={<Icon icon="folder" />}
            trailing={<Pill tone="success">Live</Pill>}
          />
        </div>
      )}
    >
      <div className="poodle-specimen">
        <SpecimenGroup
          label="Interactive rows"
          description="Click, open, and act. The last click stays visible so the page is not a picture."
        >
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="design-system-v2.figma"
              subtitle="Updated by Clay · 2h ago"
              meta="14.2 MB"
              interactive
              onClick={() => setLastClick("design-system-v2.figma")}
              leading={<Icon icon="folder" />}
            />
            <ListCard
              title="component-specs.pdf"
              subtitle="Shared with team · Yesterday"
              meta="2.8 MB"
              interactive
              onClick={() => setLastClick("component-specs.pdf")}
              leading={<Icon name="file-text" />}
              corner={<Icon name="lock" ariaLabel="Restricted" size="sm" />}
            />
            <ListCard
              title="brand-assets.zip"
              subtitle="Archived"
              meta="48 MB"
              disabled
              leading={<Icon icon="layers" />}
            />
            <ListCard
              title="Billing settings"
              subtitle="Manage invoices and payment methods"
              href="#billing"
              leading={<Icon name="credit-card" />}
              badges={<Pill appearance="badge" tone="neutral">2</Pill>}
            />
            <ListCard
              title="Project Alpha"
              subtitle="Replaces the old media-trigger pattern with explicit actions"
              interactive
              onClick={() => setLastClick("Project Alpha")}
              leading={<Icon icon="folder" />}
              actions={<IconButton icon="ellipsis" ariaLabel="Project actions" variant="ghost" />}
            />
          </div>
          <p style={{ margin: 0 }}>Last click: {lastClick || "—"}</p>
        </SpecimenGroup>

        <SpecimenGroup label="Hierarchy and selection">
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="Cash flow forecasts"
              subtitle="Module content"
              interactive
              onClick={() => setLastClick("Cash flow forecasts")}
              leading={<Icon icon="grid-2x2" />}
              titleContent={
                <>
                  <span style={secondary}>Pathway</span>{" "}
                  <Icon name="chevron-right" size="xs" />{" "}
                  <span style={secondary}>Module</span>{" "}
                  <Icon name="chevron-right" size="xs" />{" "}
                  <span>Cash flow forecasts</span>
                </>
              }
              metaContent={<span style={secondary}>Weight 3</span>}
            />
            <ListCard
              title="Week 1: Cash Flow"
              subtitle="Move within section"
              layout="compact"
              showReorderHandle
              titleContent={
                <>
                  <span style={secondary}>Module</span>{" "}
                  <Icon name="chevron-right" size="xs" />{" "}
                  <span>Week 1: Cash Flow</span>
                </>
              }
              badges={<Pill tone="info">Move</Pill>}
            />
            <ListCard
              title="Selected row"
              subtitle="Batch-selection ready"
              selectable
              selected={selectedCard}
              onSelectedChange={(selected) => setSelectedCard(selected)}
              leading={<Icon name="check-square" />}
              badges={<Pill tone="success">Chosen</Pill>}
            />
            <ListCard
              title="Compact reorder item"
              layout="compact"
              showReorderHandle
              leading={<Icon name="grip" />}
              badges={<Pill appearance="badge" tone="neutral">Draft</Pill>}
            />
          </div>
        </SpecimenGroup>

        <SpecimenGroup label="Leading content and layout">
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="hero-banner.png"
              subtitle="Uploaded by Jamie · 4h ago"
              meta="3.1 MB"
              leadingShape="rounded-square"
              interactive
              onClick={() => setLastClick("hero-banner.png")}
              leading={<Icon name="image" />}
            />
            <ListCard
              title="onboarding-flow.mp4"
              subtitle="Screen recording · Today"
              meta="128 MB"
              leadingShape="rounded-square"
              interactive
              onClick={() => setLastClick("onboarding-flow.mp4")}
              leading={<Icon name="play" />}
            />
            <ListCard
              title="Default leading"
              subtitle="Matches the card size ladder"
              interactive
              leading={<Icon name="file-text" />}
            />
            <ListCard
              title="Offset leading"
              subtitle="Leading block steps up relative to the card size"
              interactive
              leadingSizeOffset={1}
              leading={<Icon name="file-text" />}
            />
          </div>
          <div style={tiles}>
            <ListCard
              title="Release notes"
              subtitle="Summarize the latest component changes and known migration edges."
              layout="stacked"
              leadingShape="rounded-square"
              leadingFill="solid"
              accentColor="#6366f1"
              interactive
              leading={<Icon icon="layers" />}
              trailing={<Pill tone="success">Published</Pill>}
            />
            <ListCard
              title="Media library"
              subtitle="Review uploads, approve assets, and keep metadata consistent across the library."
              layout="stacked"
              leadingShape="rounded-square"
              interactive
              leading={<Icon name="image" />}
              footer={
                <>
                  <ListCardCounter icon="image" count={18} tooltip="18 images" />
                  <ListCardCounter icon="file-text" count={6} tooltip="6 notes" />
                </>
              }
              trailing={<IconButton icon="ellipsis" ariaLabel="Media library actions" variant="ghost" />}
            />
          </div>
        </SpecimenGroup>

        <SpecimenGroup label="Badges and counters">
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="API integration guide"
              subtitle="Updated yesterday"
              meta="Draft"
              interactive
              onClick={() => setLastClick("API integration guide")}
              leading={<Icon name="file-text" />}
              badges={<Pill tone="info">New</Pill>}
            />
            <ListCard
              title="Q4 planning deck"
              subtitle="Shared with leadership"
              interactive
              onClick={() => setLastClick("Q4 planning deck")}
              leading={<Icon icon="layers" />}
              badges={
                <>
                  <Pill appearance="badge" tone="neutral">3</Pill>
                  <Pill tone="warning">Review</Pill>
                </>
              }
            />
          </div>
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="Design system"
              subtitle="12 contributors"
              leadingShape="rounded-square"
              interactive
              onClick={() => setLastClick("Design system")}
              leading={<Icon icon="folder" />}
              badges={<Pill tone="success">Active</Pill>}
              footer={
                <>
                  <ListCardCounter icon="file-text" count={24} tooltip="24 documents" />
                  <ListCardCounter icon="image" count={8} tooltip="8 images" />
                  <ListCardCounter icon="layers" count={3} tooltip="3 sub-folders" href="#sub-folders" />
                </>
              }
            />
            <ListCard
              title="Brand guidelines"
              subtitle="Last updated 2 weeks ago"
              leadingShape="rounded-square"
              interactive
              onClick={() => setLastClick("Brand guidelines")}
              leading={<Icon icon="folder" />}
              footer={
                <>
                  <ListCardCounter icon="file-text" count={6} tooltip="6 documents" />
                  <ListCardCounter icon="image" count={42} tooltip="42 images" />
                </>
              }
            />
          </div>
        </SpecimenGroup>

        <SpecimenGroup label="Visual status">
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard title="Highlighted row" subtitle="Accent gradient and inset ring" interactive highlighted />
            <ListCard
              title="Highlighted and selected"
              subtitle="Both at once"
              interactive
              selectable
              selected
              highlighted
            />
            <ListCard title="Ordinary row" subtitle="For comparison" interactive />
            <ListCard
              title="a private consumer Build Test"
              subtitle="Registered 28/07/2026 16:35"
              interactive
              active
            />
            <ListCard title="a private consumer Build Test" subtitle="Registered 28/07/2026 16:35" interactive />
            <ListCard
              title="Active and selected"
              subtitle="Both states at once"
              interactive
              selectable
              selected
              active
            />
          </div>
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="Design tokens"
              subtitle="Foundation layer"
              leadingShape="rounded-square"
              leadingFill="solid"
              accentColor="#6366f1"
              interactive
              onClick={() => setLastClick("Design tokens")}
              leading={<Icon icon="layers" />}
            />
            <ListCard
              title="Components"
              subtitle="Primitives and composites"
              leadingShape="rounded-square"
              leadingFill="solid"
              accentColor="#ec4899"
              interactive
              onClick={() => setLastClick("Components")}
              leading={<Icon icon="grid-2x2" />}
            />
            <ListCard
              title="Documentation"
              subtitle="Contracts and guides"
              leadingShape="rounded-square"
              leadingFill="solid"
              accentColor="#14b8a6"
              interactive
              onClick={() => setLastClick("Documentation")}
              leading={<Icon name="file-text" />}
            />
            <ListCard
              title="Default accent (no custom color)"
              subtitle="Uses theme accent"
              leadingShape="rounded-square"
              leadingFill="solid"
              interactive
              onClick={() => setLastClick("Default accent")}
              leading={<Icon icon="folder" />}
            />
          </div>
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="Unpublished draft"
              subtitle="Created yesterday · not yet deployed"
              meta="Draft"
              interactive
              notLive
              onClick={() => setLastClick("Unpublished draft")}
              leading={<Icon name="file-text" />}
            />
            <ListCard
              title="Staging environment"
              subtitle="Pending approval"
              interactive
              notLive
              leadingShape="rounded-square"
              leading={<Icon icon="layers" />}
              badges={<Pill tone="warning" size="md">Pending</Pill>}
            />
          </div>
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="Free tier plan"
              subtitle="No credit card required"
              sash="Free"
              interactive
              onClick={() => setLastClick("Free tier plan")}
              leading={<Icon icon="layers" />}
            />
            <ListCard
              title="Premium integration"
              subtitle="Unlocks advanced features"
              sash="New"
              sashColor="#6366f1"
              leadingShape="rounded-square"
              leadingFill="solid"
              accentColor="#6366f1"
              interactive
              onClick={() => setLastClick("Premium integration")}
              leading={<Icon icon="grid-2x2" />}
            />
            <ListCard
              title="Legacy connector"
              subtitle="Deprecated — migrate by Q2"
              sash="EOL"
              sashColor="#ef4444"
              interactive
              onClick={() => setLastClick("Legacy connector")}
              leading={<Icon name="file-text" />}
            />
          </div>
        </SpecimenGroup>

        <SpecimenGroup label="Actions and static use">
          <div className="poodle-specimen__stack" style={stack}>
            <ListCard
              title="Right-click for actions"
              subtitle="Context menu on the whole card"
              meta="12 KB"
              interactive
              contextMenuItems={[
                { label: "Open", value: "open" },
                { label: "Rename", value: "rename" },
                { label: "Duplicate", value: "duplicate" },
                { kind: "separator", label: "", value: "sep-1" },
                { label: "Delete", value: "delete" },
              ]}
              contextMenuAriaLabel="File actions"
              onContextAction={(value) => setLastClick(`Action: ${value}`)}
              onClick={() => setLastClick("Card clicked")}
              leading={<Icon name="file-text" />}
            />
            <ListCard
              title="Workspace settings"
              subtitle="Shared defaults and access controls"
              meta="Updated 2h ago"
              interactive
              leading={<Icon icon="folder" />}
              trailing={<Pill tone="success">Live</Pill>}
            />
            <ListCard title="Read-only item" subtitle="No click handler" />
          </div>
        </SpecimenGroup>

        <SpecimenGroup
          label="Listbox and list item roles"
          description="Option and listitem modes so a listbox of cards has no nested button role. Keyboard stays with the list owner."
        >
          <div className="poodle-specimen__stack" style={stack} role="listbox" aria-label="Library documents">
            <ListCard
              title="Selected option"
              subtitle="aria-selected on the card itself"
              itemRole="option"
              selected
              interactive
              leading={<Icon name="file-text" />}
            />
            <ListCard
              title="Idle option"
              subtitle="Ready for the listbox owner"
              itemRole="option"
              interactive
              leading={<Icon icon="folder" />}
            />
          </div>
          <div className="poodle-specimen__stack" style={stack} role="list" aria-label="Static rows">
            <ListCard
              title="Plain list item"
              subtitle="No button role"
              itemRole="listitem"
              leading={<Icon icon="layers" />}
            />
          </div>
        </SpecimenGroup>
      </div>
    </SpecimenLayout>
  );
}

// packages/svelte/preview/src/specimens/ListCardSpecimen.svelte
<script lang="ts">
  import { Icon, IconButton, ListCard, ListCardCounter, Pill } from "@inflatable-cookie/poodle-svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  const [folder, layers, grid2x2] = ["folder", "layers", "grid-2x2"] as const;

  let lastClick = $state("");
  let selectedCard = $state(false);
</script>

<SpecimenLayout>
  <div class="poodle-specimen">
    <SpecimenGroup
      label="Interactive rows"
      description="Click, open, and act. The last click stays visible so the page is not a picture."
    >
      <div class="poodle-specimen__stack">
        <ListCard
          title="design-system-v2.figma"
          subtitle="Updated by Clay · 2h ago"
          meta="14.2 MB"
          interactive
          onClick={() => (lastClick = "design-system-v2.figma")}
        >
          {#snippet leading()}
            <Icon icon={folder} />
          {/snippet}
        </ListCard>
        <ListCard
          title="component-specs.pdf"
          subtitle="Shared with team · Yesterday"
          meta="2.8 MB"
          interactive
          onClick={() => (lastClick = "component-specs.pdf")}
        >
          {#snippet leading()}
            <Icon name="file-text" />
          {/snippet}
          {#snippet corner()}
            <Icon name="lock" ariaLabel="Restricted" size="sm" />
          {/snippet}
        </ListCard>
        <ListCard
          title="brand-assets.zip"
          subtitle="Archived"
          meta="48 MB"
          disabled
        >
          {#snippet leading()}
            <Icon icon={layers} />
          {/snippet}
        </ListCard>
        <ListCard
          title="Billing settings"
          subtitle="Manage invoices and payment methods"
          href="#billing"
        >
          {#snippet leading()}
            <Icon name="credit-card" />
          {/snippet}
          {#snippet badges()}
            <Pill appearance="badge" tone="neutral">2</Pill>
          {/snippet}
        </ListCard>
        <ListCard
          title="Project Alpha"
          subtitle="Replaces the old media-trigger pattern with explicit actions"
          interactive
          onClick={() => (lastClick = "Project Alpha")}
        >
          {#snippet leading()}
            <Icon icon={folder} />
          {/snippet}
          {#snippet actions()}
            <IconButton icon="ellipsis" ariaLabel="Project actions" variant="ghost" />
          {/snippet}
        </ListCard>
      </div>
      <p>Last click: {lastClick || "—"}</p>
    </SpecimenGroup>

    <SpecimenGroup label="Hierarchy and selection">
      <div class="poodle-specimen__stack">
        <ListCard
          title="Cash flow forecasts"
          subtitle="Module content"
          interactive
          onClick={() => (lastClick = "Cash flow forecasts")}
        >
          {#snippet leading()}
            <Icon icon={grid2x2} />
          {/snippet}
          {#snippet titleContent()}
            <span style="color: var(--poodle-color-text-secondary);">Pathway</span>
            <Icon name="chevron-right" size="xs" />
            <span style="color: var(--poodle-color-text-secondary);">Module</span>
            <Icon name="chevron-right" size="xs" />
            <span>Cash flow forecasts</span>
          {/snippet}
          {#snippet metaContent()}
            <span style="color: var(--poodle-color-text-secondary);">Weight 3</span>
          {/snippet}
        </ListCard>
        <ListCard
          title="Week 1: Cash Flow"
          subtitle="Move within section"
          layout="compact"
          showReorderHandle
        >
          {#snippet titleContent()}
            <span style="color: var(--poodle-color-text-secondary);">Module</span>
            <Icon name="chevron-right" size="xs" />
            <span>Week 1: Cash Flow</span>
          {/snippet}
          {#snippet badges()}
            <Pill tone="info">Move</Pill>
          {/snippet}
        </ListCard>
        <ListCard
          title="Selected row"
          subtitle="Batch-selection ready"
          selectable
          selected={selectedCard}
          onSelectedChange={(selected) => (selectedCard = selected)}
        >
          {#snippet leading()}
            <Icon name="check-square" />
          {/snippet}
          {#snippet badges()}
            <Pill tone="success">Chosen</Pill>
          {/snippet}
        </ListCard>
        <ListCard
          title="Compact reorder item"
          layout="compact"
          showReorderHandle
        >
          {#snippet leading()}
            <Icon name="grip" />
          {/snippet}
          {#snippet badges()}
            <Pill appearance="badge" tone="neutral">Draft</Pill>
          {/snippet}
        </ListCard>
      </div>
    </SpecimenGroup>

    <SpecimenGroup label="Leading content and layout">
    <div class="poodle-specimen__stack">
      <ListCard
        title="hero-banner.png"
        subtitle="Uploaded by Jamie · 4h ago"
        meta="3.1 MB"
        leadingShape="rounded-square"
        interactive
        onClick={() => (lastClick = "hero-banner.png")}
      >
        {#snippet leading()}
          <Icon name="image" />
        {/snippet}
      </ListCard>
      <ListCard
        title="onboarding-flow.mp4"
        subtitle="Screen recording · Today"
        meta="128 MB"
        leadingShape="rounded-square"
        interactive
        onClick={() => (lastClick = "onboarding-flow.mp4")}
      >
        {#snippet leading()}
          <Icon name="play" />
        {/snippet}
      </ListCard>
      <ListCard
        title="Default leading"
        subtitle="Matches the card size ladder"
        interactive
      >
        {#snippet leading()}
          <Icon name="file-text" />
        {/snippet}
      </ListCard>
      <ListCard
        title="Offset leading"
        subtitle="Leading block steps up relative to the card size"
        interactive
        leadingSizeOffset={1}
      >
        {#snippet leading()}
          <Icon name="file-text" />
        {/snippet}
      </ListCard>
    </div>
    <div class="poodle-specimen__tiles">
      <ListCard
        title="Release notes"
        subtitle="Summarize the latest component changes and known migration edges."
        layout="stacked"
        leadingShape="rounded-square"
        leadingFill="solid"
        accentColor="#6366f1"
        interactive
      >
        {#snippet leading()}
          <Icon icon={layers} />
        {/snippet}
        {#snippet trailing()}
          <Pill tone="success">Published</Pill>
        {/snippet}
      </ListCard>
      <ListCard
        title="Media library"
        subtitle="Review uploads, approve assets, and keep metadata consistent across the library."
        layout="stacked"
        leadingShape="rounded-square"
        interactive
      >
        {#snippet leading()}
          <Icon name="image" />
        {/snippet}
        {#snippet footer()}
          <ListCardCounter icon="image" count={18} tooltip="18 images" />
          <ListCardCounter icon="file-text" count={6} tooltip="6 notes" />
        {/snippet}
        {#snippet trailing()}
          <IconButton icon="ellipsis" ariaLabel="Media library actions" variant="ghost" />
        {/snippet}
      </ListCard>
    </div>
    </SpecimenGroup>

    <SpecimenGroup label="Badges and counters">
    <div class="poodle-specimen__stack">
      <ListCard
        title="API integration guide"
        subtitle="Updated yesterday"
        meta="Draft"
        interactive
        onClick={() => (lastClick = "API integration guide")}
      >
        {#snippet leading()}
          <Icon name="file-text" />
        {/snippet}
        {#snippet badges()}
          <Pill tone="info">New</Pill>
        {/snippet}
      </ListCard>
      <ListCard
        title="Q4 planning deck"
        subtitle="Shared with leadership"
        interactive
        onClick={() => (lastClick = "Q4 planning deck")}
      >
        {#snippet leading()}
          <Icon icon={layers} />
        {/snippet}
        {#snippet badges()}
          <Pill appearance="badge" tone="neutral">3</Pill>
          <Pill tone="warning">Review</Pill>
        {/snippet}
      </ListCard>
    </div>
    <div class="poodle-specimen__stack">
      <ListCard
        title="Design system"
        subtitle="12 contributors"
        leadingShape="rounded-square"
        interactive
        onClick={() => (lastClick = "Design system")}
      >
        {#snippet leading()}
          <Icon icon={folder} />
        {/snippet}
        {#snippet badges()}
          <Pill tone="success">Active</Pill>
        {/snippet}
        {#snippet footer()}
          <ListCardCounter icon="file-text" count={24} tooltip="24 documents" />
          <ListCardCounter icon="image" count={8} tooltip="8 images" />
          <ListCardCounter icon="layers" count={3} tooltip="3 sub-folders" href="#sub-folders" />
        {/snippet}
      </ListCard>
      <ListCard
        title="Brand guidelines"
        subtitle="Last updated 2 weeks ago"
        leadingShape="rounded-square"
        interactive
        onClick={() => (lastClick = "Brand guidelines")}
      >
        {#snippet leading()}
          <Icon icon={folder} />
        {/snippet}
        {#snippet footer()}
          <ListCardCounter icon="file-text" count={6} tooltip="6 documents" />
          <ListCardCounter icon="image" count={42} tooltip="42 images" />
        {/snippet}
      </ListCard>
    </div>
    </SpecimenGroup>

    <SpecimenGroup label="Visual status">
    <div class="poodle-specimen__stack">
      <ListCard title="Highlighted row" subtitle="Accent gradient and inset ring" interactive highlighted />
      <ListCard title="Highlighted and selected" subtitle="Both at once" interactive selectable selected highlighted />
      <ListCard title="Ordinary row" subtitle="For comparison" interactive />
      <ListCard title="a private consumer Build Test" subtitle="Registered 28/07/2026 16:35" interactive active />
      <ListCard title="a private consumer Build Test" subtitle="Registered 28/07/2026 16:35" interactive />
      <ListCard title="Active and selected" subtitle="Both states at once" interactive selectable selected active />
    </div>
    <div class="poodle-specimen__stack">
      <ListCard
        title="Design tokens"
        subtitle="Foundation layer"
        leadingShape="rounded-square"
        leadingFill="solid"
        accentColor="#6366f1"
        interactive
        onClick={() => (lastClick = "Design tokens")}
      >
        {#snippet leading()}
          <Icon icon={layers} />
        {/snippet}
      </ListCard>
      <ListCard
        title="Components"
        subtitle="Primitives and composites"
        leadingShape="rounded-square"
        leadingFill="solid"
        accentColor="#ec4899"
        interactive
        onClick={() => (lastClick = "Components")}
      >
        {#snippet leading()}
          <Icon icon={grid2x2} />
        {/snippet}
      </ListCard>
      <ListCard
        title="Documentation"
        subtitle="Contracts and guides"
        leadingShape="rounded-square"
        leadingFill="solid"
        accentColor="#14b8a6"
        interactive
        onClick={() => (lastClick = "Documentation")}
      >
        {#snippet leading()}
          <Icon name="file-text" />
        {/snippet}
      </ListCard>
      <ListCard
        title="Default accent (no custom color)"
        subtitle="Uses theme accent"
        leadingShape="rounded-square"
        leadingFill="solid"
        interactive
        onClick={() => (lastClick = "Default accent")}
      >
        {#snippet leading()}
          <Icon icon={folder} />
        {/snippet}
      </ListCard>
    </div>
    <div class="poodle-specimen__stack">
      <ListCard
        title="Unpublished draft"
        subtitle="Created yesterday · not yet deployed"
        meta="Draft"
        interactive
        notLive
        onClick={() => (lastClick = "Unpublished draft")}
      >
        {#snippet leading()}
          <Icon name="file-text" />
        {/snippet}
      </ListCard>
      <ListCard
        title="Staging environment"
        subtitle="Pending approval"
        interactive
        notLive
        leadingShape="rounded-square"
      >
        {#snippet leading()}
          <Icon icon={layers} />
        {/snippet}
        {#snippet badges()}
          <Pill tone="warning" size="md">Pending</Pill>
        {/snippet}
      </ListCard>
    </div>
    <div class="poodle-specimen__stack">
      <ListCard
        title="Free tier plan"
        subtitle="No credit card required"
        sash="Free"
        interactive
        onClick={() => (lastClick = "Free tier plan")}
      >
        {#snippet leading()}
          <Icon icon={layers} />
        {/snippet}
      </ListCard>
      <ListCard
        title="Premium integration"
        subtitle="Unlocks advanced features"
        sash="New"
        sashColor="#6366f1"
        leadingShape="rounded-square"
        leadingFill="solid"
        accentColor="#6366f1"
        interactive
        onClick={() => (lastClick = "Premium integration")}
      >
        {#snippet leading()}
          <Icon icon={grid2x2} />
        {/snippet}
      </ListCard>
      <ListCard
        title="Legacy connector"
        subtitle="Deprecated — migrate by Q2"
        sash="EOL"
        sashColor="#ef4444"
        interactive
        onClick={() => (lastClick = "Legacy connector")}
      >
        {#snippet leading()}
          <Icon name="file-text" />
        {/snippet}
      </ListCard>
    </div>
    </SpecimenGroup>

    <SpecimenGroup label="Actions and static use">
    <div class="poodle-specimen__stack">
      <ListCard
        title="Right-click for actions"
        subtitle="Context menu on the whole card"
        meta="12 KB"
        interactive
        contextMenuItems={[
          { label: "Open", value: "open" },
          { label: "Rename", value: "rename" },
          { label: "Duplicate", value: "duplicate" },
          { kind: "separator", label: "", value: "sep-1" },
          { label: "Delete", value: "delete" },
        ]}
        contextMenuAriaLabel="File actions"
        onContextAction={(value) => (lastClick = `Action: ${value}`)}
        onClick={() => (lastClick = "Card clicked")}
      >
        {#snippet leading()}
          <Icon name="file-text" />
        {/snippet}
      </ListCard>
      <ListCard
        title="Workspace settings"
        subtitle="Shared defaults and access controls"
        meta="Updated 2h ago"
        interactive
      >
        {#snippet leading()}
          <Icon icon={folder} />
        {/snippet}
        {#snippet trailing()}
          <Pill tone="success">Live</Pill>
        {/snippet}
      </ListCard>
      <ListCard title="Read-only item" subtitle="No click handler" />
    </div>
    </SpecimenGroup>

    <SpecimenGroup
      label="Listbox and list item roles"
      description="Option and listitem modes so a listbox of cards has no nested button role. Keyboard stays with the list owner."
    >
      <div class="poodle-specimen__stack" role="listbox" aria-label="Library documents">
        <ListCard
          title="Selected option"
          subtitle="aria-selected on the card itself"
          itemRole="option"
          selected
          interactive
        >
          {#snippet leading()}
            <Icon name="file-text" />
          {/snippet}
        </ListCard>
        <ListCard
          title="Idle option"
          subtitle="Ready for the listbox owner"
          itemRole="option"
          interactive
        >
          {#snippet leading()}
            <Icon icon={folder} />
          {/snippet}
        </ListCard>
      </div>
      <div class="poodle-specimen__stack" role="list" aria-label="Static rows">
        <ListCard
          title="Plain list item"
          subtitle="No button role"
          itemRole="listitem"
        >
          {#snippet leading()}
            <Icon icon={layers} />
          {/snippet}
        </ListCard>
      </div>
    </SpecimenGroup>
  </div>

  {#snippet sizes(size)}
    <div class="poodle-list-card-density-demo">
      <ListCard
        title="Workspace settings"
        subtitle="Shared defaults and access controls"
        interactive
        {size}
      >
        {#snippet leading()}
          <Icon icon={folder} />
        {/snippet}
        {#snippet trailing()}
          <Pill tone="success" {size}>Live</Pill>
        {/snippet}
      </ListCard>
    </div>
  {/snippet}

  {#snippet densities(density)}
    <div class="poodle-list-card-density-demo">
      <ListCard
        title="Workspace settings"
        subtitle="Shared defaults and access controls"
        interactive
        {density}
      >
        {#snippet leading()}
          <Icon icon={folder} />
        {/snippet}
        {#snippet trailing()}
          <Pill tone="success">Live</Pill>
        {/snippet}
      </ListCard>
    </div>
  {/snippet}
</SpecimenLayout>

<style>
  .poodle-specimen { display: flex; flex-direction: column; gap: 1rem; }
  .poodle-specimen__stack { display: flex; flex-direction: column; gap: 0.25rem; }
  .poodle-specimen__tiles {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
    gap: 0.75rem;
  }
  .poodle-list-card-density-demo { width: min(100%, 26rem); }
  p { margin: 0; }
</style>
