// packages/react/preview/src/gallery/specimens/TimeZoneSelectSpecimen.tsx
import { useState, type CSSProperties } from "react";
import { TimeZoneSelect, Eyebrow, Surface } from "@poodle/react";
import { SpecimenLayout } from "../SpecimenLayout";

const specimenStyle: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: "0.75rem",
};

const itemStyle: CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: "0.75rem",
};

const valueStyle: CSSProperties = {
  fontSize: "0.75rem",
  color: "var(--poodle-color-text-secondary)",
};

export function TimeZoneSelectSpecimen() {
  const [zone, setZone] = useState("");

  return (
    <SpecimenLayout
      sizes={(size) => <TimeZoneSelect size={size} ariaLabel={size} />}
      densities={(density) => <TimeZoneSelect density={density} ariaLabel={density} />}
    >
      <Surface tone="panel" border="subtle" padding="md">
        <div style={specimenStyle}>
          <div style={itemStyle}>
            <Eyebrow>Default</Eyebrow>
            <TimeZoneSelect ariaLabel="Time zone" onValueChange={(value) => setZone(value)} />
            {zone && <span style={valueStyle}>{zone}</span>}
          </div>

          <div style={itemStyle}>
            <Eyebrow>Pre-selected</Eyebrow>
            <TimeZoneSelect defaultValue="America/New_York" ariaLabel="Pre-filled" />
          </div>

          <div style={itemStyle}>
            <Eyebrow>Disabled</Eyebrow>
            <TimeZoneSelect disabled ariaLabel="Disabled" />
          </div>
        </div>
      </Surface>
    </SpecimenLayout>
  );
}

// packages/svelte/preview/src/specimens/TimeZoneSelectSpecimen.svelte
<script lang="ts">
  import { TimeZoneSelect, Eyebrow, Surface } from "@poodle/svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  let zone = "";
</script>

<SpecimenLayout>
  <Surface tone="panel" border="subtle" padding="md">
    <div class="specimen">
      <div class="specimen__item">
        <Eyebrow>Default</Eyebrow>
        <TimeZoneSelect ariaLabel="Time zone" on:valueChange={(e) => (zone = e.detail.value)} />
        {#if zone}<span class="specimen__value">{zone}</span>{/if}
      </div>

      <div class="specimen__item">
        <Eyebrow>Pre-selected</Eyebrow>
        <TimeZoneSelect defaultValue="America/New_York" ariaLabel="Pre-filled" />
      </div>

      <div class="specimen__item">
        <Eyebrow>Disabled</Eyebrow>
        <TimeZoneSelect disabled ariaLabel="Disabled" />
      </div>
    </div>
  </Surface>

  <svelte:fragment slot="sizes" let:size>
    <TimeZoneSelect {size} ariaLabel={size} />
  </svelte:fragment>

  <svelte:fragment slot="densities" let:density>
    <TimeZoneSelect {density} ariaLabel={density} />
  </svelte:fragment>
</SpecimenLayout>

<style>
  .specimen { display: flex; flex-direction: column; gap: 0.75rem; }
  .specimen__item { display: flex; align-items: center; gap: 0.75rem; }
  .specimen__value { font-size: 0.75rem; color: var(--poodle-color-text-secondary); }
</style>
