// packages/react/preview/src/gallery/ComponentsSection.tsx
import { useEffect, useRef, useState } from "react";
import { Icon, SidebarNav } from "@inflatable-cookie/poodle-react";
import { allComponents, findComponent } from "./registry";
import {
  componentsBySection,
  isFamilyDisclosed,
  matchesCatalogueSearch,
} from "@poodle/svelte-preview/catalogue-nav";
import { CatalogueLanding } from "./CatalogueLanding";
import { ComponentPage } from "./ComponentPage";
import { specimenMap } from "./specimen-map";

export interface ComponentsSectionProps {
  activeComponent?: string;
  search?: string;
}

export function ComponentsSection({
  activeComponent,
  search = "",
}: ComponentsSectionProps) {
  const contentRef = useRef<HTMLDivElement | null>(null);
  const previousActiveComponent = useRef(activeComponent);
  const [userDisclosure, setUserDisclosure] = useState<Map<string, boolean>>(
    () => new Map(),
  );

  const entry = activeComponent ? findComponent(activeComponent) : undefined;
  const specimen = entry?.slug ? (specimenMap[entry.slug] ?? null) : null;

  useEffect(() => {
    if (previousActiveComponent.current !== activeComponent) {
      const activeFamily = activeComponent
        ? findComponent(activeComponent)?.family
        : undefined;
      if (activeFamily) {
        setUserDisclosure((current) => {
          if (!current.has(activeFamily)) return current;
          const next = new Map(current);
          next.delete(activeFamily);
          return next;
        });
      }
      previousActiveComponent.current = activeComponent;
    }
    if (activeComponent && contentRef.current) {
      contentRef.current.scrollTop = 0;
    }
  }, [activeComponent]);

  const searchActive = search.trim().length > 0;
  const filteredComponents = searchActive
    ? allComponents.filter((component) =>
        matchesCatalogueSearch(component, search),
      )
    : allComponents;
  const sectionGroups = componentsBySection(allComponents);

  const toggleFamily = (familyId: string, open: boolean) => {
    setUserDisclosure((current) => {
      const next = new Map(current);
      next.set(familyId, !open);
      return next;
    });
  };

  return (
    <div className="poodle-catalogue-layout">
      <div className="poodle-catalogue-sidebar">
        {searchActive ? (
          <div className="poodle-catalogue-search" data-catalogue-search="true">
            {filteredComponents.length === 0 ? (
              <p className="poodle-catalogue-search__empty">
                No matching components.
              </p>
            ) : (
              filteredComponents.map((component) => (
                <a
                  key={component.slug}
                  className="poodle-catalogue-search__item"
                  href={`#components/${component.slug}`}
                  aria-current={
                    component.slug === activeComponent ? "page" : undefined
                  }
                  data-catalogue-result={component.slug}
                >
                  <span className="poodle-catalogue-search__name">
                    {component.displayName}
                  </span>
                  <span className="poodle-catalogue-search__crumb">
                    {component.familyLabel} · {component.kindLabel}
                  </span>
                </a>
              ))
            )}
          </div>
        ) : (
          <nav className="poodle-catalogue-nav" aria-label="Components">
            {sectionGroups.map((section) => (
              <div
                key={section.id}
                className="poodle-catalogue-nav__section"
                data-catalogue-section={section.id}
              >
                <h2 className="poodle-catalogue-nav__section-title">
                  {section.label}
                </h2>
                {section.families.map((family) => {
                  const open = isFamilyDisclosed(
                    family.id,
                    activeComponent,
                    userDisclosure,
                    allComponents,
                  );
                  return (
                    <div
                      key={family.id}
                      className="poodle-catalogue-family"
                      data-catalogue-family={family.id}
                      data-open={open || undefined}
                    >
                      <button
                        type="button"
                        className="poodle-catalogue-family__trigger"
                        aria-expanded={open}
                        onClick={() => toggleFamily(family.id, open)}
                      >
                        <Icon
                          name={open ? "chevron-down" : "chevron-right"}
                          size="sm"
                        />
                        <span className="poodle-catalogue-family__label">
                          {family.label}
                        </span>
                        <span className="poodle-catalogue-family__count">
                          {family.items.length}
                        </span>
                      </button>
                      {open ? (
                        <div className="poodle-catalogue-family__items">
                          <SidebarNav
                            ariaLabel={family.label}
                            groups={[
                              {
                                id: family.id,
                                items: family.items.map((component) => ({
                                  value: component.slug,
                                  label: component.displayName,
                                  href: `#components/${component.slug}`,
                                })),
                              },
                            ]}
                            value={activeComponent ?? null}
                          />
                        </div>
                      ) : null}
                    </div>
                  );
                })}
              </div>
            ))}
          </nav>
        )}
      </div>

      <div className="poodle-catalogue-content" ref={contentRef}>
        {entry ? (
          <ComponentPage entry={entry} specimenComponent={specimen} />
        ) : (
          <CatalogueLanding components={filteredComponents} />
        )}
      </div>
    </div>
  );
}

// packages/svelte/preview/src/sections/ComponentsSection.svelte
<script lang="ts">
  import { Icon, SidebarNav } from "@inflatable-cookie/poodle-svelte";
  import { allComponents, findComponent, type ComponentEntry } from "../component-registry";
  import {
    componentsBySection,
    isFamilyDisclosed,
    matchesCatalogueSearch,
  } from "../catalogue-nav";
  import CatalogueLanding from "../pages/CatalogueLanding.svelte";
  import ComponentPage from "../pages/ComponentPage.svelte";
  import { specimenMap } from "../specimens/registry";

  let { activeComponent = undefined, search = "" }: { activeComponent?: string | undefined; search?: string } = $props();
  let contentElement: HTMLDivElement | undefined = $state();
  let previousActiveComponent = $state<string | undefined>();
  let userDisclosure = $state<Record<string, boolean>>({});

  let entry = $derived(activeComponent ? findComponent(activeComponent) : undefined);
  $effect(() => {
    if (previousActiveComponent !== activeComponent) {
      const activeFamily = activeComponent ? findComponent(activeComponent)?.family : undefined;
      if (activeFamily && activeFamily in userDisclosure) {
        const remainingChoices = { ...userDisclosure };
        delete remainingChoices[activeFamily];
        userDisclosure = remainingChoices;
      }
      previousActiveComponent = activeComponent;
    }
    if (activeComponent && contentElement) {
      contentElement.scrollTop = 0;
    }
  });
  let specimen = $derived(entry?.slug ? specimenMap[entry.slug] ?? null : null);
  let searchLower = $derived(search.trim());
  let searchActive = $derived(searchLower.length > 0);
  let filteredComponents = $derived(
    searchActive
      ? allComponents.filter((component) => matchesCatalogueSearch(component, searchLower))
      : allComponents,
  );
  let disclosureMap = $derived(new Map(Object.entries(userDisclosure)));
  let sectionGroups = $derived(componentsBySection(allComponents));
  let searchResults = $derived(filteredComponents);

  function toggleFamily(familyId: string, open: boolean): void {
    userDisclosure = { ...userDisclosure, [familyId]: !open };
  }

  function familyOpen(familyId: (typeof sectionGroups)[number]["families"][number]["id"]): boolean {
    return isFamilyDisclosed(familyId, activeComponent, disclosureMap, allComponents);
  }

  function navItems(items: ComponentEntry[]) {
    return items.map((component) => ({
      value: component.slug,
      label: component.displayName,
      href: `#components/${component.slug}`,
    }));
  }
</script>

<div class="poodle-catalogue-layout">
  <div class="poodle-catalogue-sidebar">
    {#if searchActive}
      <div class="poodle-catalogue-search" data-catalogue-search="true">
        {#if searchResults.length === 0}
          <p class="poodle-catalogue-search__empty">No matching components.</p>
        {:else}
          {#each searchResults as component (component.slug)}
            <a
              class="poodle-catalogue-search__item"
              href="#components/{component.slug}"
              aria-current={component.slug === activeComponent ? "page" : undefined}
              data-catalogue-result={component.slug}
            >
              <span class="poodle-catalogue-search__name">{component.displayName}</span>
              <span class="poodle-catalogue-search__crumb">{component.familyLabel} · {component.kindLabel}</span>
            </a>
          {/each}
        {/if}
      </div>
    {:else}
      <nav class="poodle-catalogue-nav" aria-label="Components">
        {#each sectionGroups as section (section.id)}
          <div class="poodle-catalogue-nav__section" data-catalogue-section={section.id}>
            <h2 class="poodle-catalogue-nav__section-title">{section.label}</h2>
            {#each section.families as family (family.id)}
              {@const open = familyOpen(family.id)}
              <div class="poodle-catalogue-family" data-catalogue-family={family.id} data-open={open || undefined}>
                <button
                  type="button"
                  class="poodle-catalogue-family__trigger"
                  aria-expanded={open}
                  onclick={() => toggleFamily(family.id, open)}
                >
                  <Icon name={open ? "chevron-down" : "chevron-right"} size="sm" />
                  <span class="poodle-catalogue-family__label">{family.label}</span>
                  <span class="poodle-catalogue-family__count">{family.items.length}</span>
                </button>
                {#if open}
                  <div class="poodle-catalogue-family__items">
                    <SidebarNav
                      ariaLabel={family.label}
                      groups={[{ id: family.id, items: navItems(family.items) }]}
                      value={activeComponent ?? null}
                    />
                  </div>
                {/if}
              </div>
            {/each}
          </div>
        {/each}
      </nav>
    {/if}
  </div>

  <div class="poodle-catalogue-content" bind:this={contentElement}>
    {#if entry}
      <ComponentPage {entry} specimenComponent={specimen} />
    {:else}
      <CatalogueLanding components={filteredComponents} />
    {/if}
  </div>
</div>
