// packages/svelte/preview/src/specimens/AgentPlanSpecimen.svelte
<script lang="ts">
  import { AgentChatInput, type AgentPlanStatus } from "@inflatable-cookie/poodle-svelte";
  import { AgentPlan } from "@inflatable-cookie/poodle-svelte/markdown";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  // Named `planMarkdown`, not `plan`: inside `{#snippet plan()}` the identifier
  // `plan` is the snippet itself, so a same-named string would be shadowed and
  // the snippet function would reach `AgentPlan.plan` — a non-string that
  // crashes the markdown lexer.
  const planMarkdown = [
    "## Proposed plan",
    "",
    "1. Add the `AgentPlan` surface to the composer",
    "2. Wire the decision callbacks through the host",
    "3. Append the settled record to the transcript",
    "",
    "Then run the gates.",
  ].join("\n");

  // The arrangement that matters: the plan inside the composer, where the
  // editor is the revise channel — feedback goes as an ordinary message.
  let composerValue = $state("");
  let decision = $state<AgentPlanStatus>("pending");
  let lastMessage = $state("");
</script>

<SpecimenLayout>
  <SpecimenGroup
    label="Hosted by the composer"
    description="A proposed plan is input, so it mounts in the composer region — not the transcript. The turn is already complete; sending a message is the revise channel."
  >
    <AgentChatInput
      bind:value={composerValue}
      status="reviewing-plan"
      onSubmit={(value) => { lastMessage = value; composerValue = ""; }}
    >
      {#snippet plan()}
        <AgentPlan
          plan={planMarkdown}
          status={decision}
          onAccept={() => (decision = "accepted")}
          onRevise={() => (decision = "revised")}
          onDismiss={() => (decision = "dismissed")}
        />
      {/snippet}
    </AgentChatInput>
    <p style="color: var(--poodle-color-text-secondary); font-size: 0.8125rem;">
      {decision !== "pending" ? `decided: ${decision}` : lastMessage ? `revision sent: ${lastMessage}` : "no decision yet"}
    </p>
  </SpecimenGroup>

  <SpecimenGroup label="Pending" description="Controls render only while the plan waits on the operator.">
    <AgentPlan plan={planMarkdown} />
  </SpecimenGroup>

  <SpecimenGroup label="Settled" description="A settled status swaps the controls for the badge — the transitional render before the host swaps in the record.">
    <AgentPlan plan={planMarkdown} status="accepted" />
  </SpecimenGroup>

  <SpecimenGroup label="Not dismissible" description="Dismiss is a first-class decision for a plan, so it renders by default; a host can still withhold it.">
    <AgentPlan plan={planMarkdown} dismissible={false} />
  </SpecimenGroup>

  {#snippet sizes(size)}
    <AgentPlan plan={planMarkdown} {size} />
  {/snippet}

  {#snippet densities(density)}
    <AgentPlan plan={planMarkdown} {density} />
  {/snippet}
</SpecimenLayout>

// packages/react/preview/src/gallery/specimens/AgentPlanSpecimen.tsx
import { useState } from "react";
import { AgentChatInput, type AgentPlanStatus } from "@inflatable-cookie/poodle-react";
import { AgentPlan } from "@inflatable-cookie/poodle-react/markdown";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

const planMarkdown = [
  "## Proposed plan",
  "",
  "1. Add the `AgentPlan` surface to the composer",
  "2. Wire the decision callbacks through the host",
  "3. Append the settled record to the transcript",
  "",
  "Then run the gates.",
].join("\n");

export function AgentPlanSpecimen() {
  // The arrangement that matters: the plan inside the composer, where the
  // editor is the revise channel — feedback goes as an ordinary message.
  const [composerValue, setComposerValue] = useState("");
  const [decision, setDecision] = useState<AgentPlanStatus>("pending");
  const [lastMessage, setLastMessage] = useState("");

  return (
    <SpecimenLayout
      sizes={(size) => <AgentPlan plan={planMarkdown} size={size} />}
      densities={(density) => <AgentPlan plan={planMarkdown} density={density} />}
    >
      <SpecimenGroup
        label="Hosted by the composer"
        description="A proposed plan is input, so it mounts in the composer region — not the transcript. The turn is already complete; sending a message is the revise channel."
      >
        <AgentChatInput
          value={composerValue}
          onValueChange={setComposerValue}
          status="reviewing-plan"
          plan={
            <AgentPlan
              plan={planMarkdown}
              status={decision}
              onAccept={() => setDecision("accepted")}
              onRevise={() => setDecision("revised")}
              onDismiss={() => setDecision("dismissed")}
            />
          }
          onSubmit={(value) => {
            setLastMessage(value);
            setComposerValue("");
          }}
        />
        <p style={{ color: "var(--poodle-color-text-secondary)", fontSize: "0.8125rem" }}>
          {decision !== "pending"
            ? `decided: ${decision}`
            : lastMessage
              ? `revision sent: ${lastMessage}`
              : "no decision yet"}
        </p>
      </SpecimenGroup>

      <SpecimenGroup
        label="Pending"
        description="Controls render only while the plan waits on the operator."
      >
        <AgentPlan plan={planMarkdown} />
      </SpecimenGroup>

      <SpecimenGroup
        label="Settled"
        description="A settled status swaps the controls for the badge — the transitional render before the host swaps in the record."
      >
        <AgentPlan plan={planMarkdown} status="accepted" />
      </SpecimenGroup>

      <SpecimenGroup
        label="Not dismissible"
        description="Dismiss is a first-class decision for a plan, so it renders by default; a host can still withhold it."
      >
        <AgentPlan plan={planMarkdown} dismissible={false} />
      </SpecimenGroup>
    </SpecimenLayout>
  );
}
