// packages/svelte/preview/src/specimens/BlockEditorSpecimen.svelte
<script lang="ts">
  import { BlockEditor } from "@inflatable-cookie/poodle-svelte";
  import type { BlockTypeDefinition, BlockTypeGroup, EditorBlock } from "@inflatable-cookie/poodle-svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  const blockTypes: BlockTypeDefinition[] = [
    { type: "paragraph", label: "Paragraph", icon: "file-text" },
    { type: "heading", label: "Heading", icon: "hash" },
    { type: "code", label: "Code", icon: "code" },
    { type: "quote", label: "Quote", icon: "bookmark" },
    { type: "divider", label: "Divider", icon: "minus" },
  ];

  let blocks: EditorBlock[] = $state([
    { id: "1", type: "heading", version: 3, hash: "a1", data: { text: "Block Editor Shell" }, content: "Block Editor Shell" },
    { id: "2", type: "paragraph", version: 3, hash: "a2", data: { text: "Block types and rendering are provided by the consumer. The shell handles ordering, type selection, add/remove, and drag-drop." }, content: "Block types and rendering are provided by the consumer. The shell handles ordering, type selection, add/remove, and drag-drop." },
    { id: "3", type: "quote", version: 3, hash: "a3", data: { text: "The best way to predict the future is to invent it." }, content: "The best way to predict the future is to invent it." },
    { id: "4", type: "code", version: 3, hash: "a4", data: { text: 'console.log("Hello, world!");' }, content: 'console.log("Hello, world!");' },
    { id: "5", type: "divider", version: 3, hash: "a5", data: {}, content: "" },
    { id: "6", type: "paragraph", version: 3, hash: "a6", data: { text: "Use the type dropdown to change a block, or the + dropdown to add a new one after." }, content: "Use the type dropdown to change a block, or the + dropdown to add a new one after." },
  ]);

  let singleBlocks: EditorBlock[] = $state([
    {
      id: "hero-1",
      type: "heading",
      version: "initial",
      hash: "hero-hash",
      data: { text: "Single-block Nightfire posture" },
      content: "Single-block Nightfire posture",
    },
  ]);

  const groupedTypeOptions: BlockTypeGroup[] = [
    {
      label: "Text",
      options: [
        { type: "paragraph", label: "Paragraph", icon: "file-text" },
        { type: "heading", label: "Heading", icon: "hash" },
        { type: "quote", label: "Quote", icon: "bookmark" },
      ],
    },
    {
      label: "Structure",
      options: [
        { type: "code", label: "Code", icon: "code" },
        { type: "divider", label: "Divider", icon: "minus" },
      ],
    },
  ];

  function handleChange(nextBlocks: EditorBlock[]): void {
    blocks = nextBlocks;
  }

  function handleSingleChange(nextBlocks: EditorBlock[]): void {
    singleBlocks = nextBlocks;
  }

  /* One stable, ordinary editing state for the axis panes. */
  const axisBlocks: EditorBlock[] = [
    { id: "axis-1", type: "heading", version: 3, hash: "a1", data: { text: "Release notes" }, content: "Release notes" },
    { id: "axis-2", type: "paragraph", version: 3, hash: "a2", data: { text: "Draft your post here." }, content: "Draft your post here." },
  ];
</script>

<SpecimenLayout>
  <SpecimenGroup label="Consumer-driven block types">
    <BlockEditor {blocks} {blockTypes} onChange={handleChange}>
      {#snippet block({ block, disabled, update })}
  {#if block.type === "divider"}
    <hr class="poodle-block-divider" />
  {:else if block.type === "heading"}
    <input
      type="text"
      class="poodle-block-input poodle-block-input--heading"
      placeholder="Heading..."
      disabled={disabled}
      value={block.content ?? block.data?.text ?? ""}
      oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
    />
  {:else if block.type === "code"}
    <textarea
      class="poodle-block-input poodle-block-input--code"
      placeholder="Code..."
      disabled={disabled}
      value={block.content ?? block.data?.text ?? ""}
      oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
      rows="3"
    ></textarea>
  {:else if block.type === "quote"}
    <textarea
      class="poodle-block-input poodle-block-input--quote"
      placeholder="Quote..."
      disabled={disabled}
      value={block.content ?? block.data?.text ?? ""}
      oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
      rows="2"
    ></textarea>
  {:else}
    <textarea
      class="poodle-block-input"
      placeholder="Type something..."
      disabled={disabled}
      value={block.content ?? block.data?.text ?? ""}
      oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
      rows="2"
    ></textarea>
  {/if}
{/snippet}
    </BlockEditor>
    <p class="poodle-specimen__count">{blocks.length} blocks</p>
  </SpecimenGroup>

  <SpecimenGroup label="Single posture with custom grouped type picker">
    <BlockEditor
      blocks={singleBlocks}
      {blockTypes}
      blockTypeItems={groupedTypeOptions}
      mode="single"
      onChange={handleSingleChange}
    >
      {#snippet block({ block, disabled, update })}
        <input
          type="text"
          class="poodle-block-input poodle-block-input--heading"
          placeholder="Heading..."
          disabled={disabled}
          value={block.content ?? block.data?.text ?? ""}
          oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
        />
      {/snippet}
    </BlockEditor>
    <p class="poodle-specimen__count">Single posture hides reorder, add, and remove controls while the built-in picker accepts grouped Nightfire-style options.</p>
  </SpecimenGroup>

  {#snippet sizes(size)}
    <BlockEditor blocks={axisBlocks} {blockTypes} {size}>
      {#snippet block({ block, disabled, update })}
        {#if block.type === "heading"}
          <input
            type="text"
            class="poodle-block-input poodle-block-input--heading"
            placeholder="Heading..."
            disabled={disabled}
            value={block.content ?? block.data?.text ?? ""}
            oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
          />
        {:else}
          <textarea
            class="poodle-block-input"
            placeholder="Type something..."
            disabled={disabled}
            value={block.content ?? block.data?.text ?? ""}
            oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
            rows="2"
          ></textarea>
        {/if}
      {/snippet}
    </BlockEditor>
  {/snippet}

  {#snippet densities(density)}
    <BlockEditor blocks={axisBlocks} {blockTypes} {density}>
      {#snippet block({ block, disabled, update })}
        {#if block.type === "heading"}
          <input
            type="text"
            class="poodle-block-input poodle-block-input--heading"
            placeholder="Heading..."
            disabled={disabled}
            value={block.content ?? block.data?.text ?? ""}
            oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
          />
        {:else}
          <textarea
            class="poodle-block-input"
            placeholder="Type something..."
            disabled={disabled}
            value={block.content ?? block.data?.text ?? ""}
            oninput={(e) => update({ content: (e.currentTarget).value, data: { ...(block.data ?? {}), text: (e.currentTarget).value } })}
            rows="2"
          ></textarea>
        {/if}
      {/snippet}
    </BlockEditor>
  {/snippet}
</SpecimenLayout>

<style>
  .poodle-specimen__count {
    margin: 0;
    font-size: 0.75rem;
    color: var(--poodle-color-text-tertiary);
  }

  /* Block rendering styles — owned by the consumer, not the shell */
  .poodle-block-input {
    width: 100%;
    padding: 0.25rem 0.375rem;
    border: 0;
    background: transparent;
    color: var(--poodle-color-text-primary);
    font-family: var(--poodle-typography-body-family);
    font-size: 0.875rem;
    line-height: 1.6;
    outline: none;
    resize: vertical;
  }

  .poodle-block-input--heading {
    font-size: 1.125rem;
    font-weight: 700;
  }

  .poodle-block-input--code {
    font-family: var(--poodle-typography-code-family);
    font-size: 0.8125rem;
    color: var(--poodle-color-text-secondary);
  }

  .poodle-block-input--quote {
    border-left: 0.1875rem solid var(--poodle-color-border-default);
    padding-left: 0.625rem;
    color: var(--poodle-color-text-secondary);
    font-style: italic;
  }

  .poodle-block-divider {
    border: 0;
    border-top: 0.0625rem solid var(--poodle-color-border-subtle);
    margin: 0.5rem 0;
  }
</style>

// packages/react/preview/src/gallery/specimens/BlockEditorSpecimen.tsx
import { useState, type ChangeEvent, type CSSProperties } from "react";
import { BlockEditor, type BlockEditorBlockProps, type BlockTypeDefinition, type BlockTypeGroup, type EditorBlock } from "@inflatable-cookie/poodle-react";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

const blockTypes: BlockTypeDefinition[] = [
  { type: "paragraph", label: "Paragraph", icon: "file-text" },
  { type: "heading", label: "Heading", icon: "hash" },
  { type: "code", label: "Code", icon: "code" },
  { type: "quote", label: "Quote", icon: "bookmark" },
  { type: "divider", label: "Divider", icon: "minus" },
];

const groupedTypeOptions: BlockTypeGroup[] = [
  {
    label: "Text",
    options: [
      { type: "paragraph", label: "Paragraph", icon: "file-text" },
      { type: "heading", label: "Heading", icon: "hash" },
      { type: "quote", label: "Quote", icon: "bookmark" },
    ],
  },
  {
    label: "Structure",
    options: [
      { type: "code", label: "Code", icon: "code" },
      { type: "divider", label: "Divider", icon: "minus" },
    ],
  },
];

const countStyle: CSSProperties = { margin: 0, fontSize: "0.75rem", color: "var(--poodle-color-text-tertiary)" };

const baseInputStyle: CSSProperties = {
  width: "100%",
  padding: "0.25rem 0.375rem",
  border: 0,
  background: "transparent",
  color: "var(--poodle-color-text-primary)",
  fontFamily: "var(--poodle-typography-body-family)",
  fontSize: "0.875rem",
  lineHeight: 1.6,
  outline: "none",
};

const textareaStyle: CSSProperties = { ...baseInputStyle, resize: "vertical" };

const headingStyle: CSSProperties = { ...baseInputStyle, fontSize: "1.125rem", fontWeight: 700 };

const codeStyle: CSSProperties = {
  ...textareaStyle,
  fontFamily: "var(--poodle-typography-code-family)",
  fontSize: "0.8125rem",
  color: "var(--poodle-color-text-secondary)",
};

const quoteStyle: CSSProperties = {
  ...textareaStyle,
  borderLeft: "0.1875rem solid var(--poodle-color-border-default)",
  paddingLeft: "0.625rem",
  color: "var(--poodle-color-text-secondary)",
  fontStyle: "italic",
};

const dividerStyle: CSSProperties = {
  border: 0,
  borderTop: "0.0625rem solid var(--poodle-color-border-subtle)",
  margin: "0.5rem 0",
};

function blockText(block: EditorBlock): string {
  return block.content ?? (block.data as { text?: string } | undefined)?.text ?? "";
}

/** One stable, ordinary editing state for the axis panes. */
const axisBlocks: EditorBlock[] = [
  { id: "axis-1", type: "heading", version: 3, hash: "a1", data: { text: "Release notes" }, content: "Release notes" },
  { id: "axis-2", type: "paragraph", version: 3, hash: "a2", data: { text: "Draft your post here." }, content: "Draft your post here." },
];

function renderBlock({ block, disabled, update }: BlockEditorBlockProps) {
  const value = blockText(block);
  const onInput = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) =>
    update({
      content: e.currentTarget.value,
      data: { ...((block.data as Record<string, unknown>) ?? {}), text: e.currentTarget.value },
    });
  if (block.type === "divider") {
    return <hr style={dividerStyle} />;
  }
  if (block.type === "heading") {
    return (
      <input type="text" style={headingStyle} placeholder="Heading..." disabled={disabled} value={value} onChange={onInput} />
    );
  }
  if (block.type === "code") {
    return (
      <textarea style={codeStyle} placeholder="Code..." disabled={disabled} value={value} onChange={onInput} rows={3} />
    );
  }
  if (block.type === "quote") {
    return (
      <textarea style={quoteStyle} placeholder="Quote..." disabled={disabled} value={value} onChange={onInput} rows={2} />
    );
  }
  return (
    <textarea style={textareaStyle} placeholder="Type something..." disabled={disabled} value={value} onChange={onInput} rows={2} />
  );
}

export function BlockEditorSpecimen() {
  const [blocks, setBlocks] = useState<EditorBlock[]>([
    { id: "1", type: "heading", version: 3, hash: "a1", data: { text: "Block Editor Shell" }, content: "Block Editor Shell" },
    {
      id: "2",
      type: "paragraph",
      version: 3,
      hash: "a2",
      data: {
        text: "Block types and rendering are provided by the consumer. The shell handles ordering, type selection, add/remove, and drag-drop.",
      },
      content:
        "Block types and rendering are provided by the consumer. The shell handles ordering, type selection, add/remove, and drag-drop.",
    },
    {
      id: "3",
      type: "quote",
      version: 3,
      hash: "a3",
      data: { text: "The best way to predict the future is to invent it." },
      content: "The best way to predict the future is to invent it.",
    },
    {
      id: "4",
      type: "code",
      version: 3,
      hash: "a4",
      data: { text: 'console.log("Hello, world!");' },
      content: 'console.log("Hello, world!");',
    },
    { id: "5", type: "divider", version: 3, hash: "a5", data: {}, content: "" },
    {
      id: "6",
      type: "paragraph",
      version: 3,
      hash: "a6",
      data: { text: "Use the type dropdown to change a block, or the + dropdown to add a new one after." },
      content: "Use the type dropdown to change a block, or the + dropdown to add a new one after.",
    },
  ]);

  const [singleBlocks, setSingleBlocks] = useState<EditorBlock[]>([
    {
      id: "hero-1",
      type: "heading",
      version: "initial",
      hash: "hero-hash",
      data: { text: "Single-block Nightfire posture" },
      content: "Single-block Nightfire posture",
    },
  ]);

  return (
    <SpecimenLayout
      sizes={(size) => (
        <BlockEditor blocks={axisBlocks} blockTypes={blockTypes} size={size} block={renderBlock} />
      )}
      densities={(density) => (
        <BlockEditor blocks={axisBlocks} blockTypes={blockTypes} density={density} block={renderBlock} />
      )}
    >
      <SpecimenGroup label="Consumer-driven block types">
        <BlockEditor
          blocks={blocks}
          blockTypes={blockTypes}
          onChange={setBlocks}
          block={renderBlock}
        />
        <p style={countStyle}>{blocks.length} blocks</p>
      </SpecimenGroup>

      <SpecimenGroup label="Single posture with custom grouped type picker">
        <BlockEditor
          blocks={singleBlocks}
          blockTypes={blockTypes}
          blockTypeItems={groupedTypeOptions}
          mode="single"
          onChange={setSingleBlocks}
          block={({ block, disabled, update }) => {
            const value = blockText(block);
            const onInput = (e: ChangeEvent<HTMLInputElement>) =>
              update({
                content: e.currentTarget.value,
                data: { ...((block.data as Record<string, unknown>) ?? {}), text: e.currentTarget.value },
              });
            return (
              <input type="text" style={headingStyle} placeholder="Heading..." disabled={disabled} value={value} onChange={onInput} />
            );
          }}
        />
        <p style={countStyle}>
          Single posture hides reorder, add, and remove controls while the built-in picker accepts grouped Nightfire-style options.
        </p>
      </SpecimenGroup>
    </SpecimenLayout>
  );
}
