// packages/svelte/preview/src/specimens/DataTableSpecimen.svelte
<script lang="ts">
  import { DataTable } from "@inflatable-cookie/poodle-svelte";
  import type { TableColumn, TableFilters, TablePagination, TableRow } from "@inflatable-cookie/poodle-svelte";
  import { Pill } from "@inflatable-cookie/poodle-svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  const columns: TableColumn[] = [
    { id: "name", label: "Name", sortable: true, hideable: false },
    { id: "email", label: "Email", sortable: true, hideable: true },
    { id: "role", label: "Role", sortable: true, hideable: true },
    { id: "status", label: "Status", sortable: false, hideable: true },
  ];

  const rows: TableRow[] = [
    { id: "1", cells: { name: "Alice Chen", email: "alice@example.com", role: "Engineer", status: "Active" }, summary: "Senior frontend engineer" },
    { id: "2", cells: { name: "Bob Martinez", email: "bob@example.com", role: "Designer", status: "Active" }, summary: "UX lead" },
    { id: "3", cells: { name: "Carol Patel", email: "carol@example.com", role: "PM", status: "On leave" }, summary: "Product manager" },
    { id: "4", cells: { name: "Dan Okoro", email: "dan@example.com", role: "Engineer", status: "Active" }, summary: "Backend engineer" },
    { id: "5", cells: { name: "Eve Nakamura", email: "eve@example.com", role: "Designer", status: "Active" }, summary: "Visual designer" },
  ];

  let selectedRowIds: string[] = $state([]);
  let sortColumnId: string | null = $state(null);
  let sortDirection: "asc" | "desc" = $state("asc");
  let hiddenColumnIds: string[] = $state([]);
  let lastAction = $state("");
  let expandedIncidentId: string | null = $state(null);
  let filters: TableFilters = $state({
    name: "",
    role: "",
  });
  let pagination: TablePagination = $state({
    page: 1,
    limit: 10,
    total: 42,
  });

  type Incident = {
    status: "open" | "resolved";
    endpoint: string;
    owner: string;
    updatedAt: string;
  };

  const incidentColumns: TableColumn[] = [
    { id: "expand", label: "", width: "3rem", align: "center", hideable: false, isRowHeader: false },
    { id: "status", label: "Status", width: "7rem" },
    { id: "endpoint", label: "Endpoint", width: "minmax(14rem, 1fr)" },
    { id: "owner", label: "Owner", width: "10rem" },
  ];

  const incidentRows: TableRow<Incident>[] = [
    {
      id: "incident-1",
      cells: { expand: "", status: "Open", endpoint: "POST /api/orders", owner: "Alice" },
      data: { status: "open", endpoint: "POST /api/orders", owner: "Alice", updatedAt: "2026-03-27T11:18:00Z" },
    },
    {
      id: "incident-2",
      cells: { expand: "", status: "Resolved", endpoint: "GET /api/catalog", owner: "Bob" },
      data: { status: "resolved", endpoint: "GET /api/catalog", owner: "Bob", updatedAt: "2026-03-27T09:42:00Z" },
    },
  ];

  function handleSortChange(payload: { columnId: string; direction: "asc" | "desc" }): void {
    sortColumnId = payload.columnId;
    sortDirection = payload.direction;
    lastAction = `Sorted by ${payload.columnId} ${payload.direction}`;
  }

  function handleRowToggle(payload: { rowId: string; selected: boolean }): void {
    if (payload.selected) {
      selectedRowIds = [...selectedRowIds, payload.rowId];
    } else {
      selectedRowIds = selectedRowIds.filter((id) => id !== payload.rowId);
    }
    lastAction = `Toggled row ${payload.rowId}: ${payload.selected ? "selected" : "deselected"}`;
  }

  function handleToggleAll(payload: { selected: boolean }): void {
    selectedRowIds = payload.selected ? rows.map((r) => r.id) : [];
    lastAction = payload.selected ? "Selected all rows" : "Deselected all rows";
  }

  function handleRowAction(payload: { rowId: string }): void {
    lastAction = `Action on row ${payload.rowId}`;
  }

  function handleColumnVisibility(payload: { columnId: string; visible: boolean }): void {
    if (payload.visible) {
      hiddenColumnIds = hiddenColumnIds.filter((id) => id !== payload.columnId);
    } else {
      hiddenColumnIds = [...hiddenColumnIds, payload.columnId];
    }
    lastAction = `${payload.visible ? "Showed" : "Hid"} column: ${payload.columnId}`;
  }
</script>

<SpecimenLayout>
  <div class="poodle-specimen">
    <SpecimenGroup bare label="With sorting, column visibility, and export">
      <DataTable
        {columns}
        {rows}
        selectable
        {selectedRowIds}
        {sortColumnId}
        {sortDirection}
        {hiddenColumnIds}
        showColumnVisibility
        showExport
        ariaLabel="Team members"
        onSortChange={handleSortChange}
        onRowToggle={handleRowToggle}
        onToggleAll={handleToggleAll}
        onRowAction={handleRowAction}
        onColumnVisibilityChange={handleColumnVisibility}
      />
      {#if lastAction}
        <p class="poodle-last-action">Last action: <strong>{lastAction}</strong></p>
      {/if}
      <p class="poodle-selection-count">{selectedRowIds.length} of {rows.length} selected</p>
    </SpecimenGroup>

    <SpecimenGroup bare label="With filters and pagination">
      <DataTable
        {columns}
        {rows}
        {filters}
        {pagination}
        compact
        striped
        stickyHeader
        ariaLabel="Directory table"
        onFilterChange={({ filters: nextFilters }) => (filters = nextFilters)}
        onPageChange={({ page }) => (pagination = { ...pagination, page })}
        onLimitChange={({ limit }) => (pagination = { ...pagination, page: 1, limit })}
      />
    </SpecimenGroup>

    <SpecimenGroup bare label="With custom cells and expanded rows">
      <DataTable
        columns={incidentColumns}
        rows={incidentRows}
        showRowActions={false}
        expandedRowIds={expandedIncidentId ? [expandedIncidentId] : []}
        ariaLabel="Active incidents"
      >
        {#snippet cell(column, row)}
          {@const incident = row.data as Incident | undefined}
          {#if column.id === "expand"}
            <button type="button" class="poodle-expand-button" onclick={() => (expandedIncidentId = expandedIncidentId === row.id ? null : row.id)}>
              {expandedIncidentId === row.id ? "Hide" : "Show"}
            </button>
          {:else if column.id === "status"}
            <Pill appearance="badge" tone={incident?.status === "open" ? "danger" : "success"}>
              {row.cells.status}
            </Pill>
          {:else}
            {row.cells[column.id]}
          {/if}
        {/snippet}
        {#snippet expandedRow(row)}
          {@const incident = row.data as Incident | undefined}
          {#if incident}
            <div class="poodle-incident-detail">
              <strong>{incident.endpoint}</strong>
              <span>Owned by {incident.owner}</span>
              <span>Updated {new Date(incident.updatedAt).toLocaleString()}</span>
            </div>
          {/if}
        {/snippet}
      </DataTable>
    </SpecimenGroup>

    <SpecimenGroup bare label="Empty state">
      <DataTable
        {columns}
        rows={[]}
        ariaLabel="Empty data table"
        emptyMessage="No team members match the current filters."
      />
    </SpecimenGroup>
  </div>

  {#snippet sizes(size)}
    <DataTable
      {columns}
      {rows}
      {size}
      ariaLabel={`Data table at ${size}`}
    />
  {/snippet}

  {#snippet densities(density)}
    <DataTable
      {columns}
      {rows}
      {density}
      ariaLabel={`Data table at ${density} density`}
    />
  {/snippet}
</SpecimenLayout>

<style>
  .poodle-specimen {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .poodle-last-action,
  .poodle-selection-count {
    margin: 0;
    font-size: 0.8125rem;
    color: var(--poodle-color-text-secondary);
  }

  .poodle-expand-button {
    border: 0;
    background: transparent;
    color: var(--poodle-color-text-secondary);
    font: inherit;
    cursor: pointer;
  }

  .poodle-incident-detail {
    display: grid;
    gap: 0.25rem;
    font-size: 0.8125rem;
    color: var(--poodle-color-text-secondary);
  }
</style>

// packages/react/preview/src/gallery/specimens/DataTableSpecimen.tsx
import { useState, type CSSProperties } from "react";
import { DataTable, Pill } from "@inflatable-cookie/poodle-react";
import type { TableColumn, TableFilters, TablePagination, TableRow } from "@inflatable-cookie/poodle-react";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

const columns: TableColumn[] = [
  { id: "name", label: "Name", sortable: true, hideable: false },
  { id: "email", label: "Email", sortable: true, hideable: true },
  { id: "role", label: "Role", sortable: true, hideable: true },
  { id: "status", label: "Status", sortable: false, hideable: true },
];

const rows: TableRow[] = [
  { id: "1", cells: { name: "Alice Chen", email: "alice@example.com", role: "Engineer", status: "Active" }, summary: "Senior frontend engineer" },
  { id: "2", cells: { name: "Bob Martinez", email: "bob@example.com", role: "Designer", status: "Active" }, summary: "UX lead" },
  { id: "3", cells: { name: "Carol Patel", email: "carol@example.com", role: "PM", status: "On leave" }, summary: "Product manager" },
  { id: "4", cells: { name: "Dan Okoro", email: "dan@example.com", role: "Engineer", status: "Active" }, summary: "Backend engineer" },
  { id: "5", cells: { name: "Eve Nakamura", email: "eve@example.com", role: "Designer", status: "Active" }, summary: "Visual designer" },
];

type Incident = {
  status: "open" | "resolved";
  endpoint: string;
  owner: string;
  updatedAt: string;
};

const incidentColumns: TableColumn[] = [
  { id: "expand", label: "", width: "3rem", align: "center", hideable: false, isRowHeader: false },
  { id: "status", label: "Status", width: "7rem" },
  { id: "endpoint", label: "Endpoint", width: "minmax(14rem, 1fr)" },
  { id: "owner", label: "Owner", width: "10rem" },
];

const incidentRows: TableRow<Incident>[] = [
  {
    id: "incident-1",
    cells: { expand: "", status: "Open", endpoint: "POST /api/orders", owner: "Alice" },
    data: { status: "open", endpoint: "POST /api/orders", owner: "Alice", updatedAt: "2026-03-27T11:18:00Z" },
  },
  {
    id: "incident-2",
    cells: { expand: "", status: "Resolved", endpoint: "GET /api/catalog", owner: "Bob" },
    data: { status: "resolved", endpoint: "GET /api/catalog", owner: "Bob", updatedAt: "2026-03-27T09:42:00Z" },
  },
];

const mutedText: CSSProperties = {
  margin: 0,
  fontSize: "0.8125rem",
  color: "var(--poodle-color-text-secondary)",
};

const expandButton: CSSProperties = {
  border: 0,
  background: "transparent",
  color: "var(--poodle-color-text-secondary)",
  font: "inherit",
  cursor: "pointer",
};

const incidentDetail: CSSProperties = {
  display: "grid",
  gap: "0.25rem",
  fontSize: "0.8125rem",
  color: "var(--poodle-color-text-secondary)",
};

export function DataTableSpecimen() {
  const [selectedRowIds, setSelectedRowIds] = useState<string[]>([]);
  const [sortColumnId, setSortColumnId] = useState<string | null>(null);
  const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc");
  const [hiddenColumnIds, setHiddenColumnIds] = useState<string[]>([]);
  const [lastAction, setLastAction] = useState("");
  const [expandedIncidentId, setExpandedIncidentId] = useState<string | null>(null);
  const [filters, setFilters] = useState<TableFilters>({ name: "", role: "" });
  const [pagination, setPagination] = useState<TablePagination>({ page: 1, limit: 10, total: 42 });

  const handleSortChange = (payload: { columnId: string; direction: "asc" | "desc" }) => {
    setSortColumnId(payload.columnId);
    setSortDirection(payload.direction);
    setLastAction(`Sorted by ${payload.columnId} ${payload.direction}`);
  };

  const handleRowToggle = (payload: { rowId: string; selected: boolean }) => {
    setSelectedRowIds((prev) =>
      payload.selected ? [...prev, payload.rowId] : prev.filter((id) => id !== payload.rowId),
    );
    setLastAction(`Toggled row ${payload.rowId}: ${payload.selected ? "selected" : "deselected"}`);
  };

  const handleToggleAll = (payload: { selected: boolean }) => {
    setSelectedRowIds(payload.selected ? rows.map((r) => r.id) : []);
    setLastAction(payload.selected ? "Selected all rows" : "Deselected all rows");
  };

  const handleRowAction = (payload: { rowId: string }) => {
    setLastAction(`Action on row ${payload.rowId}`);
  };

  const handleColumnVisibility = (payload: { columnId: string; visible: boolean }) => {
    setHiddenColumnIds((prev) =>
      payload.visible ? prev.filter((id) => id !== payload.columnId) : [...prev, payload.columnId],
    );
    setLastAction(`${payload.visible ? "Showed" : "Hid"} column: ${payload.columnId}`);
  };

  return (
    <SpecimenLayout
      sizes={(size) => <DataTable columns={columns} rows={rows} size={size} ariaLabel={`Data table at ${size}`} />}
      densities={(density) => <DataTable columns={columns} rows={rows} density={density} ariaLabel={`Data table at ${density} density`} />}
    >
      <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
        <SpecimenGroup bare label="With sorting, column visibility, and export">
          <DataTable
            columns={columns}
            rows={rows}
            selectable
            selectedRowIds={selectedRowIds}
            sortColumnId={sortColumnId}
            sortDirection={sortDirection}
            hiddenColumnIds={hiddenColumnIds}
            showColumnVisibility
            showExport
            ariaLabel="Team members"
            onSortChange={handleSortChange}
            onRowToggle={handleRowToggle}
            onToggleAll={handleToggleAll}
            onRowAction={handleRowAction}
            onColumnVisibilityChange={handleColumnVisibility}
          />
          {lastAction ? (
            <p style={mutedText}>Last action: <strong>{lastAction}</strong></p>
          ) : null}
          <p style={mutedText}>{selectedRowIds.length} of {rows.length} selected</p>
        </SpecimenGroup>

        <SpecimenGroup bare label="With filters and pagination">
          <DataTable
            columns={columns}
            rows={rows}
            filters={filters}
            pagination={pagination}
            compact
            striped
            stickyHeader
            ariaLabel="Directory table"
            onFilterChange={({ filters: nextFilters }) => setFilters(nextFilters)}
            onPageChange={({ page }) => setPagination((prev) => ({ ...prev, page }))}
            onLimitChange={({ limit }) => setPagination((prev) => ({ ...prev, page: 1, limit }))}
          />
        </SpecimenGroup>

        <SpecimenGroup bare label="With custom cells and expanded rows">
          <DataTable
            columns={incidentColumns}
            rows={incidentRows}
            showRowActions={false}
            expandedRowIds={expandedIncidentId ? [expandedIncidentId] : []}
            ariaLabel="Active incidents"
            cell={(column, row) => {
              const incident = row.data as Incident | undefined;
              if (column.id === "expand") {
                return (
                  <button
                    type="button"
                    style={expandButton}
                    onClick={() => setExpandedIncidentId((prev) => (prev === row.id ? null : row.id))}
                  >
                    {expandedIncidentId === row.id ? "Hide" : "Show"}
                  </button>
                );
              }
              if (column.id === "status") {
                return (
                  <Pill appearance="badge" tone={incident?.status === "open" ? "danger" : "success"}>
                    {row.cells.status}
                  </Pill>
                );
              }
              return row.cells[column.id];
            }}
            expandedRow={(row) => {
              const incident = row.data as Incident | undefined;
              if (!incident) {
                return null;
              }
              return (
                <div style={incidentDetail}>
                  <strong>{incident.endpoint}</strong>
                  <span>Owned by {incident.owner}</span>
                  <span>Updated {new Date(incident.updatedAt).toLocaleString()}</span>
                </div>
              );
            }}
          />
        </SpecimenGroup>

        <SpecimenGroup bare label="Empty state">
          <DataTable
            columns={columns}
            rows={[]}
            ariaLabel="Empty data table"
            emptyMessage="No team members match the current filters."
          />
        </SpecimenGroup>
      </div>
    </SpecimenLayout>
  );
}
