// packages/svelte/preview/src/specimens/EditableLabelSpecimen.svelte
<script lang="ts">
  import { EditableLabel } from "@poodle/svelte-primitives";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  let title = "My project title";
  let emptyValue = "";
  let flushValue = "Inline heading";
  let lastEvent = "";
</script>

<SpecimenLayout>
  <SpecimenGroup label="Double-click to edit (default)">
    <EditableLabel
      bind:value={title}
      ariaLabel="Project title"
      on:commit={(e) => (lastEvent = `Committed: "${e.detail.value}" (was: "${e.detail.previousValue}")`)}
      on:cancel={() => (lastEvent = "Edit cancelled")}
    />
  </SpecimenGroup>

  <SpecimenGroup label="Click to edit with icon">
    <EditableLabel
      bind:value={title}
      ariaLabel="Project title"
      activationMode="enterOrSpace"
      showEditIcon
      on:commit={(e) => (lastEvent = `Committed: "${e.detail.value}"`)}
    />
  </SpecimenGroup>

  <SpecimenGroup label="Empty state">
    <EditableLabel
      bind:value={emptyValue}
      ariaLabel="Description"
      activationMode="enterOrSpace"
      emptyText="Add a description…"
      on:commit={(e) => (lastEvent = `Committed: "${e.detail.value}"`)}
    />
  </SpecimenGroup>

  <SpecimenGroup label="Flush variant">
    <EditableLabel
      bind:value={flushValue}
      ariaLabel="Heading"
      variant="flush"
      activationMode="enterOrSpace"
      showEditIcon
    />
  </SpecimenGroup>

  <SpecimenGroup label="With max length">
    <EditableLabel
      value="Short text"
      ariaLabel="Short text"
      activationMode="enterOrSpace"
      maxLength={20}
      placeholder="Enter text…"
    />
  </SpecimenGroup>

  <SpecimenGroup label="Disabled">
    <EditableLabel
      value="Read-only value"
      ariaLabel="Read-only"
      disabled
    />
  </SpecimenGroup>

  {#if lastEvent}
    <SpecimenGroup label="Last event">
      <p>{lastEvent}</p>
    </SpecimenGroup>
  {/if}

  <svelte:fragment slot="sizes" let:size>
    <EditableLabel value={size.toUpperCase()} ariaLabel={"Label at " + size} />
  </svelte:fragment>

  <svelte:fragment slot="densities" let:density>
    <EditableLabel value="Edit me" />
  </svelte:fragment>
</SpecimenLayout>

<style>
  p { margin: 0; }
</style>

// packages/react/preview/src/gallery/specimens/EditableLabelSpecimen.tsx
import { useState } from "react";
import { EditableLabel } from "@poodle/react";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

export function EditableLabelSpecimen() {
  const [title, setTitle] = useState("My project title");
  const [emptyValue, setEmptyValue] = useState("");
  const [flushValue, setFlushValue] = useState("Inline heading");
  const [lastEvent, setLastEvent] = useState("");

  return (
    <SpecimenLayout
      sizes={(size) => <EditableLabel value={size.toUpperCase()} size={size} ariaLabel={"Label at " + size} />}
      densities={(density) => <EditableLabel value="Edit me" density={density} />}
    >
      <SpecimenGroup label="Double-click to edit (default)">
        <EditableLabel
          value={title}
          ariaLabel="Project title"
          onCommit={(detail) => {
            setTitle(detail.value);
            setLastEvent(`Committed: "${detail.value}" (was: "${detail.previousValue}")`);
          }}
          onCancel={() => setLastEvent("Edit cancelled")}
        />
      </SpecimenGroup>

      <SpecimenGroup label="Click to edit with icon">
        <EditableLabel
          value={title}
          ariaLabel="Project title"
          activationMode="enterOrSpace"
          showEditIcon
          onCommit={(detail) => {
            setTitle(detail.value);
            setLastEvent(`Committed: "${detail.value}"`);
          }}
        />
      </SpecimenGroup>

      <SpecimenGroup label="Empty state">
        <EditableLabel
          value={emptyValue}
          ariaLabel="Description"
          activationMode="enterOrSpace"
          emptyText="Add a description…"
          onCommit={(detail) => {
            setEmptyValue(detail.value);
            setLastEvent(`Committed: "${detail.value}"`);
          }}
        />
      </SpecimenGroup>

      <SpecimenGroup label="Flush variant">
        <EditableLabel
          value={flushValue}
          ariaLabel="Heading"
          variant="flush"
          activationMode="enterOrSpace"
          showEditIcon
          onCommit={(detail) => setFlushValue(detail.value)}
        />
      </SpecimenGroup>

      <SpecimenGroup label="With max length">
        <EditableLabel
          value="Short text"
          ariaLabel="Short text"
          activationMode="enterOrSpace"
          maxLength={20}
          placeholder="Enter text…"
        />
      </SpecimenGroup>

      <SpecimenGroup label="Disabled">
        <EditableLabel
          value="Read-only value"
          ariaLabel="Read-only"
          disabled
        />
      </SpecimenGroup>

      {lastEvent ? (
        <SpecimenGroup label="Last event">
          <p style={{ margin: 0 }}>{lastEvent}</p>
        </SpecimenGroup>
      ) : null}
    </SpecimenLayout>
  );
}
