// packages/svelte/preview/src/specimens/MediaPickerSpecimen.svelte
<script lang="ts">
  import { MediaPicker } from "@poodle/svelte";
  import { Button } from "@poodle/svelte";
  import type { MediaPickerItem } from "@poodle/svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  let open = $state(false);
  let selected = $state("");
  let sizeOpenMap: Record<string, boolean> = {};
  let densityOpenMap: Record<string, boolean> = {};
  let sizeSelectedMap: Record<string, string> = {};
  let densitySelectedMap: Record<string, string> = {};

  const sampleItems: MediaPickerItem[] = [
    { id: "1", label: "hero-banner.jpg", thumbnailUrl: undefined, kind: "image" },
    { id: "2", label: "logo-dark.png", thumbnailUrl: undefined, kind: "image" },
    { id: "3", label: "product-shot.jpg", thumbnailUrl: undefined, kind: "image" },
    { id: "4", label: "report-q4.pdf", thumbnailUrl: undefined, kind: "document" },
    { id: "5", label: "team-photo.jpg", thumbnailUrl: undefined, kind: "image" },
    { id: "6", label: "presentation.pdf", thumbnailUrl: undefined, kind: "document" },
  ];
</script>

<SpecimenLayout>
  <div class="poodle-specimen">
    <SpecimenGroup label="Media picker dialog">
      <Button variant="secondary" onClick={() => (open = true)}>Select media</Button>
      <MediaPicker
        {open}
        items={sampleItems}
        title="Select an asset"
        onSelect={(item) => { selected = item.label; open = false; }}
        onOpenChange={(nextOpen) => (open = nextOpen)}
      />
      {#if selected}
        <p>Selected: <strong>{selected}</strong></p>
      {/if}
    </SpecimenGroup>
  </div>

  {#snippet sizes(size)}
    <div class="poodle-media-picker-specimen__variant">
      <p class="poodle-media-picker-specimen__label">{size.toUpperCase()}</p>
      <Button variant="secondary" size={size} onClick={() => (sizeOpenMap[size] = true)}>
        Open {size.toUpperCase()} picker
      </Button>
      <MediaPicker
        open={sizeOpenMap[size] ?? false}
        items={sampleItems}
        title={`${size.toUpperCase()} asset picker`}
        {size}
        onSelect={(item) => {
          sizeSelectedMap[size] = item.label;
          sizeOpenMap[size] = false;
        }}
        onOpenChange={(nextOpen) => (sizeOpenMap[size] = nextOpen)}
      />
      {#if sizeSelectedMap[size]}
        <p>Selected: <strong>{sizeSelectedMap[size]}</strong></p>
      {/if}
    </div>
  {/snippet}

  {#snippet densities(density)}
    <div class="poodle-media-picker-specimen__variant">
      <p class="poodle-media-picker-specimen__label">{density}</p>
      <Button variant="secondary" onClick={() => (densityOpenMap[density] = true)}>
        Open {density} picker
      </Button>
      <MediaPicker
        open={densityOpenMap[density] ?? false}
        items={sampleItems}
        title={`${density} asset picker`}
        {density}
        onSelect={(item) => {
          densitySelectedMap[density] = item.label;
          densityOpenMap[density] = false;
        }}
        onOpenChange={(nextOpen) => (densityOpenMap[density] = nextOpen)}
      />
      {#if densitySelectedMap[density]}
        <p>Selected: <strong>{densitySelectedMap[density]}</strong></p>
      {/if}
    </div>
  {/snippet}
</SpecimenLayout>

<style>
  .poodle-specimen {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .poodle-media-picker-specimen__variant {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }

  .poodle-media-picker-specimen__label {
    margin: 0;
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-label-family);
    font-size: var(--poodle-typography-label-size);
    font-weight: var(--poodle-typography-label-weight);
    letter-spacing: 0.08em;
    text-transform: uppercase;
  }

  p { margin: 0; }
</style>

// packages/react/preview/src/gallery/specimens/MediaPickerSpecimen.tsx
import { useState, type CSSProperties } from "react";
import { Button, MediaPicker } from "@poodle/react";
import type { MediaPickerItem } from "@poodle/react";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

const sampleItems: MediaPickerItem[] = [
  { id: "1", label: "hero-banner.jpg", kind: "image" },
  { id: "2", label: "logo-dark.png", kind: "image" },
  { id: "3", label: "product-shot.jpg", kind: "image" },
  { id: "4", label: "report-q4.pdf", kind: "document" },
  { id: "5", label: "team-photo.jpg", kind: "image" },
  { id: "6", label: "presentation.pdf", kind: "document" },
];

const variantStyle: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  alignItems: "flex-start",
  gap: "0.5rem",
};

const labelStyle: CSSProperties = {
  margin: 0,
  color: "var(--poodle-color-text-secondary)",
  fontFamily: "var(--poodle-typography-label-family)",
  fontSize: "var(--poodle-typography-label-size)",
  fontWeight: "var(--poodle-typography-label-weight)",
  letterSpacing: "0.08em",
  textTransform: "uppercase",
};

export function MediaPickerSpecimen() {
  const [open, setOpen] = useState(false);
  const [selected, setSelected] = useState("");
  const [sizeOpenMap, setSizeOpenMap] = useState<Record<string, boolean>>({});
  const [densityOpenMap, setDensityOpenMap] = useState<Record<string, boolean>>({});
  const [sizeSelectedMap, setSizeSelectedMap] = useState<Record<string, string>>({});
  const [densitySelectedMap, setDensitySelectedMap] = useState<Record<string, string>>({});

  return (
    <SpecimenLayout
      sizes={(size) => (
        <div style={variantStyle}>
          <p style={labelStyle}>{size.toUpperCase()}</p>
          <Button variant="secondary" size={size} onClick={() => setSizeOpenMap((m) => ({ ...m, [size]: true }))}>
            Open {size.toUpperCase()} picker
          </Button>
          <MediaPicker
            open={sizeOpenMap[size] ?? false}
            items={sampleItems}
            title={`${size.toUpperCase()} asset picker`}
            size={size}
            onSelect={(item) => {
              setSizeSelectedMap((m) => ({ ...m, [size]: item.label }));
              setSizeOpenMap((m) => ({ ...m, [size]: false }));
            }}
            onOpenChange={(nextOpen) => setSizeOpenMap((m) => ({ ...m, [size]: nextOpen }))}
          />
          {sizeSelectedMap[size] ? (
            <p style={{ margin: 0 }}>
              Selected: <strong>{sizeSelectedMap[size]}</strong>
            </p>
          ) : null}
        </div>
      )}
      densities={(density) => (
        <div style={variantStyle}>
          <p style={labelStyle}>{density}</p>
          <Button variant="secondary" onClick={() => setDensityOpenMap((m) => ({ ...m, [density]: true }))}>
            Open {density} picker
          </Button>
          <MediaPicker
            open={densityOpenMap[density] ?? false}
            items={sampleItems}
            title={`${density} asset picker`}
            density={density}
            onSelect={(item) => {
              setDensitySelectedMap((m) => ({ ...m, [density]: item.label }));
              setDensityOpenMap((m) => ({ ...m, [density]: false }));
            }}
            onOpenChange={(nextOpen) => setDensityOpenMap((m) => ({ ...m, [density]: nextOpen }))}
          />
          {densitySelectedMap[density] ? (
            <p style={{ margin: 0 }}>
              Selected: <strong>{densitySelectedMap[density]}</strong>
            </p>
          ) : null}
        </div>
      )}
    >
      <div className="poodle-specimen">
        <SpecimenGroup label="Media picker dialog">
          <Button variant="secondary" onClick={() => setOpen(true)}>
            Select media
          </Button>
          <MediaPicker
            open={open}
            items={sampleItems}
            title="Select an asset"
            onSelect={(item) => {
              setSelected(item.label);
              setOpen(false);
            }}
            onOpenChange={(nextOpen) => setOpen(nextOpen)}
          />
          {selected ? (
            <p style={{ margin: 0 }}>
              Selected: <strong>{selected}</strong>
            </p>
          ) : null}
        </SpecimenGroup>
      </div>
    </SpecimenLayout>
  );
}
