// packages/svelte/preview/src/specimens/OrderBySpecimen.svelte
<script lang="ts">
  import { OrderBy, type OrderByValue, type SortField } from "@inflatable-cookie/poodle-svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";

  let value = $state<OrderByValue>([
    { key: "updatedAt", direction: "desc" },
    { key: "title", direction: "asc" },
  ]);

  let sizeValue = $state<OrderByValue>([{ key: "title", direction: "asc" }]);
  let densityValue = $state<OrderByValue>([{ key: "title", direction: "asc" }]);
  let iconValue = $state<OrderByValue>([
    { key: "updatedAt", direction: "desc" },
    { key: "title", direction: "asc" },
  ]);

  const fields: SortField[] = [
    { key: "title", label: "Title" },
    { key: "kind", label: "Kind" },
    { key: "updatedAt", label: "Updated", defaultDirection: "desc" },
    { key: "createdAt", label: "Created", defaultDirection: "desc" },
    { key: "visibility", label: "Visibility", disabled: true },
  ];
</script>

<SpecimenLayout>
  <SpecimenGroup label="Multi-field sort builder">
    <OrderBy {fields} bind:value compact />
    <pre>{JSON.stringify(value, null, 2)}</pre>
  </SpecimenGroup>

  <SpecimenGroup label="Disabled">
    <OrderBy {fields} value={[{ key: "title", direction: "asc" }]} disabled />
  </SpecimenGroup>

  <SpecimenGroup label="Icon trigger">
    <OrderBy {fields} bind:value={iconValue} triggerVariant="icon" />
  </SpecimenGroup>

  {#snippet sizes(size)}
    <OrderBy {fields} {size} bind:value={sizeValue} />
  {/snippet}

  {#snippet densities(density)}
    <OrderBy {fields} {density} bind:value={densityValue} />
  {/snippet}
</SpecimenLayout>

<style>
  pre { margin: 0; font-size: 0.75rem; }
</style>

// packages/react/preview/src/gallery/specimens/OrderBySpecimen.tsx
import { useState } from "react";
import { OrderBy, type OrderByValue, type SortField } from "@inflatable-cookie/poodle-react";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";

const fields: SortField[] = [
  { key: "title", label: "Title" },
  { key: "kind", label: "Kind" },
  { key: "updatedAt", label: "Updated", defaultDirection: "desc" },
  { key: "createdAt", label: "Created", defaultDirection: "desc" },
  { key: "visibility", label: "Visibility", disabled: true },
];

export function OrderBySpecimen() {
  const [value, setValue] = useState<OrderByValue>([
    { key: "updatedAt", direction: "desc" },
    { key: "title", direction: "asc" },
  ]);
  const [sizeValue, setSizeValue] = useState<OrderByValue>([{ key: "title", direction: "asc" }]);
  const [densityValue, setDensityValue] = useState<OrderByValue>([{ key: "title", direction: "asc" }]);
  const [iconValue, setIconValue] = useState<OrderByValue>([
    { key: "updatedAt", direction: "desc" },
    { key: "title", direction: "asc" },
  ]);

  return (
    <SpecimenLayout
      sizes={(size) => <OrderBy fields={fields} size={size} value={sizeValue} onChange={setSizeValue} />}
      densities={(density) => (
        <OrderBy fields={fields} density={density} value={densityValue} onChange={setDensityValue} />
      )}
    >
      <SpecimenGroup label="Multi-field sort builder">
        <OrderBy fields={fields} value={value} onChange={setValue} compact />
        <pre style={{ margin: 0, fontSize: "0.75rem" }}>{JSON.stringify(value, null, 2)}</pre>
      </SpecimenGroup>

      <SpecimenGroup label="Disabled">
        <OrderBy fields={fields} value={[{ key: "title", direction: "asc" }]} disabled />
      </SpecimenGroup>

      <SpecimenGroup label="Icon trigger">
        <OrderBy fields={fields} value={iconValue} onChange={setIconValue} triggerVariant="icon" />
      </SpecimenGroup>
    </SpecimenLayout>
  );
}
