// packages/svelte/preview/src/specimens/SpacerSpecimen.svelte
<script lang="ts">
  import { Spacer, Stack, Surface } from "@poodle/svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
</script>

<div class="specimen">
  <SpecimenGroup label="Push items apart">
    <Stack direction="row" gap="md">
      <Surface padding="sm" border="subtle"><span>Logo</span></Surface>
      <Spacer />
      <Surface padding="sm" border="subtle"><span>Sign in</span></Surface>
    </Stack>
  </SpecimenGroup>

  <SpecimenGroup label="Between three items">
    <Stack direction="row" gap="md">
      <Surface padding="sm" border="subtle"><span>Left</span></Surface>
      <Spacer />
      <Surface padding="sm" border="subtle"><span>Center</span></Surface>
      <Spacer />
      <Surface padding="sm" border="subtle"><span>Right</span></Surface>
    </Stack>
  </SpecimenGroup>
</div>

<style>
  .specimen {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  span {
    font-size: 0.875rem;
    white-space: nowrap;
  }
</style>

// packages/react/preview/src/gallery/specimens/SpacerSpecimen.tsx
import type { CSSProperties } from "react";
import { Spacer, Stack, Surface } from "@poodle/react";
import { SpecimenGroup } from "../SpecimenGroup";

const spanStyle: CSSProperties = { fontSize: "0.875rem", whiteSpace: "nowrap" };

export function SpacerSpecimen() {
  return (
    <div className="poodle-specimen">
      <SpecimenGroup label="Push items apart">
        <Stack direction="row" gap="md">
          <Surface padding="sm" border="subtle">
            <span style={spanStyle}>Logo</span>
          </Surface>
          <Spacer />
          <Surface padding="sm" border="subtle">
            <span style={spanStyle}>Sign in</span>
          </Surface>
        </Stack>
      </SpecimenGroup>

      <SpecimenGroup label="Between three items">
        <Stack direction="row" gap="md">
          <Surface padding="sm" border="subtle">
            <span style={spanStyle}>Left</span>
          </Surface>
          <Spacer />
          <Surface padding="sm" border="subtle">
            <span style={spanStyle}>Center</span>
          </Surface>
          <Spacer />
          <Surface padding="sm" border="subtle">
            <span style={spanStyle}>Right</span>
          </Surface>
        </Stack>
      </SpecimenGroup>
    </div>
  );
}
