// packages/svelte/preview/src/specimens/ValueReadoutSpecimen.svelte
<script lang="ts">
  import { ValueReadout } from "@inflatable-cookie/poodle-svelte";
  import SpecimenGroup from "../components/SpecimenGroup.svelte";
  import SpecimenLayout from "../components/SpecimenLayout.svelte";
  const examples = [
    ["Number", 12.345, { type: "number", decimals: 2 }],
    ["dB", -12.4, { type: "db", decimals: 1 }],
    ["Hz / kHz", 12_500, { type: "hz", decimals: 2 }],
    ["Percent", 0.625, { type: "percent", decimals: 1 }],
    ["Ratio", 4, { type: "ratio", decimals: 2 }],
    ["Milliseconds", 1250, { type: "milliseconds", decimals: 2 }],
    ["Note name", 60, { type: "note" }],
    ["Semitones", -7, { type: "semitones", decimals: 1 }],
  ] as const;
</script>
<SpecimenLayout variantDirection="row"><div class="page">
  {#each examples as [label, value, format]}
    <SpecimenGroup label={label}><ValueReadout {value} min={-20_000} max={20_000} {format} ariaLabel={label} /></SpecimenGroup>
  {/each}
  <SpecimenGroup label="Negative / boundary / disabled"><div class="row"><ValueReadout value={-1} min={-1} max={1} /><ValueReadout value={1} min={-1} max={1} /><ValueReadout value={0} disabled ariaLabel="Disabled readout" /></div></SpecimenGroup>
</div>
  {#snippet sizes(size)}<ValueReadout value={-12.4} format={{ type: "db" }} {size} ariaLabel={`Readout ${size} size`} />{/snippet}
  {#snippet densities(density)}<ValueReadout value={-12.4} format={{ type: "db" }} {density} ariaLabel={`Readout ${density} density`} />{/snippet}
</SpecimenLayout>
<style>.page { display: grid; gap: 1rem; }
.row { display: flex; gap: .75rem; flex-wrap: wrap; }</style>

// packages/react/preview/src/gallery/specimens/ValueReadoutSpecimen.tsx
import { ValueReadout } from "@inflatable-cookie/poodle-react";
import { AudioSpecimenRow as Row } from "./AudioSpecimen";
import { SpecimenGroup } from "../SpecimenGroup";
import { SpecimenLayout } from "../SpecimenLayout";
export function ValueReadoutSpecimen() { return (
    <SpecimenLayout
      variantDirection="row"
      sizes={(size) => <ValueReadout value={-12.4} format={{ type: "db" }} size={size} ariaLabel={`Readout ${size} size`} />}
      densities={(density) => <ValueReadout value={-12.4} format={{ type: "db" }} density={density} ariaLabel={`Readout ${density} density`} />}
    >
      <div style={{ display: "grid", gap: "1.5rem" }}>
        <SpecimenGroup label="Number"><ValueReadout value={12.345} min={-20_000} max={20_000} format={{ type: "number", decimals: 2 }} ariaLabel="Number" /></SpecimenGroup>
  <SpecimenGroup label="dB"><ValueReadout value={-12.4} min={-60} max={6} format={{ type: "db" }} ariaLabel="Gain" /></SpecimenGroup>
  <SpecimenGroup label="Hz / kHz"><ValueReadout value={12_500} min={20} max={20_000} format={{ type: "hz" }} ariaLabel="Frequency" /></SpecimenGroup>
  <SpecimenGroup label="Percent"><ValueReadout value={0.625} format={{ type: "percent" }} ariaLabel="Mix" /></SpecimenGroup>
  <SpecimenGroup label="Ratio"><ValueReadout value={4} min={1} max={20} format={{ type: "ratio" }} ariaLabel="Ratio" /></SpecimenGroup>
  <SpecimenGroup label="Milliseconds"><ValueReadout value={1250} min={0} max={5000} format={{ type: "milliseconds" }} ariaLabel="Time" /></SpecimenGroup>
  <SpecimenGroup label="Note name"><ValueReadout value={60} min={0} max={127} format={{ type: "note" }} ariaLabel="Note" /></SpecimenGroup>
  <SpecimenGroup label="Semitones"><ValueReadout value={-7} min={-24} max={24} format={{ type: "semitones" }} ariaLabel="Transpose" /></SpecimenGroup>
  <SpecimenGroup label="Negative / boundary / disabled"><Row><ValueReadout value={-1} min={-1} max={1} /><ValueReadout value={1} min={-1} max={1} /><ValueReadout value={0} disabled ariaLabel="Disabled readout" /></Row></SpecimenGroup>
      </div>
    </SpecimenLayout>
  ); }
