// packages/react/components/src/DockRegion.tsx
import "@poodle/styles/dock-region.css";

import { useEffect, useRef, useState, type DragEvent as ReactDragEvent, type ReactNode } from "react";

import { CollapseToggle } from "./CollapseToggle";
import { Tabs } from "./Tabs";
import type {
  ControlDensity,
  ControlSize,
  DockCollapsedPosture,
  DockEdge,
  DockEmphasis,
  DockSizing,
  PanelDragData,
  PanelTabItem,
  SemanticControlSizeRole,
  TabItem,
  TabVariant,
} from "./types";

export interface DockRegionProps {
  edge?: DockEdge;
  sizing?: DockSizing;
  collapsible?: boolean;
  collapsed?: boolean;
  collapsedPosture?: DockCollapsedPosture;
  emphasis?: DockEmphasis;
  size?: ControlSize | null;
  sizeRole?: SemanticControlSizeRole;
  density?: ControlDensity | null;
  tabVariant?: TabVariant;
  items?: PanelTabItem[];
  value?: string | null;
  ariaLabel?: string | null;
  canAcceptPanel?: ((panelId: string, sourceEdge: DockEdge) => boolean) | null;
  onValueChange?: ((value: string) => void) | undefined;
  onCollapsedChange?: ((isCollapsed: boolean) => void) | undefined;
  onClose?: ((value: string) => void) | undefined;
  onReorder?: ((items: string[]) => void) | undefined;
  onPanelDrop?: ((payload: { panel: PanelDragData; targetEdge: DockEdge }) => void) | undefined;
  panel?: (item: PanelTabItem) => ReactNode;
  children?: (item: PanelTabItem | null) => ReactNode;
}

const PANEL_DRAG_TYPE = "application/x-poodle-panel-drag";

export function DockRegion({
  edge = "left",
  sizing = "flexible",
  collapsible = false,
  collapsed = false,
  collapsedPosture = "icon-strip",
  emphasis = "standard",
  size = null,
  sizeRole = "chrome",
  density = null,
  tabVariant = "strip",
  items = [],
  value = null,
  ariaLabel = null,
  canAcceptPanel = null,
  onValueChange = undefined,
  onCollapsedChange = undefined,
  onClose = undefined,
  onReorder = undefined,
  onPanelDrop = undefined,
  panel,
  children,
}: DockRegionProps) {
  const isVerticalEdge = edge === "left" || edge === "right";
  const activeItem = items.find((item) => item.value === value) ?? items[0] ?? null;
  const collapseDirection = ({ left: "left", right: "right", top: "up", bottom: "down" } as const)[edge];
  const tabItems: TabItem[] = items.map((item) => ({
    value: item.value,
    label: item.label,
    icon: item.icon ?? undefined,
    closable: item.closable,
  }));
  const stackDirection = isVerticalEdge ? "column" : "row";
  const showIconStrip = collapsed && collapsedPosture === "icon-strip";
  const showHidden = collapsed && collapsedPosture === "hidden";

  const stripTabsRef = useRef<HTMLDivElement | null>(null);
  const fullLabelScrollWidth = useRef(0);
  const [isCompact, setIsCompact] = useState(false);

  const isCompactRef = useRef(isCompact);
  isCompactRef.current = isCompact;
  const itemsLengthRef = useRef(items.length);
  itemsLengthRef.current = items.length;

  // Compact detection: observe the strip and its tablist; keep the natural
  // (uncompacted) label width so expansion re-checks against it.
  useEffect(() => {
    const el = stripTabsRef.current;
    if (!el) return;

    function checkCompact(): void {
      const target = stripTabsRef.current;
      if (!target || itemsLengthRef.current === 0) {
        setIsCompact(false);
        return;
      }
      const list = target.querySelector("[role='tablist']") as HTMLElement | null;
      if (!list) return;

      const containerWidth = target.clientWidth;

      if (!isCompactRef.current) {
        fullLabelScrollWidth.current = list.scrollWidth;
        setIsCompact(list.scrollWidth > containerWidth + 2);
        return;
      }

      setIsCompact(fullLabelScrollWidth.current > containerWidth);
    }

    const resizeObserver = new ResizeObserver(checkCompact);
    resizeObserver.observe(el);
    const list = el.querySelector("[role='tablist']");
    if (list) resizeObserver.observe(list);
    checkCompact();

    return () => resizeObserver.disconnect();
  }, [showIconStrip, showHidden, sizing, items.length]);

  const [isDragOver, setIsDragOver] = useState(false);
  const [dropInsertIndex, setDropInsertIndex] = useState(-1);
  const dragSourceIndex = useRef(-1);
  const [dragSourceState, setDragSourceState] = useState(-1);

  function handleValueChange(nextValue: string): void {
    onValueChange?.(nextValue);
    if (collapsed) {
      onCollapsedChange?.(false);
    }
  }

  function handleCollapseToggle(): void {
    onCollapsedChange?.(!collapsed);
  }

  function handleStripDragStart(event: ReactDragEvent): void {
    if (!event.dataTransfer) return;

    const target = event.target as HTMLElement;
    const tab = target.querySelector?.("[role='tab']") ?? target.closest?.("[role='tab']");
    if (!tab) return;

    const tabId = tab.getAttribute("id") ?? "";
    const item = items.find((entry) => tabId.endsWith(`-${entry.value}`));
    if (!item) return;

    const data: PanelDragData = { panelId: item.value, sourceEdge: edge };
    event.dataTransfer.setData(PANEL_DRAG_TYPE, JSON.stringify(data));
  }

  function handleRegionDragOver(event: ReactDragEvent): void {
    if (!event.dataTransfer?.types.includes(PANEL_DRAG_TYPE)) return;
    event.preventDefault();
    setIsDragOver(true);
    event.dataTransfer.dropEffect = "move";
  }

  function handleRegionDragLeave(event: ReactDragEvent): void {
    const current = event.currentTarget as HTMLElement;
    const related = event.relatedTarget as Node | null;
    if (related && current.contains(related)) return;
    setIsDragOver(false);
  }

  function handleRegionDrop(event: ReactDragEvent): void {
    event.preventDefault();
    setIsDragOver(false);

    const raw = event.dataTransfer?.getData(PANEL_DRAG_TYPE);
    if (!raw) return;

    let data: PanelDragData;
    try {
      data = JSON.parse(raw);
    } catch {
      return;
    }

    if (data.sourceEdge === edge && sizing === "flexible") return;
    if (canAcceptPanel && !canAcceptPanel(data.panelId, data.sourceEdge)) return;

    onPanelDrop?.({ panel: data, targetEdge: edge });
  }

  function handleStackItemDragStart(event: ReactDragEvent, index: number): void {
    if (!event.dataTransfer) return;
    dragSourceIndex.current = index;
    setDragSourceState(index);
    const data: PanelDragData = { panelId: items[index].value, sourceEdge: edge };
    event.dataTransfer.setData(PANEL_DRAG_TYPE, JSON.stringify(data));
    event.dataTransfer.effectAllowed = "move";
  }

  function handleStackItemDragOver(event: ReactDragEvent, index: number): void {
    if (!event.dataTransfer?.types.includes(PANEL_DRAG_TYPE)) return;
    event.preventDefault();
    setDropInsertIndex(index);
    event.dataTransfer.dropEffect = "move";
  }

  function handleStackItemDrop(event: ReactDragEvent, index: number): void {
    event.preventDefault();
    event.stopPropagation();
    setIsDragOver(false);
    setDropInsertIndex(-1);

    const raw = event.dataTransfer?.getData(PANEL_DRAG_TYPE);
    if (!raw) return;

    let data: PanelDragData;
    try {
      data = JSON.parse(raw);
    } catch {
      return;
    }

    if (data.sourceEdge === edge && dragSourceIndex.current >= 0) {
      const order = items.map((item) => item.value);
      const [moved] = order.splice(dragSourceIndex.current, 1);
      order.splice(index, 0, moved);
      dragSourceIndex.current = -1;
      setDragSourceState(-1);
      onReorder?.(order);
      return;
    }

    if (canAcceptPanel && !canAcceptPanel(data.panelId, data.sourceEdge)) return;
    onPanelDrop?.({ panel: data, targetEdge: edge });
  }

  function handleStackDragEnd(): void {
    setIsDragOver(false);
    dragSourceIndex.current = -1;
    setDragSourceState(-1);
    setDropInsertIndex(-1);
  }

  const stripTabs = (orientation: "horizontal" | "vertical", withTooltips: boolean) => (
    <Tabs
      variant={tabVariant}
      orientation={orientation}
      size={size}
      sizeRole={sizeRole}
      density={density}
      showTooltips={withTooltips}
      items={tabItems}
      value={activeItem?.value ?? ""}
      reorderable={true}
      ariaLabel={ariaLabel ?? `${edge} dock panels`}
      onValueChange={handleValueChange}
      onReorder={(next) => onReorder?.(next)}
      onClose={(next) => onClose?.(next)}
    />
  );

  return (
    <section
      className="poodle-dock-region"
      data-edge={edge}
      data-sizing={sizing}
      data-emphasis={emphasis}
      data-collapsed={collapsed || undefined}
      data-collapsed-posture={collapsed ? collapsedPosture : undefined}
      aria-label={ariaLabel ?? `${edge} dock`}
      onDragOver={handleRegionDragOver}
      onDragLeave={handleRegionDragLeave}
      onDrop={handleRegionDrop}
    >
      {isDragOver ? <div className="poodle-dock-region__drop-zone" /> : null}

      {sizing === "static" ? (
        <div className="poodle-dock-region__stack" data-direction={stackDirection}>
          {items.map((item, index) => (
            <div
              key={item.value}
              className="poodle-dock-region__stack-item"
              data-drop-target={dropInsertIndex === index || undefined}
              data-drag-source={dragSourceState === index || undefined}
              draggable="true"
              role="group"
              aria-label={item.label ?? `Panel ${index + 1}`}
              onDragStart={(event) => handleStackItemDragStart(event, index)}
              onDragOver={(event) => handleStackItemDragOver(event, index)}
              onDragLeave={() => setDropInsertIndex(-1)}
              onDrop={(event) => handleStackItemDrop(event, index)}
              onDragEnd={handleStackDragEnd}
            >
              {panel?.(item)}
            </div>
          ))}
        </div>
      ) : showHidden ? (
        collapsible ? (
          <div className="poodle-dock-region__edge-toggle">
            <CollapseToggle
              collapsed={collapsed}
              direction={collapseDirection}
              ariaLabel={`Expand ${edge} dock`}
              onToggle={handleCollapseToggle}
            />
          </div>
        ) : null
      ) : showIconStrip && isVerticalEdge ? (
        <div className="poodle-dock-region__strip" data-orientation="vertical">
          {collapsible ? (
            <CollapseToggle
              collapsed={collapsed}
              direction={collapseDirection}
              ariaLabel={`Expand ${edge} dock`}
              onToggle={handleCollapseToggle}
            />
          ) : null}
          {stripTabs("vertical", false)}
        </div>
      ) : showIconStrip ? (
        <div
          className="poodle-dock-region__strip"
          data-orientation="horizontal"
          data-compact={isCompact || undefined}
          onDragStart={handleStripDragStart}
        >
          <div className="poodle-dock-region__tabs" ref={stripTabsRef}>
            {stripTabs("horizontal", isCompact)}
          </div>
          {collapsible ? (
            <CollapseToggle
              collapsed={collapsed}
              direction={collapseDirection}
              ariaLabel={`Expand ${edge} dock`}
              onToggle={handleCollapseToggle}
            />
          ) : null}
        </div>
      ) : (
        <>
          <div
            className="poodle-dock-region__strip"
            data-orientation="horizontal"
            data-compact={isCompact || undefined}
            onDragStart={handleStripDragStart}
          >
            <div className="poodle-dock-region__tabs" ref={stripTabsRef}>
              {stripTabs("horizontal", isCompact)}
            </div>
            {collapsible ? (
              <CollapseToggle
                collapsed={collapsed}
                direction={collapseDirection}
                ariaLabel={`Collapse ${edge} dock`}
                onToggle={handleCollapseToggle}
              />
            ) : null}
          </div>

          <div className="poodle-dock-region__body">{children?.(activeItem)}</div>
        </>
      )}
    </section>
  );
}

// packages/svelte/composites/src/DockRegion.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, tick } from "svelte";

  import { CollapseToggle, Tabs } from "@poodle/svelte-primitives";
  import type { TabItem } from "@poodle/svelte-primitives";
  import type {
    ControlDensity,
    ControlSize,
    SemanticControlSizeRole,
  } from "@poodle/svelte-primitives";

  import type {
    DockEdge,
    DockEmphasis,
    DockCollapsedPosture,
    DockSizing,
    PanelDragData,
    PanelTabItem,
  } from "./types";

  export let edge: DockEdge = "left";
  export let sizing: DockSizing = "flexible";
  export let collapsible = false;
  export let collapsed = false;
  export let collapsedPosture: DockCollapsedPosture = "icon-strip";
  export let emphasis: DockEmphasis = "standard";
  export let size: ControlSize | null = null;
  export let sizeRole: SemanticControlSizeRole = "chrome";
  export let density: ControlDensity | null = null;
  export let items: PanelTabItem[] = [];
  export let value: string | null = null;
  export let ariaLabel: string | null = null;
  export let canAcceptPanel: ((panelId: string, sourceEdge: DockEdge) => boolean) | null = null;

  const PANEL_DRAG_TYPE = "application/x-poodle-panel-drag";

  const dispatch = createEventDispatcher<{
    valueChange: { value: string };
    collapsedChange: { isCollapsed: boolean };
    close: { value: string };
    reorder: { items: string[] };
    panelDrop: { panel: PanelDragData; targetEdge: DockEdge };
  }>();

  // ── Derived state ──────────────────────────────────────────────────

  $: activeItem = items.find((item) => item.value === value) ?? items[0] ?? null;

  $: collapseDirection = (
    { left: "left", right: "right", top: "up", bottom: "down" } as const
  )[edge];

  $: tabOrientation =
    collapsed && collapsedPosture === "icon-strip" && isVerticalEdge ? "vertical" : "horizontal";

  $: tabItems = items.map<TabItem>((item) => ({
    value: item.value,
    label: item.label,
    icon: item.icon ?? undefined,
    closable: item.closable,
  }));

  $: isVerticalEdge = edge === "left" || edge === "right";
  $: stackDirection = isVerticalEdge ? "column" : "row";
  $: showIconStrip = collapsed && collapsedPosture === "icon-strip";
  $: showHidden = collapsed && collapsedPosture === "hidden";

  // ── Compact mode (auto-collapse labels when too narrow) ─────────────

  let stripEl: HTMLElement | null = null;
  let isCompact = false;
  let resizeObserver: ResizeObserver | null = null;
  let fullLabelScrollWidth = 0;

  function checkCompact(el: HTMLElement): void {
    if (!el || items.length === 0) {
      isCompact = false;
      return;
    }
    const list = el.querySelector("[role='tablist']") as HTMLElement | null;
    if (!list) return;

    const containerWidth = el.clientWidth;

    if (!isCompact) {
      // Currently showing full labels — cache their natural width
      fullLabelScrollWidth = list.scrollWidth;
      const shouldCompact = list.scrollWidth > containerWidth + 2;
      isCompact = shouldCompact;
    } else {
      // Currently compact — only un-compact if container is wide enough for full labels
      // No buffer needed — if fullLabelScrollWidth fits, show full labels
      isCompact = fullLabelScrollWidth > containerWidth;
    }
  }

  function observeStrip(el: HTMLElement) {
    stripEl = el;
    resizeObserver?.disconnect();

    const check = () => checkCompact(el);

    resizeObserver = new ResizeObserver(check);
    resizeObserver.observe(el);

    // Also observe the tab list itself — its scrollWidth changes when items render
    tick().then(() => {
      const list = el.querySelector("[role='tablist']");
      if (list) resizeObserver?.observe(list);
      check();
    });

    return {
      destroy() {
        resizeObserver?.disconnect();
        resizeObserver = null;
      },
    };
  }

  onDestroy(() => resizeObserver?.disconnect());

  // ── Drag-and-drop state ────────────────────────────────────────────

  let isDragOver = false;
  let dropInsertIndex = -1;
  let dragSourceIndex = -1;

  // ── Flexible mode: tab event handlers ──────────────────────────────

  function handleValueChange(event: CustomEvent<{ value: string }>): void {
    dispatch("valueChange", event.detail);
    if (collapsed) {
      dispatch("collapsedChange", { isCollapsed: false });
    }
  }

  function handleReorder(event: CustomEvent<{ items: string[] }>): void {
    dispatch("reorder", event.detail);
  }

  function handleClose(event: CustomEvent<{ value: string }>): void {
    dispatch("close", event.detail);
  }

  function handleCollapseToggle(): void {
    dispatch("collapsedChange", { isCollapsed: !collapsed });

    if (!collapsed) {
      // Collapsing — focus will move to collapse toggle via DOM
      void tick();
    }
  }

  // ── Cross-region drag-and-drop (flexible + static) ─────────────────

  function handleStripDragStart(event: DragEvent): void {
    if (!event.dataTransfer) return;

    // Find which tab is being dragged by examining the event target
    // event.target is the .poodle-tabs__item div (draggable element)
    // The tab button (with id="poodle-tab-{tabsId}-{item.value}") is a child
    const target = event.target as HTMLElement;
    const tab = target.querySelector?.("[role='tab']") ?? target.closest?.("[role='tab']");
    if (!tab) return;

    const tabId = tab.getAttribute("id") ?? "";
    const item = items.find((i) => tabId.endsWith(`-${i.value}`));
    if (!item) return;

    const data: PanelDragData = { panelId: item.value, sourceEdge: edge };
    event.dataTransfer.setData(PANEL_DRAG_TYPE, JSON.stringify(data));
  }

  function handleRegionDragOver(event: DragEvent): void {
    if (!event.dataTransfer?.types.includes(PANEL_DRAG_TYPE)) return;
    event.preventDefault();
    isDragOver = true;
    event.dataTransfer.dropEffect = "move";
  }

  function handleRegionDragLeave(event: DragEvent): void {
    const current = event.currentTarget as HTMLElement;
    const related = event.relatedTarget as Node | null;
    if (related && current.contains(related)) return;
    isDragOver = false;
  }

  function handleRegionDrop(event: DragEvent): void {
    event.preventDefault();
    isDragOver = false;

    const raw = event.dataTransfer?.getData(PANEL_DRAG_TYPE);
    if (!raw) return;

    let data: PanelDragData;
    try {
      data = JSON.parse(raw);
    } catch {
      return;
    }

    if (data.sourceEdge === edge && sizing === "flexible") return;

    if (canAcceptPanel && !canAcceptPanel(data.panelId, data.sourceEdge)) return;

    dispatch("panelDrop", { panel: data, targetEdge: edge });
  }

  // ── Static mode: internal reorder drag-and-drop ────────────────────

  function handleStackItemDragStart(event: DragEvent, index: number): void {
    if (!event.dataTransfer) return;
    dragSourceIndex = index;
    const data: PanelDragData = { panelId: items[index].value, sourceEdge: edge };
    event.dataTransfer.setData(PANEL_DRAG_TYPE, JSON.stringify(data));
    event.dataTransfer.effectAllowed = "move";
  }

  function handleStackItemDragOver(event: DragEvent, index: number): void {
    if (!event.dataTransfer?.types.includes(PANEL_DRAG_TYPE)) return;
    event.preventDefault();
    dropInsertIndex = index;
    event.dataTransfer.dropEffect = "move";
  }

  function handleStackItemDragLeave(): void {
    dropInsertIndex = -1;
  }

  function handleStackItemDrop(event: DragEvent, index: number): void {
    event.preventDefault();
    event.stopPropagation();
    isDragOver = false;
    dropInsertIndex = -1;

    const raw = event.dataTransfer?.getData(PANEL_DRAG_TYPE);
    if (!raw) return;

    let data: PanelDragData;
    try {
      data = JSON.parse(raw);
    } catch {
      return;
    }

    // Internal reorder within static region
    if (data.sourceEdge === edge && dragSourceIndex >= 0) {
      const order = items.map((i) => i.value);
      const [moved] = order.splice(dragSourceIndex, 1);
      order.splice(index, 0, moved);
      dragSourceIndex = -1;
      dispatch("reorder", { items: order });
      return;
    }

    // Cross-region drop
    if (canAcceptPanel && !canAcceptPanel(data.panelId, data.sourceEdge)) return;
    dispatch("panelDrop", { panel: data, targetEdge: edge });
  }

  function handleStackDragEnd(): void {
    isDragOver = false;
    dragSourceIndex = -1;
    dropInsertIndex = -1;
  }
</script>

<section
  class="dock-region"
  data-edge={edge}
  data-sizing={sizing}
  data-emphasis={emphasis}
  data-collapsed={collapsed || undefined}
  data-collapsed-posture={collapsed ? collapsedPosture : undefined}
  aria-label={ariaLabel ?? `${edge} dock`}
  on:dragover={handleRegionDragOver}
  on:dragleave={handleRegionDragLeave}
  on:drop={handleRegionDrop}
>
  {#if isDragOver}
    <div class="dock-region__drop-zone"></div>
  {/if}

  {#if sizing === "static"}
    <!-- Static: stacked panels, no tabs, no collapse -->
    <div class="dock-region__stack" data-direction={stackDirection}>
      {#each items as item, index (item.value)}
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <div
          class="dock-region__stack-item"
          data-drop-target={dropInsertIndex === index || undefined}
          data-drag-source={dragSourceIndex === index || undefined}
          draggable="true"
          role="group"
          aria-label={item.label ?? `Panel ${index + 1}`}
          on:dragstart={(e) => handleStackItemDragStart(e, index)}
          on:dragover={(e) => handleStackItemDragOver(e, index)}
          on:dragleave={handleStackItemDragLeave}
          on:drop={(e) => handleStackItemDrop(e, index)}
          on:dragend={handleStackDragEnd}
        >
          <slot name="panel" {item} />
        </div>
      {/each}
    </div>

  {:else if showHidden}
    <!-- Flexible collapsed (hidden): just the collapse toggle -->
    {#if collapsible}
      <div class="dock-region__edge-toggle">
        <CollapseToggle
          collapsed={collapsed}
          direction={collapseDirection}
          ariaLabel={`Expand ${edge} dock`}
          on:toggle={handleCollapseToggle}
        />
      </div>
    {/if}

  {:else if showIconStrip && isVerticalEdge}
    <!-- Flexible collapsed (icon-strip) for left/right: collapse toggle + vertical tabs -->
    <div class="dock-region__strip" data-orientation="vertical">
      {#if collapsible}
        <CollapseToggle
          collapsed={collapsed}
          direction={collapseDirection}
          ariaLabel={`Expand ${edge} dock`}
          on:toggle={handleCollapseToggle}
        />
      {/if}
        <Tabs
          variant="strip"
          orientation="vertical"
          size={size}
          {sizeRole}
          density={density}
          items={tabItems}
          value={activeItem?.value ?? ""}
          reorderable={true}
          ariaLabel={ariaLabel ?? `${edge} dock panels`}
          on:valueChange={handleValueChange}
          on:reorder={handleReorder}
          on:close={handleClose}
        />
    </div>

  {:else if showIconStrip}
    <!-- Flexible collapsed (icon-strip) for top/bottom: horizontal tabs, no body -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div
      class="dock-region__strip"
      data-orientation="horizontal"
      data-compact={isCompact || undefined}
      on:dragstart={handleStripDragStart}
    >
      <div class="dock-region__tabs" use:observeStrip>
        <Tabs
          variant="strip"
          orientation="horizontal"
          size={size}
          {sizeRole}
          density={density}
          showTooltips={isCompact}
          items={tabItems}
          value={activeItem?.value ?? ""}
          reorderable={true}
          ariaLabel={ariaLabel ?? `${edge} dock panels`}
          on:valueChange={handleValueChange}
          on:reorder={handleReorder}
          on:close={handleClose}
        />
      </div>
      {#if collapsible}
        <CollapseToggle
          collapsed={collapsed}
          direction={collapseDirection}
          ariaLabel={`Expand ${edge} dock`}
          on:toggle={handleCollapseToggle}
        />
      {/if}
    </div>

  {:else}
    <!-- Flexible expanded: horizontal tabs + body -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div
      class="dock-region__strip"
      data-orientation="horizontal"
      data-compact={isCompact || undefined}
      on:dragstart={handleStripDragStart}
    >
      <div class="dock-region__tabs" use:observeStrip>
        <Tabs
          variant="strip"
          orientation="horizontal"
          size={size}
          {sizeRole}
          density={density}
          showTooltips={isCompact}
          items={tabItems}
          value={activeItem?.value ?? ""}
          reorderable={true}
          ariaLabel={ariaLabel ?? `${edge} dock panels`}
          on:valueChange={handleValueChange}
          on:reorder={handleReorder}
          on:close={handleClose}
        />
      </div>
      {#if collapsible}
        <CollapseToggle
          collapsed={collapsed}
          direction={collapseDirection}
          ariaLabel={`Collapse ${edge} dock`}
          on:toggle={handleCollapseToggle}
        />
      {/if}
    </div>

    <div class="dock-region__body">
      <slot activeItem={activeItem} />
    </div>
  {/if}
</section>

<style>
  .dock-region {
    position: relative;
    display: grid;
    min-width: 0;
    min-height: 0;
    height: 100%;
    border: 0;
    background: color-mix(in srgb, var(--poodle-color-background-panel) 94%, transparent);
  }

  /* Emphasis variants */
  .dock-region[data-emphasis="quiet"] {
    border-color: transparent;
    background: transparent;
  }

  .dock-region[data-emphasis="strong"] {
    border-color: color-mix(in srgb, var(--poodle-color-accent-base) 32%, var(--poodle-color-border-subtle));
  }

  /* ── Static mode ── */

  .dock-region[data-sizing="static"] {
    grid-template-rows: 1fr;
  }

  .dock-region__stack {
    display: flex;
    min-width: 0;
    min-height: 0;
  }

  .dock-region__stack[data-direction="column"] {
    flex-direction: column;
  }

  .dock-region__stack[data-direction="row"] {
    flex-direction: row;
  }

  .dock-region__stack-item {
    flex: 1 1 0;
    min-width: 0;
    min-height: 0;
    cursor: grab;
  }

  .dock-region__stack-item[data-drag-source] {
    opacity: 0.4;
  }

  .dock-region__stack-item[data-drop-target] {
    box-shadow: inset 0 0 0 0.125rem var(--poodle-color-accent-base);
    border-radius: var(--poodle-radius-control);
  }

  /* ── Flexible expanded ── */

  .dock-region[data-sizing="flexible"]:not([data-collapsed]) {
    grid-template-rows: auto minmax(0, 1fr);
  }

  .dock-region[data-sizing="flexible"]:not([data-collapsed])[data-edge="left"] {
    border-right: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region[data-sizing="flexible"]:not([data-collapsed])[data-edge="right"] {
    border-left: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region[data-sizing="flexible"]:not([data-collapsed])[data-edge="top"] {
    border-bottom: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region[data-sizing="flexible"]:not([data-collapsed])[data-edge="bottom"] {
    border-top: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region__strip[data-orientation="horizontal"] {
    display: flex;
    align-items: center;
    gap: var(--poodle-space-inline-sm);
    padding-right: 0.5rem;
    border-bottom: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region__tabs {
    flex: 1 1 0;
    min-width: 0;
  }

  .dock-region__strip[data-orientation="horizontal"] :global(.poodle-tabs[data-variant="strip"] .poodle-tabs__list) {
    border-bottom: 0;
  }

  /* Compact mode: icon-only horizontal tabs when strip is too narrow */
  .dock-region__strip[data-compact] :global(.poodle-tabs__label),
  .dock-region__strip[data-compact] :global(.poodle-tabs__close) {
    display: none;
  }

  .dock-region__strip[data-compact] :global(.poodle-tabs__tab) {
    padding: 0 0.5rem;
    justify-content: center;
  }

  .dock-region__strip[data-compact] :global(.poodle-tabs__list) {
    overflow: visible;
  }

  .dock-region__body {
    min-height: 0;
    overflow: auto;
  }

  /* ── Flexible collapsed (icon-strip) ── */

  .dock-region[data-collapsed][data-collapsed-posture="icon-strip"] {
    grid-template-rows: 1fr;
  }

  .dock-region[data-collapsed][data-collapsed-posture="icon-strip"][data-edge="top"] {
    border-bottom: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region[data-collapsed][data-collapsed-posture="icon-strip"][data-edge="bottom"] {
    border-top: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  /* Side docks collapse to narrow icon strip */
  .dock-region[data-collapsed][data-collapsed-posture="icon-strip"][data-edge="left"],
  .dock-region[data-collapsed][data-collapsed-posture="icon-strip"][data-edge="right"] {
    width: fit-content;
  }

  /* Top/bottom docks collapse to a thin horizontal strip */
  .dock-region[data-collapsed][data-collapsed-posture="icon-strip"][data-edge="top"],
  .dock-region[data-collapsed][data-collapsed-posture="icon-strip"][data-edge="bottom"] {
    height: fit-content;
  }

  .dock-region__strip[data-orientation="vertical"] {
    display: flex;
    flex-direction: column;
    align-items: stretch;
    gap: 0;
    padding: 0;
    border-right: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region__strip[data-orientation="vertical"] :global(.poodle-tabs) {
    flex: 1 1 0;
    min-height: 0;
  }

  .dock-region__strip[data-orientation="vertical"] > :global(.collapse-toggle) {
    align-self: center;
    padding: var(--poodle-space-panel-y, 0.5rem) 0;
  }

  /* Override Tabs grid so the list column stretches to fill the strip width.
     The default vertical Tabs uses `grid-template-columns: auto minmax(0,1fr)`
     which sizes the list to content. We need it to fill so the active item's
     accent border sits flush on the strip's right divider. */
  .dock-region__strip[data-orientation="vertical"] :global(.poodle-tabs) {
    grid-template-columns: 1fr !important;
  }

  .dock-region__strip[data-orientation="vertical"] :global(.poodle-tabs__list) {
    border-right: 0 !important;
  }

  /* Ensure items' accent border overlaps the strip's border-right */
  .dock-region__strip[data-orientation="vertical"] :global(.poodle-tabs__item) {
    margin-right: -0.0625rem !important;
  }

  .dock-region[data-edge="right"] .dock-region__strip[data-orientation="vertical"] {
    border-right: 0;
    border-left: 0.0625rem solid var(--poodle-color-border-subtle);
  }

  .dock-region[data-edge="right"] .dock-region__strip[data-orientation="vertical"] :global(.poodle-tabs__item) {
    border-right: 0;
    border-left: 0.125rem solid transparent;
    margin-right: 0 !important;
    margin-left: -0.125rem !important;
  }

  .dock-region[data-edge="right"] .dock-region__strip[data-orientation="vertical"] :global(.poodle-tabs__item[data-selected="true"]) {
    border-left-color: var(--poodle-color-accent-base);
  }

  /* ── Flexible collapsed (hidden) ── */

  .dock-region[data-collapsed][data-collapsed-posture="hidden"] {
    border-color: transparent;
    background: transparent;
  }

  .dock-region__edge-toggle {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--poodle-space-panel-y, 0.5rem);
  }

  /* ── Drop zone overlay ── */

  .dock-region__drop-zone {
    position: absolute;
    inset: 0;
    z-index: 10;
    border: 0.125rem dashed var(--poodle-color-accent-base);
    border-radius: var(--poodle-radius-surface);
    background: color-mix(in srgb, var(--poodle-color-accent-base) 10%, transparent);
    pointer-events: none;
  }
</style>
