// packages/react/components/src/MetricTile.tsx
import "@poodle/styles/metric-tile.css";

import { Icon } from "./Icon";
import { useUiPresentation } from "./presentation";
import type { ControlDensity } from "./types";

export interface MetricTileProps {
  label: string;
  value: string;
  ariaLabel?: string | null;
  trend?: "up" | "down" | "flat" | null;
  trendLabel?: string | null;
  sparklineData?: number[] | null;
  density?: ControlDensity | null;
}

function buildSparkline(data: number[]): string {
  const min = Math.min(...data);
  const max = Math.max(...data);
  const range = max - min || 1;
  const w = 64;
  const h = 24;
  const pad = 1;

  return data
    .map((v, i) => {
      const x = pad + (i / (data.length - 1)) * (w - pad * 2);
      const y = pad + (1 - (v - min) / range) * (h - pad * 2);
      return `${i === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
    })
    .join(" ");
}

export function MetricTile({
  label,
  value,
  ariaLabel = null,
  trend = null,
  trendLabel = null,
  sparklineData = null,
  density = null,
}: MetricTileProps) {
  const uiPresentation = useUiPresentation();
  const resolvedDensity = density ?? uiPresentation.density;

  const sparklinePath = sparklineData && sparklineData.length > 1 ? buildSparkline(sparklineData) : null;

  return (
    <div className="poodle-state-tile" data-density={resolvedDensity} aria-label={ariaLabel ?? `${label}: ${value}`}>
      <span className="poodle-state-tile__label">{label}</span>
      <div className="poodle-state-tile__body">
        <strong className="poodle-state-tile__value">{value}</strong>
        {sparklinePath ? (
          <svg className="poodle-state-tile__sparkline" viewBox="0 0 64 24" fill="none" aria-hidden="true">
            <path
              d={sparklinePath}
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        ) : null}
      </div>
      {trend ? (
        <span className="poodle-state-tile__trend" data-trend={trend}>
          <span className="poodle-state-tile__trend-arrow" aria-hidden="true">
            {trend === "up" ? <Icon name="trending-up" /> : trend === "down" ? <Icon name="trending-down" /> : <Icon name="arrow-right" />}
          </span>
          {trendLabel ? <span>{trendLabel}</span> : null}
        </span>
      ) : null}
    </div>
  );
}

// packages/svelte/composites/src/MetricTile.svelte
<script lang="ts">
  import { Icon } from "@poodle/svelte-primitives";

  export let label: string;
  export let value: string;
  export let ariaLabel: string | null = null;
  export let trend: "up" | "down" | "flat" | null = null;
  export let trendLabel: string | null = null;
  export let sparklineData: number[] | null = null;

  $: sparklinePath = sparklineData && sparklineData.length > 1 ? buildSparkline(sparklineData) : null;

  function buildSparkline(data: number[]): string {
    const min = Math.min(...data);
    const max = Math.max(...data);
    const range = max - min || 1;
    const w = 64;
    const h = 24;
    const pad = 1;

    return data
      .map((v, i) => {
        const x = pad + (i / (data.length - 1)) * (w - pad * 2);
        const y = pad + (1 - (v - min) / range) * (h - pad * 2);
        return `${i === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
      })
      .join(" ");
  }
</script>

<div class="state-tile" aria-label={ariaLabel ?? `${label}: ${value}`}>
  <span class="state-tile__label">{label}</span>
  <div class="state-tile__body">
    <strong class="state-tile__value">{value}</strong>
    {#if sparklinePath}
      <svg
        class="state-tile__sparkline"
        viewBox="0 0 64 24"
        fill="none"
        aria-hidden="true"
      >
        <path
          d={sparklinePath}
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    {/if}
  </div>
  {#if trend}
    <span class="state-tile__trend" data-trend={trend}>
      <span class="state-tile__trend-arrow" aria-hidden="true">
        {#if trend === "up"}<Icon name="trending-up" size="sm" />{:else if trend === "down"}<Icon name="trending-down" size="sm" />{:else}<Icon name="arrow-right" size="sm" />{/if}
      </span>
      {#if trendLabel}
        <span>{trendLabel}</span>
      {/if}
    </span>
  {/if}
</div>

<style>
  .state-tile {
    display: grid;
    gap: var(--poodle-space-inline-sm);
    padding: var(--poodle-space-panel-y) var(--poodle-space-panel-x);
    border: 0.0625rem solid transparent;
    border-radius: var(--poodle-radius-surface);
    background: color-mix(in srgb, var(--poodle-color-background-surface) 60%, transparent);
  }

  .state-tile__label {
    color: var(--poodle-color-text-secondary);
    font-family: var(--poodle-typography-code-family);
    font-size: 0.75rem;
  }

  .state-tile__body {
    display: flex;
    align-items: center;
    gap: var(--poodle-space-inline-md);
  }

  .state-tile__value {
    font-size: 1rem;
  }

  .state-tile__sparkline {
    width: 4rem;
    height: 1.5rem;
    color: var(--poodle-color-text-tertiary);
    flex-shrink: 0;
  }

  .state-tile__trend {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
    font-size: 0.75rem;
    font-family: var(--poodle-typography-code-family);
    color: var(--poodle-color-text-secondary);
  }

  .state-tile__trend[data-trend="up"] {
    color: var(--poodle-color-status-success, #22c55e);
  }

  .state-tile__trend[data-trend="down"] {
    color: var(--poodle-color-status-danger, #ef4444);
  }

  .state-tile__trend[data-trend="flat"] {
    color: var(--poodle-color-text-tertiary);
  }

  .state-tile__trend-arrow {
    font-size: 0.875rem;
    line-height: 1;
  }

  :global([data-theme="light"]) .state-tile {
    background: var(--poodle-treatment-surface-fill);
  }
</style>
