// packages/react/components/src/NavCard.tsx
import "@poodle/styles/nav-card.css";

import type { MouseEvent as ReactMouseEvent, ReactNode } from "react";

import { useUiPresentation } from "./presentation";
import type { ControlDensity } from "./types";

export interface NavCardProps {
  title: string;
  description?: string | null;
  href?: string | null;
  badge?: string | null;
  disabled?: boolean;
  ariaLabel?: string | null;
  density?: ControlDensity | null;
  onClick?: ((event: ReactMouseEvent) => void) | null;
  icon?: ReactNode;
}

export function NavCard({
  title,
  description = null,
  href = null,
  badge = null,
  disabled = false,
  ariaLabel = null,
  density = null,
  onClick = null,
  icon,
}: NavCardProps) {
  const uiPresentation = useUiPresentation();
  const resolvedDensity = density ?? uiPresentation.density;

  function handleClick(event: ReactMouseEvent): void {
    if (disabled) {
      event.preventDefault();
      return;
    }
    onClick?.(event);
  }

  const inner = (
    <>
      {icon ? (
        <span className="poodle-nav-card__icon" aria-hidden="true">
          {icon}
        </span>
      ) : null}
      <div className="poodle-nav-card__content">
        <span className="poodle-nav-card__title">
          {title}
          {badge ? <span className="poodle-nav-card__badge">{badge}</span> : null}
        </span>
        {description ? <span className="poodle-nav-card__description">{description}</span> : null}
      </div>
      <svg className="poodle-nav-card__arrow" viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <path d="M6 4l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    </>
  );

  if (href && !disabled) {
    return (
      <a
        className="poodle-nav-card"
        href={href}
        aria-label={ariaLabel ?? title}
        data-disabled={disabled}
        data-density={resolvedDensity}
        onClick={handleClick}
      >
        {inner}
      </a>
    );
  }

  return (
    <button
      type="button"
      className="poodle-nav-card"
      aria-label={ariaLabel ?? title}
      disabled={disabled}
      data-disabled={disabled}
      data-density={resolvedDensity}
      onClick={handleClick}
    >
      {inner}
    </button>
  );
}

// packages/svelte/composites/src/NavCard.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  export let title: string;
  export let description: string | null = null;
  export let href: string | null = null;
  export let badge: string | null = null;
  export let isDisabled = false;
  export let ariaLabel: string | null = null;

  const dispatch = createEventDispatcher<{
    click: MouseEvent;
  }>();

  function handleClick(event: MouseEvent): void {
    if (isDisabled) {
      event.preventDefault();
      return;
    }
    dispatch("click", event);
  }
</script>

{#if href && !isDisabled}
  <a
    class="nav-card"
    {href}
    aria-label={ariaLabel ?? title}
    data-disabled={isDisabled}
    on:click={handleClick}
  >
    {#if $$slots.icon}
      <span class="nav-card__icon" aria-hidden="true">
        <slot name="icon" />
      </span>
    {/if}
    <div class="nav-card__content">
      <span class="nav-card__title">
        {title}
        {#if badge}
          <span class="nav-card__badge">{badge}</span>
        {/if}
      </span>
      {#if description}
        <span class="nav-card__description">{description}</span>
      {/if}
    </div>
    <svg class="nav-card__arrow" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path d="M6 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
  </a>
{:else}
  <button
    type="button"
    class="nav-card"
    aria-label={ariaLabel ?? title}
    disabled={isDisabled}
    data-disabled={isDisabled}
    on:click={handleClick}
  >
    {#if $$slots.icon}
      <span class="nav-card__icon" aria-hidden="true">
        <slot name="icon" />
      </span>
    {/if}
    <div class="nav-card__content">
      <span class="nav-card__title">
        {title}
        {#if badge}
          <span class="nav-card__badge">{badge}</span>
        {/if}
      </span>
      {#if description}
        <span class="nav-card__description">{description}</span>
      {/if}
    </div>
    <svg class="nav-card__arrow" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <path d="M6 4l4 4-4 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
  </button>
{/if}

<style>
  .nav-card {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.875rem 1rem;
    border: 0.0625rem solid color-mix(in srgb, var(--pug-color-border-subtle) 32%, transparent);
    border-radius: var(--pug-radius-surface);
    background: var(--pug-color-background-surface);
    color: inherit;
    cursor: pointer;
    text-decoration: none;
    text-align: left;
    font: inherit;
    width: 100%;
    transition:
      background var(--pug-motion-duration-interaction) var(--pug-motion-easing-standard),
      border-color var(--pug-motion-duration-interaction) var(--pug-motion-easing-standard),
      box-shadow var(--pug-motion-duration-interaction) var(--pug-motion-easing-standard);
  }

  .nav-card:hover:not(:disabled):not([data-disabled="true"]) {
    border-color: color-mix(in srgb, var(--pug-color-accent-base) 28%, var(--pug-color-border-subtle));
    background: color-mix(in srgb, var(--pug-color-background-elevated) 52%, var(--pug-color-background-surface));
  }

  .nav-card:focus-visible {
    outline: var(--pug-border-width-focus) solid var(--pug-color-accent-focusRing);
    outline-offset: 0.0625rem;
  }

  .nav-card[data-disabled="true"] {
    cursor: not-allowed;
    opacity: var(--pug-state-opacity-disabled);
  }

  .nav-card__icon {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    width: 2rem;
    height: 2rem;
    border-radius: var(--pug-radius-control);
    background: color-mix(in srgb, var(--pug-color-accent-base) 12%, transparent);
    color: var(--pug-color-accent-base);
    font-size: 1rem;
  }

  .nav-card__content {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
  }

  .nav-card__title {
    display: flex;
    align-items: center;
    gap: 0.375rem;
    font-family: var(--pug-typography-label-family);
    font-size: var(--pug-typography-label-size);
    font-weight: 600;
    color: var(--pug-color-text-primary);
  }

  .nav-card__badge {
    display: inline-flex;
    align-items: center;
    padding: 0.0625rem 0.375rem;
    border-radius: 999px;
    background: color-mix(in srgb, var(--pug-color-accent-base) 16%, transparent);
    color: var(--pug-color-accent-base);
    font-size: 0.625rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .nav-card__description {
    font-size: 0.8125rem;
    color: var(--pug-color-text-secondary);
    line-height: 1.4;
  }

  .nav-card__arrow {
    flex-shrink: 0;
    width: 1rem;
    height: 1rem;
    color: var(--pug-color-text-secondary);
    opacity: 0;
    transition: opacity var(--pug-motion-duration-interaction) var(--pug-motion-easing-standard);
  }

  .nav-card:hover .nav-card__arrow {
    opacity: 1;
  }
</style>
